### ISSUE TITLE
Dynamic theme color from album art

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#102]
(sorry for so many issues! i have many ideas haha.)
#### Describe the feature you want to  implement?
determine a dominant color from the album art and then pick the color theme that is closest to that color. a few examples:
![Screenshot_20220312-201351_Auxio.png](https://user-images.githubusercontent.com/21956756/158032217-81f7c599-8755-468f-855c-44260017ed1f.png)
![Screenshot_20220312-201425_Auxio.png](https://user-images.githubusercontent.com/21956756/158032221-8e586c15-d28b-42e0-bcca-8abdd1f9d6a3.png)
![Screenshot_20220312-201803_Auxio.png](https://user-images.githubusercontent.com/21956756/158032223-d28abaa4-7394-4479-b9a5-d2789f0d6630.png)
- this would pick the theme closest to the current color, not make a new theme.
- idk if for the whole app or only playback screen, both could work
  

#### Why do you think this will improve everyone's usage of Auxio
it will be pretty. honestly this is just a not important thing so it might not be worth implementing, but would be cool to see. 
if you won't implement because you don't want to, that's fine.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Yeah, I've never been too fond of this idea for the same reasons that I'm not fond of custom accents. For one, monet (the new material you palette extractor) is *still* not available as an official library, which prevents me from making good palettes for the UI. I also prefer Auxio retaining a consistent native feel throughout, and using the palette system like that breaks it somewhat. Sorry.

**Comment by KraXen72** [comment]
alrighty. no problem.
