### ISSUE TITLE
Improve the app description on fdroid

### ISSUE THREAD

**Issue by robinpaulson** [OxygenCobalt/Auxio#103]
I read the description for this app on fdroid. So arrogant, it was astonishing.

**Comment by OxygenCobalt** [comment]
Sorry about that. I don't really know how else to word "Auxio is a music player trying to avoid a bloated feature set and buggy eye candy" in a compelling way. If you're willing to give me advice on how to word it less arrogantly, that would be nice.

**Comment by OxygenCobalt** [comment]
It's been awhile and I haven't got a response, so I'm going to close this issue as it's not exactly constructive. Sorry.
