### ISSUE TITLE
USB audio access ( Usb bit perfect)

### ISSUE THREAD

**Issue by Darkside5252** [OxygenCobalt/Auxio#106]
Better if you can add this feature perfect for audiophile and the people using dac dongle

**Comment by OxygenCobalt** [comment]
I need an example of another music app on android that's capable of doing this. Preferably one with source code.

I think I *might* be able to add something like this using ExoPlayer's `AudioSink` API, but that is is a huge maybe, as I have no idea what restrictions android puts on writing to USB directly.

**Comment by Darkside5252** [comment]
@OxygenCobalt I have an example of music player that capable of Usb bit perfect the USB Audio Pro Player, Hiby, Sony Music Center and Neutron but idk about the source code tho i found those app in playstore and those are paid app except for Hiby

**Comment by Darkside5252** [comment]
@OxygenCobalt I have an example of music player that capable of Usb bit perfect the USB Audio Pro Player, Hiby, Sony Music Center and Neutron but idk the source code tho i found these app in Playstore and those are paid except for Hiby and Sony Music Center

**Comment by OxygenCobalt** [comment]
I don't think I can really add this then. All of those apps are closed source and likely use their ability to hack in USB bit-perfect to get sales. I think judging by [this](https://developer.android.com/guide/topics/connectivity/usb/host) I could *maybe* implement it if I were to put in a bunch of time and effort, but honestly I have more pressing concerns right now. Sorry about this.

**Comment by Archeix7** [comment]
Hi, I saw that there was such a suggestion and it was closed because there were more important things, but if you can add this feature now - it would be great

**Comment by OxygenCobalt** [comment]
Not that there was more important things @Archeix7. More that I really have no clue how this would even work.

**Comment by OxygenCobalt** [comment]
Update: [Android 14 Beta 2](https://android-developers.googleblog.com/2023/05/android-14-beta-2.html) seems to have added something related to this:

> Lossless USB audio
> Android 14 gains support for lossless audio formats for audiophile-level experiences over USB wired headsets. You can query a USB device for its preferred mixer attributes, register a listener for changes in preferred mixer attributes, and configure mixer attributes using a new [AudioMixerAttributes](https://developer.android.com/reference/android/media/AudioMixerAttributes) class. It represents the format, such as channel mask, sample rate, and behavior of the audio mixer. The class allows for [audio to be sent directly](https://developer.android.com/reference/android/media/AudioMixerAttributes#MIXER_BEHAVIOR_BIT_PERFECT), without mixing, volume adjustment, or processing effects. We are working with our OEM partners to enable this feature in devices later this year.

I don't know where I would go from here though, it might be added to ExoPlayer or I have to use it myself.

**Comment by Archeix7** [comment]
Ohh, looks ingesting
