### ISSUE TITLE
Secondary playback buttons

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#108]
This issue is about adding the option for a secondary playback button that will be shown in the playback bar. It will be shown beside the normal play/skip buttons, and will likely consist of a couple of options:
- No button
- A "cancel playback" button that removes the playback state entirely
- A shuffle button
- A repeat mode button
- A queue button that opens the queue
- Skip buttons
- When added, a "like" button

There aren't exactly any blockers except with how to make some of these buttons work with the other playback buttons, which are actually larger than normal icons due to historical reasons.

**Comment by KraXen72** [comment]
where exatly will the new button be? in the main playback screen ? (making the < || > buttons off center?) or just in the playback bar that is present throughout the app when something is playing?

**Comment by OxygenCobalt** [comment]
It's in the playback button present throughout the app. This feature is mostly inspired by how apps like spotify place an another action next to the play/pause button, however in Auxio you'll have the ability to customize (or remove) it.

**Comment by OxygenCobalt** [comment]
This is probably the closest issue related to this, so can I ask you on feedback for something @KraXen72 @qwerty287 @foss-?

Due to the technical changes required for #92, I'm considering adding a new gesture where one could slide the playback bar down to clear the playback state, like this:

https://user-images.githubusercontent.com/65370175/182046428-3a0917f1-b2c5-4e07-a9c8-059334cb2f3e.mp4

The technical reason for this is that I can't disable the "hide" gesture while still allowing me to hide the playback sheet programmatically. I have to enable the "hide" gesture flag and then hide the playback sheet programmatically. This ends up causing a visual bug that I can't reproduce enough to fix. Thus, I just have to keep the hide gesture enabled perpetually in order to enable basic app functionality.

Thus, I have two options:
1. I can add the hide gesture, in which hiding it will clear the playback state entirely (Stopping playback, wiping the current song). I'm not sure how popular this would be however.
2. I could patch the vendored bottom sheet code I use to allow me to enable the flag constantly, but disable the hide gesture. This would preserve Auxio's current behavior, but it's also not ideal internally, as I don't like vendoring thousands of lines of external code and needlessly bloating the project.

**Comment by KraXen72** [comment]
it's pretty cool, i just feel like I'll accidentally clear the playback State a bunch with this gesture. I'd rather not have it or maybe have it do something else? (don't really know what tho)

**Comment by OxygenCobalt** [comment]
Yeah, that's what I was thinking, honestly. Again, quite frustrated that I have to do this. Ideally, the bottom sheet component I use should have two flags for the hiding *gesture* and the hiding *state*, but instead they're a single flag and I'm forced either to do this or vendor the bottom sheet component.

**Comment by KraXen72** [comment]
you could just have the bottom gesture and have it do nothing. like it would hide and then re-show, music still playing. long term pr-ing a fix to material components is a better idea but for now this hack around it would be fine by me.

**Comment by OxygenCobalt** [comment]
Okay, so good news. A patch for me to implement two has been nominally [approved](https://github.com/material-components/material-components-android/pull/2880), however it could get stuck in the "Review hell" that happens with a lot of PRs.

**Comment by OxygenCobalt** [comment]
Okay, so this is implemented, but it's a bit more restricted in scope. Only shuffle and repeat actions are implemented. The others are not included for the following reasons:

- No button: No demand given that a second action has been around for a few versions and most have gotten used to it.
- Cancel playback: Could feasibly be implemented, but would revolve around the hide gesture. No demand and comes with a few annoying bugs.
- Queue: No longer needed given the queue rework.
- Like: Not implemented
- Skip previous: No demand
