### ISSUE TITLE
Add "recently added songs" as one of Library items in settings.

### ISSUE THREAD

**Issue by main-character** [OxygenCobalt/Auxio#11]
Hi im new to github so im sorry if i cant make a proper way to request a feature.

The title says it all and im frustrated sometimes when i cant find my newly downloaded songs.

It would be much easier for us to find it if we somehow can put "Newly added songs" as an option to "Library Items" in settings.

Thank you

**Comment by OxygenCobalt** [comment]
This doesn't really benefit [my usage](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md#feature-addtions-and-ui-changes) that much. When I add music, I don't really need to see what the new songs I added are, I just integrate them whenever I shuffle/reshuffle.

I could revisit this when I implement playlists however. Depends on how much it could cost to loading times.
