### ISSUE TITLE
Equalizer

### ISSUE THREAD

**Issue by exorcist365** [OxygenCobalt/Auxio#113]
#### Describe the feature you want to implement:
Can't be more concise than that.

#### Is your feature request related to a problem? Please describe:
I'm always frustrated when I listen to heavy metal and it sounds like shit.

#### Do other music players handle this? If so, how?
Many but I haven't dove deep into the codebase, so I can't tell you how exactly but some provide their own equalizers and others just use the buildin one.

#### Why do you think this will improve everyone's usage of Auxio?
Makes music sound better when done tastefully.

#### Due Diligence:
- [ ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [ ] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [ ] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I don't really [get any benefit](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) from this, so I don't see myself adding this. Sorry.

**Comment by exorcist365** [comment]
If I pr it will you add?

**Comment by OxygenCobalt** [comment]
Probably not. Feel free to fork it to add an equalizer if you desire, but I usually don't upstream features that benefit my use.

**Comment by OxygenCobalt** [comment]
@exorcist365 Auxio now has equalizer support in external apps like Wavelet. I much prefer this solution, as I can ignore equalization while still allowing others to use it.
