### ISSUE TITLE
Album with songs in MP3 format not displaying date.

### ISSUE THREAD

**Issue by rhynec** [OxygenCobalt/Auxio#116]
#### Describe the bug/crash:
An album with its songs in mp3 format isn't correctly displaying a date when opened. The album in question is Polygondwanaland, with the Year parameter set to 2017. You can test the files for yourself by obtaining them [here](https://kinggizzardandthelizardwizard.com/polygondwanaland) (the album was released to the public domain, so it's completely free).

This may be related: Some audio players struggle to display this particular album as a single album. Retro Music and Odeon display tracks 01 and 10 as belonging to an entirely separate album (with identical tags as the original album).

#### Expected behavior
The album should display the year as its date, instead of showing "No Date"

#### Phone Information:
Moto G Fast running Android 11

#### Due Diligence:
- [ x ] I have checked this issue for any duplicates.
- [ x ] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [ x ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Android only reads dates from ID3v2.3 tags and tags from OGG Vorbis files. I have no idea why, and it's impossible for me to fix this on my end. Sorry.

**Comment by rhynec** [comment]
Makes sense; I checked the files and they were using ID3v2.4. I'll probably change them to v2.3 and see how those work. Thanks for the info!

**Comment by foss-** [comment]
https://issuetracker.google.com/issues/238425624 couldn't believe this bug exists in android 😳

**Comment by OxygenCobalt** [comment]
@foss- I may or may not have realized something:

Internally, the `YEAR` field corresponds to ID3v2.3's `TYER` and Vorbis' `YEAR` tags. ***However,*** I've just figured out that `DATE_TAKEN` corresponds to ID3v2.4's `TDRC` and Vorbis' `DATE` tags. Theoretically, I could check for `YEAR`, then fall back to `DATE_TAKEN` and parse a year out of that.

The only slight drawback is that in MP4 files, `DATE_TAKEN` is this weird garbage date that usually isn't correct. Thus, I can't parse anything more complex than a standalone year value (YYYY, nothing cool like YYYY-MM-DD).

**Comment by OxygenCobalt** [comment]
Actually, never mind. Turns out Android only populates DATE_TAKEN in the media database with the junk MP4 dates and picture dates. Because of course it would [Say one thing in the documentation](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#DATE_MODIFIED) and then do the exact opposite. Sigh.
