### ISSUE TITLE
Audio info and Hide Status bar

### ISSUE THREAD

**Issue by Darkside5252** [OxygenCobalt/Auxio#119]
Can you add audio info (ex. 44.1khz 16bit FLAC) below music title and also hide the status bar

**Comment by OxygenCobalt** [comment]
> Can you add audio info (ex. 44.1khz 16bit FLAC)

Eh. Doesn't exactly fit into my scope. Maybe I'll re-consider this if I add different Seekbar styles.

> also hide the status bar

What do you mean by status bar. Do you mean the text that states "Now Playing"?

**Comment by Darkside5252** [comment]
@OxygenCobalt i mean the Status bar at the top like signal, wifi, etc.

**Comment by OxygenCobalt** [comment]
@Darkside5252 I don't really like forcing immersive mode like that. Too many device-specific bugs. Sorry.
