### ISSUE TITLE
Allow songs tab to be opened by default

### ISSUE THREAD

**Issue by mizzunet** [OxygenCobalt/Auxio#12]
#### Describe the feature you want to implement:

An option for setting the songs tab as default when the app is launched.

#### Is your feature request related to a problem? Please describe:

Somewhat.

#### Why do you think this will improve everyone's usage of Auxio?

This would help many who don't benefit from the Library tab and instead want to see the songs tab first.

#### Due Diligence:

- [x] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Do you mean viewing the songs tab by default? I don't fully understand what you are asking.

**Comment by mizzunet** [comment]
> Do you mean viewing the songs tab by default? I don't fully understand what you are asking.

Yeah, when we open Auxio br in Songs tab instaed of Library tab

**Comment by OxygenCobalt** [comment]
Seems reasonable, honestly. I think I'll integrate this into a future library update [I've been considering merging the song and library tabs anyway]. It may take awhile but I'll implement this in some way.

**Comment by OxygenCobalt** [comment]
Completed. One will be able to sort songs by Ascending, Descending, Album, Artist, and Year in the next release.

**Comment by OxygenCobalt** [comment]
Wait, wrong issue.

**Comment by OxygenCobalt** [comment]
This feature has finally been added. Sort of.
The new Auxio home menu allows the tabs for each music item to be customized. So, if you move the songs tab to the beginning, Auxio will open that tab by default.

![tabs](https://user-images.githubusercontent.com/65370175/137660733-3865da81-04b6-403a-bad9-f013b8b599ee.gif)

This was not shown in the video, but one can also now enable and disable tabs as well. Hope this works well, the change should arrive in the 2.0.0 release.
