### ISSUE TITLE
Show more information regarding library length

### ISSUE THREAD

**Issue by ktutsch** [OxygenCobalt/Auxio#121]
#### Describe the feature you want to implement:
On the "About" page below "Loaded Songs: " a new sections shows up "Total lenght: D days H h M m S s" 

#### Is your feature request related to a problem? Please describe:
Not really. I'm just curious how much music I own.
 
#### Do other music players handle this? If so, how?
Strawberry: All music can be added into the current queue. Strawberry shows the lenght of the queue.

#### Why do you think this will improve everyone's usage of Auxio?
It doesn't make the usage of everyone better. It's just a nice touch for some people.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Oh, so you want the total duration of all songs in your library? I can add that. If anything, I could also add genre/artist/album counts while I'm at it. I'll work on this when I get the time.

**Comment by ktutsch** [comment]
> Oh, so you want the total duration of all songs in your library?

Yes

> I could also add genre/artist/album counts

Cool! Thanks
