### ISSUE TITLE
Pull to reload music

### ISSUE THREAD

**Issue by Naverim** [OxygenCobalt/Auxio#127]
#### Describe the feature you want to implement:
I want a pull to refresh feature.

#### Is your feature request related to a problem? Please describe:
Im always frustrated when I want to reload my music, I gotta go to the setting to do it everytime.

#### Do other music players handle this? If so, how?
One music player I tried automatically refresh the library.

#### Why do you think this will improve everyone's usage of Auxio?
Well currently I see that the dev is having a hard time implementing an automatic refresh, so adding this feature would be a great alternative.

#### Due Diligence:
- [✅] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [✅] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [✅] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I put the reload music option into settings for two reasons:
1. Usually people don't need to update their library frequently. If I were to make it a first-class action, it would likely be triggered accidentally more often than it being deliberately used.
2. Generally, the more UI magic you add to android apps, the buggier it is. I really don't want to add yet another layer of UI complexity to the already complicated home layout.

I don't see myself adding this. Sorry. Hopefully I can implement #72 soon, as I've converged on a solution that I believe will work well.
