### ISSUE TITLE
Android 13

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#129]
This issue is about implementing Android 13 support. This release is actually going to require a bunch of major technical changes to Auxio, such as:
- ~~Themed icons are now a public API. Auxio's icon needs to be ported as such.~~ Resolved in e90983e.
- ~~The media notification now relies on the `MediaSession`. This is actually quite nice, as it removes a lot of annoying state issues that existed beforehand. However, it does require some reworks on the playback end, including porting the notification actions to the `MediaSession` instance.~~ Resolved in 40a34f0596a8a8bff0c9973b1a7a6e2e84e432ec.
- ~~Storage access is now segmented based on songs, images, and videos. This is a simple permission change right now, but may become more complicated with things like #68 and #104.~~ Resolved in 3cef088d126c219d6304d9d6614a1da4805dff01
- ~~Notifications require a permission. This does not matter for Auxio, as the app only uses foreground services, which is pseudo-exempt from these changes.~~
- Back navigation is now contextual. I will need to port Auxio's existing back navigation in order to handle this.
- Panlingual functionality needs to be implemented alongside #64.
- ~~Fixing an issue where widget covers will refuse to load properly. This requires me to work around an Android 13 bug where the size of `RemoteViews` is multiplied by the amount of view variants. I cannot believe this was not caught in testing.~~ Resolved in f5f28b891ad77ca6bd33cf1535323cff71ccb88c.

I'll be keeping this updated as new development releases are made.

**Comment by alanorth** [comment]
Do you think this will help #76?

BTW why don't you have a Patreon or GitHub sponsors link? You are actively creating the best audio player on Android (or maybe just one that appeals to people like me who share your taste!). I also enjoy reading your commit messages of course, because I also think Android is ghetto as f***. Sigh... :tongue:

**Comment by OxygenCobalt** [comment]
As for #76, no. Google has never fixed metadata issues. I think your best bet is #128, which should some soon™ (in fact, you could enable it now if you wanted to build the project).

As for sponsors, I'm not technically an adult yet, so handling donations is a bit of a mess. I'll definitely consider it when I am 18 in a few months.

**Comment by OxygenCobalt** [comment]
Okay, Android 13 has hit platform stability, so I'm going to start working on this. Not going to arrive in 2.4.0, but definitely in 2.5.0.

**Comment by OxygenCobalt** [comment]
Scratch that, not 2.5.0. I'm waiting for the next android gradle plugin to be released, at least for the time being.

**Comment by OxygenCobalt** [comment]
And another update: Auxio may not actually have Android 13 support on it's release. Google did a google again and completely borked XML elements if I switch to SDK 33, which makes development incredibly cumbersome. This is combined with several other dev issues in what is possible the most botched SDK release I have ever seen. I'm waiting for those to be resolved before I work on the migration.

**Comment by OxygenCobalt** [comment]
Okay, I was able to work around the issue by just upgrading to alpha versions of all the development tools. Fun. This should be priority for 2.7.0.

**Comment by OxygenCobalt** [comment]
Everything except panlingual support has been completed. That will be rolled into #64. Android 13 support should arrive in 2.6.2.
