### ISSUE TITLE
Allow theme customization from Android 12 onwards

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#131]
#### Describe the feature you want to implement:
auxios theme picker is really good and has a lot of themes. so why hide it on android 12 and up? Please show the theme picker even on android 12 and up.

#### Is your feature request related to a problem? Please describe:
I'm on a samsung device where material you is implemented very roughly so far, basically no real options and the palette is not respecting the wallpaper almost at all. i really liked the brown auxio theme, but now that i updated to android12 i can no longer switch to it, im stuck with whatever samsung picks.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Sounds reasonable. I use a pixel, so I never realized that OEMs would botch dynamic theming as bad as they did.

**Comment by OxygenCobalt** [comment]
Yeah, I'm going for a new accent option, since it effectively is one anyway.

**Comment by KraXen72** [comment]
coolio. 
only problem with that, maybe i'm recalling incorrectly, didn't the theme picker have an exact grid of items? like all rows and columns full. adding the material you will make a new row just for 1 color.

**Comment by OxygenCobalt** [comment]
The grid is adaptive. I'm fine with adding a new row, as the accent picker has been uneven in the past.

**Comment by KraXen72** [comment]
~~well, well, well, isn't that the perfect oportunity to add more themes to fill it in~~ jk. cool, thanks.

**Comment by OxygenCobalt** [comment]
I wish, haha. Sadly the utility I use to make new themes either produces really ugly accents for new colors, or produces themes are too similar to existing themes (This was why deep orange and blue grey themes were removed)
