### ISSUE TITLE
Genres not separated

### ISSUE THREAD

**Issue by illdeletethis** [OxygenCobalt/Auxio#133]
version 2.2.2
while the number of songs tagged with a genre is displayed correctly, opening that genre tab displays all songs from all bands that have any song tagged with that genre.
this makes the genre tab useless, since instead of being able to listen to a genre by itself it plays a seemingly random selection of stuff, some of which is what it should be, but much isn"t.

**Comment by illdeletethis** [comment]
the band i was looking at when noticing it
![Screenshot_20220517-213309_Auxio](https://user-images.githubusercontent.com/62331598/168898948-9f3b9900-3db0-4f10-bb10-38cdb31fd9ae.png)
![Screenshot_20220517-213349_Auxio](https://user-images.githubusercontent.com/62331598/168898956-27bd009f-71a5-4381-bc8a-7edb165c2e09.png)
![Screenshot_20220517-213414_Auxio](https://user-images.githubusercontent.com/62331598/168898961-fd8d58e6-3361-4828-a66c-011a1165bab5.png)
![Screenshot_20220517-213444_Auxio](https://user-images.githubusercontent.com/62331598/168898967-66091d8d-8f22-4079-bf2a-53ce22189a11.png)
a genre with very few songs in it, but clearly more than should be there when opening
![Screenshot_20220517-213527_Auxio](https://user-images.githubusercontent.com/62331598/168898972-8f394c0d-305f-49a9-8731-d28954450893.png)
![Screenshot_20220517-213538_Auxio](https://user-images.githubusercontent.com/62331598/168898976-e827afab-b735-4ccd-804d-593899e686cb.png)
![Screenshot_20220517-213550_Auxio](https://user-images.githubusercontent.com/62331598/168898982-2cf6ed83-1133-4dbe-aac1-e7900ba092d8.png)
![Screenshot_20220517-213600_Auxio](https://user-images.githubusercontent.com/62331598/168898984-286386da-d575-4277-bef5-f2f7c06a5b98.png)
one Country song is enough to have all the Motörhead on my phone in that genre too
![Screenshot_20220517-213921_Auxio](https://user-images.githubusercontent.com/62331598/168898987-2d3caae1-2529-403e-8d27-707150fcce93.png)

**Comment by illdeletethis** [comment]
sorry about the size of the screenshots on this page, don"t know how to properly format it

**Comment by OxygenCobalt** [comment]
I think what might be happening is that your phone adds whole artist/album groups to a genre as soon as it finds a song that is part of the genre. This is absolutely insane, but also completely expected from Samsung, which is notorious for botching the media database in order to make you use their ad-infested music app.

So, for something like "Gothic metal", how many songs should there be? If it's like one or two from that same album, then I am confident that it's that issue. In this case, there is nothing I can do and you should await #128 for something resembling a fix.

**Comment by illdeletethis** [comment]
Yes, something like that is happening, but only inside the genre view. In this case it means the 10 songs from "The Children of the Night" should be in Gothic Metal, the songs from "The Horror" shouldn"t be. From what i can tell all of the displayed numbers are correct, only the lists of songs have the error.
But i certainly hope #128 fixes the issue.

**Comment by OxygenCobalt** [comment]
Hey, I've been able to create an ***extremely*** experimental APK that implements #128. If you want, you could try it out and report back to me whether it solves your issue or not.

[Auxio_Ignore_MediaStore_Tags.zip](https://github.com/OxygenCobalt/Auxio/files/8827993/Auxio_Ignore_MediaStore_Tags.zip)
