### ISSUE TITLE
Search in Queue

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#135]
#### Describe the feature you want to implement:
if a user has queued a bunch of songs, and wants to play a particular one without losing the queue, it would be nice if you could search in the queue and play the item

#### Do other music players handle this? If so, how?
Not that i know of, but i've always bwanted this in some music player, however didn't find it

#### Why do you think this will improve everyone's usage of Auxio?
see point 1.

#### NOTES
- this relies on #92 to work, because it needs a queur item to be played when clicked
- this is a low priority feature
- it would also nicely work for playlists once those are implemented (easily play playlist from desired song)

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I don't see myself adding this, mostly because it would be quite challenging to understand given queue ordering. Sorry.

**Comment by KraXen72** [comment]
alright, no worries. thanks for considering anyway
