### ISSUE TITLE
add bottom padding to now playing screen

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#137]
#### Describe the feature you want to implement:
add slight (8-16dp maybe even 32dp) padding/margin to the bottom of the screen, now it's almost touching the system nav and it feels cramped

#### Is your feature request related to a problem? Please describe:
see above

![Screenshot_20220524-225729_Auxio Debug.png](https://user-images.githubusercontent.com/21956756/170131468-bf88da99-d8c6-40bd-9a08-c915a27c592e.png)  
here it's almost touching the bottom, and there is a bunch of space above. add some padding or margin please.
  
#### notes
- sorry for making an issue for such a small thing
- i could implement and pr this, just tell me which xml is the player view

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I'm assuming you use gesture navigation? (i.e a really thin navigation bar that you swipe with). In that case, I can modify the padding to move up the playback view more in that navigation mode compared to something like 3-button navigation.

**Comment by KraXen72** [comment]
Sorry to re-open this, did you actually implement this? I'm on 2.3.1 and it is still sticking to the bottom:
![Screenshot_20220613-154138_Auxio.png](https://user-images.githubusercontent.com/21956756/173368251-6a471db2-824a-4cfc-9ba4-bcc10f998eb0.png)

**Comment by OxygenCobalt** [comment]
Yeah, at some point the commit got reverted while I was working on something else. I re-added it yesterday.

**Comment by KraXen72** [comment]
ok. thanks
