### ISSUE TITLE
Tag Editor

### ISSUE THREAD

**Issue by Github-contribute** [OxygenCobalt/Auxio#138]
#### Describe the feature you want to implement:

Audio Tag Editor

#### Why do you think this will improve everyone's usage of Auxio?

I have separate app for this, only for tag editor. If u implement this, it great for use one and only app. I really miss this in auxio. 
1. Change cover picture
2. Change artist picture
3. Edit metadata

#### Due Diligence:
- [ ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [ ] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [ ] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Duplicate of #82 and #33. Auxio is a music player. It does not edit tags and it never will.

**Comment by ian1ilych** [comment]
Did you know that Oto Music actually added that feature?

**Comment by OxygenCobalt** [comment]
Yes. And I am not trying to be like Oto Music.
