### ISSUE TITLE
Side Seekbar inside Genres

### ISSUE THREAD

**Issue by Github-contribute** [OxygenCobalt/Auxio#139]
#### Describe the feature you want to implement:

Side Seekbar inside Genres
I like to play music genre wise mostly. But problem is, I have hundreds of songs. Auxio don't have side seekbar for search particular song easily. 

#### Do other music players handle this? If so, how?

Retro/Metro Music Player

#### Why do you think this will improve everyone's usage of Auxio?
Yes
![2](https://user-images.githubusercontent.com/106362356/170622916-4b5df4c9-a08c-4b77-9885-cca469c29d51.png)
![1](https://user-images.githubusercontent.com/106362356/170622933-dd7b51ef-78f2-4aac-8a83-d969fdd90715.png)

#### Due Diligence:
- [ ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [ ] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [ ] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
You mean the queue view? In that case, I would have to effectively add fast scrollers to the entire app for consistency, which is *possible* but not entirely practical right now. I'll be rejecting this for now and re-considering it at another time.

**Comment by OxygenCobalt** [comment]
Consider this something I may work on as part of #92.

**Comment by Github-contribute** [comment]
Ya iam talking about fast scrolled. It helps to play certain song at same genre. I have lot of songs. Every time I want to swipe up every time to search songs. My hands pain. So, pls reconsider this.
