### ISSUE TITLE
Seekbar Crashes

### ISSUE THREAD

**Issue by Naverim** [OxygenCobalt/Auxio#140]
#### Describe the bug/crash:
When I go back with the gesture control right in the start or the end of the seekbar, it stops counting down the music, the music still plays; And when I swipe back again, it crashes the app.

#### Expected behavior
To not crash

#### Steps To Reproduce the bug/crash:
1. Swipe back around the start or the end of the seekbar
2. Skip songs and do it a couple of times
3. And it crashes

#### Screenshots:
https://user-images.githubusercontent.com/103884904/170670273-0d6ba549-f303-4a66-b4e6-5d524098c13f.mp4

#### Phone Information:
Xiaomi
Pocophone F1
Android 12
Pixel Experience Plus

#### Due Diligence:
- [✔️] I have checked this issue for any duplicates.
- [✔️] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [✔️] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Another day, yet another insane Slider crash because the developers don't make it gracefully degrade but rather make it crash entirely. I hate android so much.
