### ISSUE TITLE
View file properties

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#144]
#### Describe the feature you want to implement:

A simple way to view file properties like
- size
- file location on disk (file path)

#### Why do you think this will improve everyone's usage of Auxio?

It can be helpful if you would like to know where a track is stored on the disk.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by KraXen72** [comment]
![image](https://user-images.githubusercontent.com/21956756/172038840-1fe6fb93-64e5-46fa-987e-9171dd68d9e9.png)
this is the info i provide in my app for extra details like this, might be useful for reference. most of the other stuff can be read from the song tag

**Comment by OxygenCobalt** [comment]
Seems interesting. Some issues I've found though:

- I can't retrieve codecs, but I can retrieve mime types. So the format field likely won't be "MPEG 1 Layer 3" but rather "MP3", if that's okay.
- The bitrate and sample rates are not fully accessible from the media database, and accessing them with #128 is flaky at best. I'll need to fetch the values using some built-in android API when one opens the dialog. Not too difficult, but it's also a built-in android API that has probably been crippled by some OEM.

**Comment by KraXen72** [comment]
honestly, as far as im concerned, MP3 is fine and if it's too much trouble axcessing the 2 things you mentioned just leave them out ig

**Comment by OxygenCobalt** [comment]
Added the view. This should arrive in 2.4.0.
