### ISSUE TITLE
Edge-to-edge mode does not work on certain Samsung devices

### ISSUE THREAD

**Issue by fingerpad** [OxygenCobalt/Auxio#149]
the bottom of the app is covered by the navigation bar in portrait mode. landscape mode is fine.

![image](https://i.imgur.com/UF1UyHQ.jpeg) ![image](https://i.imgur.com/cTQA6e6.jpeg)

auxio version 2.3.1
samsung galaxy s8
android 9

**Comment by OxygenCobalt** [comment]
Auxio implements edge-to-edge functionality from Android 5 upwards, under the assumption that the OS actually provides window insets. But apparently your phone does not give those window insets, so everything appears below the navigation bar. Samsung phones tend to be notorious for breaking basic android features for no reason other to make their OEM bloatware look better. I'll add some toggle to disable the feature.

**Comment by OxygenCobalt** [comment]
Wait, quick question @fingerpad: Are you using any tools like SystemUI Tuner that can change how the navigation UI works? In some situations you might be able to cause unexpected behavior like this if you try to change certain settings.

**Comment by fingerpad** [comment]
> Wait, quick question @fingerpad: Are you using any tools like SystemUI Tuner that can change how the navigation UI works? In some situations you might be able to cause unexpected behavior like this if you try to change certain settings.

nope, i've never used SystemUI Tuner.

i toggled every navigation bar option in the phone settings and tried the default launcher but the issue remains the same. my usual launcher is Nova which only allows me to change the navigation bar opacity on the homescreen and doesn't seem to be the cause either. those are all the things on my phone that would affect the navigation bar, i'm pretty sure.

**Comment by OxygenCobalt** [comment]
Okay, yeah it's either Samsung or one of those situations where SystemUI just breaks for no particular reason. I'll implement something to fix it.

**Comment by OxygenCobalt** [comment]
If you want, you can try out this new APK with the toggle enabled (Rename the extension from ZIP). 

As a sidenote, this *might* also fix the original issue since I discovered a (somewhat big) logic hole with the way I'm insetting the playback bar.

[Auxio_Edge.zip](https://github.com/OxygenCobalt/Auxio/files/8863107/Auxio_Edge.zip)

**Comment by fingerpad** [comment]
it works! the playback bar is in the right place with the toggle on or off. maybe the toggle isn't necessary, haha.

**Comment by OxygenCobalt** [comment]
After doing more research, I've figured out the true culprit. Basically, gesture-based window insets technically were added in Android 9, but didn't work at all. They only worked properly starting in Android 10. Hence, why this issue exists.
