### ISSUE TITLE
may i have a list of your songs?

### ISSUE THREAD

**Issue by disdaogitacc** [OxygenCobalt/Auxio#15]
i lately looked upon this repo and those songs in the screenshots in the README and checked one of them out, enjoyed it, went on and got them all.
i know there should be more and i'd really like to listen to your favorite tunes.

regards

**Comment by OxygenCobalt** [comment]
This is not exactly on topic [Github issues are to report problems or suggest things], but I guess I can give you a list of some artists that I enjoy:

- 65daysofstatic
- God Is An Astronaut
- Four Tet
- Epic Mountain [They compose the music for kurzgesagt]
- Radiohead/Thom Yorke
- Muse [Everything before The 2nd Law]
- This Will Destroy You

**Comment by disdaogitacc** [comment]
i apologize and wish you an awesome week as you made mine. thank you for real.
