### ISSUE TITLE
Rounded Covers tweak

### ISSUE THREAD

**Issue by rhynec** [OxygenCobalt/Auxio#152]
#### Describe the feature you want to implement:
Disabling album covers in Auxio should preferably not gray-out the option to use rounded covers, as the option also affects how the default (missing/no artwork) artist/album/track icons are displayed in the app. While re-enabling cover art and selecting the option works, it isn't exactly a clean solution.

#### Due Diligence:
- [ x ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [ x ] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [ x ] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Yeah, I've realized this already but haven't found the time to fix it.
