### ISSUE TITLE
Add a whilelist for folders with media

### ISSUE THREAD

**Issue by MagicRB** [OxygenCobalt/Auxio#154]
#### Describe the feature you want to implement:
I'd like to be able to whitelist folders with music, not just blacklist. The setup I'm imagining in my head for my music collection, would involve just one carefully managed folder on my device, so having the ability to whitelist just that one folder would be splendid.

#### Is your feature request related to a problem? Please describe:
Kind of? I'd like to hold my music in a plain folder somewhere remote, then using a cronjob transcode it from FLAC to OGG-Opus and sync that to my phond using Syncthing. Poor man's replacement for a media server.

#### Do other music players handle this? If so, how?
They either have a music root or allow you to whitelist folders.

#### Why do you think this will improve everyone's usage of Auxio?
I can't be the only one with one folder holding their music library.

#### Due Diligence:
- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [X] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [X] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Okay, fine, I'll add this. But it won't be a separate option from Excluded directories, it will instead be a separate mode within that feature.

I'll add some toggle in the menu that allows you to choose between two modes:
- Exclude: The current behavior (Exclude these directories from indexing)
- Include: The behavior you want (Restrict indexing to these directories)

This would also help issues like #148, as the new mode will exclude directories that can't be excluded normally.

**Comment by MagicRB** [comment]
Thanks! :)
