### ISSUE TITLE
Blur now-playing theme

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#155]
#### Describe the feature you want to implement:
option for a gradient blur of the album cover in the background of now playing screen. see oto music:
![Screenshot_20220612-210032_Oto Music.png](https://user-images.githubusercontent.com/21956756/173249192-3af905db-e7f8-4050-ae8f-31bf5e9ed407.png)

#### Is your feature request related to a problem? Please describe:
aesthetics/eye candy

#### Do other music players handle this? If so, how?
oto music, see above screenshot

#### Why do you think this will improve everyone's usage of auxio?
aesthetics/eye candy

#### other notes
- completely understand if you won't add this because it's a lot of work. if you would even cosider adding it, feel free to shelve it as a someday(tm) feature

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Eh, I don't like this idea. Once I add some kind of option for "Now Playing Themes", the genie is out of the bottle, and eventually there are a dozen themes that all only work sometimes (See: Retro). I tend to prefer having one layout that I can make as good as possible, and then make customization more modular [#130].

For this in particular, I can't really integrate it as a modular setting, so I don't really want to add it. Sorry.
