### ISSUE TITLE
 Issue playing wav file of Audio: 8.8Mb/s Duration: 00:04:59... Is high bitrate not supported ?

### ISSUE THREAD

**Issue by missyraja** [OxygenCobalt/Auxio#157]
#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
What is the issue? I cannot debug this if I don't know what is going wrong? Is it like #151?

**Comment by OxygenCobalt** [comment]
Merging this into #174, as I'm assuming it is related to such.
