### ISSUE TITLE
Sort Option in Songs Tab

### ISSUE THREAD

**Issue by Badmarine47** [OxygenCobalt/Auxio#16]
Please allow Songs to be sorted as Date Modified or Latest added .. and alphabetical order .

**Comment by OxygenCobalt** [comment]
While I can definitely do alphabetical order, date modified/last added could increase loading times, so I would have to consider this further before implementing it.

**Comment by OxygenCobalt** [comment]
Completed. One will able to sort by Ascending, Descending, Artist, Album, and Year in the next release. Last-added was not added due to performance constraints [Plus it does not benefit my usage much].
