### ISSUE TITLE
Inconsistent track sorting (9 coming after 10)

### ISSUE THREAD

**Issue by sakuranonamida** [OxygenCobalt/Auxio#161]
![Screenshot_20220616_210530](https://user-images.githubusercontent.com/107634864/174104318-af6265d4-f5bf-47c4-bae9-5cdf3d03d4ed.jpg)
I would like to know what is causing this bug

**Comment by OxygenCobalt** [comment]
Okay, several questions @sakuranonamida:
- What version of Auxio are you using? 
- What version of Android are you using?
- What device are you using?
- Can I have a sample file that causes the issue?

It seems to be an issue of some kind with sorting or track/disc numbers. Hence, why I need a sample file.

**Comment by OxygenCobalt** [comment]
Hey, I've received no response, so I will be closing this for now as I cannot feasibly reproduce it. If anyone else is encountering this issue, please let me know.

**Comment by chrispalmeri** [comment]
I ran into a similar issue, which turned out to be the disc number. Tracks with an empty disc number are grouped with, but sorted before tracks explicitly tagged as disc 1.

**Comment by OxygenCobalt** [comment]
Interesting issue @chrispalmeri. AFAIK Auxio just maps songs without a disc to Disc 1, but I should probably explicitly group those tracks into an "Unknown Disc" group to reduce confusion. Spun that off into #405.
