### ISSUE TITLE
Circle pause, rectangle resume visual on the play buttons

### ISSUE THREAD

**Issue by Naverim** [OxygenCobalt/Auxio#162]
#### Describe the feature you want to implement:
The play buttons too look like this (example from the Google Clock app)
![Screenshot_20220617-192035_Clock.png](https://user-images.githubusercontent.com/103884904/174297300-229e050c-304b-4eb3-93ac-c0fbe8403e45.png)
![Screenshot_20220617-192038_Clock.png](https://user-images.githubusercontent.com/103884904/174297330-fc4bf048-c60f-4455-b164-80b7dbfd01b5.png)

#### Is your feature request related to a problem? Please describe:
Not really

#### Do other music players handle this? If so, how?
Retro Music Player has it, with an option for a MD3 play button

#### Why do you think this will improve everyone's usage of Auxio?
It looks good ¯\_(ツ)_/¯

#### Due Diligence:
- [✔️] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [✔️] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [✔️] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I don't think I will add this. Sure, the behavior does look nice when there is only three buttons (and they are all contained within a background of some kind), but it looks objectively terrible in a player like Retro where there are 5 buttons and all the other buttons are non-contained.

I'll reconsider it when I try to tackle how to make the playback controls look more consistent with the rest of the app.

**Comment by OxygenCobalt** [comment]
Just as a note, I generally dislike adding "eye candy" to Auxio. Not that I hate it, I just know that, on Android, eye candy tends to break down as soon as you add any kind of technical complexity, and implementations are usually littered with gotchas that are never handled in the tech demos they provide. Spending time improving music loading or adding a new feature is much more productive then hacking Eye-Candy UI components into a *sort-of* working state.

**Comment by OxygenCobalt** [comment]
Actually, I may implement this. Android 13 has a new media controls panel that showcases a circular play button morphing into a square pause button. For consistency, I may as well also implement it on my end.
