### ISSUE TITLE
(other) your library's indie rock genre

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#163]
hi,
in the screenshot i saw you have an indie rock genre
i wanted to get into Indie rock lately, could you send me some reccomenations or a list of songs?
thanks

**Comment by OxygenCobalt** [comment]
Uh, it's not my *favorite* genre. I just picked it because it looked like the most appealing genre screenshot. The only ones I like are alt-J and Low Roar.
