### ISSUE TITLE
Customize playback mode in detail views

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#164]
#### Describe the feature you want to implement:

If I play a track in a list, I can change what should be played. But there's no option "Current list". What I'd like to have is the behavior to play the crruent list. I.e. if I look at an album, play the album, if I look at a genre, play the genre, if I look at all tracks, play all tracks etc.

#### Do other music players handle this? If so, how?

Most do this by default, I think.

#### Why do you think this will improve everyone's usage of Auxio?

It's useful and can help preventing tracks in the queue you don't want to have there.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I don't fully understand what you want. Are you talking about adding another option to "When a song is selected" that jumps to the position of the song in the queue?

**Comment by OxygenCobalt** [comment]
Oh. Okay, like the "When a song is selected" setting but applied to particular views. I don't see why I couldn't necessarily add this, but at the same time I'm worried it could create confusion if it was changed accidentally.

@qwerty287 Would you be okay with a single "When a song is selected from details" setting that applies across album, artist, and genre lists? I feel like having a configuration for each list would be too confusing. It would also make it more consistent with the other setting, which also applies to multiple views (Library and search).

**Comment by OxygenCobalt** [comment]
Okay, I'll be adding this then.
