### ISSUE TITLE
move queue button setting

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#165]
#### Describe the feature you want to implement:
setting to move queue button here for easier reach
![Screenshot_20220619-201045_Auxio.png](https://user-images.githubusercontent.com/21956756/174494984-d6e02872-4e26-4712-80c9-8e2d3351f1c3.png)

#### Is your feature request related to a problem? Please describe:
queue button is hard to reach on tall devices

#### Do other music players handle this? If so, how?
oto music, queue button is on the bottom

#### Why do you think this will improve everyone's usage of Auxio?
queue button will be easier to reach

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
That place is already reserved for a "like" button, so I can't do this. Again, with #92 I might be able to add the swipe up behavior that you wanted originally.

**Comment by KraXen72** [comment]
oh word. i thought you can't implement swipe up behavior as stated in #92 , but if you can, that would be really good, even better than this! thanks

**Comment by OxygenCobalt** [comment]
I could because of the new queue editing mechanism that I wanted to add. If queue editing is toggleable, I can simply disable the swiping mechanism and thus eliminate the conflicting events that prevented me from doing it prior.
