### ISSUE TITLE
Control via Intents ?

### ISSUE THREAD

**Issue by Tiemichael** [OxygenCobalt/Auxio#17]
#### Describe the feature you want to implement:
I would like to control Auxio via Tasker by sending Intents like
`INTENT_PLAYBACK_COMMAND_PLAY = "auxio.command.PLAY";`
#### Why do you think this will improve everyone's usage of Auxio?
This feature allows to control Axio eg from a car-steering wheel, or integrate into other projects.
There are a few audio-players like GoneMad or PowerAmp which offer this feature, but non of them is free.

#### Due Diligence:

- [* ] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

Thanks!

**Comment by OxygenCobalt** [comment]
Can you try using these intent names?

`ACTION_AUXIO_LOOP_`
`ACTION_AUXIO_SHUFFLE_`
`ACTION_AUXIO_SKIP_PREV_`
`ACTION_AUXIO_SKIP_PLAY_PAUSE`
`ACTION_AUXIO_SKIP_NEXT_`

These are used in the notification code, so they may work here as well.

**Comment by Tiemichael** [comment]
Thanks for your reply!
I did some tests but not yet successful.
When looking at the source-code I see `ACTION_PLAY_PAUSE` and some others but not `ACTION_AUXIO_SKIP_PLAY_PAUSE_`
Will do some more tests over the next days ...

**Comment by OxygenCobalt** [comment]
Wait, I forgot. In the current version the word `RELEASE` is appended to the actions to prevent conflicts with the debug app. Can you try:

`ACTION_AUXIO_LOOP_`
`ACTION_AUXIO_SHUFFLE_`
`ACTION_AUXIO_SKIP_PREV_`
`ACTION_AUXIO_SKIP_PLAY_PAUSE_`
`ACTION_AUXIO_SKIP_NEXT_`

**Comment by Tiemichael** [comment]
Thanks!
I am sure it's possible, but I am not experienced enough to get it going.
Need to get some help from another forum.

BTW, are you sure it's `ACTION_AUXIO_SKIP_PLAY_PAUSE_release` and not `ACTION_AUXIO_PLAY_PAUSE_release`

**Comment by OxygenCobalt** [comment]
Its `ACTION_AUXIO_PLAY_PAUSE_release`, accidentally pasted it wrong.

**Comment by OxygenCobalt** [comment]
I'm assuming that this issue is solved as of now. A quick note before I close it though, I've updated the wording of the actions. In 1.4.1, they will now be:

```
org.oxycblt.auxio.action.LOOP
org.oxycblt.auxio.action.SHUFFLE
org.oxycblt.auxio.action.PREV
org.oxycblt.auxio.action.PLAY_PAUSE
org.oxycblt.auxio.action.NEXT
```

I hope this helps!

**Comment by Tiemichael** [comment]
Thanks! will try

**Comment by OxygenCobalt** [comment]
Don't try them on the current version though! I'm talking about the next version.
