### ISSUE TITLE
Player & Navigation Bar

### ISSUE THREAD

**Issue by bakinazik** [OxygenCobalt/Auxio#170]
#### Describe the bug/crash:
player controls are stuck under navigation bar

#### Screenshots:
![screenshot](https://user-images.githubusercontent.com/64368231/175327575-d7dd522e-f81a-4dcb-883a-77ed1db9c4cd.jpg)

#### Phone Information:
Android 9 / Honor 9 Lite

#### App Information
Last F-droid release: 2.3.1

**Comment by bakinazik** [comment]
also there is no such problem in the previous version of the app

**Comment by OxygenCobalt** [comment]
Have you tried 2.4.0 at https://github.com/OxygenCobalt/Auxio/releases/tag/v2.4.0? This is a very similar issue to #149.

**Comment by OxygenCobalt** [comment]
No. There is a delay of 1-2 weeks between the original release and the F-Droid release. This is mostly to prevent major bugs from working their way into the F-Droid release, and F-Droid's own inefficiency regarding releases.
