### ISSUE TITLE
[Feature request] Clickable songs in the queue

### ISSUE THREAD

**Issue by p0yskaa** [OxygenCobalt/Auxio#175]
#### Describe the feature you want to implement:

The ability to play the songs in the queue by clicking(tapping) them. 

#### Is your feature request related to a problem? Please describe:

Not really a "problem", but I personally am used to this feature. It's just somewhat inconvenient to not be able to switch songs by clicking them. 

#### Do other music players handle this? If so, how?

Phonograph plus does this. You can change the order of the queued songs and play any one you want, maintaining the order of the queue. 

#### Why do you think this will improve everyone's usage of Auxio?

It allows the user to switch songs faster and easier, without the need to rearrange the queue as often. 

#### Due Diligence:
- [ *] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [ *] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [* ] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
This is already tracked by #92.
