### ISSUE TITLE
Auxio reports VBR MP3 bitrate as 32 kbps

### ISSUE THREAD

**Issue by anonymous5555522222** [OxygenCobalt/Auxio#177]
#### Describe the bug/crash:

Auxio reports VBR MP3 bitrate as 32 kbps.

#### Expected behavior

Vinyl Music Player displays the bitrate correctly as "~313 kb/s"
#### Steps To Reproduce the bug/crash:

1. Go to album
2. Go to song properties
3. See bug

#### Screenshots:

![Screenshot_2022-07-01-14-37-48-722](https://user-images.githubusercontent.com/92955960/176906254-643fef2d-981d-48c7-80ec-3d77975d6cde.jpg)
![Screenshot_2022-07-01-14-37-23-851](https://user-images.githubusercontent.com/92955960/176906287-79875a28-9b41-483f-908a-b87a52bfd425.jpg)

#### Phone Information:

Alcatel 3X
Android 10

Thank you for developing Auxio, I like it a lot.
#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This issue stems from the different media parsers that Auxio and Vinyl uses:
- Auxio uses android's built-in media parser, which reads the header bitrate and nothing else.
- Vinyl uses an external parser, which can calculate an approximate bitrate.

There is really nothing I can do about this. I cannot switch to the same parser as Vinyl, as it requires legacy storage access (Which basically locks Vinyl in Android 10's compatibility mode forever). However, I also can't fit this into #128 as ExoPlayer does not expose a bit-rate for local music files (yet). Sorry.
