### ISSUE TITLE
SD Card music will not load

### ISSUE THREAD

**Issue by TheSilencedOne** [OxygenCobalt/Auxio#18]
#### Describe the feature you want to implement:
 i would like the ability to play, load and see music from SD cards

#### Why do you think this will improve everyone's usage of Auxio?
 we will be able to use SD cards
which is a important feature for people with lots of music, or for people who like to have a portable music library

#### Due Diligence:

- [x] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I'm not sure if `MediaStore` [The way Auxio loads music] supports SD cards. Can you link to any apps that correctly find music on your SD card [Not including Vanilla & VLC since they don't use `MediaStore`].

**Comment by TheSilencedOne** [comment]
> I'm not sure if `MediaStore` [The way Auxio loads music] supports SD cards. Can you link to any apps that correctly find music on your SD card [Not including Vanilla & VLC since they don't use `MediaStore`].

Im not sure if either of these apps use MediaStore
https://github.com/SimpleMobileTools/Simple-Gallery
https://github.com/HardcodeCoder/PulseMusic

**Comment by lscambo13** [comment]
On my phone (Android 8.1), sdcard is working already as the app can load and play songs from there without issues.

**Comment by OxygenCobalt** [comment]
That's what I thought. Theres no difference between my implementation and Pulse's implementation aside from that I do all the loading upfront. It could be a device-specific issue.

**Comment by TheSilencedOne** [comment]
> That's what I thought. Theres no difference between my implementation and Pulse's implementation aside from that I do all the loading upfront. It could be a device-specific issue.

Thats strange SD card support works fine on pulse music for me.

**Comment by OxygenCobalt** [comment]
Are you stuck at the "Music loading failed" screen when you open Auxio? Or is the music just not loading? If its the former I could be able to trace back the issue further.

**Comment by TheSilencedOne** [comment]
> Are you stuck at the "Music loading failed" screen when you open Auxio? Or is the music just not loading? If its the former I could be able to trace back the issue further.

its not that its stuck or wont load, its just that my music on my SD card wont show up in the app, the music on my internal storage works as expected,
When i try to add any SD card folder to the excluded folder list it says "this directory isnt supported" 
but when i open music from my file manager (thats on my SD card) 
it works fine,

**Comment by OxygenCobalt** [comment]
> its not that its stuck or wont load, the issue is the music on my SD card wont show up in the app

Strange. It might be a quirk with the way I'm filtering out music. I'll prepare an APK for what I think may be the issue.

> When i try to add any SD card folder to the excluded folder list it says "this directory isnt supported"

This is expected behavior, as the excluded folder system only works with internal storage currently.

> but when i open music from my file manager (thats on my SD card) it works fine,

When you do that, does it open up Auxio and play the music correctly or are you using another player?

**Comment by OxygenCobalt** [comment]
Can you try this APK? I disabled a part of the loader which could be filtering out your SD card music due to a device quirk.

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/6489566/app-debug.zip)

**Comment by TheSilencedOne** [comment]
> Can you try this APK? I disabled a part of the loader which could be filtering out your SD card music due to a device quirk.
> 
> [app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/6489566/app-debug.zip)
> 
> [Quick Note: Don't add any folders to the excluded folders list with this build, as that will break the app]

Ok so it turns out (im really sorry for this) that my SD card music does show up in debug and non-debug versions,

So what happened was that all of my SD card music got stuffed into one album called "unknown album" instead of it having albums for each of my music folders

![Screenshot_20210517-000944_1](https://user-images.githubusercontent.com/78061111/118431606-b99e8e80-b6a4-11eb-88d5-8cf140aa3044.png)

**Comment by TheSilencedOne** [comment]
> Can you try this APK? I disabled a part of the loader which could be filtering out your SD card music due to a device quirk.
> 
> [app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/6489566/app-debug.zip)
> 
> [Quick Note: Don't add any folders to the excluded folders list with this build, as that will break the app]

Ok so it turns out (im really sorry for this) that my SD card music does show up in debug and non-debug versions,

So what happened was that all of my SD card music got stuffed into one album called "unknown album" instead of it having albums for each of my music folders, 

![Screenshot_20210517-000944_1](https://user-images.githubusercontent.com/78061111/118431689-e8b50000-b6a4-11eb-9ad4-22a39921dbb5.png)


again im sorry for wasting your time, 
Suggestion: maybe have music folders on SD cards show up as there own album instead of them all getting stuffed into one.

**Comment by OxygenCobalt** [comment]
Okay, thats even stranger. This seems very device-specific and unless someone else is able to reproduce the issue theres nothing I can really do about it. Sorry.
