### ISSUE TITLE
Accessible after screen timeout/lock

### ISSUE THREAD

**Issue by illdeletethis** [OxygenCobalt/Auxio#183]
#### Describe the feature you want to implement:
The navigation app i use, Sygic, remains accessible as usual even after shutting down the screen, coming up instead of the lock screen then, or after screen timeout.
in either case pressing the home button then brings up the lock screen, making only the just used app further usable without knowing how to unlock.
while it also remains visible on its own, keeping the screen on after timeout that would go to far for an audio player.

#### Why do you think this will improve everyone's usage of Auxio?
There have been times at which i wanted to have full access to the music player without unlocking anything else, or leave someone else with a reasonably compatible taste in charge of music selection without handing over my phone completely.
likely other users have had that experience too.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Huh. I don't really know how I could do that. There is no information about keeping the device unlocked on android developers (only to keep the device awake, which isn't what you want), and Sygic seems to be closed-source, so no luck determining how they implement such. 

Unless someone can point me in the right direction, I don't think I can add this. Albeit, Auxio should expose it's notification (which has controls and the playing song) in the lockscreen, which sort-of accomplishes the same.
