### ISSUE TITLE
(Other) what is the stable ID3 version?

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#193]
I'm writing a tagging program in python for my uses and i am wondering, what id3 version to use so it gets easily and without hassle recognized by Auxio (and other music players)?
Thanks.

**Comment by OxygenCobalt** [comment]
ID3v2.3 tends to have the best support, however you do miss out on some features like ID3v2.4's sort tags.

**Comment by KraXen72** [comment]
thanks! i'm already using eyed3 (even tho it's a massive pain but it works now so i can't be bothered to rewrite it).
is it a good idea to add both id3v2.3 and id3v2.4 tags to the same file? is it even possible? 
(i tried looking this up online but i couldn't find a good answer)
thx.
also, the tagging script is like a yt downloader + tagger thing, for just tagging i'd use MusicBrainz Picard

**Comment by OxygenCobalt** [comment]
You can't add ID3v2 tags of different versions like that. The spec just isn't designed for that. You have to pick one or the other. Auxio should be able to handle ID3v2.4 more gracefully in the next version with #128.

**Comment by animaldaydream** [comment]
For all practical purposes you should always use ID3v2.4, most implementations expect that version. The only case that would bring you trouble is an old dedicated DAP (an MP3 player device) that does not handle it, but you probably don't have one if you're here.

**Comment by OxygenCobalt** [comment]
@animaldaydream is right about this, albeit android's native support for ID3v2.4 is notoriously poor. Auxio will have excellent support for ID3v2.4 in the next version however, and you can enable the system already in the current system with "Ignore MediaStore tags".

**Comment by animaldaydream** [comment]
> android's native support for ID3v2.4 is notoriously poor

It is? I wouldn't know, I encode everything as Opus 160k before sending to my phone, even the lossy music.

Is it broken, has fewer features than ID3v2.3, or is it just incomplete?

**Comment by OxygenCobalt** [comment]
There's two big issues with Android's support of ID3v2.4 @animaldaydream:
1. UTF-8 tags get corrupted in some cases due to a dynamic encoding check
2. No date support since the parser still checks for `TYER` instead of `TDAT`

This has largely made ID3v2.4 impractical until recently.
