### ISSUE TITLE
Audio Normalisation

### ISSUE THREAD

**Issue by Doge7734** [OxygenCobalt/Auxio#194]
#### Describe the feature you want to implement:

If possible, an option to enable music to be around the same volume due to some albums/artists being at different volumes.
#### Is your feature request related to a problem? Please describe:

Some albums/artist's music is louder or quieter than the rest of the songs. This can be annoying when listening with earbuds and having to adjust the volume of them so you don't damage your eardrums or so you can actually hear the music.
#### Do other music players handle this? If so, how?

The only ones I know are big streaming services like Apple Music and Spotify. I'm not sure how since they are proprietary >:(
#### Why do you think this will improve everyone's usage of Auxio?

I believe this will make the app a lot friendlier to delicate ears and people out of reach of their phone.
#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
This is done by ReplayGain, an open standard that uses audio metadata to allow normalization. These tags can be applied to your files using a tool like [rgbpm](https://github.com/Moonbase59/loudgain/blob/master/bin/rgbpm).

**Comment by Doge7734** [comment]
Ah, cool, didn't know that. Sorry!
