### ISSUE TITLE
Play single song

### ISSUE THREAD

**Issue by sn0n** [OxygenCobalt/Auxio#196]
#### Describe the feature you want to implement:

Play single song from songs list

#### Is your feature request related to a problem? Please describe:

In settings I do see an option to play a single song from "item details",.. but no clear way to navigate there. Long press doesn't give an option for item details, only properties, which doesn't allow a playback. 

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
There's no menu option because you can play a song by just tapping it normally. If you want to play a song without generating a queue, that is covered by #93, as I plan to add a "play selected" option with that feature that would allow a queue to be created based on the songs that you select.
