### ISSUE TITLE
Show number of songs/duration of queue

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#199]
Possibly with a subtitle, similar to how the genre is shown in the currently playing view.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I think this would be best if bundled with #92, as that is the super-issue for a total rework of the Queue UI I want to do.

Only concern honestly is UI clutter. I'll see what I can do.

**Comment by OxygenCobalt** [comment]
I really couldn't find a good way to integrate it into the UI, yeah. Sorry.
