### ISSUE TITLE
versionCode is not incremented

### ISSUE THREAD

**Issue by IzzySoft** [OxygenCobalt/Auxio#2]
looks like you forgot to increase `versionCode` – there have been 3 releases meanwhile, but `versionCode` is [still set to 1](https://github.com/OxygenCobalt/Auxio/blob/dev/app/build.gradle#L14). As that's what Android uses to tell versions apart, this makes updates difficult for end users.

Could you please always increase this right before tagging a new release in the future? It doesn't matter how much, as long as the new value is larger. Thanks!

**Comment by IzzySoft** [comment]
PS: Fastlane changelog files must be named `<versionCode>.txt` in order to be properly detected. Another reason why you should increment :wink:

**Comment by OxygenCobalt** [comment]
I didn't know I had to do that :sweat_smile:. Thanks for letting me know. Is there anything I can do to back-port a different version code to 12303

**Comment by OxygenCobalt** [comment]
It may not matter, actually. I'm only planning to put this up on F-Droid around 1.3 or 1.4 so having bad version codes isn't as big of a problem for the versions that likely wont be built. Thanks for the heads-up though!

**Comment by IzzySoft** [comment]
> I didn't know I had to do that

I thought so, hence I brought it app, ahem, up :smile:

> Is there anything I can do to back-port a different version code to 1.1 and 1.2?

I don't think that is needed. If the latest version has it increased, that's what users can easily install then / update to. Just remember to always increase – and never ever decrease.

> I'm only planning to put this up on F-Droid around 1.3 or 1.4

Oh. Then be in for a surprise tomorrow around 8 pm CET/UTC+1, to [be found here](https://apt.izzysoft.de/fdroid/index/apk/org.oxycblt.auxio). Your app just passed the pre-check, so to say. And yes, for new apps F-Droid starts with the latest available release, skipping all older (disclosure: I'm one of the F-Droid maintainers).

Thanks for picking up and fixing that quickly!

Btw: will you take care for the length limit of your fastlane changelogs as well? Starting with the next release is fine, no need to fix older ones (again, F-Droid will pick the latest only).

**Comment by OxygenCobalt** [comment]
> Oh. Then be in for a surprise tomorrow around 8 pm CET/UTC+1, to be found here. Your app just passed the pre-check, so to say. And yes, for new apps F-Droid starts with the latest available release, skipping all older (disclosure: I'm one of the F-Droid maintainers).

What? I did not ask to put my app up on F-Droid. It doesn't have any translations, there is no metadata on the master branch and there's still a variety of issues I'm working on. I really don't want it to be public to users at this time, is it possible to pause the release until I'm able to wrap up 1.3? Thanks!

> Btw: will you take care for the length limit of your fastlane changelogs as well? Starting with the next release is fine, no need to fix older ones (again, F-Droid will pick the latest only).

I decided to wipe them in 9ebb647 thinking that they wouldn't be needed given that I was only planning to submit my app during 1.3/1.4. Ill need to re-add them if my app is going to be public now!

**Comment by IzzySoft** [comment]
> Is it possible to pause the release until I'm able to wrap up 1.3, which is the release I'm specifically intending to be meant for a greater audience?

Sure it is (that repo is my own). Your release was marked as stable (i.e. not pre-release), so I assumed it was meant as being public. So I'll take it out for now (setting it to "disabled") and wait for your ping when 1.3 is ready and it's OK for you to have it published with my repo.

Btw: you can consider your app's presence in my repo a "test drive". Hundreds of apps have started there before moving on to the "official repo". Users are aware that apps in my repo often are such "test drives", do not reach the F-Droid standards for other reasons or simply feel "not yet ready" for it (though then it's usually pointed out in the app's description – which would be in your hands with Fastlane, as my updater pulls that along as well).

**Comment by OxygenCobalt** [comment]
Got it. Ill ping you when 1.3 is finished, which should be today or tomorrow given that I just completed the last partial translation set. I've also updated the changelogs in c41c3be for 1.2 and soon 1.3. Should `full_description.txt` also be below 500 characters? Thanks!

**Comment by IzzySoft** [comment]
All fine :smile: what reaches me before 7pm CET/UTC+1 goes live the same day, else the next day. And no, `full_description.txt` has no such limitation (there will be one I guess, but much higher). The only other limitation is the `short_description.txt` with 80 chars.

Looking forward to your ping then, best luck!

**Comment by OxygenCobalt** [comment]
1.3.0 is now public! You can re-enable my app listing now.

**Comment by IzzySoft** [comment]
Thanks! Done, should go live with the next sync in less than 16h from now.

**Comment by abh-oss01** [comment]
> Btw: you can consider your app's presence in my repo a "test drive". Hundreds of apps have started there before moving on to the "official repo". Users are aware that apps in my repo often are such "test drives", do not reach the F-Droid standards for other reasons or simply feel "not yet ready" for it (though then it's usually pointed out in the app's description – which would be in your hands with Fastlane, as my updater pulls that along as well).


I've no idea what you're talking about, been happily using apps from your repo for over a year now, all apps are absolutely stable and usable, not "test drives" at all
Great work btw, big fan of what you're doing, thank you sir!

**Comment by IzzySoft** [comment]
Well, must be that what we call "test drive" is more stable than what MS calls "release" :speak_no_evil: 

Actually, only some apps in my repo are "test drives" (and clearly marked then). Others are just "not yet ready" for the "official repo" (or their authors feel like that), or have a single (hopefully minor) show-stopper and thus cannot enter F-Droid.org. I'm glad your experience as this positive as we all are aiming for – thanks!
