### ISSUE TITLE
Media controls on lockscreen not properly showing

### ISSUE THREAD

**Issue by Roddyboii** [OxygenCobalt/Auxio#20]
#### Describe the bug/crash:
Media player controls & info not properly working on lockscreen (instead it shows up in a notification)

#### Steps To Reproduce the bug/crash:
1. Open Auxio and play some music
2. Lock then open the screen
3. Lockscreen says that it doesn't detect a music player.

#### Screenshots:
![Screenshot_20210531-025515](https://user-images.githubusercontent.com/78095397/120116890-fdbd8300-c1bc-11eb-8576-aec5b1825d55.jpg)

#### Phone Information:
Device: Samsung Galaxy J2 2015 (j2lte)
Android version: 7.1.1 (Custom Samsung ROM)

#### Due Diligence:

- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

I have been looking for a good FOSS music player and I came across this one. Really liking it :) It's simple but functional. I'll be using it as my daily use audio player and post bugs that I may come across, like this one.

**Comment by OxygenCobalt** [comment]
Most of these "Control music from the lockscreen" systems use the `MediaSession` API, and I'm aware that there may be some issues with the way I'm currently implementing it. I'll try to look into it.

**Comment by OxygenCobalt** [comment]
I've located the issue, my implementation of `MediaSession` is too sparse and does not signal that it supports play/pause/skip actions, hence why it does now show up. I'll try to implement those changes and come back to you eventually.

**Comment by OxygenCobalt** [comment]
Can you try this APK? I think I've set it up so that the lock screen can detect it.
[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/6592779/app-debug.zip)

**Comment by Roddyboii** [comment]
![Screenshot_20210603-234244](https://user-images.githubusercontent.com/78095397/120673556-dc62dc80-c4c5-11eb-8540-40836aba1c71.jpg)

It works :)

**Comment by OxygenCobalt** [comment]
Great, I'll mark this issue as resolved then.
