### ISSUE TITLE
Various genres on each artist section

### ISSUE THREAD

**Issue by anonymous5555522222** [OxygenCobalt/Auxio#200]
Sorry, this is a little bit of a nitpick. But it seems that when a artist has a various albums with different genres, only one random genre is displayed. Could this be fixed, by showing all the genres, or maybe instead of showing the genres on an artist's section, show the genre of an album on that album's section instead? (Next, above or under the date, total songs and duration). Thanks!

**Comment by OxygenCobalt** [comment]
Auxio picks the most "prominent" genre (the one that shows up on the most songs) from the artist and displays them. I don't want to display all of the genres, as all of them wouldn't fit on a small screen.

As for albums, the album menu is already becoming a bit cramped (The lower line now has release type, year, songs, and duration), so I don't feel comfortable adding it there.

**Comment by illdeletethis** [comment]
usually when an artist has multiple generes it"s due to cover songs or interludes/intros/outros, much rarer for the relevant output to cover multiple genres, and how could the app possibly know the difference?

**Comment by anonymous5555522222** [comment]
> usually when an artist has multiple generes it"s due to cover songs or interludes/intros/outros

That's not true with certain artists. It's true for some, but not all.

> and how could the app possibly know the difference?

By indexing the genres of all the albums from that artist.

But it's OK to not add this, I do not think it's fundamental to the app.

**Comment by OxygenCobalt** [comment]
Okay, given some recent developments in #195, I'm going to try to implement an algorithm that allows me to display multiple entries well. For example, "Item A, Item B, and 2 others". This could open the door for this feature as well.
