### ISSUE TITLE
Overlapping playtime display

### ISSUE THREAD

**Issue by intrnl** [OxygenCobalt/Auxio#205]
#### Describe the bug/crash:

In the Albums view, the playtime display can overlap other text

#### Expected behavior

It shouldn't.

#### Steps To Reproduce the bug/crash:

1. Have an album with a long playtime duration
2. Open the album view for it

#### Logs/Stack Traces:

Not applicable.

#### Screenshots:

![Screenshot_2022-08-01-19-23-27-10_e7dcd68fdcfdc2ab307738dbc82b3952](https://user-images.githubusercontent.com/20620901/182147420-ccf4ef78-12d4-44e5-a59d-cb3bb9f16950.jpg)

#### Phone Information:

realme 9, using realme UI 3.0 on Android 12

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I have seen nothing like this before. Can you try this APK (rename it from zip) that replaces the formatted playtime with a placeholder value (`<duration>`)? That way, I can narrow it down to whether it's the way I'm formatting the playtime, the way I'm formatting several items, or realme being a typical OEM and breaking basic android functionality.

[Auxio_NoDuration.zip](https://github.com/OxygenCobalt/Auxio/files/9235149/Auxio_NoDuration.zip)

**Comment by intrnl** [comment]
Here's a screenshot with the provided debug build
![Screenshot_2022-08-02-06-15-14-54_65b8df5a000978b3161002a299fb7747](https://user-images.githubusercontent.com/20620901/182260859-31d9cc9c-26b9-47c7-be81-3301956ca47a.jpg)

It's very likely to be realme UI specific as I've noticed stuff like Play Store having some weird padding around the app size count

![Screenshot_2022-08-02-06-17-22-69_b5a5c5cb02ca09c784c5d88160e2ec24](https://user-images.githubusercontent.com/20620901/182260919-c292df0b-bf32-4504-95ef-c362f2f11e29.jpg)

**Comment by OxygenCobalt** [comment]
I think I know what's going on. Realme's format code is seemingly busted. I think you could confirm this by long clicking on a song, selecting "View Properties", and seeing if the "File size" value is also oddly spaced like that in Google Play (Assuming that yes, we are using the same code to format sizes). In that case, that is a realme issue and there's nothing I that I could feasibly do on my end.

**Comment by intrnl** [comment]
Can confirm it's also busted, a little unfortunate, but since there's not much that can be done here, closing the issue.

![Screenshot_2022-08-02-06-41-22-38_65b8df5a000978b3161002a299fb7747](https://user-images.githubusercontent.com/20620901/182262945-d2581a6a-a1f2-4ccc-bade-d38579991771.jpg)

**Comment by gabeweb** [comment]
Hi,

Auxio Dev's version (4.0.0) on Android 15 (Xiaomi's HyperOS 2.0), the queue list overlaps the player controls. I'm not sure if this issue exists on other Android versions or devices (mine is a Redmi Note 13 4G).

![Auxio 4.0.0-dev on Android 15 Xiaomi HyperOS](https://github.com/user-attachments/assets/722cd73a-4db7-4351-83c4-0fdcb1255fe2)

While stable version (from F-Droid) hasn't that issue but the padding is "too much" (I think):

![Auxio 3.6.3 on Android 15 Xiaomi HyperOS 2.0](https://github.com/user-attachments/assets/3c6cf436-ad3b-4f98-a6aa-8d8010c7fe6c)

**Comment by OxygenCobalt** [comment]
That's actually an entirely different issue @gabeweb, can you go and make a new one?
