### ISSUE TITLE
Fast music reloading

### ISSUE THREAD

**Issue by intrnl** [OxygenCobalt/Auxio#206]
#### Describe the feature you want to implement:

Now that Auxio gains the ability to ignore Media Store tags, and parse the files on its own, there should be a way to have a fast music reloading by keeping track of file modified time.

#### Is your feature request related to a problem? Please describe:

With a music collection of 6251 songs stored on SD card, it currently takes 1min30sec to fully reload the music library. This doesn't seem ideal.

#### Do other music players handle this? If so, how?

Musicolet does this and it seems that Omnia does as well, both players skips over files that hasn't been changed according to their file modified time.

Musicolet reloads the entire library in 14 seconds.

#### Why do you think this will improve everyone's usage of Auxio?

Most of the reasons why you would want to reload the library (whether manually or automatic) is to have your new music appear or see the changes you did to a part of your collection, and checking music that hasn't even changed a single bit is rather unnecessary.

It would still be worth having a full reload that completely ignores the file modified time though, as a sort of precaution if it doesn't seem to pick up on changes (though this could also mean that the user is doing something bad)

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
This is actually pretty hard. Auxio currently loads all music into memory at startup. For me to adequately diff files when they are modified would require me to make a music database that caches all song metadata and then loads it into memory when it is read so it can be re-used later. I mean, I've been considering this for awhile since I'm worried about the memory implications of very large libraries, but it's also a technical change on the scale of #72 and will likely be extremely far-off. Not really looking at doing at this right now since it continues to push major features further away.

**Comment by OxygenCobalt** [comment]
Alternatively, I could band-aid the feature in by making a database of paths and their last-modified timestamps. I could then cross-reference with the database to see if the file is new or not. 

The only issue is that while reloading at *runtime* is faster, initial startup is *not.* It will be just as slow as it still needs to built the in-memory music library. I don't know how much this would solve your issue @intrnl.

**Comment by OxygenCobalt** [comment]
Okay, I actually did some more thinking, and I decided to focus this issue more into #207. The solution I'm going to implement should be much less invasive, as the in-memory music library will not be changed.
