### ISSUE TITLE
Sort albums and/or songs by most recent additions

### ISSUE THREAD

**Issue by hellpe** [OxygenCobalt/Auxio#208]
This was the default setting in Google Play Music, and I think it is still available in YouTube Music as well. Personally, it helps me a lot to keep track of my newest album downloads and focus on the fresh music.

Note: VLC has just implemented this feature on their latest 3.5.0 release, however it is not retroactive, and thus displays my whole music library as it was all added at once.

**Comment by foss-** [comment]
Dupe of https://github.com/OxygenCobalt/Auxio/issues/181
