### ISSUE TITLE
Future of Auxio

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#21]
One may have noticed that the pace of Auxio releases has slowed down. This is not because I am abandoning the project. I've been working on another project [Hint: Its also music-related] and in all honestly Auxio has a reached a point I'm somewhat satisfied with. However, there are some notable issues many of you have raised:

- Disjointed library system: There are two library tabs, one for genres/artists/albums and one for songs. Theres no way to see genres/artists/albums at the same time, and theres no way to make the songs tab default [#12].
- ~~The library view does not have a fast scroller, which can be an issue for long album lists~~
- The songs view cannot be sorted [#16]
- ~~No widget support~~ [#8]

There are also issues when it comes to the system Auxio uses to get its music: `MediaStore`. `MediaStore` is the "recommended" way to get music on android, but is deeply flawed and clunky. Getting the genre of a song is horrifically inefficent [It takes up usually half of the time it takes to load music], getting the year of a song just isn't possible outside of a single type of MP3 file, and further support for features like playlisting would be even harder.

There is no way to salvage this system that isn't just begging google to improve `MediaStore` so I am considering implementing a system similar to [Vanilla Music](https://github.com/vanilla-music/vanilla/releases) where I use the Exoplayer Metadata Retrieval system to read metadata instead and simply store the results in a database. This seems to work okay with Vanilla to an extent, but would require most of the app to be completely refactored.

If this change [or something similar] succeeds, playlisting will likely be implemented as well, which would mean that the UI would likely be redesigned to accommodate the new feature and finally resolve the library conflict. This new library view would show genres/artists/albums/songs all in a single view with tabs between them. You could then customize the visibility and ordering of these tabs. What used to be the songs tab would now be the tab for playlists since I generally consider them separate from the music library. The end result would look something like this:

![Mockup](https://user-images.githubusercontent.com/65370175/122603234-92502e00-d063-11eb-8035-198a1f2df07f.png)

I would like to receive feedback on this change. I personally see this as an improvement, but I don't want to pull a GNOME and make a sudden change that everyone dislikes.

As of now, the roadmap looks roughly as:

#### 1.4.1
- Black Theme [Finished in 5dc7b52]
- Fast-scrolling in the library view [Finished in 5131db5]

#### 1.4.2
- Android 12 support
- Widgets
- Possible "Material You" customization if I can figure out how that works
- Song sorting

Should be released in likely August as I continue to work on my other project

#### Some nebulous future 1.5.0 release
- Liked Songs and Playlists
- Library redesign

Auxio is not dead, its just in hibernation. Stay tuned.

**Comment by offa** [comment]
@OxygenCobalt the FAQ mention F-Droid, is there any ETA or blocker? Would be nice to have it in the main repo!

**Comment by OxygenCobalt** [comment]
Hm. I wrote that line in the FAQ when the app had some really bad UI issues that I was still working out. I think it could be okay to get onto the mainline repo, but I'm not sure where I'd start. I do have a `.yml` I created that could be proposed on the repo though.

**Comment by offa** [comment]
Best starting point is opening a [request for packaging](https://gitlab.com/fdroid/rfp) I guess.

https://gitlab.com/fdroid/rfp/-/issues/1777

Let's see, what's next :-)

**Comment by offa** [comment]
[RFP has been merged](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9307) and it should appear on F-Droid soon :+1:.

Additionally, I have opened a PR to add permission documentation as suggested in the comments.

**Comment by OxygenCobalt** [comment]
Nice. I did notice what izzy pointed out about my translations. The german was almost completely done by me, a non-native speaker who took 3 years of german with a dictionary being used to fill in the gaps. The rest of the translations were largely derived from other projects as I have no understanding of those languages.

I would love for more people to contribute translations though, would fix the broken ones I made myself and the incomplete translations that are missing values I could not find analogues to in other projects. Time will tell now that Auxio is accessible to a wider group of people.

**Comment by alanorth** [comment]
> There is no way to salvage this system that isn't just begging google to improve MediaStore so I am considering implementing a system similar to Vanilla Music where I use the Exoplayer Metadata Retrieval system to read metadata instead and simply store the results in a database. This seems to work okay with Vanilla to an extent, but would require most of the app to be completely refactored.

@OxygenCobalt would switching to the Exoplayer Metadata Retrieval system allow support for reading album artist tags? Currently Auxio chooses the artist tag from the first track of the album and decides that is the artist for the whole album:

![auxio](https://user-images.githubusercontent.com/191754/125031299-1d39ac80-e095-11eb-842c-7cb524ecc180.png)

In reality the album artist for all the tracks in that album is "Migos", and the artist tag of each track has "Migos feat. some other artist".

It kills me how so many Android audio applications don't support this. It makes using a well-tagged media library (beets and MusicBrainz) a very annoying experience. By my count, these applications support album artist tags (likely by doing their filesystem own scanning):

- Odyssey
- Vanilla
- VLC

Thanks!

**Comment by OxygenCobalt** [comment]
The hypothetical system would also read from the filesystem directly, and since ExoPlayer has its own parsers instead of relying on the busted `MediaMetadataRetreiver` API, it would be able to recognize the album artist tag. However, the amount of changes I would have to make to get Auxio working with this new system would easily take months as I have to iron out bugs and make the experience as fluid as possible.

I think the short term right now is getting widgets, custom accents, and playlists done, and then trying to move on to this new system if possible.

Another option might be getting google to add a new `ALBUM_ARTIST` field to the albums database in the next android version. This way, I could keep relying on `MediaStore` and load things quickly while respecting well-tagged media libraries. Might be easier said that done though.

**Comment by OxygenCobalt** [comment]
Issue has outlived its usefulness. I've split it up into #34, #36, and #38.
