### ISSUE TITLE
Folder browser and a toggle between miniplayer and fullsize player

### ISSUE THREAD

**Issue by Neomanbeta** [OxygenCobalt/Auxio#217]
#### Describe the feature you want to implement:

1: Add a "Folder" tab to library allow users to choose files to play like a file browser.
2: Add a setting to allow user to toggle when start playing a song switch to a full size player interface instead of the mini player at the bottom.

#### Is your feature request related to a problem? Please describe:

No
#### Why do you think this will improve everyone's usage of Auxio?

1: Some audio files have really messy tags, so in the folder they are named like 1.mp3 2.mp3 3.mp3 etc... So currently it's really hard to use the "Songs" or "Artists" or "Albums" to see which one is the first file to play because the tags are like "202211111_3335455", all of the artist is "Unknown Artist", all of the Albums are "www.exanmple.com". For example, i have 10 folders each of them have 10 files in them, they have messy tags but the file names are named from 1.mp3 to 10.mp3. If i want to play 8.mp3 from the 7th folder, in the "Songs" list, it is impossible to find. But with the folder browser it can be done easily. 
2:Auxio has full Dpad control support, this is fantastic, which means i can use it on some non-touchable screen android devices. But the thing is when i start playing, it only starts a mini player at the bottom of the screen which is no way to control by using only Dpad, but on the fullsize player interface, the Dpad control works. If i want to switch to the fullsize player i have to click on the miniplayer, but this cannot be done with a non-touchable screen. So i would like to know could you please add a toggle to allow users to choose whether they want the miniplayer at the bottom or fullsize player while playing.
#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
First, why can't you just spend time correcting your tags? Tools like Picard can automatically populate tags too based on an audio fingerprint, I think. Auxio generally isn't designed with poorly tagged libraries in mind, as there are so many edge-cases with that functionality that accommodating such would lead to massive scope creep.  

Second, I really don't know how such a setting would work, and it generally seems like the wrong solution to your problem. I'm not familiar with D-Pads, but I was aware of some accessibility issues with the old player UI. In 2.6.0, I switched the component used in the playback UI to a new one that properly broadcasted those kinds of events. Assuming that your D-Pad relies on the accessibility framework, I think the new UI should work better. If not, I could very much recommend filing an issue at [material-components-android](https://github.com/material-components/material-components-android) about D-Pad support in `BottomSheetBehavior`, as there is nothing I can really do on my end.
