### ISSUE TITLE
Improved playing indicators

### ISSUE THREAD

**Issue by missyraja** [OxygenCobalt/Auxio#218]
Hey 👋

I know it's too much to ask as auxio is more than what a lot of other open source music player app do... The clean and beautiful design is just beautiful... 

This is just a suggestion. Do consider it if you think it's necessary.

When a song is played the song's name changes to the accent color inside the album and also it is denoted by a Equalizer style icon over it...

I think two things can be improved here...

1. The album name of the song that is playing should also have their name changed to the accent color in the main album view... 

2. The Equalizer icon over the song album should be animated while playing ![Screenshot_20220817-162203-055.png](https://user-images.githubusercontent.com/40870763/185101491-5c209a65-eba2-4c71-aa0d-cc433f5fce5c.png)![Screenshot_20220817-162242-778.png](https://user-images.githubusercontent.com/40870763/185101523-a6e564c8-d6ba-42e9-beac-85e490aacaca.png)

**Comment by OxygenCobalt** [comment]
- Why not. Was planning to do this *eventually*, other things just got into the way.
- This used to be implemented, but I dropped it because of miscellaneous state issues. I could probably try doing it again.

**Comment by missyraja** [comment]
Take you time dude. I've been using my previous music app for offline playing for 6yrs before i finnally switched to auxio... This is the most clean ui/ux offline player that is around. Thanks for this...

**Comment by OxygenCobalt** [comment]
So I've implemented playing indicator support in the home and search views. However, the animated icon is much harder and will likely force me to write my own drawing code since Android's animated icon code was written by insane people. Will probably do that in the future.

**Comment by missyraja** [comment]
Thank you for this

**Comment by OxygenCobalt** [comment]
2.6.3.


https://user-images.githubusercontent.com/65370175/188221821-067032b7-bd4f-4ebe-8e62-c4393f5ec710.mp4
