### ISSUE TITLE
LG devices not displaying notification metadata

### ISSUE THREAD

**Issue by roy-heinrich** [OxygenCobalt/Auxio#219]
#### Describe the bug/crash:
When I play a music, it doesnt show the notification details. It just show the seek bar and controls. The music plays fine, but the notification is kinda empty.

#### Expected behavior
It should show all the relevant song information in the notification bar.

#### Steps To Reproduce the bug/crash:

1. Play music
2. Swipe notification bar
3. See the error

#### Screenshots:
![Screenshot_20220817-210804](https://user-images.githubusercontent.com/93825933/185143797-f738ea40-1c4e-41cb-af9b-b2036cef20cb.png)

#### Phone Information:
LG V50s
LG ux 10 based on Android 12

#### Due Diligence:
- [/ ] I have checked this issue for any duplicates.
- [/ ] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [ /] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Oh, you have got to be kidding me. I thought Android 11 and 12 made the notification metadata rely on the media session, but NOPE! Here I go having to add yet ANOTHER edge-case.

**Comment by illdeletethis** [comment]
if only our phones had regular, not crippled linux :D

**Comment by OxygenCobalt** [comment]
Judging by "LG UX 10", LG is probably updating core components to "Android 12", but not bothering to update the SystemUI at all. The media notification looks a lot like Android 10's, which does not support that trick I use.

**Comment by roy-heinrich** [comment]
I just wanna add that it used to work on v2.4.0. After 2.5.0, it stopped working

**Comment by OxygenCobalt** [comment]
Checks out. I fixed #179 in 2.5.0, and that fix causes the bug.
