### ISSUE TITLE
Bug @Android:string/Cancel Ok

### ISSUE THREAD

**Issue by edilberto507h** [OxygenCobalt/Auxio#222]
Bug on settings dialogues show @Android:string/cancel others also show @Android:string/ok  at the bottom of dialogue box.

It should display Cancel and OK respectively in system selected language.

Steps To Reproduce the bu
1. Open settings
2. Select theme o accent color
3. The bottom of the dialog show @Android:string/cancel

![Screenshot_20220821-210300](https://user-images.githubusercontent.com/109629876/185828573-62260336-215a-4d9f-ad70-c19a501de0c9.png)

![Screenshot_20220821-210203](https://user-images.githubusercontent.com/109629876/185828666-ddc2a9b2-1bab-4630-9e55-8afc1c381fbc.png)

LG, K42, Android 11, manufacturer launcher.

#### Due Diligence:
- [ /] I have checked this issue for any duplicates.
- [ /] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [ ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Already reported by #215 and fixed. Was a issue with Weblate not understanding a string trick I used.
