### ISSUE TITLE
[Not sure if it's a bug] Music library not refreshing after adding new music

### ISSUE THREAD

**Issue by 0xphk** [OxygenCobalt/Auxio#225]
#### Describe the bug/crash:

Hi, not quite sure if this is a bug or a Android 12 related issue.

I usually add new stuff to my Android using 'termux' ssh connection to copy it from my PC to /sdcard/Music
I've checked the permission of the newly added files and they match the music already in the filesystem and visible in the player.

Already tested adding the sub directories (/sdcard/Music/subdir) via the options 'Music folders'  feature.
(Include / directory / save) They are listed as 'Internal shared storage/Music/subdir', mode is set to include.

Used the 'Reload music' option in the settings of 'Auxio' multiple times.

Tested the 'Automatic reloading' option as described in the FAQ but to no avail.

I can access and play the music using my FX file explorer, navigating to the directory. 
Although it's not listed in the FX file explorer 'Music library' section too,
so I guess it's more of a problem with the library, than the player.

So far only music copied to sdcard with MTP usb connection is listed 
(might be important to mention that it was already there before the Android 12 update)

#### Expected behavior

New music is listed after adding it to the phone.

#### Phone Information:

Oneplus Nord 'AC2003 EU', Android 12 (stock Oxygen OS 12.1_F14, rooted)

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
MediaStore is notoriously flaky regarding updates. Judging by the behavior of FX file explorer, the MediaStore database is stale. If the database is stale, Auxio's music will be stale too.

Sometimes a reboot fixes it, sometimes you just have to keep uploading it until it actually bothers to update.

**Comment by OxygenCobalt** [comment]
Yeah, that checks out. Generally, the best way to get Auxio to update the music library is to use a USB connection. There used to be workarounds that allowed apps to force MediaStore to rescan music, but those have all been locked off by Google, as apparently they think that the current busted update system is good enough. Goes to show how much they care about the filesystem.
