### ISSUE TITLE
Move more button in playback view

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#226]
#### Describe the feature you want to implement:
After 2.6.2, the new more button makes it so long titles get marqueed. this is suboptimal. here's my proposed change:
![edited screenshot playback2](https://user-images.githubusercontent.com/21956756/187301414-fdbb7e04-e192-4d4c-af29-c6246a689449.png)

> move the more icon down to only be aligned between the title and artist.   
  
if you'll add a like icon later, replace the more icon with the like and move more icon to equalizer (equalizer is now in more)

#### Is your feature request related to a problem? Please describe:
long titles get marqueed even when there's still screens space

#### Do other music players handle this? If so, how?
they sometimes use smaller fonts or different alignments, but for this case this solution would be ideal

#### Why do you think this will improve everyone's usage of Auxio?
better use of space? idk

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Honestly, this feels a bit misaligned, especially since more buttons will be used in a similarly aligned manner when I add them to other parts of the app.

**Comment by KraXen72** [comment]
ehh okay. the more button in general feels like it has nothing to do there, you really don't need it that close. 
id move it back to the top and put the equalizer in there. but that's just me.

**Comment by OxygenCobalt** [comment]
Yeah, I agree. I'll move it back for the sake of consistency with other UIs. However, eventually a "Like song" button will eventually be added in the same place.

**Comment by OxygenCobalt** [comment]
Okay, I decided to move the button back to the toolbar. I'll consider what to do with it later.

**Comment by KraXen72** [comment]
yes and thank you.

**Comment by KraXen72** [comment]
personally i value information density really high in ui/ux, like yes adding padding to stuff makes it look a lot more spacious and not cramped, but there is a limit.  
For example the Material You notification shade is making really poor use of the space. Auxio strikes a good balance so far between consistent, nice ui & good information density, although earlier patches where the bullet notation was used (artist • album) were better at this, but i understand there were some technical difficulties with it.  
 
also not sure if i should create a new issue for this (its just a quick question):
Was the circle paused and squircle playing button addition really necessary? i can't find it in the docs, and yes i guess I'll get used to it, but it does look pretty goofy. I'd either go with one of the other. I know auxio first had it circle, then switched to squircle, both are fine on it's own, but just seeing this animation in-between + the ripple is, well, not pleasant, at least for me. If you really like it then keep it i guess, just asking if it was necessary. Thanks

**Comment by KraXen72** [comment]
to add to the future like button placement, i'd still rather take "reach to top to like a song" & "see the full title" rather than "marquee title" & "like song easily", but that's just me not using the like songs feature even on spotify and also most songs don't have that long of a title.

**Comment by OxygenCobalt** [comment]
> Was the circle paused and squircle playing button addition really necessary? i can't find it in the docs, and yes i guess I'll get used to it, but it does look pretty goofy

It was mostly from this issue #162 and Android 13 introducing this behavior in the media control panel. It's not documented, but it's "implied" by how google designers make new UIs.

> to add to the future like button placement, i'd still rather take "reach to top to like a song" & "see the full title" rather than "marquee title" & "like song easily", but that's just me not using the like songs feature even on spotify and also most songs don't have that long of a title.

I'll take that in mind, however I think most users would prefer that easier reach.
