### ISSUE TITLE
Skipping backwards on a single song queue crashes app

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#231]
#### Describe the bug/crash:
When playing from an album with one song, and skipping a song back, the time flashes to 0:-1 and app crashes (4 times out of 5)

#### Expected behavior
when skipping back on a single song queue, it should go to the start of the song and pause playback (same thing that happens when you skip forward)

#### Steps To Reproduce the bug/crash:
1. play a single song from an album with only one song
2. let it play for more than 3 seconda
3. click the skip to previous song button

#### Screenshots:
couldn't get a screenshot because it crashes really fast 

#### Phone Information:
Galaxy M21 Android 12 OneUI 4.1

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I can't seem to reproduce this on my device, but the "0:-1" number is a dead giveaway that something happened to the currently playing song that shouldn't have happened. I'll look into it.

**Comment by KraXen72** [comment]
idk if it helps (probably not) but the album and song was "minnesota is a place that exists" by Glaive and i let it play for 2-3 sec before skipping back and it crashing.

(also happens on other single albums too)
i reproduced it reliably by skipping to start with button, skipping to 0:12 on seekbar and skipping to start with button again.

**Comment by OxygenCobalt** [comment]
I seemingly cannot reproduce this on my end, but I think my guess at what's happening is that there is a gap with some music files where ExoPlayer returns -1 as a position value. Assuming that's the case, here is a debug build with some guards around situations where the position is lower than 0.

[Auxio_FixedPosition.zip](https://github.com/OxygenCobalt/Auxio/files/9492743/Auxio_FixedPosition.zip)


~~I really need to migrate the position to a reactive system instead of the awful observer setup I currently have, ugh~~

**Comment by KraXen72** [comment]
sorry just got to this, will try it out

**Comment by KraXen72** [comment]
yes this debug apk fixed it thanks

**Comment by KraXen72** [comment]
there also was a memory leak in the debug build lol![Screenshot_20220908-071102_Auxio Debug.png](https://user-images.githubusercontent.com/21956756/189039543-ecadc7fb-64f5-4cc7-912f-a6da7653ff19.png)
lmk if i should add the logs or something like that
