### ISSUE TITLE
Apostrophes being displayed as weird characters

### ISSUE THREAD

**Issue by ourigen** [OxygenCobalt/Auxio#232]
#### Describe the bug/crash:

For some songs, apostrophes in their titles are displaying as garbled characters. In my case, the apostrophe occurs in the album title. What's odd is that only some songs are displayed incorrectly while others aren't. As a result, these are being separated into a different album because there are issues with recognizing the apostrophe.

#### Expected behavior

These songs were all tagged with Musicbrainz Picard under the same album ID, so the album tag for all songs should be consistent. All songs under the same album should be grouped together and displayed the same.

#### Steps To Reproduce the bug/crash:

1. Load up songs with apostrophes (eg. Red (Taylor's Version))
2. Click "Album"
3. Note that there are 2 entries for the album

#### Logs/Stack Traces:

N/A

#### Screenshots:

![Auxio](https://user-images.githubusercontent.com/79729735/188322547-bb02d9c4-5e67-491a-b63a-b34a03f5e466.jpg)

#### Phone Information:

Pixel 5 GrapheneOS Android 13

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is a known issue with how `MediaStore` likes to re-interpret UTF-8 as a variety of incorrect encodings. Does "Ignore MediaStore tags" work?

**Comment by OxygenCobalt** [comment]
Also, MusicBrainz ID's aren't supported by Auxio yet. That's #202. Currently Auxio tries to group albums by the lowercase album name + the lowercase artist name.

**Comment by ourigen** [comment]
Enabling "Ignore MediaStore tags" fixed it. Thanks for the help, I'll close the issue. Do you know why the encoding is only incorrect for some songs and not all? That's what I found odd

**Comment by OxygenCobalt** [comment]
I'm going to assume some of your songs might use Vorbis Comment and ID3v2.4 metadata, while other songs use ID3v2.3. The metadata formats where UTF-8 is recommended (Like vorbis and ID3v2.4) will have this issue, while formats that are limited to UTF-16 (Like ID3v2.3) don't have the issue.

I really want to start work on stabilizing that option soon.
