### ISSUE TITLE
Add new android 13 player support

### ISSUE THREAD

**Issue by muznyo** [OxygenCobalt/Auxio#233]
#### Describe the feature you want to implement:
The new android 13 update changed behavior of music players, [youtube music](https://9to5google.com/2022/08/18/android-13-media-player/) already has new ui

#### Is your feature request related to a problem? Please describe:
The play/resume button is much more noticable.

#### Why do you think this will improve everyone's usage of Auxio?
This feature will make Auxio more up to date.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Already done in 2.6.2/2.6.3.

**Comment by muznyo** [comment]
oh then fdroid version is not updated

**Comment by OxygenCobalt** [comment]
Yes, I didn't consider 2.6.2 well-baked enough, and 2.6.3 is going to take at least a week of show up on F-Droid.

**Comment by muznyo** [comment]
ok, downloading from github then
