### ISSUE TITLE
Problem in widget while song is playing 

### ISSUE THREAD

**Issue by AnujMehto** [OxygenCobalt/Auxio#234]
Hello sir i really like your work but i want to tell you about a bug or something like that, there's a problem in widget where if i had the widget size to the smallest it goes into an disc player type widget which is fine i like that but for some songs it also goes into an text mode like something so can you please make it so it will only appear in text mode cause that one looks more simple and minimalistic. My phone is running on Android 8.1 and i am using an custom launcher (lawnchair 12) but this widget problem also happens in the default launcher 
![Screenshot_2022-09-06-18-59-36-41](https://user-images.githubusercontent.com/91065049/189147837-6de4051c-7ea7-4d3b-99e3-ce82b1b42020.png)
![Screenshot_2022-09-06-18-59-28-76](https://user-images.githubusercontent.com/91065049/189147854-751272e5-8694-4420-b2cb-961b36e68c7c.png)
![Screenshot_2022-09-06-18-59-04-43](https://user-images.githubusercontent.com/91065049/189147867-a20b847b-6791-47d1-81ba-f4f938001ec6.png)
![Screenshot_2022-09-06-18-58-59-57](https://user-images.githubusercontent.com/91065049/189147872-b341cad0-a4cc-4fb2-9fbc-1ac7bec1f1fe.png)

**Comment by AnujMehto** [comment]
Well sorry I didn't specify that this isn't an samsung actually it's an
oppo phone (oppo A3S) i am using an launcher and using samsung icons on it.
Well i discover something that in default launcher at the minimum size the
widget is looking like that disc type and also at the larger then that but
after that at every size it's the text type widget so that means it's only
glitching while using an 3rd party launcher i think this isn't an big issue
so no need to fix things 🙂 anyways love your work

**Comment by OxygenCobalt** [comment]
Oh, that's actually a bit more expected. The idea is that a 2x3 widget is the disc widget, taller widgets are the text widget, and shorter widgets are the text widget you see. It's hard to get that size calculation to perfectly follow that behavior though, as the grid size is different between devices and launchers.

**Comment by AnujMehto** [comment]
Well i think making it so that only the text widget will show up is a good
idea cause the disc widget just doesn't quite seem to fit in the home
screen and the text widget would also give an clean look if you stack some
apps around the widget. just a suggestion
