### ISSUE TITLE
Triple press of media button doesn't skip song back 

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#237]
#### Describe the bug/crash:
clicking the media button on a bluetooth device/wired headphones doesn't go back a song as it should, but goes one song forward and pauses playback 

#### Expected behavior
tripple clicking media button should go 1 song back. all other players im aware of support this.

#### Steps To Reproduce the bug/crash:
1. play something over bluetooh with your speaker connected (i have a jbl go 1)
2. tripple click the media button.

#### Phone Information:
Samsung Galaxy M21 Android 12 Oneui 4.1

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I don't roll my own media button code, and I can skip back just fine with my earbuds. Closing this as device-specific.
