### ISSUE TITLE
Queue drops additions/deletions when unshuffling

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#240]
#### Describe the bug/crash:
After making a queue out of 2 albums, and hitting the shuffle on and off, queue is only one of the albums

#### Expected behavior
Queue would stay the same length and mix songs of the 2 albums

#### Steps To Reproduce the bug/crash:
1. Make queue by playing and album and adding another with Play Next or Add to Queue
2. Click on shuffle button twice
3. See queue is shorter than expected

#### Screenshots:
( i have a video of the bug but it won't let me upload because of size and im on cell data. can upload later if needed)

#### Phone Information:
Samsung Galaxy M21 A12 OneUI4.1

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Yep, this is a known quirk stemming how unshuffling a queue actually makes Auxio read the list of songs from whatever it's playing from instead of re-order the current queue.

I'll be forced to change it with #110 anyway, so may as well change it now.

**Comment by OxygenCobalt** [comment]
Okay, I knocked this out really quickly. Note that unshuffling the queue is still a bit wonky since it's relying on the sorting that you use in the genre/artist/album ui depending on the context. I'll get to that in #110 when I'm forced to remove it too.

**Comment by KraXen72** [comment]
how do you mean unshuffling? i hit the shuffle button twice to "shake" up the queue after adding new stuff that comes in order

**Comment by OxygenCobalt** [comment]
"Unshuffling" means what occurs when you turn off the shuffle button without turning it on again. @KraXen72
