### ISSUE TITLE
The album is divided into separate tracks if the track has different authors

### ISSUE THREAD

**Issue by shpatter** [OxygenCobalt/Auxio#241]
If there are different authors in the album, the tracks are divided into different tracks, even though they are from the same album and the metadata of the tracks indicates that the album was created by different artists.

**Comment by OxygenCobalt** [comment]
I think this is related to #195. Auxio doesn't quite support multiple artists yet, only single artists. Multiple artist tags are currently concatenated into a single artist value, which leads to multiple albums. I'm working on it.
