### ISSUE TITLE
Add toggle to load non-music

### ISSUE THREAD

**Issue by Donkey-Doug** [OxygenCobalt/Auxio#246]
#### Describe the feature you want to implement:

By default Auxio seems to only detect audio in the downloads folder. I tried to add some folders, but on Android 12 you cannot add the downloads folder to included paths. This means that I have two options:

- Use default settings amd only have access to audio in downloads folder
- Manually include and exclude paths and lose access to songs in download folder.

Please make it possible to scan system wide for audio.

#### Is your feature request related to a problem? Please describe:

Cannot discover all my audio in Auxio.

#### Do other music players handle this? If so, how?

VLC media players scans the entire device.

#### Why do you think this will improve everyone's usage of Auxio?

Discoverability ensures all media can be played easily. 

#### Due Diligence:
- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [X] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [X] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Auxio uses the `IS_MUSIC=1` selector in order to get rid of ringtones from appearing in the library, with the secondary consequences of also not indexing podcasts and sound recordings. Since Auxio plays music, I see this as okay, as music files should be in the `Music` folder. 

I have been considering adding an additional toggle to the "Music folders" setting that would allow one to turn off the selector. There is just not a lot of demand for that though.

Is there any reason you want Auxio to get music from sound recordings?

**Comment by Donkey-Doug** [comment]
I record sound often, but the default audio recorder playback interface is extremely basic (only play/pause). Perhaps add another tab for "recordings", such that music and recordings are not mixed.

**Comment by OxygenCobalt** [comment]
Auxio plays music. It's not a general-purpose audio player, as different audio types have different UI expectations. The most I'm willing to do is add the aforementioned toggle so Auxio can treat any audio as "music".

**Comment by Donkey-Doug** [comment]
The toggle is fine then. Would be very much appreciated and should be easy to implement.

**Comment by OxygenCobalt** [comment]
Okay, sounds good.

**Comment by Donkey-Doug** [comment]
@OxygenCobalt You completed this issue a while ago (and many others) but did not release an updated version of the app yet. Some general advice from me would be to release updated more frequently, for example, monthly.

**Comment by OxygenCobalt** [comment]
2.6.4 was a hotfix for some annoying crashes I found out. Everything else is set for a major 3.0.0 release that has, yes, accrued a bunch of feature additions. However, often I tend to focus a particular update around a set of changes I want to make, which leads to the additions becoming interlocked and hard to untangle into smaller and more frequent updates.
