### ISSUE TITLE
"Up next" Queue UI improvement suggestion

### ISSUE THREAD

**Issue by Donkey-Doug** [OxygenCobalt/Auxio#247]
#### Describe the feature you want to implement:

The app has a really polished UI. I saw something in pulse music player that I prefer over the current implementation of Auxio. Maybe other people agree.

Instead of the text "Queue" at the bottom of the now playing view, show the text "Up next [Song name]" Clicking or swiping on "up next" opens the queue.
 
See screenshot:
![Screenshot_20220923-125044_Trebuchet](https://user-images.githubusercontent.com/50382414/191945813-436b6dfa-c973-4af3-86dd-f9da62607253.png)

#### Is your feature request related to a problem? Please describe:

UI refinement

#### Do other music players handle this? If so, how?

Pulse music player

#### Due Diligence:
- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [X] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [X] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
"Queue" is used here because you can view next and previous items, so switching it to "up next" wouldn't make any sense. Moreover, I think the "peeking" behavior you want will be covered by #94 (The implementation details are still being worked out).
