### ISSUE TITLE
Option to not create a queue

### ISSUE THREAD

**Issue by Donkey-Doug** [OxygenCobalt/Auxio#248]
#### Describe the feature you want to implement:

Whenever I play a song on my device, all other songs are automatically added to a queue. If issue #246 is getting implemented, it does not make a lot of sense to aoways create a queue. For example, if I replay a recording then it would be strange to auto-play some music or the next recording when it is done.

#### Is your feature request related to a problem? Please describe:

Autoplay can be annoying sometimes.

#### Why do you think this will improve everyone's usage of Auxio?

Just a toggle to only play one audio file instead of creating a queue should be easily implemented.

#### Due Diligence:
- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [X] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [X] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Covered already by #93 I think. I want to add some "Play selected" option that only creates a queue from the selected songs. So, in your case, you could select a single track and use "play selected" to just make a queue from that.

**Comment by Donkey-Doug** [comment]
@OxygenCobalt Would it then be possible to disable autoplay? Thus not automatically play the next song in the queue?

**Comment by OxygenCobalt** [comment]
I think that's possible by:
1. Enabling "Pause on repeat" in settings
2. Changing the repeat mode to repeat once

That will cause the track to repeat, but also pause, preventing the queue from going forward. This is the preferred solution since, again, Auxio is designed to play music and thus it's UI isn't optimized for other uses.
