### ISSUE TITLE
Can't detect new mp3 file

### ISSUE THREAD

**Issue by NSTAdventure** [OxygenCobalt/Auxio#249]
#### Describe the bug/crash:
Your app can't detect my new downloaded mp3 file it's really horsemen of annoyance to me

#### Expected behavior
App should detect newly added music mp3 file

#### Screenshots:
![Screenshot_2022-09-24-11-30-47-38](https://user-images.githubusercontent.com/50813528/192080019-d886a67a-5cca-4887-b7b7-9804fbd06d32.jpg)
![Screenshot_2022-09-24-11-30-56-09_1](https://user-images.githubusercontent.com/50813528/192080029-41285a03-b76e-4806-99b0-ba84d18accc7.jpg)

(Music called yubatake isn't detected in auxio see the round mark on screenshot)

#### Due Diligence:
- [✓ ] I have checked this issue for any duplicates.
- [ ✓] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [✓ ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by NSTAdventure** [comment]
Try to force auxio to load music from specific folder only isn't working at all before any developer ask me about it -_-

**Comment by OxygenCobalt** [comment]
Have you tried selecting the "Reload music" option in settings? If that does not work, your phone's media database has not updated correctly and I can't help you.

**Comment by NSTAdventure** [comment]
> Have you tried selecting the "Reload music" option in settings? If that does not work, your phone's media database has not updated correctly and I can't help you.

1. Reloading isn't helping
2. Confirmed this your app issues my default mp3 player music is working well without problem

**Comment by OxygenCobalt** [comment]
Yep. The media database has not updated correctly. Your OEM is likely deliberately breaking third-party music players so that you use the built-in music player (Which is probably crammed with ads and tracking). Samsung, Huawei, and Xiaomi in particular do this constantly.

**Comment by NSTAdventure** [comment]
> Yep. The media database has not updated correctly. Your OEM is likely deliberately breaking third-party music players so that you use the built-in music player (Which is probably crammed with ads and tracking). Samsung, Huawei, and Xiaomi in particular do this constantly.

I have idea what about adding a file to a playlist feature sir? That maybe can help

**Comment by OxygenCobalt** [comment]
Nope. Auxio does not read your music folder, it reads data provided by the system. However, if that data is not updated by the system, Auxio cannot know that new music exists *at all.*
