### ISSUE TITLE
Icon for F-Droid

### ISSUE THREAD

**Issue by offa** [OxygenCobalt/Auxio#25]
#### Describe the feature you want to implement:
It turned out, F-Droid doesn't support adaptive icons ([fdroiddata#2426](https://gitlab.com/fdroid/fdroiddata/-/issues/2426)). However, adding a `.png` image to fastlane data should work – at least that's what I understand from the [docs](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#image-file-formats).

#### Is your feature request related to a problem? Please describe:

- [fdroiddata#2426](https://gitlab.com/fdroid/fdroiddata/-/issues/2426)
- #24

#### Why do you think this will improve everyone's usage of Auxio?
A better icon than the placeholder.

#### Due Diligence:

- [x] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I never knew that. I'll do that right now.

**Comment by offa** [comment]
Nice, so let's see whether the next release has an icon :+1:
