### ISSUE TITLE
Do not remember playback state

### ISSUE THREAD

**Issue by Donkey-Doug** [OxygenCobalt/Auxio#252]
#### Describe the feature you want to implement:

Every time I open the app, the song, playback position and queue from the previous time I used the app are remembered. It would be nice to have an option to not remember these settings.

#### Is your feature request related to a problem? Please describe:

I am annoyed by the fact that I keep getting presented with content I do not want to use.

#### Do other music players handle this? If so, how?

I believe most players do not remember the queue and playback position.

#### Why do you think this will improve everyone's usage of Auxio?

I believe just one simple toggle makes the app more user friendly.

#### Due Diligence:
- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [X] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [X] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
This is actually really technically difficult combined with the other playback state settings (TL;DR Race conditions galore), so I don't really want to add such a setting. Sorry.
