### ISSUE TITLE
Floating button

### ISSUE THREAD

**Issue by Donkey-Doug** [OxygenCobalt/Auxio#253]
#### Describe the feature you want to implement:

Make it possible to hide the floating button.

#### Is your feature request related to a problem? Please describe:

I sometimes accidentally hit the key, I do not like staring at buttons I will never use.

#### Do other music players handle this? If so, how?

I don't think most players have a floating button.

#### Why do you think this will improve everyone's usage of Auxio?

It should be easily implemented.

#### Due Diligence:
- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [X] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [X] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I'm going to assume you mean the shuffle button in the main app view. If that's the case, I'll tack this onto #221. You'll eventually be able to customize what that button does specifically or whether to show it outright.
