### ISSUE TITLE
Read music's from other drives.

### ISSUE THREAD

**Issue by ian1ilych** [OxygenCobalt/Auxio#255]
#### Describe the feature you want to implement:
A while I want to get an microSD card to buy it soon, as I realized, does Auxio scan music's from Drivers? And my mind said, No. So I want Auxio to read All the Drivers Connected to the Phone, Example: micros (I think this feature is added so ignore it), USB Drive (some people use usbs to USB charger).

#### Is your feature request related to a problem? Please describe:
The problem is that it can be complicated sometimes, but that how it goes to.

#### Do other music players handle this? If so, how?
Some of them has it.

#### Why do you think this will improve everyone's usage of Auxio?
To hear songs on the drives without having to install another player to play.

#### Due Diligence:
- [ ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [ ] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [ ] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Yes. If it is loaded into the media database, Auxio will load it.
