### ISSUE TITLE
Fullscreen cover themes

### ISSUE THREAD

**Issue by ian1ilych** [OxygenCobalt/Auxio#256]
#### Describe the feature you want to implement:
A theme for the fullscreen cover to be elegant, minimalistic and cool.

#### Is your feature request related to a problem? Please describe:
I'm pretty sure, there are lot of themes to choose from for example: Gradient, Color Matching, etc.

#### Do other music players handle this? If so, how?
Yea, they handled it.

#### Why do you think this will improve everyone's usage of Auxio?
For a little better visuals for everyone to see.

#### Due Diligence:
- [ ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [ ] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [ ] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I do not add alternative playback screens, as it is a slippery slope that eventually leads to there being a dozen types of playback screens that all only work okay.
