### ISSUE TITLE
Stop playback on task removal

### ISSUE THREAD

**Issue by Donkey-Doug** [OxygenCobalt/Auxio#257]
#### Describe the feature you want to implement:

If I pause the music playback and remove the app from recent apps menu, then the media player notification (android 12) should be destroyed as well.

#### Is your feature request related to a problem? Please describe:

I need to manually kill the notification every time I am done listening.

#### Do other music players handle this? If so, how?

Most have an option to always have the notification visible or just kill the app.

#### Why do you think this will improve everyone's usage of Auxio?

It uses space in my notification center and I need to swipe down twice to reveal the X to close the notification. This just is a very annoying experience.

#### Due Diligence:
- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [X] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [X] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
As far as I'm aware, Android can and will kill my activity, even with a foreground service running. This would lead to the notification disappearing seemingly at random when android kills my activity, forcing me to re-open the app to start playback again. Not adding this.

**Comment by fice-t** [comment]
I was just about to open an issue for something like this.

@OxygenCobalt I don't understand the limitation here as I don't know of other apps that sticky their notifications even when the app is closed via the Recent Apps menu.

A quick search yielded this service method which looks like it could be used to implement this without seemingly random disappearing: [onTaskRemoved](https://developer.android.com/reference/android/app/Service#onTaskRemoved(android.content.Intent))

**Comment by Donkey-Doug** [comment]
> @OxygenCobalt I don't understand the limitation here as I don't know of other apps that sticky their notifications even when the app is closed via the Recent Apps menu.

VLC does, but I think it is a bug because the only way to remove the notification is by force closing the app in settings.

**Comment by OxygenCobalt** [comment]
> VLC does, but I think it is a bug because the only way to remove the notification is by force closing the app in settings.

That's because VLC still thinks you can swipe away media notifications. You cannot.

> A quick search yielded this service method which looks like it could be used to implement this without seemingly random disappearing: [onTaskRemoved](https://developer.android.com/reference/android/app/Service#onTaskRemoved(android.content.Intent))

I mean, technically the documentation states that it is called when the user swipes away the activity. If they are being truthful that it's only user-initiated, then this is fine, actually.

**Comment by OxygenCobalt** [comment]
Okay, so I can do this @Donkey-Doug @fice-t, but it requires some changes to the app logic as this behavior allows android to kill the entire app when the task is removed, which results in the playback state not saving and other things not being properly resolved. 

I'll be keeping this open until I'm in a position to do it.

**Comment by KraXen72** [comment]
not entirely sure if this issue would change that, but i for one really like that music keeps playing even when you remove the app from recents list - i click the close all button (in recents screen) a lot and it's extremly infuriating when spotify stops playing just because it's app was swiped away - something auxio does well (continues playing). so if possible, i would prefer if this behaviour was kept. (i can stop the playback by swiping away notification or hitting pause button)

**Comment by OxygenCobalt** [comment]
In this system, if the music is still playing, playback will not stop @KraXen72.
