### ISSUE TITLE
App crash when long click on any song from "Genres" tab

### ISSUE THREAD

**Issue by inothest** [OxygenCobalt/Auxio#258]
#### Describe the bug/crash:
App is crashing when I long clicking on any song from "Genres" tab

#### Steps To Reproduce the bug/crash:

1. Go to tab "Genres"
2. Click on any genre
3. Long click on any song

#### Screenshots:
 
https://user-images.githubusercontent.com/107348155/193141440-25961eba-b221-4613-9370-6bd2513522bf.mp4
 

#### Phone Information:
 Google Pixel 3, Android 11 

#### Due Diligence:
- [×] I have checked this issue for any duplicates.
- [×] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [×] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

https://user-images.githubusercontent.com/107348155/193141440-25961eba-b221-4613-9370-6bd2513522bf.mp4

**Comment by OxygenCobalt** [comment]
Already identified and fixed.

**Comment by OxygenCobalt** [comment]
I'm aiming to release a patch for this issue this weekend.
