### ISSUE TITLE
FLAC files not being indexed

### ISSUE THREAD

**Issue by Tobaganner** [OxygenCobalt/Auxio#26]
#### Describe the feature you want to implement:
Adding FLAC support to Auxio would increase its usability and versatility, while exoplayer doesn't support FLAC out of the box, there is an extension that allows playback of FLAC files.

#### Is your feature request related to a problem? Please describe:
When I open Auxio many of my songs aren't listed because they are in an unsupported format (FLAC).

#### Why do you think this will improve everyone's usage of Auxio?
Adding support for more file types makes Auxio a more capable application without increasing complexity of the UI.

**Comment by OxygenCobalt** [comment]
That's odd. Can you tell me what android version you're using? I know Android 7 and below can't play FLAC files without an extension, but theres nothing about not being able to load them.

**Comment by Tobaganner** [comment]
> That's odd. Can you tell me what android version you're using? I know Android 7 and below can't _play_ FLAC files without an extension, but theres nothing about not being able to load them.

Im using android 11, although I am using grapheneos so that may have caused some compatibility issues

**Comment by OxygenCobalt** [comment]
Are other types of music indexed by Auxio? Reading the GrapheneOS [FAQ](https://grapheneos.org/faq#non-hardware-identifiers) they might have an extra guard against reading user data [such as music] to prevent user tracking.

**Comment by OxygenCobalt** [comment]
As a side note, I've been considering rolling my own ExoPlayer for awhile now. I have a shell script and everything that would automatically set up the library with the FLAC extension, making FLAC work on all android versions. However, the blocker is getting F-Droid to play along and build the project with that special extension. I could implement it as a build script with gradle, but I'm not too familiar with that and I don't think those are powerful enough.

**Comment by Tobaganner** [comment]
> Are other types of music indexed by Auxio? Reading the GrapheneOS [FAQ](https://grapheneos.org/faq#non-hardware-identifiers), it seems that they might have an extra guard against reading user data [such as music] to prevent fingerprinting.

mp3 files are indexed and readable, on other audio players (I was using blackplayer ex), flac files are recognized, and even when I open the file from the files application into auxio, it isn't played

**Comment by OxygenCobalt** [comment]
> mp3 files are indexed and readable

Okay, that's extremely weird. It seems like BlackPlayer Ex doesn't rely on `MediaStore`, so this is probably yet another device-specific quirk with that API. Again. The only other option now is for you to upload an example FLAC file to see if I can reproduce the issue on my own device. If not, I think you might have to take this to the GrapheneOS devs since they may have introduced a bug in `MediaStore` that causes this.

>  even when I open the file from the files application into auxio, it isn't played

Thats expected, if the file wasn't indexed, then Auxio can't play it.

**Comment by Tobaganner** [comment]
> The only other option now is for you to upload an example FLAC file to see if I can reproduce the issue on my own device. If not, I think you might have to take this to the GrapheneOS devs since they may have introduced a bug in `MediaStore` that causes this.
I downloaded the test flac file from here: https://helpguide.sony.net/high-res/sample1/v1/en/index.html

**Comment by Tobaganner** [comment]
>I think you might have to take this to the GrapheneOS devs since they may have introduced a bug in `MediaStore` that causes this.
I think you are right about this, when I go to files and switch to the audio tab, mp3 files are listed but flac is not

**Comment by Tobaganner** [comment]
I found the issue, I had .nomedia files in the flac folders causing them to not be indexed, sorry for wasting your time
