### ISSUE TITLE
A homescreen when you open the app.

### ISSUE THREAD

**Issue by ian1ilych** [OxygenCobalt/Auxio#260]
#### Describe the feature you want to implement:
A new activity view all your favorite, recently added, recently listened songs.

#### Is your feature request related to a problem? Please describe:
To have this type of favorites, you need a m3u type file to store all the favorite songs you had.

#### Do other music players handle this? If so, how?
There are some types of ones that had it, it sure look them good.

#### Why do you think this will improve everyone's usage of Auxio?
To see their favorite songs whenever they want.

#### Due Diligence:
- [ ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [ ] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [ ] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by ian1ilych** [comment]
I misspelled something :(

**Comment by OxygenCobalt** [comment]
I'm am not making a music streaming app. Adding a crude emulation of the algorithmic home screens of Spotify (or similar) is useless.
