### ISSUE TITLE
An alternative to vlc

### ISSUE THREAD

**Issue by missyraja** [OxygenCobalt/Auxio#263]
After auxio i ditched every other offline music player app because of its fast and clean ui. I always wanted something to replace my video player usage. I use mx player a stripped down version and i hate vlc as its slow in loading media and the ui isn't great. 

I hope in future the dev decides to do something like this...

Thanks for auxio

**Comment by OxygenCobalt** [comment]
You're asking one of two things here:
1. For me to extend auxio into a super-player like VLC. This would bloat the app far too much. Auxio plays music.
2. To create an alternative video player in the same vain as Auxio. Sadly, I simply do not have enough resources to do this.

**Comment by missyraja** [comment]
Hey i don't want auxio to have any support for videos. 

I just wanted to say that there is a space similar to what auxio has achieved to audio that can be done for videos. I don't want you to dedicate your time for a single person like me.

**Comment by harishkumarankr2004** [comment]
> Hey i don't want auxio to have any support for videos. 
> 
> I just wanted to say that there is a space similar to what auxio has achieved to audio that can be done for videos. I don't want you to dedicate your time for a single person like me.

Always remember that all of this work is licensed under GPLv3 license so, the time dedicated here will not only be for a single person but anyone in the world to utilise it without any restrictions.

**Comment by missyraja** [comment]
I'm not familiar with open source licence policies. If what you are saying is true. Yes, it belongs to everyone and. I hope someone creates a video player like this in future.

**Comment by harishkumarankr2004** [comment]
> I'm not familiar with open source licence policies. If what you are saying is true. Yes, it belongs to everyone and. I hope someone creates a video player like this in future.

Surprised to see a #THAMIZHAN here

**Comment by missyraja** [comment]
We are everywhere... 😆

**Comment by harishkumarankr2004** [comment]
> We are everywhere... 😆

Could you give your contact?
Matrix?
Email?
Signal?
Whatsapp?

**Comment by missyraja** [comment]
Ok this is going out of topic... So here you go.. maha1314@gmail.com
