### ISSUE TITLE
Index song from .nomedia & dot directories

### ISSUE THREAD

**Issue by AdityaMishra135** [OxygenCobalt/Auxio#265]
#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I rely on the media database, which excludes everything in .nomedia and dot directories. There is no way I can change it.

Why do you want this anyway? Can't you just change your directory names/.nomedia contents?
