### ISSUE TITLE
Micro widgets

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#266]
This is an issue about adding new widget layouts so that Auxio's widget can scale even smaller, down to possibly 1x1.

Google keeps making infuriatingly subtle changes to launcher3 that break Auxio's "minimum size" configuration. This allows the user to resize the widget down to 1x2, 1x1, etc, which often breaks the layout since it's not expected for such a configuration.

So, I'm planning to drop that minimum size configuration and make even smaller layouts. I'm not sure about the extend exactly, but it might be down to 1x2 or maybe even 1x1. It's likely these layouts will be similar in substance to the current smallest layout (The one with only a play/pause button), albeit with more information removed to make it fit.

This feature is not about text-based widgets or anything similar. It's moreso just deriving existing layouts to make them fit into smaller dimensions while still being elegant.

**Comment by OxygenCobalt** [comment]
Actually, this won't be possible for now. Android 13 has an infurating bitmap bug that limits me to only 5 widget layouts. I need to get that resolved first.

**Comment by OxygenCobalt** [comment]
If I am able to do this one day, here's some toy designs that would likely be what the smaller widgets would look like:

![image](https://user-images.githubusercontent.com/65370175/195743635-8941a993-c7c4-48a6-98f5-676caeaa16ec.png)

![image](https://user-images.githubusercontent.com/65370175/195743669-9b9040ce-c184-44c1-8375-7fba21905f86.png)

![image](https://user-images.githubusercontent.com/65370175/195744372-a1fa4639-f1d1-409e-a14c-b97ed681f640.png)

These are not final at all.

**Comment by KraXen72** [comment]
>did anyone say textwidget

**Comment by OxygenCobalt** [comment]
Never mind, turns out I can't get these widgets working at all below Android 31 to widget insanity once again.
