### ISSUE TITLE
Please give us a way to empty the queue

### ISSUE THREAD

**Issue by nobrowser** [OxygenCobalt/Auxio#267]
#### Describe the feature you want to implement:
Provide a way to remove songs from the queue, either one by one or clear the entire queue.

It's really, really hard to believe this basic feature doesn't already exist, but if it does it is not discoverable (by me).

#### Is your feature request related to a problem? Please describe:
Yes, and I describe the problem below. But please understand the operative word is "related". It's *not* like
the need for the feature would disappear with the problem.

When I started Auxio I had some ghost audio files - files that have been deleted but persisted in the media
database. It's quite easy for this to happen, just delete the files with anything else than "Google Files". I accidentally queued them, and Auxio started trying to play them, and failing in a fast loop (this continued even when I tried to pause playback). I could do absolutely nothing to stop it other than Force Stop the app. Had there been a button or menu item to clear the queue, I think it would've broken the loop.

#### Do other music players handle this? If so, how?
Vanilla Music has been my usual app until now. It has a menu item (from the 3 dot menu on the queue screen) to clear the queue. 

#### Why do you think this will improve everyone's usage of Auxio?
Even forgetting about the fsckup above, I think this is quite esssential. Another, more quotidian scenario:

- I enqueue a long album and start listening to it
- But I don't have time to finish listening
- Next time I'm in a different mood and I want to listen to something else.

I'd think this is quite common (?)

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
You can swipe them away to delete them. It's hard to discover, but having it front-and-center is cluttered. I can maybe add clearing the entire queue if I can make it coherent.

As for the skipping issue, I'm aware of it.

**Comment by kevinclevenger** [comment]
Please reopen this. Hitting the very prominent shuffle button in the lower right apparently adds the entire library to the queue, with no practical way to clean the queue of the 1000's of tracks it except clear cache and storage.

**Comment by OxygenCobalt** [comment]
Do you want to stop playback entirely @kevinclevenger, or just play something else. If I unintentionally played something while trying to play something else, I would just pause and then play what I actually wanted to play.

**Comment by kevinclevenger** [comment]
@OxygenCobalt It really has nothing to do with playback per se, the needed functionality is a way to clear the queue completely. for example, you've added 12 albums to the queue but change your mind and want another genre. Do you really want to have to left-swipe 150 tracks? 

Have a look at Pulsar for an example of being able to clear the play queue.

**Comment by OxygenCobalt** [comment]
Oh, so what you really want is the ability to stop playback entirely. I've been trying to find ways to implement that, and the queue UI does actually look like an okay place to do that.

**Comment by OxygenCobalt** [comment]
Actually, I still don't get what you mean. I can't interpret whether you want:
- To clear the entirety of the queue (In this case, couldn't you just play something else?)
- To easily clear several songs at once from the queue (i.e multi-select in the queue view)

**Comment by e-zk** [comment]
Sometimes when I'm done listening to the music I'm currently listening to I'd like to create a fresh new queue of other music. 

So for this I'd also like a clear queue option. Something that'll clear it so I can then add songs one-by-one/individually.

**Comment by OxygenCobalt** [comment]
Yeah, that's something I'm planning @e-zk. It's going to be available through the new selection functionality and be called "play selected" or "shuffle selected". The issue is that the queue system is not properly set up for that just yet, as it still likes consistent sources of music.
