### ISSUE TITLE
Change Font Size in UI

### ISSUE THREAD

**Issue by chezui** [OxygenCobalt/Auxio#268]
#### Describe the feature you want to implement:
Be able to increase/decrease font size for the UI in the app.

#### Why do you think this will improve everyone's usage of Auxio?
 I'm using Auxio on a flip phone and the screen is small, being able to have smaller font would make it more usable. Could be helpful for people who have hard time reading smaller fonts too.

#### Due Diligence:
- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [X] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [X] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Android already has a system setting for this.
