### ISSUE TITLE
Better label dynamic theme in options

### ISSUE THREAD

**Issue by rhynec** [OxygenCobalt/Auxio#269]
#### Describe the feature you want to implement:
In the color scheme picker, it isn't very clear that the last color on the list represents the MaterialYou/Dynamic theme for Android 13. Maybe it'd be better to add button next to cancel/ok labeled as "Dynamic Theme", which pressing enables the feature (or a separate toggle outside the color picker).

#### Why do you think this will improve everyone's usage of Auxio?
More clarity in the settings menu.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I guess that's reasonable. I only thew it into the accent picker since it's the easiest option.

**Comment by OxygenCobalt** [comment]
Actually, I feel like adding this would add too many bugs for it to be reasonable. It's already default on Android 12 onwards.
