### ISSUE TITLE
Remove network permission

### ISSUE THREAD

**Issue by Glitchy-Tozier** [OxygenCobalt/Auxio#27]
#### Describe the bug/crash:

In the description, it's said that this player has no internet connectivity whatsoever. However, there IS a network permission.

In English it would probably be titled "Get network connections".

#### Steps To Reproduce the bug:
1. Go to this app's f-droid page
2. Look at it.

#### Screenshots:

![Screenshot_20210716-081517_F-Droid.jpg](https://user-images.githubusercontent.com/59611881/125901787-6a056143-5c62-4f48-b4cb-b2a4e0e328e3.jpg)
⋮
![Screenshot_20210716-081629_F-Droid.jpg](https://user-images.githubusercontent.com/59611881/125901802-b7620f4e-5c47-441b-a51e-d9563cd9b924.jpg)

#### Due Diligence:

- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
The network permission was side-effect of the addition of ExoPlayer. It was removed in f1f2fcf, so in 1.4.1 it should not be present.

**Comment by Glitchy-Tozier** [comment]
Great, looking forward to that update!
