### ISSUE TITLE
Folders as Playlists

### ISSUE THREAD

**Issue by d00maz** [OxygenCobalt/Auxio#270]
Hey there.

AIMP has this feature where a folder i have files in can be used as "a playlist" which is a great way of sorting media like music/audiobooks etc and this is literally the only function not being available thats annoying me.

"Pick a folder - give it a name - boom, everything inside that folder is now in a new playlist you just named."

Please consider this feature. Thank you for your time and have a great day.

**Comment by OxygenCobalt** [comment]
I can't quite discern what you want. I think it's either:
1. You want a folder view. This has already been rejected.
2. You want an addition to #36 that allows a playlist to be imported from a folder. I can feasibly do this one, albeit I would merge it into the issue.

**Comment by d00maz** [comment]
2nd option is exactly what im looking for.

**Comment by OxygenCobalt** [comment]
Okay, I'll merge this into #36 since it makes more sense there.
