### ISSUE TITLE
Duplicate artists with certain MBID configurations

### ISSUE THREAD

**Issue by alanorth** [OxygenCobalt/Auxio#274]
#### Describe the bug/crash:
I have two albums from one artist, but the artist shows up twice in the library Artists tab. I have checked the names of each in the media tags and they are the same Unicode characters. These albums are FLAC, perhaps that has something to do with it?

#### Screenshots:

![signal-2022-10-29-202107_002](https://user-images.githubusercontent.com/191754/198845139-16b8b5c4-a593-4efe-91ca-50bb0b81ee7f.png)

#### Phone Information:
Pixel 4a. Android 13.

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Curious. I'm assuming you are using 2.6.3 w/Ignore MediaStore tags on, so I don't imagine encoding has much to do with it as much as it is a logic error.

Could I have some sample files? If you don't want to run into copyright issues, just copy the metadata into a silent track.

**Comment by alanorth** [comment]
Strange! I was on latest git master (d6e747cf), but now I went back to v2.6.3 and the duplicate artist is OK (see Батюшка):

![signal-2022-10-30-085022_002](https://user-images.githubusercontent.com/191754/198864628-be00cd5a-f790-4a15-b423-44d5d1cefe47.png)

**Comment by illdeletethis** [comment]
maybe the app disagrees with you on which the real Батюшка is ;)

**Comment by OxygenCobalt** [comment]
@alanorth Hm. Perhaps you missed adding MusicBrainz IDs to all songs made by Батюшка? To Auxio, artists with an MBID and artists without an MBID are considered different artists.

**Comment by alanorth** [comment]
> _maybe the app disagrees with you on which the real Батюшка is ;)_

@illdeletethis it's hilarious, but I also had the same thought! :-D I went so far as to check these two albums and make sure they were from the same Батюшка.

> _@alanorth Hm. Perhaps you missed adding MusicBrainz IDs to all songs made by Батюшка? Auxio considers artists with an MBID and artists without an MBID to be different artists._

@OxygenCobalt you're right! I just checked the MusicBrainz Artist IDs and they are different. These are tagged by Picard, so in this case I guess MusicBrainz's database is wrong.

**Comment by OxygenCobalt** [comment]
Quite interesting. Perhaps you should go and fix the IDs then, haha.

Sadly, Auxio can't really be very lenient with MBIDs, as it would lead to unexpected behavior otherwise. Hence why even one bad tag can cause a weird issue like this.

**Comment by alanorth** [comment]
> Quite interesting. Perhaps you should go and fix the IDs then, haha.
> 
> Sadly, Auxio can't really be very lenient with MBIDs, as it would lead to unexpected behavior otherwise. Hence why even one bad tag can cause a weird issue like this.

Definitely. I just updated my previous comment. Definitely not Auxio's problem! Damn Black death metal politics. :P

**Comment by OxygenCobalt** [comment]
>  Looking at MusicBrainz's tagging of these, it seems to be due to the issue @illdeletethis alluded to, and likely this way for a reason (original band dissolved and two members formed new bands with the same name).

That's super interesting. Gotta plug [this article](https://dustri.org/b/horrible-edge-cases-to-consider-when-dealing-with-music.html) every time a really interesting (yet intentional) behavior pops up like this.
