### ISSUE TITLE
Add perfect looping for audio and crossfading

### ISSUE THREAD

**Issue by Raiyan-AP** [OxygenCobalt/Auxio#275]
#### Describe the feature you want to implement:
Loop audio without delay by default and add an adjustable crossfade slider. 

#### Is your feature request related to a problem? Please describe:
Sometimes I listen to very short songs or samples that loop perfectly if you play it in for example a DAW but Auxio has a slight delay when looping tracks which makes those songs unlistenable. There are also songs that loop perfectly if you have 1 second of crossfade between the loop.

#### Do other music players handle this? If so, how?
Eon Player does this by default where if you put a song on loop it will loop without any delay and Spotify has adjustable crossfading.

#### Why do you think this will improve everyone's usage of Auxio?
People who listen to short songs, songs that loop perfectly, or smooth transitions between songs will be able to listen to them on Auxio.

#### Due Diligence:
- [✔ ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [ ✔] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [✔ ] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Perfect looping is already covered by #110, crossfading is not possible currently with ExoPlayer.

**Comment by OxygenCobalt** [comment]
Okay, slight clarification: I can theoretically do perfect looping right now, but it would only work when looping an individual song. Doing that feels really inconsistent both in UX and in the implementation, hence #110.
