### ISSUE TITLE
Any Guide For Windows

### ISSUE THREAD

**Issue by HNY11** [OxygenCobalt/Auxio#276]
Any Guide for Windows, that how to add those extensions of exoplayer to build the project.

**Comment by OxygenCobalt** [comment]
ExoPlayer does not provide build instructions for windows, and I don't know enough about how the SDK works on Windows to port `prebuild.py`

You could probably use Windows PowerShell to do this, assuming you are building 2.6.3:
- Run the [manual installation steps](https://github.com/google/ExoPlayer/tree/release-v2/extensions/flac#build-instructions-linux-macos) for the flac extension.
- Run `./gradlew extension-flac:bundleReleaseAar` and move the output `.aar` file to the `app/libs` folder.
