### ISSUE TITLE
Option to disable lock screen album cover

### ISSUE THREAD

**Issue by srtopster** [OxygenCobalt/Auxio#278]
I would like for you guys to implement (if possible) an option to disable the lock screen album cover when the app is playing<br>
<img src="https://i.imgur.com/6g1zbR5.png" height=500px>

**Comment by OxygenCobalt** [comment]
I can't do this on my end without jeopardizing other functionality. AFAIK, most android distributions have an option to turn it off, albeit it can be really hard to find.

**Comment by illdeletethis** [comment]
wow, i wish i could get this feature back
my first android phone had lock screen album art, was lovely, but none of the later ones did and i haven"t been able to find that setting
