### ISSUE TITLE
Sleep timer features

### ISSUE THREAD

**Issue by kuchingneko28** [OxygenCobalt/Auxio#279]
#### Describe the feature you want to implement:

Hi

I want to request some features name Sleep Timer like Sleep option on Spotify. So it's a timer option that can stop a music automatically after time that we set.

#### Is your feature request related to a problem? Please describe:

I don't think so

#### Why do you think this will improve everyone's usage of Auxio?

Most people using that for sleep music i think is really useful people will like it.

Maybe you can add that to on Auxio i really appreciate that

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
[I personally get no use](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) from sleep timers, so I will likely not add them. Sorry.

**Comment by Martysh12** [comment]
P.S, you can download a sleep timer app to pause playback of music after a certain amount of time. https://github.com/SimonMarquis/SleepTimer
