### ISSUE TITLE
[Support] release fix for slow "Loading your music library…"

### ISSUE THREAD

**Issue by foss-** [OxygenCobalt/Auxio#285]
Since I don't have a direct contact asking via an issue, feel free to close after reading.

After #128 got closed I was very happy to see music cashing improved in https://github.com/OxygenCobalt/Auxio/issues/207#issuecomment-1257399032

Since I use this I am seeing a "Loading your music library…" on many starts (whenever a change in music library has happened which was then synced via syncthing, which is very often.

In real life use this means, I am about to leave home, want to start music in auxio, launch it and see the loading screen, which means I cannot access my music library. Since this library is rather large bit above 35k tracks, the loading takes several minutes. This is a bit frustrating.

Seeing how fast loading is in https://github.com/OxygenCobalt/Auxio/issues/207#issuecomment-1257399032 I am very excited about that change which is planned for 3.0.

I know there is no use in asking about ETAs in software development, but is there any chance to port this to 2.x if 3.x is still a bit away? Speeding up loading music library would make a huge difference for me with my Auxio usage.

I get this is a bit of a pet bug as for users with smaller libraries the current behavior may not be so problematic.

**Comment by OxygenCobalt** [comment]
The issue is that music caching is so intertwined with all of the other 3.0.0 changes that it's near-impossible to backport it to 2.0.0. I could only do 2.6.4 since it was relatively easy to bandaid the issues I wanted to hotfix.

I see a 3.0.0 being released some time in December when I have nothing going on.
