### ISSUE TITLE
Fix (& improve) repetition options

### ISSUE THREAD

**Issue by Glitchy-Tozier** [OxygenCobalt/Auxio#29]
#### Describe the bug:

This option (look at the left) probably does, what it should. It jumps to the next song when the current one is finished. The symbol is debatable, but otherwise it works fine:
![Screenshot_20210717-070933_Auxio.jpg](https://user-images.githubusercontent.com/59611881/126026676-6644fec4-2b7c-44e0-891c-fc462495d56c.jpg)

___

This symbol ALSO doesn't loop the song. It seems to work just as the first one does:
![Screenshot_20210717-071013_Auxio.jpg](https://user-images.githubusercontent.com/59611881/126026694-916ed34c-8e74-4b4b-8c8d-a419a5b59fe8.jpg)

___

This symbol loops the song forever (or at least 3 times) instead of just once.
![Screenshot_20210717-071024_Auxio.jpg](https://user-images.githubusercontent.com/59611881/126026708-be5577ca-f403-4e88-a8bc-cd10c8162029.jpg)

___

Sometimes people don't want to binge through their music, but instead only listen to one track and then have the playing stop until they want to listen to the next track. It can be annoying to immediately be bombarded with a different song.
I suggest adding an option that lets the user play a song, and then pauses (and rewinds) the song when it's done playing.

#### Screenshots:

![Screenshot_20210717-072414_Auxio.jpg](https://user-images.githubusercontent.com/59611881/126026792-d0350d85-d19e-48d6-9594-30a84ebcc96c.jpg)

#### Phone Information:

Samsung Galaxy S9
Android 10

#### Due Diligence:

- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Oh. After #13, I assumed that the "none, loop playlist, then loop forever" design was the preferred method of repeat design. If I understand, you want the "Loop Forever" option to pause the song every time it loops? If that's the case, I can add a toggle for that behavior in the settings menu.

**Comment by Glitchy-Tozier** [comment]
1. Yes, It would be great to see another option that rewinds and pauses the song after it's done.
1. regarding the rest of your message, I'm not sure I fully understand your comment.
Is there a difference between [black] and [blue]?

**Comment by OxygenCobalt** [comment]
Basically:

[black] - Loop the playlist, but pause when it loops
[blue] - Loop the playlist, continuing playback when it loops
[blue 1] - Loop the song forever.

I'll add an option to the "Behavior" part of the settings menu that toggles this change. It will still be represented as [loop 1], but instead of playing immediately after looping, it will just rewind and pause, like you said.

**Comment by Glitchy-Tozier** [comment]
Thank you for the explanation. The change you described sounds great, looking forward to using it!  :)

**Comment by Glitchy-Tozier** [comment]
It could also be added as one of the regular options (it could be a pause icon or a pause icon inside the arrows), but if you prefer using the settings, that's fine too.

**Comment by OxygenCobalt** [comment]
I usually choose the settings for two reasons:

1. Your preferred loop behavior tends to apply to a subset of users. I prefer keeping Auxio sensible by default and moving the quirks to the behavior menu, so thats where behavior additions tend to go. If theres sufficient demand for a dedicated mode for this specific behavior, it would likely be upgraded to one. 
2. There's not a ready-made icon for such a mode, meaning that I would have to create my own. Not impossible [I did it with the sorting icons], but hard.

**Comment by Glitchy-Tozier** [comment]
Understood, lets go the settings-route then!
