### ISSUE TITLE
FTP support

### ISSUE THREAD

**Issue by terr72** [OxygenCobalt/Auxio#290]
#### Describe the feature you want to implement:
It would be nice to have support for files stored on a FTP server, e.g. on a NAS.
Ideally the amount of concurrent connections should be configurable, since typical FTP servers integrated in SOHO routers limit these.

#### Do other music players handle this? If so, how?
VLC for Android and foobar2000 mobile both support FTP sources.

#### Why do you think this will improve everyone's usage of Auxio?
Many people store their music on a NAS.
SMB support would be an alternative, but from what I've read there are no "turn-key" GPL libraries for Android, which could be used for implementation.

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
I don't think ExoPlayer has any support for FTP streaming, and I don't want to write my own netcode to implement it myself (Protocol, File Downloading, Caching, etc.). 

SubSonic servers (For example, [Navidrome](https://github.com/navidrome/navidrome)) are far superior for remote music streaming anyway. If I were to add support for any kind of streaming, it would almost certainly be through SubSonic, albeit my library is not large enough to warrant that right now.
