### ISSUE TITLE
Replaygain may stop working after playing a non-replaygain-tagged file

### ISSUE THREAD

**Issue by bodayw** [OxygenCobalt/Auxio#293]
#### Describe the bug/crash:

~Under the "Songs" tab of media library,~ a replaygain tagged file may sometimes played with original volume (without replaygain applied).

~Seems only can happen when replaygain strategy is set to "Prefer album" or "Prefer album if one is playing", although not always.~

Seems only can happen when the file is played after a non-replaygain-tagged file, or a replaygain-unsupported file (? .m4a here, see #292).

Never saw this happen when the file is played after another replaygain-tagged & supported (.mp3) file.

~Never saw this happen under the "Album" tab.~
#### Expected behavior

Files should always played with replaygain applied if properly tagged.
#### Steps To Reproduce the bug/crash:

~1. Settings - Audio - ReplayGain strategy set to "Prefer album" or "Prefer album if one is playing"~
~2. Switch to "Songs" tab in media library~
3. Play a non-replaygain-tagged file for a couple of seconds
4. Switch to play a replaygain-tagged file, and there is a good chance that it's played with original volume without replaygain applied.

#### Phone Information:

Redmi Note 10 Pro (China), MIUI 13.0.11 (based on Android 12)
#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
That's really strange.

- "Prefer album if one is playing" -> Are we in an album? If so, use the album gain.
- "Prefer album" -> Always use album gain, falling back to track gain if it is not available.
- "Prefer track" -> Always use track gain, falling back to album gain if it is not available.

Can I have a sample file? You can remove the audio, all I want are the tags. I found one logic bug after taking a quick glance at the ReplayGain system, but it couldn't be the cause of the bug.

**Comment by OxygenCobalt** [comment]
Oh. That might be a race condition. Will try to reproduce it on my end.

**Comment by OxygenCobalt** [comment]
Okay, I can't seem to reproduce this sadly, even with your sample files. I'm going to have to assume this is a device-specific issue.

**Comment by bodayw** [comment]
Just did some more tests, and I can confirm that this seems has nothing to do with file types (either m4a or mp3 here), just that if it has replaygain tags or not.

That is, the issue only happens (about 50% of the time) when I play the (RG-tagged) file right after playing a non-RG-tagged file (either it's m4a which is not supported yet, or it's a mp3 without RG tags).

Funny thing is that with the upcoming new version with m4a RG support, this issue might never be triggered because my entire library are RG-tagged...i.e. I might never notice this if we don't have the m4a `----` issue.

**Comment by OxygenCobalt** [comment]
Extremely strange. I tried doing it as well (Playing one of my files, which do not use RG, and then playing one of your files right after), and judging by the logs it should be applying the gain.

If possible, could you try to take a logcat using that debug build you provided? If you don't know how, here's a guide:

```
<!-- 
If possible, provide a stack trace or a Logcat. This can help identify the issue. 
To take a logcat, you must do the following:
1. Use a desktop/laptop to download the android platform tools from https://developer.android.com/studio/releases/platform-tools.
2. Extract the downloaded file to a folder.
3. Enable USB debugging on your phone [See https://developer.android.com/studio/command-line/adb#Enabling], and then connect your
phone to a laptop. You will get a prompt to "Allow USB debugging" when you run the logcat command. Accept this.
4. Open up a terminal/command prompt in that folder and run:
	- `./adb -d logcat | grep -i "[DWE] Auxio"` in the case of a bug [may require some changes on windows]
	- `./adb -d logcat AndroidRuntime:E *:S` in the case of a crash
5. Copy and paste the output to this area of the issue.
```

There should be some logs formatted like "Applying ReplayGain Adjustment: ??db". This should allow you to see what Auxio thinks your ReplayGain adjustment is at a given time. If the adjustment seems correct (not 0.0db or something weird like that), but the gain isn't being applied, then the issue is much deeper.

**Comment by bodayw** [comment]
> If the adjustment seems correct (not 0.0db or something weird like that), but the gain isn't being applied, then the issue is much deeper.

Unfortunately (?) this is the case.

So with the debug apk I got this:

```
>adb logcat | findstr /i "replaygain"
12-16 14:32:34.090  7184  7184 D Auxio.ReplayGainAudioProcessor: Using track gain
12-16 14:32:34.090  7184  7184 D Auxio.ReplayGainAudioProcessor: Applying ReplayGain adjustment -13.13db
12-16 14:32:54.247  7184  7184 D Auxio.ReplayGainAudioProcessor: Using track gain
12-16 14:32:54.247  7184  7184 D Auxio.ReplayGainAudioProcessor: Applying ReplayGain adjustment -11.76db
12-16 14:33:00.373  7184  7184 D Auxio.ReplayGainAudioProcessor: Using track gain
12-16 14:33:00.373  7184  7184 D Auxio.ReplayGainAudioProcessor: Applying ReplayGain adjustment -13.13db
12-16 14:33:41.248  7184  7184 D Auxio.ReplayGainAudioProcessor: No ReplayGain tags present
12-16 14:33:41.248  7184  7184 D Auxio.ReplayGainAudioProcessor: Applying ReplayGain adjustment 0.0db
12-16 14:33:44.836  7184  7184 D Auxio.ReplayGainAudioProcessor: Using track gain
12-16 14:33:44.836  7184  7184 D Auxio.ReplayGainAudioProcessor: Applying ReplayGain adjustment -13.13db
```

I played the test file (has -13.13 dB track gain) 3 times, while playing two other files (w/ and wo/ RG) in between. Log always reports expected RG values, however on the first (see below) and last occasion the test file sounds much louder as if no RG is applied.

While I said earlier that this happens about 50% of the time, that is probably not accurate at all. During one of this round of testing, I couldn't reproduce the issue playing the test file 10 times straight.

Also maybe worth noting that I got the above results by killing the app in the background and restart it, and it happened on the very first try - so it doesn't have to follow a non-RG-tagged file.

**Comment by OxygenCobalt** [comment]
> While I said earlier that this happens about 50% of the time, that is probably not accurate at all. During one of this round of testing, I couldn't reproduce the issue playing the test file 10 times straight (switching back and forth).

Feels a lot like a race condition (or some other time-dependent bug) somewhere within the audio processing code of your phone. Auxio has to tamper with the raw PCM data in order to implement ReplayGain, which I'd imagine could lead to instability like this. 

> Also maybe worth noting that I got the above results by killing the app in the background and restart it, and it happened on the very first try - so it doesn't have to follow a non-RG-tagged file.

Perhaps that's can avenue I can take to reproduce it. I'll need to make a test file with a much bigger adjustment so I can test this discrepancy.

**Comment by bodayw** [comment]
Alright, so with the new 3.0.0 test build (and the R2 build), I can no longer reproduce this issue...Good news, maybe?

FYI about two weeks ago, I could still reproduce this issue with the MP4-RG-test-build in #292 - I actually kept using that debug build for a while (so I can have RG support with my entire music collection).

**Comment by OxygenCobalt** [comment]
I've actually figured out why this is occuring.

As an optimization, I turn off ReplayGain audio processing when there is nothing to adjust. When I then started to apply an adjustment, I was under the impression that I could then call a method to tell ExoPlayer "My activation status has changed, please check me again". Turns out that this does not occur, and so the audio processor will remain inactive up until another track is loaded.

I managed to reproduce this by playing a track with no ReplayGain with no pre-amp configured, and then modifying the pre-amp setting. The volume won't change no matter what you do.

Now I'm stuck having to ask the ExoPlayer developers how to actually resolve this. It might not even be implemented, which would thus require me to either disable the optimization or accept the bug.

**Comment by OxygenCobalt** [comment]
Waiting on https://github.com/google/ExoPlayer/issues/10896 to resolve this.

**Comment by bodayw** [comment]
Really appreciate your effort for digging into this.

I wonder why I cannot reproduce the issue anymore with v3.0.0, then...just coincidence?

**Comment by OxygenCobalt** [comment]
3.0.0 completed ReplayGain support for more or less your entire music library. This bug seems to manifest when a Song with *no* adjustment is played, and then a Song *with* an adjustment is played. If you always have ReplayGain adjustments, you don't need to worry.

**Comment by bodayw** [comment]
Yup, I'm aware of that, so I deliberately put a test file with the RG tags stripped just for testing, and I still couldn't reproduce it.

**Comment by OxygenCobalt** [comment]
Oh. Weird. Since I can still reliably reproduce a similar behavior with the pre-amp configuration, I'm going to keep this issue open as I'm almost certain the activation issue caused the discrepancy.
