### ISSUE TITLE
audio support in .dsd .dsf .ape .wv format

### ISSUE THREAD

**Issue by Luiz-bro** [OxygenCobalt/Auxio#295]
audio support in .dsd .dsf .ape .wv format

**Comment by OxygenCobalt** [comment]
No [ExoPlayer](https://exoplayer.dev/supported-formats.html) support, so I can't support it either. I'd imagine you should be able to losslessly convert those files to FLAC with [ffmpeg](https://ffmpeg.org/), which should be supported by Auxio.
