### ISSUE TITLE
Open a music file through a file provider

### ISSUE THREAD

**Issue by JosephPelletier** [OxygenCobalt/Auxio#30]
#### Describe the feature you want to implement:

Auxio should be capable of requesting access to a folder via the android files app (the new standard), instead of asking for access to the entire local storage (the old standard), and accessing the files via that interface. This will allow users to play music from any location on or off the device, including but not limited to, local folders other than 'Music' and  various cloud services, like nextcloud, onedrive, or google drive which expose their storage to the device file manager.

[TEdit](https://github.com/ATryder/TEdit/) and [KeePassDX](https://github.com/Kunzisoft/KeePassDX) use this method to access files (if i did a terrible job explaining what I mean, checking one of the apps may help)

#### Is your feature request related to a problem? Please describe:

The problem, auxio assumes the location of the music. Firstly that is is stored on the local device, secondly that it is in a particular directory. As of right now this problem seems to be universal among similar apps.

#### Why do you think this will improve everyone's usage of Auxio?

Many users may wish to store their music on a remote filesystem (cloud) instead of syncing to the music folder of their android device and wasting gigabytes of spage. 

#### Due Diligence:

- [y ] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
As far as I'm aware, requesting access to a folder is not the "new standard" for media apps.  According to [This official article](https://developer.android.com/training/data-storage/shared/media). `MediaStore` is the **recommended** way to index a devices media.

What I believe you're talking about is the Storage Access Framework, which is more-so meant for file-picking tasks. On top of that, streaming media from the internet is not the same as streaming a file. One is a simple download operation, while the other is a much more complicated process that would require refactoring much of Auxio to accommodate.

Unless I'm misunderstanding something here, I can't implement this.

**Comment by JosephPelletier** [comment]
Yes the storage access framework is what i am talking about (thanks for the name) and you did misunderstand me.

I am not suggesting you implement media streaming, I'm suggesting that you implement an SAF Client app that can be used optionally. 
described here](https://developer.android.com/guide/topics/providers/document-provider)
- Client app—A custom app that invokes the ACTION_CREATE_DOCUMENT, ACTION_OPEN_DOCUMENT, and ACTION_OPEN_DOCUMENT_TREE intent actions and receives the files returned by document providers.

The SAF should call the document provider's code to retrieve the document (a music file in this case) from local storage or the network. Neither your app nor the SAF needs to be network aware since the Document Provider handles it if applicable. Document providers do not have to be cloud applications either, Termux is also a document provider, it provides access to the termux user's home folder which is part of the app's private storage. 

my understanding is that this is relatively simple to do and should only require change to the code that opens media files, and of course the related UI.

If it sounds too sketchy or complex, ill take a crack at it if i get the time in the next couple months. I have tons of programing experience, but almost none with android, so we will see.

**Comment by OxygenCobalt** [comment]
Okay, so you're saying that I implement a file-picker action that opens a music file through a provider? I have the opposite workflow implemented [e.g opening a music file through a file picker will open Auxio], but not this. I'll try to see what I can do.

**Comment by OxygenCobalt** [comment]
Looking back on this, I really don't see the point in this. You can open music *from* the file manager, and other theoretical uses [like streaming] are more aligned with the possible idea of converting Auxio to a SoundPod client. I also have no clue where to add this. Sorry.
