### ISSUE TITLE
FLAC files not recognized on Android 13

### ISSUE THREAD

**Issue by dumbuz** [OxygenCobalt/Auxio#304]
### Describe the Bug/Crash

No music at all is showing up in the app

My music is in the "Music" folder on the root of the app, I have double checked that I am set to include that folder and not exclude it. Auxio has 'Music and audio' privileges. I have tried resetting both the cache for Auxio and all user data. 

All of my music is in FLAC and in sub folders. Ex:
/Music/Arctic Monkeys/AM/11 - Knee Socks.flac

I have tried adding the specific subfolders to Auxio (ex: /Music/Arctic Monkeys/AM/) and this still does not work.

### Describe the intended behavior

All songs show up

### What android version do you use?

Android 13

### What device model do you use?

Pixel 6a, non-rooted, stock android
build TP1A.221105.002

Auxio is version 3.0.0
Issue also occurs on older version, 2.6.4

### Relevant log output
This is all I can find relating to Auxio.
```shell
12-31 00:52:01.460 15584 15617 E Auxio.Indexer: No music found
```

When attempting to grant Auxio the `READ_EXTERNAL_STORAGE` permission, it complains saying that Auxio never requested this permission.
```Package org.oxycblt.auxio has not requested permission android.permission.READ_EXTERNAL_STORAGE```
Auxio has the `READ_MEDIA_AUDIO` permission. I do not know how to give it the `READ_EXTERNAL_STORAGE` permission because it never requested it. I cannot find a way to request this permission manually from within Auxio

### Duplicates

- [x] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Very weird issue.

First, `READ_MEDIA_AUDIO` is the new storage permission that should be used on Android 13+. `READ_EXTERNAL_STORAGE` won't work anymore as far as I'm aware. You can test [2.6.1](https://github.com/OxygenCobalt/Auxio/releases/tag/v2.6.1) to ensure that the differing permission is not the cause of the issue.

If that doesn't work, your phone is either not recognizing FLAC files or not creating a media database at all. The former should not occur, but the latter could occur due to Android insanity.

**Comment by dumbuz** [comment]
This seems to be an issue with the media database, according to you.
I have created a new folder with OGG files to workaround my FLACs not being found, and Auxio picks them up just fine.
I've tested Auxio 2.6.1 and it does not work, it only picks up my OGG files.
The issue does appear in Music Player GO and I haven't tested Vinyl. 

Since this isn't Auxio's fault, do you know how I could make my system recreate the media database correctly?

**Comment by OxygenCobalt** [comment]
Sadly there isn't much you can do if your media database is malfunctioning. There used to be ways to work around issues, but Google has killed pretty much all of them in newer Android versions. 

If OGG files work however, you may be able to convert your FLAC files to OGG FLAC and still be able to use them in Auxio without any loss in quality.Sorry for the inconvenience. Google hates the file-system and refuses to make the media database work well.

**Comment by dumbuz** [comment]
Yeah that's a Google moment. That sucks for me but I guess I'll just use OGG. Thanks!
