### ISSUE TITLE
Built-in Eqalizer

### ISSUE THREAD

**Issue by IronCR7** [OxygenCobalt/Auxio#307]
### Description

It would be great if you add support for a built-in equalizer to the app.

### Problem solved

No it's not related to any problem.

### Other implementations

I don't know. Didn't understand this question.
They implement a feature to modify different frequencies.

### Benefit

This will help users who doesn't have built-in equalizer in their phone. 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio doesn't have an equalizer as feature creep can be really crazy with it. Instead, Auxio delegates to external equalizers like [Wavelet](https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet&gl=US), which I'd heavily recommend.
