### ISSUE TITLE
Play selected

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#313]
Left over from #93 and discussion in #267 and #196. More or less, an option that allows all songs in a user selection to be played or shuffled, without having to play another item like an album and then remove the items you do not want.

**Comment by KraXen72** [comment]
+1, good idea. would be cool if you could do stuff like select 3 albums, click this new button and it would play them in order, and another button that would shuffle them.

**Comment by OxygenCobalt** [comment]
Good idea @KraXen72. Currently it only shuffles by songs, but if #221 comes to fruition your idea should be possible (Assuming you are only selecting albums).

**Comment by KraXen72** [comment]
very cool and very swag
