### ISSUE TITLE
New release notification & "Check update" button

### ISSUE THREAD

**Issue by Dyl-M** [OxygenCobalt/Auxio#314]
### Description

With the latest releases I noticed that there was no feature in Auxio that allow the user to directly update the application / download the latest APK. There is also no notification system to warn users that a new version of Auxio is available.

It would be nice to implement such a feature in the "About" section or to show a New Release notification when starting Auxio.

### Problem solved

I don't think it's instinctive for everyone to go to the GitHub repository to check for updates. And, for example, if a vulnerability is fixed with a release, all users should be aware that a patch is available as soon as possible.

### Other implementations

I don't know how open source music players are doing this, but if you take the example of [Neko](https://github.com/CarlosEsco/Neko), a manga reader, there is in "About" section a button to update the app. And the application informs users of the latest releases with a pop-up when it opens.
![Screenshot_2023-01-04-13-33-34-812_tachiyomi mangadex](https://user-images.githubusercontent.com/57560342/210556465-c6089115-48ee-4251-a244-623bb6a0b889.jpg)

### Benefit

In this way, anyone using Auxio will be guaranteed to have their application up to date, with the latest features. Or at least be aware that a new version is available.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I don't think I could add this without having to break my "no internet connectivity" promise. The most I could do is add an "updates" button in the about screen.

**Comment by Dyl-M** [comment]
I guess yes, that would be enough. But with your "no internet connectivity" rule, it will means that the app wouldn't be able to download the latest release by itself, isn't it?

**Comment by Dyl-M** [comment]
Well ok... I guess it might be better than nothing. It might be redundant with the GitHub button already present though.

**Comment by illdeletethis** [comment]
glad the "no internet connectivity" rule prevents this, apps that nag about updates are a major nuisance

**Comment by OxygenCobalt** [comment]
Yeah, I think I'm not going to do this. I'd rather delegate the task entirely to app stores.
