### ISSUE TITLE
Long press menu - close menu when pressing the back button (navigation bar) instead of going back in the app

### ISSUE THREAD

**Issue by min7-i** [OxygenCobalt/Auxio#316]
### Description

When long pressing an element (song, album, artist, etc.) the long press menu is opened. Now, when the back button (navigation bar) is pressed once the long-press menu should be closed. Similar to pressing the 'x' button in the upper left corner to close the menu.

### Problem solved

Currently, when the long press menu is open and the back button (navigation bar) is pressed the previous view is opened or the app is closed (depending on which view is open).

I created a short screen recording that shows the current behavior.

https://user-images.githubusercontent.com/97251923/211157251-f8e9f1f9-6851-44d5-af48-853565c51cba.mp4

### Other implementations

The desired behavior is available in the Metro app: pressing the back button while the long press menu is active will close the menu and cancel the selection.

https://user-images.githubusercontent.com/97251923/211157181-5421f1f5-e2f2-421c-814b-d264fcdaf9de.mp4

### Benefit

Personally, I'm used to the desired behavior from many other Android apps which have a long press menu, e.g. Metro, AntennaPod, but also messaging apps like Signal, Threema.

Especially on smartphones with a larger display I feel that it's more comfortable to quickly tap the back button once instead of trying to reach the 'x' button in the upper left corner with one hand in order to close the long press menu.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Shoot, I forgot to add that when I was working on multi-select. I'll go do it.
