### ISSUE TITLE
3 dots

### ISSUE THREAD

**Issue by illdeletethis** [OxygenCobalt/Auxio#317]
As much as i appreciate your work otherwise, the tree dots after every item introduced with version 3 seem excessive.
Would merging those options into the selection bar brought up by long pressing something be an acceptable option?

**Comment by OxygenCobalt** [comment]
While removing the three-dot menu would look "cleaner", it also massively increases the friction to get to common functionality.

For example, to go to a Song's Album with the current menu, you have to do:
- 1 click on the menu button
- A minimal amount of movement to "Go to album"
- 1 click on "Go to album" 

Meanwhile, with your idea, you would have to do this:
- 1 *long* click on the item
- A longer amount of movement to the top left of the screen
- Another click on the overflow menu
- A minimal amount of movement to "Go to album"
- 1 click on "Go to album"

"Clean" UIs taken to their extreme often result in much more friction on the users end. I would rather avoid that when reasonable.

**Comment by illdeletethis** [comment]
you are completely right in those usability advantages, and not having considered those before i now understand why such a menu exists.
however, would it be possible to use the area taken by the album art instead of the 3 dots?

**Comment by OxygenCobalt** [comment]
That would be extremely bad for accessibility. It's convention that a 3-dot icon will open a menu, but not that the album art would.
