### ISSUE TITLE
Force music widget to show song name after playback stopped 

### ISSUE THREAD

**Issue by U1M450W** [OxygenCobalt/Auxio#319]
When i stop playback... After sometime music widget stops showing song name on widget.... please make it save song name untill i relaunch app

**Comment by OxygenCobalt** [comment]
This is intentional behavior. When the app is killed by the system, the widget can no longer obtain song information, so it must reset.

**Comment by U1M450W** [comment]
Okay at least replace it with someone more good looking... because that no music playing text is ugly
