### ISSUE TITLE
Make the artist view scroll the same as the all songs scroll

### ISSUE THREAD

**Issue by toniz4** [OxygenCobalt/Auxio#32]
#### Describe the feature you want to implement:

I have a library with lots of artirts,  so trying to find a specific one is hard, making the scroll like the all songs scroll, it would make easy to find a specific artist.

#### Is your feature request related to a problem? Please describe:

It's hard to find a single artist easily.

#### Why do you think this will improve everyone's usage of Auxio?

It would make finding artists easier.

#### Due Diligence:

- [x] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Can you elaborate? I'm assuming that you want a fast-scroller on the library view [e.g those letters on the songs view]. If thats the case, then you should install [1.4.1](https://github.com/OxygenCobalt/Auxio/releases/tag/v1.4.1) or wait for it to arrive on F-Droid, as I've added it in that version.

**Comment by toniz4** [comment]
Exactly that, sorry for not checking the current version on the repo. Thanks!
