### ISSUE TITLE
Add wiki information for fixing missing music

### ISSUE THREAD

**Issue by Deijin27** [OxygenCobalt/Auxio#321]
I had the problem that some of my music was missing from the app. I have successfully fixed this thanks to some suggestions from a different app's FAQ.

**I think adding some of these suggestions to the troubleshooting page on the wiki would be useful.**

Here were the suggestions I saw. What worked for me was to move the music from SD to internal storage then back, then in auxio app to a full reload of the music.

![Screenshot_20230111_203740_com vivaldi browser](https://user-images.githubusercontent.com/40903783/211920782-6bab5f52-1f22-44ab-85e2-08e630208a17.jpg)

**Comment by OxygenCobalt** [comment]
Updated the wiki. Thanks for this.
