### ISSUE TITLE
Replay Gain working erratically

### ISSUE THREAD

**Issue by Moarc** [OxygenCobalt/Auxio#324]
I don't get Replay Gain when playing Opus files I generated using foobar2000 and ffmpeg.
The pre-amp setting "Adjustment without tags" is applied to such files, not "Adjustment with tags", which suggests they're seen as not having Replay Gain at all (duh).

The files in question are converted using One Way Sync and `ffmpeg.exe -f s16le -ar %sr% -ac 2 -i %in% -y -f ogg -c:a libopus -b:a 256k -ar 48000 -vn %out%`.
Inspecting them with foobar2000 shows that they do have Track Gain and Album Gain specified, but no peak values. Conveniently I have such a file which I can share (the song is CC-licensed): [07. Co widział gawron w locie.opus](https://github.com/OxygenCobalt/Auxio/files/10415937/07.Co.Widzial.Gawron.W.Locie.tar.gz).

The same thing happens with some MP3 files, but not all of them. For those - what would be a preferable way of dumping their metadata to provide here?

It's also not unlikely that the issue is with some older tag values being cached in the media database, but I have no way of confirming that - more precisely, I've got no idea how to clear the database on this version of Android.

**Comment by OxygenCobalt** [comment]
I'm not sure what you want. Can you explain what you want to happen with your files?

My closest guess to what you want is for me to support dynamic normalization when no gain tags are present. This is not possible, as I am unable to have a "birds-eye-view" of the file.

You can dump MP3 metadata by just taking a screenshot with a tool like [kid3](https://kid3.kde.org).

**Comment by Moarc** [comment]
As usual, I realize what I was doing wrong *after* bothering someone.

All of my files are *supposed* to be tagged with replay gain. Turns out foobar2000 was putting zeroes there, and storing the actual value in the Opus header (?). Telling it zero out the header gain and only use tags solved the issue.

The MP3 files, for their part, were tagged with APE tags instead of ID3.

What confused me was that both foobar2000 and Strawberry were able to deal with all that mess, applying replaygain from wherever it was stored.

**Comment by OxygenCobalt** [comment]
Oh. Yeah, AFAIK ExoPlayer (or the media framework as a whole on Android) aren't aware of the OPUS Gain value. There's no way I can work it on my end either outside of the specific track and gain tags.
