### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by xmha97** [OxygenCobalt/Auxio#325]
### Description

Please add support external lyrics (LRC file) and embedded lyrics (ID3).

### Other implementations

-

### Benefit

I

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by KraXen72** [comment]
this was already rejected multiple times as far as i know

**Comment by OxygenCobalt** [comment]
This is the second time you have made this issue. Please stop requesting this.
