### ISSUE TITLE
Tag and Artist Editor

### ISSUE THREAD

**Issue by yesNOmaybe69420pogchamp69** [OxygenCobalt/Auxio#33]
#### Describe the feature you want to implement:
 I would like to see a tag and artist editor for songs like Oto music has.

#### Is your feature request related to a problem? Please describe:
 I'm frustrated by the fact that I can't edit the metadata of songs and make changes to artists or albums

#### Why do you think this will improve everyone's usage of Auxio?
 This way, we'd be able to edit artists, lyrics, albums etc.

#### Due Diligence:

- [x] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio **plays music**. It does not edit tags. Try some kind of dedicated tag editor like [kid3](https://kid3.kde.org/) or [quod libet/ex falso](https://github.com/quodlibet/quodlibet)
