### ISSUE TITLE
View tags in song properties dialog

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#330]
### Description

In the properties dialog of songs (where you can see filename, location, bitrate...), also view the metadata tags.

### Other implementations

Don't know about mobile players, but Elisa (KDE) does the same on desktop.

### Benefit

You can view tags for a single song - useful if you have e.g. an album with various years and would like to know from when a specific song is.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Seems vaguely reasonable. I'll see what I can do.

**Comment by OxygenCobalt** [comment]
I think this will be the tag list I'll show:

- Title
- Artists
- Album
- (Song) Date
- Track
- Disc (With subtitle)
- Genre

**Comment by OxygenCobalt** [comment]
Done. Should arrive in the next release.

https://user-images.githubusercontent.com/65370175/220148811-3b90a7ba-c0c9-4075-a854-12b3f0722f53.mp4
