### ISSUE TITLE
Support disc subtitle tags

### ISSUE THREAD

**Issue by alessandrococco** [OxygenCobalt/Auxio#331]
### Description

Hi @OxygenCobalt,
thanks for Auxio, it's an awesome app!

---

I have some multi-CD albums where each CD has a title, e.g.:

![image](https://user-images.githubusercontent.com/2331798/213225260-38f1beb6-48e1-4339-9dbf-7ba402256986.png) (this is Lollypop on Linux)

The tag is `DISCSUBTITLE`:

![image](https://user-images.githubusercontent.com/2331798/213225737-e3bdabc6-f44e-45ab-85e3-ca2774274dcf.png)

Could Auxio show the `DISCSUBTITLE` (if available) next to (or instead of) _Disc X_?

![image](https://user-images.githubusercontent.com/2331798/213227061-ecd2eb22-1369-46ec-b604-b9bb08e6aad4.png)

---

ps: I'm a Java/Kotlin backend developer with a little Android experience - I could try to open a pull request 😄 

### Other implementations

I don't know 😅 

### Benefit

This is a quality of life improvement 😄 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Oh, that's neat. I can do this, always willing to add new metadata support, but:

1. What's the ID3v2 analogue for this? I know there is a "Subtitle" tag, but that could be used for other things.
2. Would you like it formatted like `Disc 1: [subtitle]` or just `[subtitle]`?

**Comment by alessandrococco** [comment]
Great, thank you!

1. Yes, it should be `TSST`
2. Uhm, maybe the disc number should remain. What about `[subtitle]\nDisc N`? E.g.   
**The Supernal Clear Light of the Void**
(smaller) Disc 3

**Comment by illdeletethis** [comment]
while it is not directly related to this issue, could you make items tagged as "disc 0" show up as such?
this would be useful for separating classical works, where an overture might not be part of any of the acts, and other apps allow it too.

**Comment by OxygenCobalt** [comment]
The issue is that a disc number of "zero" may refer to a legitimate pre-lude such as in your case, or that there is no disc value whatsoever.

How about this: If a zeroed disc has a subtitle value, it will be shown. Otherwise, it will be ignored. What do you think @illdeletethis?

**Comment by KraXen72** [comment]
> How about this: If a zeroed disc has a subtitle value, it will be shown. Otherwise, it will be ignored. What do you think 
  
imo good idea. 
for style, i think   
**Disc 2:** The Supernal Clear Light of the Void   
could work

**Comment by OxygenCobalt** [comment]
Good idea @KraXen72. Albeit, to retain consistency I might actually do something like:

Disc 2 (Bright Font)
The Supernal Clear Light of the Void (Dimmer Font)

Sort of like how song text is structured.

Another thing: I'll probably add a special shortcut alongside this that will allow how to play and enqueue individual disc groups. Seems like a good QoL thing.

**Comment by KraXen72** [comment]
galaxybrain idea good job

**Comment by illdeletethis** [comment]
> How about this: If a zeroed disc has a subtitle value, it will be shown. Otherwise, it will be ignored. What do you think @illdeletethis?

Quite a clever solution.
Sadly wouldn"t get a benefit from it before another round of retagging, since i don"t use disc subtitles yet, only realized they exist from this request.
Would checking if anything else on the album has a nonzero disc number work as a condition too, or does that introduce other undesired effects?

**Comment by OxygenCobalt** [comment]
> Would checking if anything else on the album has a nonzero disc number work as a condition too, or does that introduce other undesired effects?

Not sure. Zeroed values are removed during the initial round of tag extraction, so some heuristics would have to occur there. Do you use "total" track/disc values @illdeletethis? I could implement a system where zeroed discs are accepted only if the total disc tag is also present and non-zero.

**Comment by illdeletethis** [comment]
Great solution, yes, that"d work

**Comment by OxygenCobalt** [comment]
Okay, I'll do that and the subtitle check when adding this.

**Comment by OxygenCobalt** [comment]
Okay, I got this implemented.

![Screenshot_20230121-172120_Auxio_Debug_1](https://user-images.githubusercontent.com/65370175/213895153-0e6f89d0-ada1-4bb4-9048-0fe936a4f57c.png)

Note: While I did add the total disc check to accept zeroed discs, I decided not to add the subtitle check, as it was much harder to test.

**Comment by KraXen72** [comment]
oh, the disc names wont make it into the app? i might also be misunderstanding this.

**Comment by OxygenCobalt** [comment]
No, disc names are making it into the app @KraXen72. They just won't factor in to the new checks for whether a disc number of 0 was intentional or not.
