### ISSUE TITLE
Repeat/shuffle indicators low contrast between on/off state

### ISSUE THREAD

**Issue by evanc577** [OxygenCobalt/Auxio#332]
On some color schemes , the indicators for repeat/shuffle are hard to distinguish between their on/off states. This is especially true when **system night color is on, dark mode is on, and with low brightness.**

There was some previous discussion in #53 but that issue is now closed. Looking at the commit messages it seems like dots were added at some point but then removed in favor of just color+bold.

## Example screenshot
Above: indicators off
Below: indicators on
Color scheme: indigo
Night light simulated in post processing because it doesn't show in screenshots
![auxio_indicators](https://user-images.githubusercontent.com/14303970/213250931-ae169179-f5a5-4436-ba28-e9a51f79b03a.png)

## Implementations in some other apps

Spotify: High contrast color and dot
![spotify_indicators](https://user-images.githubusercontent.com/14303970/213251433-f0388ea1-f0d8-41ce-bc93-bb80257474ba.png)

Poweramp Aurora skin: Untoggled icons are dimmed
![poweramp_aurora_indicators](https://user-images.githubusercontent.com/14303970/213251945-2f3b40b1-99a3-488a-a8ee-0eb24a07f99e.png)

**Comment by OxygenCobalt** [comment]
The issue is that I can't use dots everywhere, such as on the widget or on the notification. I'd rather pick the more consistent option.

**Comment by evanc577** [comment]
Maybe consider dimming untoggled state like in poweramp screenshot?

**Comment by OxygenCobalt** [comment]
Can't do. Material Design states that you should not indicate "off" states via a dimmed icon, as that can be mistaken for a "disabled" state. Instead, "on" states should be indicated via a thicker and accented icon, which is what I currently do.
