### ISSUE TITLE
M4A files have no sound

### ISSUE THREAD

**Issue by rien333** [OxygenCobalt/Auxio#337]
### Describe the Bug/Crash

1. Play a m4a file (i.e. a song encoded in the mpeg-4 audio format)
2. The song plays, but there is no sound

### Describe the intended behavior

m4a files should be able to play with sound. 

The same files play in the Android version of mpv, and doubletwist musicplayer (am looking to switch to a good open source alternative 🙂)

### What android version do you use?

Android 11

### What device model do you use?

Redmi note 10 (LineageOS 18.1)

### Relevant log output

```shell
# logcat | grep -i auxio output when playing a m4a file

01-22 11:44:00.267  4102  4102 D CntrlrRcvrCallback: org.oxycblt.auxio media metadata changed
01-22 11:44:00.278  4102  4102 D AbsPlayStatusReceiver: [player=org.oxycblt.auxio]
01-22 11:44:00.291  4102  4102 D MusicAPI: Auxio:org.oxycblt.auxio
01-22 11:44:00.295  4102  4102 D AbsPlayStatusReceiver: App: Auxio has been ignored, won't propagate
01-22 11:44:00.297  4102  4102 D CntrlrRcvrCallback: org.oxycblt.auxio playback state changed
01-22 11:44:00.302  4102  4102 D CntrlrRcvrCallback: org.oxycblt.auxio playback state changed
01-22 11:44:00.747  4102  4102 D CntrlrRcvrCallback: org.oxycblt.auxio playback state changed
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This could be caused by a variety of issues that are not clear from your log.

1. Can I have a sample M4A file? Preferably one in the public domain, but a short IP'd one would also be fine.
2. Can I have more log information? This probably isn't something that can be filtered.

If I were to guess at what might be occuring:
1. ReplayGain functionality is muting your files due to some unforeseen edge case.
2. Equalizer integration is failing due to device-specific issues.
3. Something about your M4A files is not supported by ExoPlayer.

**Comment by ravensiris** [comment]
I think I encountered the same problem with m4a.

I tried different FOSS players I found on F-Droid and they have the same issue or crash with Apple Losless codec embedded inside m4a. Apple Losless is pretty uncommon embedded in m4a. The only player that I was able to get it working on was VLC on android. What's worth mentioning is that I also have issues with this album playing in players like Sonixd on Linux but none on my favourite TUI one: musikcube. 

This might not be worth fixing tbh. It would be easier to transcode to flac seeing how uncommon and badly supported this is.

**Comment by OxygenCobalt** [comment]
Oh. ExoPlayer actually has support for ALAC if I switch to the ffmpeg extension. I can go do that @ravensiris @rien333.

**Comment by OxygenCobalt** [comment]
Merging into #346.

**Comment by rien333** [comment]
Great, thanks a lot!

> Apple Losless is pretty uncommon embedded in m4a.

I don't know, seems pretty typical for the m4a files I tried.

> What's worth mentioning is that I also have issues with this album playing in players like Sonixd on Linux but none on my favourite TUI one: musikcube.

Weird. Never had this issue before. That said, I only use cmus/mpv on linux desktop, which both use ffmpeg stuff under the hood, IIRC.

**Comment by OxygenCobalt** [comment]
> Weird. Never had this issue before. That said, I only use cmus/mpv on linux desktop, which both use ffmpeg stuff under the hood, IIRC.

Yeah, I've been wanting to back my app a bit more with FFMpeg components. Seems like what the big proprietary music players do. The issue is that beyond ALAC, doing so would require me to patch ExoPlayer, not to mention the less-than-ideal metadata support.

**Comment by OxygenCobalt** [comment]
ALAC files should be supported in the next version of Auxio.
