### ISSUE TITLE
Redesign sorting menu

### ISSUE THREAD

**Issue by etyarews** [OxygenCobalt/Auxio#338]
### Description

Take a look at the current sorting menu, running on LineageOS 19 on a Redmi Note 10:

![image](https://user-images.githubusercontent.com/113912802/214398574-e58d4a2f-7afb-442a-81a5-c43379a0687b.png)

### Problem solved

As you can see, it looks rather odd. The trailing elements aren't properly aligned: The radio buttons don't have the same right padding as the checkbox.

Another issue is that this menu offers controls for two different things: "Sorting by" AND "Order", each can be controlled independently of one another, however, this isn't represented in the menu itself. A simple divider between the two would be enough, although a small label could also be used.

### Other implementations

Another, more subjective point is the use of a checkbox as the way to change between "Ascending" and "Descending". Most apps use a radial button and show "Descending" as an option. I do understand the use of a checkbox, as it prevents wasted space, still feels necessary to point how non-standard Auxio's implementation is

### Benefit

Better UI

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by KraXen72** [comment]
imo the menu works as is.
the right padding should defo be fixed, 
but the asc/desc item can be just separated from the rest by a divider.
just my opinoin tho.
![image](https://user-images.githubusercontent.com/21956756/214538649-0a7c1e41-35da-4f88-8790-981898d442da.png)

**Comment by etyarews** [comment]
Yeah, I think fixing the padding and adding a divider is enough. Still, felt compelled to mention the way Auxio represents asc/desc is really uncommon. If the sorting menu is redesigned, might as well bring this to the dev.

**Comment by OxygenCobalt** [comment]
This seems like a good idea. 
- I know that I can hack the `minWidth` attribute to fix the misaligned padding. AFAIK it was introduced in some MDC version, will try to hunt it down. 
- As for the divider, not sure what `PopupMenu` offers for dividers, I'll try to look into it. - Should be easy to change out the ascending/descending button assuming that I can implement a divider to separate it's radio group from the main radio group.

**Comment by etyarews** [comment]
Huh, the divider is [explicitly mentioned on the guidelines](https://m3.material.io/components/menus/guidelines), should already be there

**Comment by OxygenCobalt** [comment]
Okay, here's the new sorting menu:


https://user-images.githubusercontent.com/65370175/216514633-83e85c1c-6762-4523-9c5f-2edbf2ce0f9b.mp4

**Comment by etyarews** [comment]
Looks great!

Hey, just spitballing here, but have you considered moving the menu to show below the 3 dot button?

**Comment by OxygenCobalt** [comment]
I think "Mode, Direction" is the more coherent arrangement compared to "Direction, Mode". Albeit, I did just shamelessly grab the original sorting menu design from material files, so I'm not sure if there's any standard way to arrange it.

**Comment by OxygenCobalt** [comment]
Oh. The toolbar view itself manages the menu, so I'd imagine that it stems from it choosing the anchor view as itself instead of the clicked button. Not sure how to override that behavior. I'll see what I can do.
