### ISSUE TITLE
Optional volume bar/slider on the now playing screen

### ISSUE THREAD

**Issue by niporasomo** [OxygenCobalt/Auxio#339]
### Description

Adding an optional setting to include a volume bar/slider below the 'play' and 'next and previous track buttons' on the now playing screen, so you can adjust the volume with a bar/slider much like you can currently with the bar/slider for seeking with the song playback.

### Problem solved

It can allow for finer control over the volume, and makes the playback slider and volume slider all within reach of one finger, and adjustable without having to use the physical volume buttons.

### Other implementations

The only other open source music player on F-droid I've seen with a volume slider is Metro, and I attached a screenshot from the app just as an example. However, it doesn't seem like the app will be maintained any longer, and Auxio has pretty much every other feature that I was looking for. In Metro it's just a simple toggle in the settings that enables it, so it's a choice left up to the user.
![Screenshot_20230125-050433_1](https://user-images.githubusercontent.com/123551471/214551966-030a4512-51b9-4b73-baab-4f40fc3656da.png)

### Benefit

It puts the volume controls right in front of the user, and also is good for one handed use, so if one is exercising, walking, running, etc. for example. It's a handy feature that I thought others might be interested in as well.

Thanks again for the awesome app and taking the time to consider this feature!

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Sorry, I don't think I will be doing this.
1. This needlessly duplicates system functionality.
2. I don't get use from this. The friction of volume buttons is generally quite minimal.
3. I cannot fit any more components into the playback view in the first place without it looking exceedingly cluttered.
