### ISSUE TITLE
Auto exclude unsupported files from Auxio when scanning for musics.

### ISSUE THREAD

**Issue by 14725** [OxygenCobalt/Auxio#340]
### Description

I want files that can't be played by Auxio not appeared in it instead of show them then fail and skip them when playing. 

If it would be inplemented ever, a check based  on extension might be enough. 

(Or playable check?  I don't know whether it is easier or harder.)

### Problem solved

I have a bunch of .mid files. Some for listening, but much more for data analysis. 

They can't stop Auxio from playing, but they bloats the Music list.

(Although I would exclude the folder of these midi files)

### Other implementations

( The system player of my mobile would play midi well, though midi files are often excluded as they are "too small". )

( I have a dedicated midi player that uses Timidify to play them, however it is folder-based so I,have to traverse among these folders... )

### Benefit

This feature allows users would be not confused with some strange lists that wouldn't play. 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Trying to filter out music with certain extensions would cause too much collateral damage, as there can be files with mislabeled file extensions. Not to mention the plethora of "why isn't my music appearing" issues.

I would recommend doing this:
1. Separating out your midi files and non-midi files into two folders.
2. Opening the "Music folders" setting in Auxio and adding the midi folder.

This should make Auxio ignore your midi files.
