### ISSUE TITLE
Allow grouping music

### ISSUE THREAD

**Issue by Donkey-Doug** [OxygenCobalt/Auxio#341]
### Description

I want to be able to group data in addition to sorting. For example, if I group by artist and sort by duration then all songs from the same artist are always together, but still sorted according to my liking.

See these examples from a gallery app:
![Screenshot_20230128-135827_Trebuchet](https://user-images.githubusercontent.com/50382414/215267601-cd6bceef-c2b5-4b9f-a4d7-19012e2684f7.png)
![Screenshot_20230128-135545_Trebuchet](https://user-images.githubusercontent.com/50382414/215267573-440f8519-2d95-479a-9028-758c47a81039.png)
![Screenshot_20230128-135551_Trebuchet](https://user-images.githubusercontent.com/50382414/215267578-e98ffddf-3952-438e-b042-d8c86eb0f3a6.png)

### Problem solved

It is difficult to find the right music in a large library.

### Other implementations

Honestly I don't know, but I will try and find a music player that does this.

### Benefit

Allows for easily finding music

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is a lot like grid display modes, where it opens up the avenue towards an ever-increasing amount of display options until theres a dozen different list items that all work poorly. Not doing this.
