### ISSUE TITLE
[FR] Ascending sorting for albums (by date) in Artist tab

### ISSUE THREAD

**Issue by xfzv** [OxygenCobalt/Auxio#344]
### Description

When opening an artist from the "Artists" library tab, albums are sorted by date in descending order (newest to oldest).

It would be nice if we could use ascending sorting instead (oldest to newest) here.

### Other implementations

[vanilla](https://github.com/vanilla-music/vanilla) allows both ascending and descending sorting (ascending being the default):
1. Open an artist from "Artists" tab" (or directly go to "Albums" tab)
2. Tree dot button at the bottom right corner
3. "Sort by" > "Year" and use "Reverse sort" to use descending instead of ascending (default).

### Benefit

I organize my music library as follows:

```console
Music
└── Artist 1
    ├── 2020 - Album name
    ├── 2021 - Album name
    ├── 2022 - Album name
    └── 2023 - Album name
```

so the ascending sorting feels more natural to me.

[strawberry](https://github.com/strawberrymusicplayer/strawberry) also uses ascending sorting when grouping the music collection by "Year - Album".

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This isn't really practical to implement in the current UI once you have several different release types in an artist (EPs, Singles), as the albums list becomes split into several sub-lists with no good way to indicate that a single sorting option acts on all of them. Not doing this.
