### ISSUE TITLE
Add file sharing

### ISSUE THREAD

**Issue by Benjamin-Watson0** [OxygenCobalt/Auxio#347]
### Description

Note that I am not talking about providing editing tags in the software.
I have read "Why Are These Features Missing? “
I have been sharing files in the file manager to the tag editor. I think it would be more convenient to share directly in the music player, which can more intuitively see whether the music tag is correct. You don't have to open File Manager>find the music after finding the error. This process is very troublesome.

https://user-images.githubusercontent.com/112467275/216225163-cbd5c33d-038d-4802-9ea2-e73f8ceeedeb.mp4

### Other implementations

They have the function of sharing audio files, but this software does not. I think this is the key.

### Benefit

I believe that this is very important. It will be more convenient and can cause trouble to the music player. It can still be simple and powerful.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Oh. I didn't know the share menu allowed you to do this. This is actually a really good idea. I'll try to implement it.

**Comment by OxygenCobalt** [comment]
@Koitharu has added this with #443.
