### ISSUE TITLE
Flickering when moving same songs in queue

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#350]
### Describe the Bug/Crash

1. Add the same song to the queue twice
2. Move one of them around
3. Flickering (the order is changed though)

### Describe the intended behavior

Just change order without flickering (just like two different songs).

### What android version do you use?

Android 12

### What device model do you use?

Android One (Stock Android)

### Relevant log output

```shell
N/A
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I've been aware of this issue for awhile. To put it simply, Auxio is not properly differentiating queue entries with the same *song* but different *position* in the UI. I've been considering how best to tackle this issue, and I think it will be resolved by #335.
