### ISSUE TITLE
Vorbis codec metadata isn't recognized

### ISSUE THREAD

**Issue by tearfulnumpty** [OxygenCobalt/Auxio#351]
### Describe the Bug/Crash

When vorbis codec songs in an .ogg container are played in Auxio, their metadata isn't displayed to the user.  The artist is listed as, "Unknown Artist" and cover art metadata is also incorrect, taking the form of some other song - presumably due to #342 (the art likely comes from another artist and album with vorbis data, thus #342).  

Viewing the metadata in the, "properties" setting shows a vorbis codec for all songs which don't have working metadata.  

I haven't explicitly ruled out other containers or codecs, but I've only noticed this with vorbis.  

### Describe the intended behavior

Should properly handle metadata.  

### What android version do you use?

Android 11

### What device model do you use?

Moto G8 Power - crDroid 7.7

### Relevant log output

```shell
I don't believe logs are relevant, but if they are desired just let me know and I'll follow the provided steps to obtain them.  I hope this is acceptable.
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Can you provide sample files? The cover art is probably #342, but the artist issue is weird.

**Comment by tearfulnumpty** [comment]
My mistake, it looks like I came to the entirely wrong conclusion.  I'm closing.  Sorry.
