### ISSUE TITLE
`RELEASETYPE` not detected for MP3 files

### ISSUE THREAD

**Issue by xfzv** [OxygenCobalt/Auxio#353]
### Describe the Bug/Crash

I'm using `RELEASETYPE` tag (ID3v2.4.0) to differentiate compilations / EPs / singles / soundtracks from regular albums.

While this works fine for FLAC and Opus files (Auxio displays them in a different sub-section), it doesn't for mp3 files. Auxio lists these mp3 files as "Albums", despite having either `Compilation` ; `EP` ; `Single` or `Soundtrack` in `RELEASETYPE` tag (could reproduce with all of these).

I'm using kid3 for tagging if that matters.

Not sure if this is an Auxio issue or if I'm supposed to use another entry than `RELEASETYPE` for mp3s?

### Describe the intended behavior

Auxio reads the `RELEASETYPE` tag from these mp3 files and displays them in the correct sub-section instead of "Albums"

### What android version do you use?

Android 13

### What device model do you use?

- OnePlus 7 Pro
- YAAP Vanilla
- Auxio 3.0.2

### Relevant log output

```shell
Nothing relevant in logcat
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Oh. `RELEASETYPE` is used in MP3 too? I always thought it was just used in vorbis, and that `MusicBrainz Release Type` was instead the "standard" release type for MP3 files. I can add this pretty easily.

**Comment by OxygenCobalt** [comment]
Yeah, the naming difference is specifically stated here:

> ID3v2 | `TXXX:MusicBrainz Album Type`
> Vorbis | `RELEASETYPE`

Basically, in Vorbis, `RELEASETYPE` already existed as a "standard" tag before MusicBrainz came about. In ID3v2 (MP3) however, there was no such specification outside of `GRP1`, which is weird non-standard iTunes stuff. Thus, MusicBrainz made up it's own tag for MP3 files that explicitly states that it was defined by MusicBrainz, while the pre-existing `RELEASETYPE` was used for vorbis.

Music metadata is really chaotic and incoherent like this. Honestly, falling back to `RELEASETYPE` in MP3 files is incredibly trivial, so I can just add it. Reduces the amount of confusion from people who are not aware of the (honestly absurd) state of music tagging.
