### ISSUE TITLE
Don't crop album art

### ISSUE THREAD

**Issue by occasionallyword** [OxygenCobalt/Auxio#355]
### Description

I would like for Auxio to provide a setting so that album art isn't always cropped if not desired.  Currently, any album art will be cropped to what appears to be a 1:1 aspect ratio.  I would like a setting which can disable any cropping, and provide the full image for display.  

Alternatively, perhaps clicking on the art itself could open the uncropped image.  Another idea is that it could even be displayed within the, "Song Properties" section which is accessible from, "Now Playing -> three dots -> View Properties."  I know that there's already a request with #330 for additional tags to be displayed here (I was going to make an issue myself before I found it).  

It would also be nice if there was a setting which could apply this to the lock screen art.  I realize that album art typically doesn't follow a phone screen's aspect ratio and may result in a lot of, "unused" space, but perhaps this could be filled in with the standard fuzzy/blurry setting.  [Here's the first example I found online.](https://i.stack.imgur.com/v1EZD.jpg)  Of course instead of filling in content on the left and right as in this sample image, most phone screen aspect ratios would be filling in content vertically on the top and bottom.  

### Problem solved

I'm frustrated when my album art is cropped because it's 16:9 and the image is rather awkward as a result.  

### Other implementations

In fairness a lot of art is designed for a roughly 1:1 aspect ratio and _some_ other players also crop images to roughly this aspect ratio.  However, not all do.  Some media players will simply display the image without cropping, which would be my personal preference of implementation.  Others will implement it as suggested from my alternate ideas, such as being available on the properties view.  

### Benefit

This will benefit everyone who uses Auxio and has album art that isn't a 1:1 aspect ratio by allowing them to view their full album art and retaining the related mood/atmosphere which can be provided from said album art.  

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
The big reason why cover art is cropped 1:1 is because it's really hard to make non-1:1 artwork play nicely in the UI. It often leaves a bunch of empty space and makes the album art much harder to read. Hence, the crop-by-default strategy. As for the lock screen, there's nothing I can do there. The android system handles that, and it center-crops the image.

Personally, I really like the idea of showing it in the "song properties" view like #330. That seems like the most feasible option (Ignoring #327 which complicates things even more).

**Comment by occasionallyword** [comment]
>The big reason why cover art is cropped 1:1 is because it's really hard to make non-1:1 artwork play nicely in the UI. It often leaves a bunch of empty space and makes the album art much harder to read. Hence, the crop-by-default strategy. 

Yeah I can totally understand that.  For me personally, most of my album art is 16:9 (which I realize may be strange to some).  For similar wide aspect ratios, the empty space could conceivably be filled in with metadata information and tags, but I understand that this probably wouldn't satisfy all possible situations for everyone.  

>As for the lock screen, there's nothing I can do there. The android system handles that, and it center-crops the image.

I was afraid this would be the case.  Seems to be a trend with all kinds of Android media player problems.  Google and their shenanigans.  

>Personally, I really like the idea of showing it in the "song properties" view like https://github.com/OxygenCobalt/Auxio/issues/330. That seems like the most feasible option (Ignoring https://github.com/OxygenCobalt/Auxio/issues/327 which complicates things even more).

This would be fine with me - although I just had an additional thought.  

What if tapping the art itself would open the properties menu?  I fully understand that you don't want a gesture like interface (and I personally agree) for Auxio, but would a simple tap of the art functioning as a shortcut for the properties menu be acceptable?  I guess it's a touch out of scope of this issue, but I figured I'd mention it since it's semi-related to the functionality of this issue.

**Comment by OxygenCobalt** [comment]
> Yeah I can totally understand that. For me personally, most of my album art is 16:9 (which I realize may be strange to some). For similar wide aspect ratios, the empty space could conceivably be filled in with metadata information and tags, but I understand that this probably wouldn't satisfy all possible situations for everyone.

I have to ask, why is your album art 16:9? Is it like a projected vinyl gatefold? 

> What if tapping the art itself would open the properties menu? I fully understand that you don't want a gesture like interface (and I personally agree) for Auxio, but would a simple tap of the art functioning as a shortcut for the properties menu be acceptable? I guess it's a touch out of scope of this issue, but I figured I'd mention it since it's semi-related to the functionality of this issue.

Not necessarily a fan of "implicit" behavior, such as tying click behavior to non-clickable elements. It's not necessarily the best for accessibility.

**Comment by occasionallyword** [comment]
>I have to ask, why is your album art 16:9? Is it like a projected vinyl gatefold?

Actually thumbnails from videos, usually.  Not very traditional I'm sure, but I also am sure I'm not alone in this, lol.  

>Not necessarily a fan of "implicit" behavior, such as tying click behavior to non-clickable elements. It's not necessarily the best for accessibility.

Yeah I'm not advocating for removing the three dot functionality, just adding an additional/quicker method.

**Comment by OxygenCobalt** [comment]
I really can't think of any way to implement this harmoniously in the song properties view, honestly. I think instead I will perform an alternative transformation. Instead of zooming in album covers, I will simply letterbox them and fill in the empty space with the "primary" color of the image, like the mockup below.

![image](https://user-images.githubusercontent.com/65370175/219444826-52f50261-f069-4542-917c-7a5a3f493eef.png)

This is easy enough to do *now*, but will become more annoying once #327 comes around, but I can ignore that for now.

**Comment by OxygenCobalt** [comment]
Actually, no, that solution is too complicated. I think I'm just going to avoid doing a crop altogether and try my best to make the app UI play along. I'll just devise a way that individual image components can shrink to fit the image they are currently holding.

**Comment by Akczht** [comment]
why not just put the whole image scaled to the size of the square, where album art curreny rests.

**Comment by OxygenCobalt** [comment]
@Akczht Stretching album artwork to fit a square view looks absolutely horrible.

**Comment by Akczht** [comment]
How bad ? 
(Source - iOS foobar2000)

![F0D614EA-6601-4E8C-A374-F845975F2F80](https://user-images.githubusercontent.com/79302042/223504127-28fbf80b-a553-4d49-9d6e-cb5b0aec7a88.png)

If you decide to trash the idea, at least it could be the last resort.

**Comment by OxygenCobalt** [comment]
That is the plan for this addition.

**Comment by OxygenCobalt** [comment]
This should be implementable as soon as I can confirm my image loader workaround doesn't have any side-effects.

**Comment by OxygenCobalt** [comment]
This is done, I decided to go for just placing the album artwork within the typical image background, like so:

![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/fdce0dac-69fe-4530-bde1-b3994ffbcd56)

Auxio's exposed covers to the android system are also now uncropped. Note that thin enough aspect ratios seem to confuse the Android 13+ media player, so I wouldn't recommend anything lower than 16:9.
