### ISSUE TITLE
Exclusive HQ USB audio access

### ISSUE THREAD

**Issue by ProjectRedis** [OxygenCobalt/Auxio#357]
### Description

Bypassing audio processing to external USB DAC.

### Other implementations

Several popular music players support the feature to bypass the internal DAC directly to the external DAC, for example, UAPP and Hiby Music Player.

### Benefit

The benefit that is obtained is that the player is able to play any song with the high resolution and sample rate that is supported by the external DAC.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I have absolutely no clue how to do this. Hiby and UAPP are proprietary and largely depend on this feature to get sales, so I cannot use them as a reference either.

**Comment by OxygenCobalt** [comment]
Update: [Android 14 Beta 2](https://android-developers.googleblog.com/2023/05/android-14-beta-2.html) seems to have added something related to this:

> Lossless USB audio
> Android 14 gains support for lossless audio formats for audiophile-level experiences over USB wired headsets. You can query a USB device for its preferred mixer attributes, register a listener for changes in preferred mixer attributes, and configure mixer attributes using a new [AudioMixerAttributes](https://developer.android.com/reference/android/media/AudioMixerAttributes) class. It represents the format, such as channel mask, sample rate, and behavior of the audio mixer. The class allows for [audio to be sent directly](https://developer.android.com/reference/android/media/AudioMixerAttributes#MIXER_BEHAVIOR_BIT_PERFECT), without mixing, volume adjustment, or processing effects. We are working with our OEM partners to enable this feature in devices later this year.

I don't know where I would go from here though, it might be added to ExoPlayer or I have to use it myself.
