### ISSUE TITLE
Cannot search for new Music 

### ISSUE THREAD

**Issue by robertoprubio** [OxygenCobalt/Auxio#358]
### Describe the Bug/Crash

Auxio version 3.0.2

1. open app
2. go settings
3. clic on update music or scan music

### Describe the intended behavior

New mp3 files are displayed by the app

### What android version do you use?

Android 12

### What device model do you use?

Huawei P30
EMUI 12.0.0

### Relevant log output

```shell
02-15 07:58:21.071 17763 17800 E Auxio.Indexer: Music indexing failed
02-15 07:58:21.071 17763 17800 E Auxio.Indexer: org.oxycblt.auxio.music.system.Indexer$NoMusicException: Unable to find any music
02-15 07:58:21.071 17763 17800 E Auxio.Indexer:         at org.oxycblt.auxio.music.system.Indexer.indexImpl(Indexer.kt:181)
02-15 07:58:21.071 17763 17800 E Auxio.Indexer:         at org.oxycblt.auxio.music.system.Indexer$indexImpl$1.invokeSuspend(Indexer.kt:16)
02-15 07:58:21.071 17763 17800 E Auxio.Indexer:         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
02-15 07:58:21.071 17763 17800 E Auxio.Indexer:         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-15 07:58:21.071 17763 17800 E Auxio.Indexer:         at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
02-15 07:58:21.071 17763 17800 E Auxio.Indexer:         at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
02-15 07:58:21.071 17763 17800 E Auxio.Indexer:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:82)
02-15 07:58:21.073  2472  3159 I PassThroughStats: pkg=org.oxycblt.auxio service=org.oxycblt.auxio/.music.system.IndexerService type=1 fg_duration=53 bg_duration=0
02-15 07:58:21.073  2472  3159 I AppBgModeMgr: pkg:org.oxycblt.auxio fgService:org.oxycblt.auxio/.music.system.IndexerService serviceType:1 stop, runningTime:53 bgRunningTime:0
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Please see [here](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting#music-is-missing-from-the-library) for ways to troubleshoot Auxio not finding your music library. If none of them work, it's highly likely that Huawei has broken the media database on your device in order to force you into their OEM music app.
