### ISSUE TITLE
Add option to disable sort article checks

### ISSUE THREAD

**Issue by robertoprubio** [OxygenCobalt/Auxio#359]
### Description

Alpha sort sorts:

```
Alphaville
The Allman Brothers Band
Amaia

```
instead of

```
Alphaville
Amaia
The Allman Brothers Band
```

due to sort function assumes language is English and removes articles before sort.

Please, add the option to take into account the articles when sorting.

### Other implementations

Pulsar+ Pro adds an option to do not remove articles before sort.

### Benefit

Remove of Articles before sort will not be a good idea in other languages than English

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by illdeletethis** [comment]
A setting to not remove articles could occasionally be useful for me as well, when reorganizing some media.
File explorers and easytag sort by the folder path with articles as well.
Otherwise having the articles ignored is pleasant.
