### ISSUE TITLE
Bit-perfect/DAC takeover option

### ISSUE THREAD

**Issue by ishanveersg** [OxygenCobalt/Auxio#367]
### Description

Do you plan on implementing something which would allow for bit-perfect playback by taking over the USB dac? 

### Problem solved

I use the Apple usb c to 3.5mm dongle on my phone but the output is way too low. The only way I can get it to work fine is by using Neutron player using the Direct USB Access option but the UI for that app is very dated looking and the scolling is very buggy. 

### Other implementations

[Neutron Player](https://neutroncode.com/faq/38-q-is-it-possible-to-achieve-bit-perfect-output-with-neutron) Neutron player has a very simple way of enabling this using profiles
![1](https://user-images.githubusercontent.com/45516995/220236472-c9d5a8e2-90f0-497b-9a18-622cc5f217c2.png)
![2](https://user-images.githubusercontent.com/45516995/220236474-2562f4b6-3302-43df-9c67-20719e407c07.png)

### Benefit

Better music reproduction for everyone!

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I have absolutely no idea how to do this. All the music players that do know how are proprietary and use the feature to get sales. I cannot do this.

**Comment by OxygenCobalt** [comment]
Update: [Android 14 Beta 2](https://android-developers.googleblog.com/2023/05/android-14-beta-2.html) seems to have added something related to this:

> Lossless USB audio
> Android 14 gains support for lossless audio formats for audiophile-level experiences over USB wired headsets. You can query a USB device for its preferred mixer attributes, register a listener for changes in preferred mixer attributes, and configure mixer attributes using a new [AudioMixerAttributes](https://developer.android.com/reference/android/media/AudioMixerAttributes) class. It represents the format, such as channel mask, sample rate, and behavior of the audio mixer. The class allows for [audio to be sent directly](https://developer.android.com/reference/android/media/AudioMixerAttributes#MIXER_BEHAVIOR_BIT_PERFECT), without mixing, volume adjustment, or processing effects. We are working with our OEM partners to enable this feature in devices later this year.

I don't know where I would go from here though, it might be added to ExoPlayer or I have to use it myself.
