### ISSUE TITLE
`MediaBrowserService` (Android Auto & Bluetooth AVRCP) support

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#37]
Self-explanatory. Requires #92 so that I can mirror the queue, and internal technical reworks so that I can implement a media browser into the playback engine.

**Comment by OxygenCobalt** [comment]
Merging into #52.

**Comment by OxygenCobalt** [comment]
Reopening since #52 is not happening.

**Comment by OxygenCobalt** [comment]
Related to this, in the next release you should have access to Auxio's queue from Android Auto. Still not mutation though, as I'm still grappling with the technical aspect of that.

**Comment by OxygenCobalt** [comment]
This issue will also seemingly resolve the Wavelet issue where Auxio will show up as "null" in the notification. Can't fix it until I have a working media browser implementation.

**Comment by OxygenCobalt** [comment]
Blocked until I can fix Auxio's jank service lifecycle with #244.

**Comment by OxygenCobalt** [comment]
Currently, I am busy with school and more prioritized functionality, given the difficulty of this change. You have two options to help out. @BabyBenefactor:

- Become a sponsor and prioritize this issue to force me to implement it as soon as possible. If you prioritize this for $8/month, I will start after #342 and #686, which have already been prioritized. If you prioritize this for $16/month, I will start on this first.
- If you have advanced android development knowledge, implement this yourself and PR it in. This involves a pretty drastic refactoring of Auxio's internals (See #244), but I can give guidance.

**Comment by OxygenCobalt** [comment]
> This feature isn't something that needs prioritisation so please don't feel rushed.

Prioritization would not make me have to implement it by like, march. It just means I will do it first, whenever I have the time.

**Comment by gtsiam** [comment]
It may not need prioritization, but it would be much appreciated. I've been telling myself I'll do it, but I havent been able to find the time just yet.

 I might still do it, so ping me if you start working on it @OxygenCobalt. In any case, mark it for prioritization.

**Comment by OxygenCobalt** [comment]
Okay, I've marked this and the required #244 as prioritized. It will be done after #342, which was prioritized earlier. A $16/month sponsor could prioritize this such that I do it first.

I am also open to contributions @gtsiam. Note that there are a lot of architectural details here, since you have to make `PlaybackService` operate without the assumption that the app is already in foreground. This means that in general:
- You must merge `IndexerService` and `PlaybackService` together, which also requires handling the interaction of their lifecycles.
- You must enter a foreground state as quickly as possible, possibly through a music loading notification. Then you swap that out with a playback notification.
- You have to make sure music loading (especially responding to music changes) operates correctly in all service states. I forgot the specifics here, but I'll get to them later.

**Comment by OxygenCobalt** [comment]
Update Time!

So I've merged the two services, kind-of. What used to be the services now inherit a weird "fragment" class I made up. But they are still operating under the assumption that the app is in the foreground. The issue is that the flow might be something like:

- Music starts loading, so the service goes foreground
- Music finishes loading, so the service exits foreground
- <200ms of delay ass Playback initializes
- Playback goes foreground

And that's if there's music to be loaded and things to play. If there's neither, no foreground will occur. As a result, I must design the service lifecycle under two hard rules:

1. Absolutely no downtime. Even if you're not doing work, hang on the last foreground notification until you're absolutely certain we can safely exit foreground without suprises. I think I can do this by basically making the service flag if it wants to foreground, background, or if it doesn't know what it wants to do yet.
2. Always assume you have basically no time to go foreground. OEMs probably play fast and loose with the foreground time limit, so I may have to start foreground with a fake notification just to satisfy the OS.

There's likely more refinement I need to do regarding this. I have some ideas on how to detect from the service's end if it was started by another part of the OS or if it was started by the app, which should allow me to switch between uptight and loose foreground behavior. Sadly I'm tied up with all the 3.4.0 bug reports, school, and a hackathon, so I'm not going to be able to do much for now.

**Comment by OxygenCobalt** [comment]
Minor Update: Still have no time to work. But I realized in #244 that Android may actually tolerate Auxio briefly going into the background. It could be possible that the background service restrictions only apply once. From there I can swap between background and foreground whenever I want (within reason). I need to test though.

**Comment by OxygenCobalt** [comment]
I've started implementing this using the new service implementations provided by `media3`. I'm arriving at a point I'd describe as "usable" but I need to do a lot of extensions. There's also no guarantee that I'm not silently introducing lifecycle issues.

**Comment by OxygenCobalt** [comment]
External apps can now access Auxio's music library:

![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/05c031c2-55dd-49ba-b7e0-a094d93689c5)

(This is from a controller text)

From here I need to do a full integration with android auto (requires some extra config), and then continue rounding out and making bug fixes.

**Comment by OxygenCobalt** [comment]
Introducing the first Auxio Android Auto build!

Warning:
- This is probably extremely broken since I'm can't figure out how to test it in an emulator
- You probably still need to open the app first and play some music before connecting to it on Android Auto (I'm working on that, see #244. I hope it'll work)

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/14954519/Auxio_Canary.zip)

@BabyBenefactor @gtsiam

**Comment by OxygenCobalt** [comment]
Can you send me some pictures of what it looks like in android auto (if possible) @BabyBenefactor? I can't test it and I want to make sure it "looks right".

**Comment by OxygenCobalt** [comment]
Closing this for now since it's basically "done" minus bug fixes.

**Comment by OxygenCobalt** [comment]
This is perfect, thanks @BabyBenefactor. Overall it seems like it works well.

**Comment by OxygenCobalt** [comment]
Okay, there will be one minor degradation: Due to a bunch of annoying internal issues, the notification cover will be stuck on it's default setting until #327. I didn't want to do this, but media3 is not really designed well for this.

**Comment by OxygenCobalt** [comment]
This is weird @curbengh, I'm publishing all my metadata as right as far as I am aware. Will need to see what's going on with VLC.

**Comment by zsrv** [comment]
@OxygenCobalt my car has an option to see/control the playlist for Bluetooth devices, but no information is available there when I'm playing music from Auxio. Was this something that was supposed to become working with this change? (note that I can skip to the previous/next track and play/pause, there is just no playlist information available)

**Comment by OxygenCobalt** [comment]
Hm, it all depends on your phone's ability to translate the metadata I publish to the bluetooth AVRCP which can be very flaky @zsrv 

Otherwise Id have to implement the handling myself which is much harder since Android doesn't make it easy to peek into low-level protocol details afaik
