### ISSUE TITLE
Accept REPLAYGAIN_* tags on Opus files

### ISSUE THREAD

**Issue by TheOneric** [OxygenCobalt/Auxio#372]
### Description

Parse and use `REPLAYGAIN_*` tags on Opus files.

### Problem solved

I recently tagged all audio files on my phone with replaygain info, but noticed the tags seemed to be ignored on most files, even after resetting the tag cache.

Looking at [this bit of code](https://github.com/OxygenCobalt/Auxio/blob/63e5a7ee6914a5336462840805b73a42145be9b6/app/src/main/java/org/oxycblt/auxio/playback/replaygain/ReplayGainAudioProcessor.kt#L171) it appears like Auxio accepts *only* `R128_` tags for Opus files, and only `REPLAYGAIN_*` tags everywhere else.

This fits well with the symptoms since most files on my phone are Opus and *all* formats use `REPLAYGAIN_*` tags since this is rsgain’s default behaviour. It works as expected in e.g. mpv.

### Other implementations

For comparison mpv [accepts both](https://github.com/datasone/mpv/blob/master/demux/demux.c#L2948) `REPLAYGAIN_*` and `R128_*` tags regardless of format, preferring the former.

Not directly related to my issue, but perhaps worth mentioning: If neither `REPLAYGAIN_TRACK_*` nor `REPLAYGAIN_ALBUM_*` exists, mpv also accepts `REPLAYGAIN_GAIN`/`REPLAYGAIN_PEAK` as an alias for `REPLAYGAIN_ALBUM_*`. [Supposedly](https://github.com/datasone/mpv/commit/9b15c99aa13acdbb3e86fbb3395ad107b436fdaa) this variant originates from matroska files *(and may have spread to some other files via remuxing)*.
(mpv also reads out the `REPLAYGAIN_*PEAK` value(s) and appears to use it for clipping prevention. On a first glance Auxio does not appear to use peak values, though perhpas it already uses an alternative mechanism.)

### Benefit

Given that it’s rsgains default behaviour to write out `REPLAYGAIN_*` tags, I’d assume there are more such Opus files out there. Accepting the regular `REPLAYGAIN_*` tags regardless of format, would make the replaygain feature work more smoothly for affected users.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Exactly what I thought when I made that change. Everywhere *says* that `R128_*` is the only tag use, but there are always software that doesn't get the memo. I'll go fix it.
