### ISSUE TITLE
Handle `COMPILATION` tags

### ISSUE THREAD

**Issue by Yakuky** [OxygenCobalt/Auxio#373]
### Description

I find that Auxio is considering songs as different albums if they do not share the same Artist or Album Artist, even if their Album tag is the same.

Actually there are albums whose every song has a different Artist without an Album Artist, for example, [Disney Greatest Songs](https://music.apple.com/jp/album/dream-disney-greatest-songs-global-artist-version/1436921597?l=en).

Instead of hard coding "Various Artists" as the Album Artist for every song like that, it is also possible to add `ITUNESCOMPILATION`=`1` so that these songs can be grouped as the same album in many music players.

### Problem solved

Songs in the same album to be grouped in different ablums

### Other implementations

Follow `ITUNESCOMPILATION` to group album with different artists

### Benefit

Album with such tag can be correctly organized

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Okay, I guess I can map `ITUNESCOMPILATION=1` and `COMPILATION=1` to the following:
- Set release type to "Compilation"
- Set the album artist to "Various Artists"
