### ISSUE TITLE
Crash if trying to click multiple sections in settings at once

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#374]
Hello,

Auxio crashes if you try to click multiple sections (like appearance, content) in the settings at once because it tries to navigate to mutliple fragments with destinations that do not exist.
Stacktrace:
```
FATAL EXCEPTION: main
Process: org.oxycblt.auxio, PID: 24647
java.lang.IllegalArgumentException: Navigation action/destination org.oxycblt.auxio:id/go_to_personalize_preferences cannot be found from the current destination Destination(org.oxycblt.auxio:id/ui_preferences_fragment) label=fragment_ui_preferences class=org.oxycblt.auxio.settings.categories.UIPreferenceFragment
```

You can easily fix this by putting the `navigate()` statement into a `try`-`catch`, you can safely ignore the exception.

(Sorry for creating this without template. I was using a third-party android app that doesn't support issue forms. I hope I answered all questions.)

**Comment by OxygenCobalt** [comment]
Oh. Thanks for pointing this out, I'll work on a fix.
