### ISSUE TITLE
Long album titles flickering in landscape

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#376]
### Describe the Bug

1. Play some album with a long title
2. Enter landscape mode
3. Open the current playback view
4. The album title flickers. If you pause the music, everything will work fine, but if it is playing it flickers and doesn't scroll.

### Describe the intended behavior

Should scroll, just what happens if you pause your music

### What android version do you use?

Android 12

### What device model do you use?

Stock Android (Android One)

### Relevant log output

```shell
N/A
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Known issue that stems from a UI limitation, should be an easy fix when I have time.
