### ISSUE TITLE
Unsplit Artists 

### ISSUE THREAD

**Issue by abel2580** [OxygenCobalt/Auxio#377]
### Description

Provide option to manually specify which artist should not be splitted like 'Tyler, the Creator'.

### Other implementations

![Screenshot_20230226-144746_Pixel Launcher](https://user-images.githubusercontent.com/126383629/221402152-e441b11f-a22f-4ca4-93bf-a8dfaf9c9ea0.png)

### Benefit

This feature will avoid incorrect interpretation of  multiple values. The option to prefixing unwanted separator characters with a blackslash (\) is inconvenient.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Hard-coded separator information is disabled by default for this exact reason. Re-tag your library to use [native multi-value tags](https://github.com/OxygenCobalt/Auxio/wiki/Advanced-Functionality#native-multi-value-tags) instead of separator characters. Not doing this.
