### ISSUE TITLE
Ignore punctuation in search

### ISSUE THREAD

**Issue by nzure** [OxygenCobalt/Auxio#378]
### Description

It would be neat if the search could ignore certain characters when searching, such as Quotes (`"`, `'`, `«»`, `“”`, `‘’`)
or Colons (`;`, `:`).

### Problem solved

It makes searching on the phone faster, because I don’t have to switch the keyboard page and enter a special character to get the search result that im looking for. It also makes it easier to search for tracks that use the correct typographic characters, which need even longer to input.

### Other implementations

Other music players such as spotify or Oto Music “ignore” these characters when searching for tracks. Given the Input `Aint a`, the song `Ain’t a Thing` shows up.

### Benefit

In my opinion, it would improve the general usability of Auxio. Maybe one could introduce a checkbox for backwards compatible behaviour.

### Duplicates

- [x] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I can probably do this, either by fuzzy search or just stripping separator information.

**Comment by OxygenCobalt** [comment]
I don't really see how anyone would prefer a "strict" mode over looser search options @illdeletethis.

**Comment by illdeletethis** [comment]
as someone who wants that strict mode, it finds exactly what was searched for

**Comment by OxygenCobalt** [comment]
In that case, it's already done. Auxio simultaneously checks "fuzzy" information and "strict" information when searching, so if you type down a specific song name (punctuation and all), it should return that one song.
