### ISSUE TITLE
Ability to cast music to other devices

### ISSUE THREAD

**Issue by abskmj** [OxygenCobalt/Auxio#379]
### Description

I want to be able to cast music to other devices. It is a really convenient way to play something on my smart speaker or android tv.

### Other implementations

I have been using black player and, to music player, both of them support casting to other devices. 

### Benefit

It is a really convenient way to play something on a smart speaker or a smart tv.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I can only do this with the proprietary google play services library, which then disqualifies Auxio from F-Droid. Not doing this.

**Comment by alexceltare2** [comment]
I would second that. DLNA, Chromecast and AirPlay support would be awesome some time in the future.

**Comment by Semuria** [comment]
> I would second that. DLNA, Chromecast and AirPlay support would be awesome some time in the future.

Indeed, in meantime I'll have to go with VLC as workaround. 

Let's not loose hope that ExoPlayer gets support for DLNA one day.
