### ISSUE TITLE
New added tracks not working 

### ISSUE THREAD

**Issue by Grkrz** [OxygenCobalt/Auxio#381]
### Describe the Bug/Crash

For some reasone newly added songs are not played by auxio. The format is the same as other songs, m4a 

### Describe the intended behavior

Play a song

### What android version do you use?

Android 13

### What device model do you use?

Pixel 6 ,GraphenOS 

### Relevant log output

```shell
.
```

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This can be caused by a variety of reasons. Please read the [wiki entry](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting#music-problems) to resolve the problem.

**Comment by Grkrz** [comment]
FYI - every other program is able to play the songs, i also read the wiki. It is ok i have switheched to another APP.
Thank you

**Comment by Grkrz** [comment]
Vinyl, simple music player, the Phoenix. The names of the apps might not be 100 % accurate because I have deleted them. If you won't be able to find them I can look for them.

**Comment by Grkrz** [comment]
What might be  valuables for you the newly added songs were from 
https://invidious.flokinet.to

I can also add that previously downloaded songs works, I did download the same format and in the same manner.

**Comment by OxygenCobalt** [comment]
There are a lot of audio format options on that site. Which one did you use?

**Comment by Grkrz** [comment]
Audio/mp4 
There are only to audio formats there, just different quality. I was always choosing the highest

**Comment by OxygenCobalt** [comment]
Identified the issue, accidental deletion of fragmented MP4 extractor that leads to MP4-AAC not working for whatever reason. See #388.

**Comment by Grkrz** [comment]
Great, mean while I will use older version awaiting new release. 
Great job!

**Comment by ryenyuku** [comment]
@Grkrz you can actually use a dev build in GitHub Actions, it might be not realible but it works fine for me (for now)

**Comment by ryenyuku** [comment]
> @ryenyuku I am not a developer so I have not tried that. Dont know how

I will just send some images on how to get it here
![Screenshot_20230313-202545_Chrome](https://user-images.githubusercontent.com/59136093/224715368-446e870e-9174-483e-8771-536f2b5a02f0.png)
![Screenshot_20230313-202557_Chrome](https://user-images.githubusercontent.com/59136093/224715386-0fcc514c-0044-4f67-aa80-635f389bbba2.png)
![Screenshot_20230313-202609_Chrome](https://user-images.githubusercontent.com/59136093/224715393-c918d895-1233-4287-a98f-1b73de5627b5.png)

**Comment by OxygenCobalt** [comment]
I can confirm that using the CI builds is an option, but they tend to be somewhat slower and buggier. For example, I'm pretty sure queue editing is broken in the latest one.

**Comment by ryenyuku** [comment]
Yeah that's why I said that it might be not realible. It works fine for my use cases (for now) but may not be for everyone.
