### ISSUE TITLE
Playing audio files from the file manager

### ISSUE THREAD

**Issue by tinkonk** [OxygenCobalt/Auxio#382]
### Description

I would like Auxio to add an ability to play audio files from the file manager, including ones that it is not allowed to.

### Problem solved

Auxio doesn't let me play audio files from the file manager, it instead redirects me to the app. It also only allows me to play files that I've given access to play (Storage Scopes on GrapheneOS).

### Other implementations

In ny opinion, Anrimian's Simple Music Player (https://github.com/Anrimian/music-player) does it best, only missing notifications for when closing the window if you allow it to play the audio file when the window is closed.
![IMG_20230227_215444](https://user-images.githubusercontent.com/126486576/221671090-102aded7-15e4-413c-af3d-2b5f6e0dd40f.jpg)

### Benefit

This feature allows for playing audio files from the file manager, even ones that it is not allowed to.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is basically impossible with the current approach that I take to handling music. Auxio really isn't designed for playback from music folders anyway, which is also the same reason the app has no folder view.
