### ISSUE TITLE
Sleep Timer

### ISSUE THREAD

**Issue by Nagoro79** [OxygenCobalt/Auxio#383]
### Description

Please add a Sleep Timer feature to Auxio. That'll be really helpful & awesome feature.. Thanks in advance.

### Problem solved

No, Auxio is always the best, but the feature would be really helpful.

### Other implementations

Good.

### Benefit

This will feature would allow automatic turning off the music player in specified time.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I do not get any benefit from Sleep Timer functionality. Not adding this. Sorry.
