### ISSUE TITLE
Auxio is pulling weird artist tags

### ISSUE THREAD

**Issue by pwd-github** [OxygenCobalt/Auxio#390]
### Describe the Bug/Crash

literally every other player uses normal tags but the tags Auxio is pulling, I can neither find nor edit

### Describe the intended behavior

display the same artist data as other local media apps

### What android version do you use?

Android 13

### What device model do you use?

Pixel 4XL

### Bug report

n/a

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by pwd-github** [comment]
![Screenshot_20230305-175223](https://user-images.githubusercontent.com/203217/222977238-09cec467-b342-4572-9e53-76cc1a71afb2.png)

![Screenshot_20230305-175257](https://user-images.githubusercontent.com/203217/222977243-2bf26670-f60e-4baf-bcea-dbaecd4ae5ac.png)

**Comment by OxygenCobalt** [comment]
You are delimiting multiple artist values by the / character. You can get Auxio to treat these as several artists by going to Settings -> Content -> Music Separators, enabling the "Slash" character, and pressing "Ok". This is not enabled by default as it risks false positives.

**Comment by pwd-github** [comment]
I'm confused. How do I get it to treat not touch my artist tags at all so it appears as the bottom screenshot? Because having enabled the slash, it's now showing Irah as an artist and he's not an artist of the track, he's a feature. I don't understand why Auxio is trying to do too much. Half of my scrobbles for this week were messed up.

**Comment by OxygenCobalt** [comment]
I'm not really sure how the other music player you are showing is arriving at such a tag setup, unless it's pulling from last.fm. Auxio only pulls from local music metadata, and there is no defined metadata spec for features.

**Comment by pwd-github** [comment]
is it possible that Auxio is pulling from an older version of ID3, like everything else is using v2 and Auxio is using v1?

**Comment by OxygenCobalt** [comment]
No version of ID3(v2) has support for "features". Only artists.

**Comment by pwd-github** [comment]
Not that it has support for features, but that Auxio displaying the artist as "Chase, Status, Irah" while Shuttle, Musicolet, Shuttle 2, VLC, Google Files and Plex all display the artist as simply "Chase & Status" suggests that Auxio is pulling perhaps ID3v1 instead of v2.

**Comment by OxygenCobalt** [comment]
I see. I will need a sample file to investigate further. AFAIK, Auxio doesn't even use ID3v1 unless there isn't any ID3v2 tags.

**Comment by pwd-github** [comment]
Sure thing: https://www.dropbox.com/s/mtaenuv8d2vqybz/Chase%2C%20Status%20%20Program%20featuring%20iRah.mp3?dl=0

**Comment by OxygenCobalt** [comment]
I see what's going on. Your artist information differs between the "Artist" and `ARTISTS` tags. One has the correct "Chase & Status", while the other has "Chase/Status/Irah". Auxio picks from `ARTISTS` first, as it often provides more correct information. 

I stand by my decision in this case, as I would consider three artists named "Chase, Status, Irah" to be more correct than one "Chase & Status" artist. If you don't like this, I would recommend retagging your music to either remove the `ARTISTS` tags or at least make it match up with "Artist".

**Comment by pwd-github** [comment]
I'm no expert, but if every other player respects Artist, rather than artists, it feels like the overreach of artists should be an option. Also looking at the spec on the web archive, it specifically mentions artist rather than artists.

**Comment by OxygenCobalt** [comment]
I disagree. It is common for taggers to put just one artist inside the "Artist" tag, and then put a correct list of artists in the "Artists" tag. For example, this is the default behavior of Beets. Just because something is "standard" doesn't mean it is actually followed.

**Comment by OxygenCobalt** [comment]
Quick Update: When I do #582, this issue should be resolved a little, as ideally Auxio will begin displaying "Chase & Status" as the artist even if internally it will be linked to individual Chase, Status, and Irah artists.

**Comment by pwd-github** [comment]
That's definitely a step in the right direction. The artist versus artists tag has been a pain point for me personally, but I still talk up Auxio whenever I get the chance.
