### ISSUE TITLE
Broadcast audio session close on pause 

### ISSUE THREAD

**Issue by Iscle** [OxygenCobalt/Auxio#391]
### Describe the Bug/Crash

1. Play a song
2. Audio session is opened (if it wasn't before), [broadcast](https://developer.android.com/reference/android/media/audiofx/AudioEffect.html#ACTION_OPEN_AUDIO_EFFECT_CONTROL_SESSION) is sent
3. Pause playback
4. Audio session is not closed, [broadcast](https://developer.android.com/reference/android/media/audiofx/AudioEffect.html#ACTION_CLOSE_AUDIO_EFFECT_CONTROL_SESSION) is not sent

### Describe the intended behavior

1. Play a song
2. Audio session is opened (if it wasn't before), [broadcast](https://developer.android.com/reference/android/media/audiofx/AudioEffect.html#ACTION_OPEN_AUDIO_EFFECT_CONTROL_SESSION) is sent
3. Pause playback
4. Audio session is closed, [broadcast](https://developer.android.com/reference/android/media/audiofx/AudioEffect.html#ACTION_CLOSE_AUDIO_EFFECT_CONTROL_SESSION) is sent

### What android version do you use?

Android 13

### What device model do you use?

POCO F4 (issue is not specific to any device really)

### Bug report

Basically, the audio session should be broadcasted at the beginning of playback (user presses play) and kept open until the end of playback (user presses pause). If the user seeks the current song, goes to the previous track, goes to the next one, or selects one from the list, the current session should be kept alive and no broadcasts should be sent.

Spotify has the right implementation for it. (read more [here](https://community.spotify.com/t5/Ongoing-Issues/Android-Audio-sessions-are-not-opened-and-closed-properly/idi-p/4861998))

Right now, the current implementation causes ViPER4Android (and all other effects like Wavelet, JamesDSP) to never close the session, keeping allocated memory and resources.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Are you sure about this? It says in the documentation that:

> It is good practice for applications to broadcast this intent when **music playback stops** and/or when exiting to free system resources consumed by audio effect engines.

I don't know whether to interpret that as "Paused music" or "No music playing anymore". Can you specifically confirm what it specifically means? Also, what is wrong exactly with apps like ViPER or Wavelet keeping the session allocated? It's not necessarily a memory leak.

**Comment by Iscle** [comment]
I interpret it as paused music, and in practice that makes sense. Normally when someone stops listening to music (headphones/bluetooth disconnect), Android pauses the playback but does not kill the app. When playback is paused, the app might be in the background forever, but we don't need to keep the effect's resources allocated.

Allocating effect resources takes less than 1 second, but the memory footprint is quite large (especially in advanced effects like ViPER). 

Furthermore, in ViPER if there are no sessions currently playing we release all resources and kill the background service, removing the foreground service notification and everything else. With the current Auxio implementation, ViPER resources are not freed, the service keeps running and the notification is there until you manually quit the Auxio app, which is annoying. 

Let me know if you need some more insight :)

**Comment by OxygenCobalt** [comment]
Oh. That makes a lot more sense. I'll go do that.

**Comment by Iscle** [comment]
Thanks! By the way, check your email :)
