### ISSUE TITLE
No Folders?

### ISSUE THREAD

**Issue by pete10-1-001** [OxygenCobalt/Auxio#393]
### Description

Hello
Is there really no possibility to play just the content of a folder? Neither the category songs, albums, artists nor genres are what I am looking for. Just a cetegory folder listing folders with music. I can't belive, it's nor already there.
Greetings Pete

### Other implementations

Just folders

### Benefit

This would be much better

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio is not a folder-based music player. It's more geared towards well-tagged libraries, as there are much less edge-cases to handle in the user experience. Sorry.

**Comment by pete10-1-001** [comment]
Thanks for the fast answer. Too bad because auxio would be a very good player.
