### ISSUE TITLE
More intelligent (alphabetical) sorting

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#394]
### Description

Improve the sort algorithm (which is probably standard Kotlin sorter right now) to sort numbers. For example, having titles starting with 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 will sort as 1, 10, 2, 3, ... It would be nice if this could sort after numbers.

### Problem solved

having titles starting with 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 will sort as 1, 10, 2, 3, ...

### Other implementations

Not a music player, but AFAIK GNOME Files supports this with an additional settings option.

### Benefit

Better sorting

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is a good idea. Primary concern is with efficiency. I'll look into it.
