### ISSUE TITLE
OPUS files with video streams don't show tags and can't be played

### ISSUE THREAD

**Issue by TheLastZombie** [OxygenCobalt/Auxio#396]
### Describe the Bug/Crash

1. Get an OPUS file*, for example [this one from my library](https://linx.sny.sh/selif/lbqhy9ji.ogg)
    \* I noticed that this bug does not occur with every OPUS file in my library, but about 95% of them. Here's [a file that doesn't have this issue](https://linx.sny.sh/selif/ikijv3es.ogg)
    \* See comment below for more details
3. Add it to a folder indexed by Auxio
4. Reload the library if needed

The first file above shows up like this:

![Screenshot_20230319-115701_Auxio](https://user-images.githubusercontent.com/8181990/226170837-3d911145-68bf-4a01-8861-e4054d37c674.png)

The file itself is tagged correctly, as shown by e. g. FFmpeg:

```
$ ffprobe -i 01.\ Roaming.ogg
ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
[...]
Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavc59.37.100 libopus
      title           : Roaming
      artist          : 2 Hands On Knobs
      track           : 1/2
      album           : Copper Medallion
[...]
```

When tapped on (in order to play it), Auxio immediately skips to the next track in the queue.

### Describe the intended behavior

The file's metadata should be indexed and displayed correctly, and the file should be able to be played.

### What android version do you use?

Android 13

### What device model do you use?

OnePlus 7 Pro (DivestOS 20.0-20230220)

### Bug report

[Here](https://linx.sny.sh/selif/z2icvn31.zip)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by TheLastZombie** [comment]
I did some more tinkering with the files, and it seems like this happens when the respective file also has a video stream (in my case, I encoded the files with FFmpeg, which turned the embedded album cover into a Theora stream).

The following FFmpeg command removes the embedded video stream and thus fixes (or works around) this issue:

```
ffmpeg -i input.ogg -vn -c:a copy output.ogg
```

This works for me – I have additional cover.jpg files anyway – but I suppose I'll leave this GitHub issue open anyway.

**Comment by OxygenCobalt** [comment]
From what I can see, ExoPlayer is attempting to read an ogg theora stream, doesn't recognize it, and then errors out, even if there's a valid ogg opus stream in the file as well. This is likely working as intended, and mass-converting the files is the best option.
