### ISSUE TITLE
Some Audio Entries skip to others

### ISSUE THREAD

**Issue by dreamsyntax** [OxygenCobalt/Auxio#399]
### Describe the Bug/Crash

An audio entry is found in search (or by scrolling), but clicking it skips to a random track.

4.24 MB, 44100 Hz, 4:27 duration

I will update with debug info soon.

### Describe the intended behavior

Auxio should play the audio entry

### What android version do you use?

Android 13

### What device model do you use?

Pixel 6 (Graphene OS)

### Duplicates

* [x] I have checked the Troubleshooting page.
* [x] I have checked this issue for duplicates.
* [x] I have checked that this issue occurs on the latest version.
* [x] I agree to the Contribution Guidelines.

**Comment by OxygenCobalt** [comment]
This occurs when Auxio cannot play a file. I want to change it eventually to actually show the specific error, but that's non-trivial. If I were to guess, it's probably #388.

**Comment by dreamsyntax** [comment]
Ah thanks, you are right on. I confirmed it does not occur in 3.0.2, and target is m4a type.

**Comment by OxygenCobalt** [comment]
Yep. Very sorry about that breakage, I didn't even know MP4 had two specifications like that.
