### ISSUE TITLE
Music loading failed

### ISSUE THREAD

**Issue by coderkei** [OxygenCobalt/Auxio#4]
#### Describe the bug/crash:

- Upon installing the app and granting the storage permission, it says "Music loading failed". Pressing retry yields the same error. I have ensured the storage permission was granted. According to MediaStore I have approximately 1200 songs but I not sure if that is related.

#### Steps To Reproduce the bug/crash:
1. Install app
2. Press "Allow" for the storage permission prompt
3. App says "Music Loading failed"
4. Retry does nothing, nor does force closing and trying.

#### Phone Information:

Oppo Reno
ColorOS 7.1
Android 10

App version is 1.3.0 installed from the IzzyOnDroid F-Droid Repo.

#### Due Diligence:

- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Interesting. Can you get a `logcat` of the app process so I can figure out where the error is?

**Comment by coderkei** [comment]
I filtered the logcat by the app's pid so hopefully it has the information you need. I have attached it.
[log.txt](https://github.com/OxygenCobalt/Auxio/files/6010905/log.txt)

**Comment by OxygenCobalt** [comment]
Okay, seems like Auxio is trying to apply more than one genre to a song. Is it possible that your music library has multiple genres applied to a song's metadata?

**Comment by coderkei** [comment]
I don't think so, although using another Music Player (Vanilla Music in this instance), one of the Genres in the list is simply blank and I wonder if that's the cause. The majority of the songs under this genre are still regular albums however.

**Comment by OxygenCobalt** [comment]
Possibly. Either way Im going to commit a change that removes the `IllegalStateException` that gets thrown when applying a genre again. It may result in a garbled genre but I think its better than a completely inoperable app. The change should be pushed to 1.3.1.

**Comment by coderkei** [comment]
I checked one of the songs with a blank Genre in a metadata tag editor and it seems to be a single space.

**Comment by OxygenCobalt** [comment]
Got it, Ill test it myself.

**Comment by OxygenCobalt** [comment]
Okay, Ive applied a similar song and Auxio seems to handle it just fine. It may be something else, still making the change I described earlier however.

**Comment by OxygenCobalt** [comment]
Try this debug APK, does the original issue still occur? [Rename it from `app-debug.apk`]

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/6011553/app-debug.zip)

**Comment by coderkei** [comment]
I am unable to install it, Package manager says "App not installed"

**Comment by OxygenCobalt** [comment]
Try this one, not sure what happened to the last one.

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/6011646/app-debug.zip)

**Comment by coderkei** [comment]
Seems to work fine now. Loads all the albums I have.

**Comment by OxygenCobalt** [comment]
Good, Ill push the changes and close this issue. Thanks for letting me know about this.
