### ISSUE TITLE
Incorrect artist name displayed in some songs

### ISSUE THREAD

**Issue by ibrajix** [OxygenCobalt/Auxio#40]
#### Describe the bug/crash:

Some songs are not showing the correct artist names.

Songs whose artiste name can not be determined should be marked as "Unknown" instead of displaying an entirely different artiste name, as seen currently  in Auxio

#### Steps To Reproduce the bug/crash:

On the list of songs, some songs whose artiste name cannot be determined are tagged with the wrong artiste.

As seen in the screenshot, those songs are from 'Alan Walker ' not 'Reekado Banks'

I am also attaching a screenshot of similar songs in a different music player app - Samsung Music Player

#### Screenshots:
![Screenshot_20210819-044252_Auxio Debug](https://user-images.githubusercontent.com/39574228/130004964-cf37789d-af3d-4367-9545-d4dfa8951d35.jpg)

![Screenshot_20210819-045534_Samsung Music](https://user-images.githubusercontent.com/39574228/130005280-af9d0f3c-d8ce-4c48-8222-41b81008be4c.jpg)

#### Phone Information:
Samsung Galaxy S9 plus

#### Due Diligence:

- [•] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Oh. Is your music folder just named `Music`? I think I may know whats going on here.

**Comment by ibrajix** [comment]
> Oh. Do you have music folders named `Music` and `Reekado Banks`? I think I may know whats going on here.

I have a folder named 'Music' but I dont have any folder named 'Reekado Banks'.

The 'Reekado Banks' is given to any song whose artist name cannot be determined... like a default. 

In other music players... I see "Unknown"

**Comment by OxygenCobalt** [comment]
Okay, thats strange. Android will default to the folder name [In this case, `Music`] when it can't find an album name. I can't change that behavior.

The artist though is really odd. Do you have an song with an artist named `Reekado Banks`?  If that's the case, then I bet that the Artist ID of the `Music` album is colliding with another artist and is thusly being assigned to them. That's fixable, but would result in a performance hit.

**Comment by ibrajix** [comment]
> Okay, thats strange. Android will default to the folder name [In this case, `Music`] when it can't find an album name. I can't change that behavior.
> 
> The artist though is really odd. Do you have an song with an artist named `Reekado Banks`? If that's the case, then I bet that the Artist ID of the `Music` album is colliding with another artist and is thusly being assigned to them. That's fixable, but would result in a performance hit.

Yeah, I dont have a problem with the album been displayed.

**Comment by OxygenCobalt** [comment]
Okay. It seems like this is just a plain ID collision. I'll be merging this into #38 and will try to address it eventually.

**Comment by ibrajix** [comment]
> Okay. It seems like this is just a plain ID collision. I'll be merging this into #38 and will try to address it eventually.

Alright... 👍👍

**Comment by OxygenCobalt** [comment]
I made a music refactor that I think might fix this issue in the next Auxio release. You can go test it if you want or you can wait for the next Auxio release to try it out.
