### ISSUE TITLE
Artists sort is not working properly

### ISSUE THREAD

**Issue by robertoprubio** [OxygenCobalt/Auxio#400]
### Describe the Bug/Crash

Some artists are not correctly sorted (see "Los rápidos" in the attached screenshot)
I have enabled ascending alpha sort and disabled the ignore articles when sorting

### Describe the intended behavior

Sort works properly

### What android version do you use?

Android 13

### What device model do you use?

Pixel 7 Pro

### Bug report

No one rellevant info at logs

Screenshot:

![Screenshot_20230319-074742](https://user-images.githubusercontent.com/31618496/227464881-fc7323e2-9ed6-44a1-bec4-8e4257120ec6.png)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by robertoprubio** [comment]
No, I do not have any (in fact is the first time I read about this tag field) 😅
I can send the song file if you have a email address

**Comment by OxygenCobalt** [comment]
An e-mail address is in my github profile.

**Comment by OxygenCobalt** [comment]
Yep, you have sort tags in your files. Here's the output from kid3:

![image](https://user-images.githubusercontent.com/65370175/227565771-1a99f512-88e8-42cd-8120-e213ebbcccd0.png)

More specifically, the artist and sort artist tags are not correctly set up. The artist "Los Rapidos", but then the sort artist is "El Ultimo de la Filla". This results in it being sorted near artists that start with "E". You could fix this by removing the sort tags or changing them to something like this:

![image](https://user-images.githubusercontent.com/65370175/227566272-5d06ba42-4835-4bd1-8edc-94d836b06d0e.png)
