### ISSUE TITLE
Allow to click on playing view above queue

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#402]
### Description

This is a pretty small and detailed issue, but for the sake of consistency, it would be nice if you could open the "now playing" view by clicking on the bar above the queue on the queue screen.

### Other implementations

-

### Benefit

Consistency

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Interesting idea. I'll look at what I could do.
