### ISSUE TITLE
Covers not displayed with fast "Album covers" setting for opus files

### ISSUE THREAD

**Issue by tsiflimagas** [OxygenCobalt/Auxio#409]
### Describe the Bug/Crash

1. Set "Album covers" to "Fast" in content settings. 
2. Download a track in opus format (e.g. from YT using Seal)
3. Reload music to show it up and play it.
4. The cover is not displayed. 

### Describe the intended behavior

I'm not sure if my expectation is right, since on "High quality" setting it shows the covers for opus files, but perhaps they could be shown with the "Fast" setting too. 

### What android version do you use?

Android 13

### What device model do you use?

Xiaomi Redmi note 8

### Bug report

Not sure if that's really needed in this case. 

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
"Fast" relies on the android system, which often fails to extract metadata since it has not been updated in 10 years. Nothing I can do about this, just use High Quality.
