### ISSUE TITLE
Album art not displaying in notification tray

### ISSUE THREAD

**Issue by ibrajix** [OxygenCobalt/Auxio#41]
#### Describe the feature you want to implement:

I think most modern music players have this, It'll be nice to have in Auxio.

Attached is a screen shot of notification tray of both Auxio and Samsung Music.

![Screenshot_20210819-050504_One UI Home](https://user-images.githubusercontent.com/39574228/130006205-ec3caa8d-19b2-496e-ac38-8cdb6c4a44e1.jpg)

#### Is your feature request related to a problem? Please describe:
No

#### Why do you think this will improve everyone's usage of Auxio?
From a glance, everyone could know the artiste of the song playing by just looking at the album art.

#### Due Diligence:

- [ •] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Odd. This may be a samsung thing since it works on my device. Do other apps show the cover art?

**Comment by ibrajix** [comment]
> Odd. This may be a samsung thing since it works on my device. Do other **non-samsung** apps show the cover art?

Yes. They do. I personally develped a music player and it shows... 

I used `PlayerNotificationManager.createWithNotificationChannel()`

Passing a DescriptionAdapter as a parameter which implements `PlayerNotificationManager.MediaDescriptionAdapter`

Overriden medthod `getCurrentLargeIcon()` is responsible for showing the bitmap displayed in the notification tray.

**Comment by OxygenCobalt** [comment]
Hm. I just use `NotificationBuilder.setLargeIcon` for me. It seems like the `PlayerNotificationManager` ExoPlayer extension does something that I am not. Let me investigate further.

**Comment by OxygenCobalt** [comment]
Quick question: Do you have the "Show Covers" or "Colorize Notification" setting off? Either one will result in the notification not displaying album art.

**Comment by ibrajix** [comment]
> Quick question: Do you have the "Show Covers" or "Colorize Notification" setting off? Either one will result in the notification not displaying album art.

Noppe. They are nor turned off.

**Comment by OxygenCobalt** [comment]
Okay. Can you try this debug APK [Rename the extension from .zip to .apk]? It may be that some quirk about the asynchronous cover loading that results in the cover not being displayed. If it isn't this, then I have no idea what's going on and its probably a samsung quirk.

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/7018535/app-debug.zip)

**Comment by ibrajix** [comment]
> Okay. Can you try this debug APK? [Rename the extension from .zip to .apk] It may be that some quirk about the asynchronous cover loading that results in the cover not being displayed. If it isn't this, then I have no idea what's going on.
> 
> [app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/7018535/app-debug.zip)

Cant install - I am getting "App not Installed" error

**Comment by OxygenCobalt** [comment]
Oh. Sometimes studio doesn't properly sign debug builds. I'll make a new one later today when I have time.

**Comment by OxygenCobalt** [comment]
Okay, try this build. I did my best to copy whatever ExoPlayer does into my notification code.

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/7024397/app-debug.zip)

**Comment by ibrajix** [comment]
> Okay, try this build. I did my best to copy whatever ExoPlayer does into my notification code.
> 
> [app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/7024397/app-debug.zip)

Sadly, still didnt show.. :(

**Comment by OxygenCobalt** [comment]
Okay, it may actually be a race condition somehow.

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/7025640/app-debug.zip)

**Comment by ibrajix** [comment]
> Okay, it may actually be a race condition somehow. Try this:
> 
> [app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/7025640/app-debug.zip)

Same thing, not showing.

I will check your code and see what might be the cause amd hopefully try to fix. :)

**Comment by OxygenCobalt** [comment]
Sounds good. You'll probably want to start [here](https://github.com/OxygenCobalt/Auxio/blob/dev/app/src/main/java/org/oxycblt/auxio/playback/system/PlaybackNotification.kt).

**Comment by ibrajix** [comment]
> Sounds good. You'll probably want to start [here](https://github.com/OxygenCobalt/Auxio/blob/dev/app/src/main/java/org/oxycblt/auxio/playback/system/PlaybackNotification.kt).

Check my pull request:

Its from this check:

`if (!settingsManager.colorizeNotif)`

It returns true, so this was called:

` setLargeIcon(null)`
