### ISSUE TITLE
Audio files from not added folders can't be played

### ISSUE THREAD

**Issue by robertoprubio** [OxygenCobalt/Auxio#410]
### Describe the Bug/Crash

I own a Pixel 7 Pro and Auxio is the only audio files played that is installed at my device.
In Auxio, I have added /sdcard/Music has the folder that contains my Music files.
Also I have enabled to do not include not Music files (but the described bug/issue also occurs if I do not enable this option).
The case is that when I open a files app then I click on an audio file that is not in the /sdcard/Music folder, the Auxio app is opened but nothing happends and the file that I've selected at the files app isn't played at all.
I assume that Auxio only plays Music from the selected folders but there's no sense (IMO) to do not play the file when I try to open from a external location if isn't at the playable files list.

### Describe the intended behavior

Play files that aren't in the Playable files list when I open from an external app

### What android version do you use?

Android 13

### What device model do you use?

Pixel 7 Pro, GrapheneOS

### Bug report

No bug report

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Intended behavior. Auxio can *only* be aware of the music library it has loaded due to how complicated the data model is. If the file is not in the music library, it cannot be played.

**Comment by robertoprubio** [comment]
These files are at the android media database. You can use the metadata from the system database, but in any case, you can play without show any metadata, due to are files that maybe will be played a single time, like ringtones, recorded calls, etc.
But in any case, is your app and your rules ;)
