### ISSUE TITLE
"Featured on" album grouping on collaborator artist view

### ISSUE THREAD

**Issue by chrispalmeri** [OxygenCobalt/Auxio#411]
### Description

I would like releases that an artist only collaborated on a couple tracks to be separated from releases where they are the main album artist. Basically display these as another release type, something like "Features" after "Albums", "Compilations" etc.

There was a mention of this in https://github.com/OxygenCobalt/Auxio/issues/195#issuecomment-1234480127 but I don't think it actually happened.

### Problem solved

The albums displayed for an artist can be a little confusing when they are both a collaborator and a main album artist.

For example, in this screenshot Eric Church is the album artist for all the albums, except the top one, in which he is just featured on one track of Luke Combs' album.

![image](https://user-images.githubusercontent.com/16784820/230508962-b98a71c5-433d-4b40-ace4-fc3a6221ac6a.png)

### Other implementations

Jellyfin shows these albums in an "Appears on" section.

![image](https://user-images.githubusercontent.com/16784820/230509012-cb4b91ba-efa2-42d9-9334-74f302ce6218.png)

I have not used many other music players recently, some would not have shown that additional album at all, so Auxio's current behavior is already better than that.

### Benefit

This would just make navigation clearer and more enjoyable.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is a good idea. I will look into it.

**Comment by chrispalmeri** [comment]
Yeah, I have a quite a few that appear on Compilations for example. I would say it should just go in "Featured On". Which is a bit of a trade off, no longer differentiating the actual release type, but after all it is not _their_ EP if they are not the album artist. And something like "Featured on EPs",  "Featured on Compilations", etc I think would be too much.

**Comment by OxygenCobalt** [comment]
You are right, actually. I'm already kind-of doing that with the "Live" section in an artist view, which contains all live Albums, EPs and Compilations. Should be an easy change then in the UI.
