### ISSUE TITLE
Bitrate is not correct in properties

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#413]
### Describe the Bug/Crash

This only applies to a few albums (as far as I currently see not single songs), but it's reproducible there.

Open the song properties dialog and scroll down to bitrate. For some songs, Auxio shows for example 32 kb/s, which is too low. Viewing the exactly same file in Dolphin says 181 kb/s. Also, the file is too big to just have a bitrate of 32 kb/s, it must be more.

I can send you an example file via e-mail because this description is probably not very helpful.

### Describe the intended behavior

Should show the correct one.

### What android version do you use?

Android 12

### What device model do you use?

Stock Android One

### Bug report

N/A

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Currently, Auxio relies on the android system to obtain bitrate information, which then just takes the LAME bitrate because the metadata extractor is 10 years out of date. I'm waiting for ExoPlayer to implement bitrate extraction on progressive media, but I might just do it myself when I have time.
