### ISSUE TITLE
Crash on music loading due to intelligent sort name creation

### ISSUE THREAD

**Issue by bugtrapper** [OxygenCobalt/Auxio#414]
### Describe the Bug/Crash

When opening Auxio 3.0.4, it automatically scans the music library. When this is completed, the app crashes before moving over to the library view.
It happens to me both a fresh reinstall (after giving permission to read the music folders) as well as after upgrading from 3.0.3.

3.0.3 works fine.

### Describe the intended behavior

The App shouldn't crash.

### What android version do you use?

Android 13

### What device model do you use?

Xiaomi Mi 8 "dipper" (LineageOS 20.0 / Android 13)

### Bug report

[logcat.txt](https://github.com/OxygenCobalt/Auxio/files/11178486/logcat.txt)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by smallbillgates** [comment]
I also have this. Pixel 4A5G with calyxOS.

**Comment by OxygenCobalt** [comment]
Likely bug with the new sort name system's string processing. Can you try disabling "Content -> Intelligent Sort Names" on a fresh install before granting permission? I'd also like a sample file, since this is an edge-case I have not encountered with my library. @smallbillgates @bugtrapper

**Comment by bugtrapper** [comment]
You're right, disabling the option prevents the crash on my device with this version. Thank you!

What kind of sample file would you like? A single music file which reliably crashes the app?

07.04.2023 16:37:13 Alexander Capehart ***@***.***>:

**Comment by OxygenCobalt** [comment]
Wait, I just realized that you can't provide a sample file since you don't know what file is causing the issue :facepalm:. Could you try a debug APK from [here](https://github.com/OxygenCobalt/Auxio/actions/runs/4522546566/jobs/7965092873) and then record the crash again? I need a specific line to debug that isn't really possible in the release builds @bugtrapper.

**Comment by anonymous5555522222** [comment]
Same here, when I updated to 3.0.4 from F-Droid. My Android's version is 10.

**Comment by OxygenCobalt** [comment]
Uuugh. Every time I make a minor version to fix *one* major issue *another one* pops up. I really need to start unit testing.

**Comment by anonymous5555522222** [comment]
> Likely bug with the new sort name system's string processing. Can you try disabling "Content -> Intelligent Sort Names" on a fresh install before granting permission? I'd also like a sample file, since this is an edge-case I have not encountered with my library. @smallbillgates @bugtrapper
> 
> This should be a trivial fix once I can identify it, but I probably won't be able to make a release for it until a month or so from now.

Thank you! A reinstall wasn't even needed, I just had to remove the storage permission and disable that option, this way all my tuning on the app won't vanish. I will turn it back on when this gets fixed.

**Comment by anonymous5555522222** [comment]
> Wait, I just realized that you can't provide a sample file since you don't know what file is causing the issue 🤦. Could you try a debug APK from [here](https://github.com/OxygenCobalt/Auxio/actions/runs/45225465663) and then record the crash again? I need a specific line to debug, which isn't available in the release builds @bugtrapper.

By the way, this page is giving me a 404 error.

**Comment by OxygenCobalt** [comment]
Huh. Okay. Here's the APK directly then @anonymous5555522222 @bugtrapper. Just take another bug report of the crash like prior.

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11179835/Auxio_Canary.zip)

**Comment by anonymous5555522222** [comment]
> Huh. Okay. Here's the APK directly then @anonymous5555522222 @bugtrapper. Just take another bug report of the crash like prior. Nothing else you need to change.
> 
> [Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11179835/Auxio_Canary.zip)

This build is not crashing for me, it gets stuck in "Loading your music library" instead...

**Comment by OxygenCobalt** [comment]
Probably the half-finished playlist implementation being busted again. Try this one:

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11180301/Auxio_Canary.zip)

**Comment by bugtrapper** [comment]
> Huh. Okay. Here's the APK directly then @anonymous5555522222 @bugtrapper. Just take another bug report of the crash like prior. Nothing else you need to change.
> 
> [Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11179835/Auxio_Canary.zip)

Thank you. I have the same issue as [anonymous5555522222](https://github.com/anonymous5555522222) with the app being stuck in "Loading your music library". Here's the logcat of it anyway: 
[logcat 11179835.txt](https://github.com/OxygenCobalt/Auxio/files/11181095/logcat.11179835.txt)

> Probably the half-finished playlist implementation being busted again @anonymous5555522222. Try this one:
> 
> [Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11180301/Auxio_Canary.zip)

This one properly crashes! :) 
Here's the logcat for that version: 
[logcat 11180301.txt](https://github.com/OxygenCobalt/Auxio/files/11181143/logcat.11180301.txt)

**Comment by OxygenCobalt** [comment]
Okay, I know the issue now. When Auxio attempts to dynamically handle the sorting names, some cases lead to an empty string. There could be a two cases here:

1. Titles that are just `The `, `An `, etc.
2. Titles that are entirely digits, but not parsable as a number for some reason. Like, `3000 000000`

This would result in an empty left-over string that would then later have the first character grabbed for the fast scroller. This ends up crashing since the string is empty. As for why it seemingly entirely kills the app process, it's probably parallelized music loading ruining my life again. Unexpected exceptions suck in this regard.

I will try to fix this as soon as I can. I am so terribly busy right now.

**Comment by bugtrapper** [comment]
I'm glad the logs seemed to be helpful. Thanks again for the quick support and the workaround! 👍 
Feel free to highlight me with any additional test versions if I can be of any help.

**Comment by nicoboss66** [comment]
hi,
i’m having the same issue since 3.0.4 installation from F-Droid on a S9 with /e/os
3.0.3 works fine
crashes even with intelligent sort name creation disabled though

**Comment by OxygenCobalt** [comment]
Can you provide a [bug report](https://developer.android.com/studio/debug/bug-report) @nicoboss66?

**Comment by nicoboss66** [comment]
> Can you provide a [bug report](https://developer.android.com/studio/debug/bug-report) @nicoboss66?

thanks !
I installed and run the second Auxio Canary you provided (that crashes exactlty at the same point as Auxio3.0.4), but unfortunately i can’t figure out how to get/find the logcat.txt

**Comment by OxygenCobalt** [comment]
Just share the bug report file @nicoboss66.

**Comment by nicoboss66** [comment]
sorry, but i m only able to get a 42Mo zip file that does not contain any logcat.txt file
I m certainly not doing things right as i never did it before though

**Comment by nicoboss66** [comment]
[bugreport-starltexx-QQ3A.200805.001-2023-04-11-09-49-43.txt](https://github.com/OxygenCobalt/Auxio/files/11201461/bugreport-starltexx-QQ3A.200805.001-2023-04-11-09-49-43.txt)
here it is
hope it helps
and thank you for the hints to get it

**Comment by OxygenCobalt** [comment]
Dev branch should have a fix for this now. Here is a debug APK:

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11240425/Auxio_Canary.zip)

**Comment by OxygenCobalt** [comment]
Care to test this @bugtrapper @nicoboss66 @anonymous5555522222?

**Comment by bugtrapper** [comment]
I can confirm that the issue is fixed for my device in the debug build. The app no longer crashes when scanning the music library with "Content -> Intelligent Sort Names" enabled.

Awesome!

Xiaomi Mi 8 "dipper" (LineageOS 20.0 / Android 13)

**Comment by nicoboss66** [comment]
Works like a charm here too, thanks !
Samsung S9 (/e/os 1.9 / Android 10)

**Comment by OxygenCobalt** [comment]
Okay, I am going to make a release ASAP.

**Comment by OxygenCobalt** [comment]
This should be available in 3.0.5 now, thanks to @chrispalmeri's PR when I had basically no time to pull a fix for this.

**Comment by anonymous5555522222** [comment]
> Care to test the APK @bugtrapper @nicoboss66 @anonymous5555522222?

Sorry for my inactivity. I have just tested it and it does not crash.
