### ISSUE TITLE
Playing animation icon is incorrectly scaled

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#415]
### Describe the Bug/Crash

Play some album and take a look at the "playing" animation and compare it to the one e.g. the queue or song details.

See images below. If I make a screenshot and crop it to only the playing animation, it has a size of 84x84 px on the queue and the song details, but 96x96 on the albums list. The animation seems to be built for 84x84, so edges look blurred on the albums list.
![](https://user-images.githubusercontent.com/80460567/230714027-68b63d1a-c9d9-40a9-a4a7-bfd4209e2069.png)
| Example of 84x84 px (queue) | ![queue](https://user-images.githubusercontent.com/80460567/230714043-57afe85e-fc8c-45d2-9436-38032050f7fa.png) |
| --- | --- |
 | **Example of 96x96 px with blurred edges (album list)** | ![album](https://user-images.githubusercontent.com/80460567/230714081-d68c215d-7718-4323-9b14-99e43c1772cc.png) |

Sorry for reporting such irrelevant issues, but I notice this really often and I like clean UIs :)

### Describe the intended behavior

Shouldn't look blurred anywhere.

### What android version do you use?

Android 12

### What device model do you use?

Stock Android One

### Bug report

N/A

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I have no idea how this is happening. Vector drawables are supposed to scale without becoming blurry. But I guess anything is possible when you're the Android SDK and don't care about having reasonable behavior.

**Comment by OxygenCobalt** [comment]
I figured out that this was an unexpected consequence of scaling the indicator to 28dp. For some reason, using a matrix to scale that drawable to that specific size simply resulted in it being blurry. I've "fixed" this by scaling the indicator to 32dp instead.
