### ISSUE TITLE
Optional Compilation Library Tab

### ISSUE THREAD

**Issue by kenktk** [OxygenCobalt/Auxio#416]
Request to add tab to show only compilations in the library, similar to the artists or album tab.

I can see how this could be unwanted and or unneeded but somehow filtering out the compilations from the rest of the albums would be a nice add. In the future, I'm sure this could be baked in better with playlist support.

Side note: love this project and what it's becoming!

**Comment by OxygenCobalt** [comment]
I personally think that would be really user-unfriendly. Just adding compilations is inconsistent in the presence of other release types (EPs, Singles), but adding tabs for all release types is a recipe for a very cluttered UI. I personally prefer keeping the unified album tab.
