### ISSUE TITLE
Thin widgets (1x3, 1x4)

### ISSUE THREAD

**Issue by KittyBloo** [OxygenCobalt/Auxio#420]
### Description

I want atleast a (3 to 4)×1 widget. An adaptable widget would be nice too!

### Other implementations

- [Retro Music Player](https://github.com/RetroMusicPlayer/RetroMusicPlayer)  has a bunch different widgets (some are redundant).

- [VLC](https://github.com/videolan/vlc-android)  has a widget that adapts and reforms when resized.

Some music players have widget that can be customized manually when needed.

### Benefit

Controlling music playback becomes easier. And the widget is easier to customize to a user's liking.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I keep considering 1x4 widgets, but there are a ton of edge cases I have to work through. I can take another crack at this.

**Comment by KittyBloo** [comment]
Your consideration is deeply appreciated!

**Comment by KraXen72** [comment]
one day, he will break.
with every new widget request, his willpower weakens. 
soon, the textwidget will see the light of day!

(jk, im currently happy with the existing resizable widget, but new options would be rad)

**Comment by KittyBloo** [comment]
![Screenshot_20230726_143030_Nova7](https://github.com/OxygenCobalt/Auxio/assets/74316613/2a317dad-fd6e-4622-ae4d-8cb9747f9b6c)
Look what I found! I was playing around with this launcher called [Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher) and then I resizes the widget to find that the widget actually does adapt to 1×4! The widget actually looks good in 1×3 as well as seen here: 
![Screenshot_20230726_144520_Nova7](https://github.com/OxygenCobalt/Auxio/assets/74316613/241aeed6-58ea-4524-93c2-efbbe2995a5b)
I think I can to this on Nova Launcher due to it disregarding the widgets pre-set boundaries for resizing. My default Launcher (OneUI 5) obviously does not let me do this.

**Comment by OxygenCobalt** [comment]
This actually isn't a 1x4 widget from my perspective @KittyBloo. That one is built to be an edge-case for landscape devices, and just happens to trigger in your case. A real 1x4 widget would have handle even smaller widget sizes (again due to landscape), hence the issue.

**Comment by kurokawaerne** [comment]
![Uploading Screenshot_20230827-115745_Pixel Launcher.png…]()
![Screenshot_20230513-155921_Pixel Launcher](https://github.com/OxygenCobalt/Auxio/assets/79191836/0171f550-6c37-4dd1-a2ba-ff79e4430a0f)

It randomly works. IDK why but under certain conditions it works. 
- Sometimes I can replicate the conditions and get it working but most of times it doesn't.

**Comment by kurokawaerne** [comment]
![Screenshot_20230513-155921_Pixel Launcher~01](https://github.com/OxygenCobalt/Auxio/assets/79191836/364b1ae8-7269-4042-80ff-f92ccce396bb)
![Screenshot_20230827-115745_Pixel Launcher](https://github.com/OxygenCobalt/Auxio/assets/79191836/9819fc84-5be3-43b1-8e53-19c220024abd)

https://github.com/OxygenCobalt/Auxio/assets/79191836/07182875-cb87-4dd7-bca9-300fc5691094



It randomly works. IDK why but under certain conditions it works.

Sometimes I can replicate the conditions and get it working but most of times it doesn't.

**Comment by OxygenCobalt** [comment]
Those are two different devices @kurokawaerne. They have different screen sizes and grid dimensions, which prevents the """1x4""" widget from being activated since it's targeting very small dimensions.

**Comment by kurokawaerne** [comment]
Actually the same device, different ROM, I updated recently and also same 5×4 grid. But yes, I get your point, it gets triggered under certain conditions but this behavior is not intended for phones and you're trying to fix it. The 1×4 widget is a feature that is still pending to be develop. 

Thanks for your feedback and for developing such an amazing app. I'm always looking forward to get news about this app 👍

**Comment by OxygenCobalt** [comment]
Will plug these *possible* 1x4 widget designs from an older thread:

![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/481af6a4-dea2-4dd1-bfed-9754af213403)
![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/8c9a049f-a334-4b35-ad41-de8842e0c78f)
![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/40e91176-7ec3-485b-b0ce-6a3850b3647b)

I didn't go with these originally since there was basically no good way to properly crop the background cover to rounded corners below Android 12. I think I'll still go with this, but below Android 12 it will degrade to a solid background.

**Comment by OxygenCobalt** [comment]
Just realized some other things I'm going to need to change with 1x4 widgets:
- The default album cover icon. It's currently a partially transparent album icon that is both inconsistent and won't work with the 1x4 widget.
- How the default "No music playing" widget looks, which will probably get truncated at 1x4 scale. I think I'll change it so that the normal playback layout is shown, but with disabled controls and a muted placeholder for the album cover.

**Comment by OxygenCobalt** [comment]
Planning for at minimum 1x3/1x4 to widgets to be in 3.4.0. Anything more is out of scope since making Hx2/Hx1 layouts work is kinda hard.
