### ISSUE TITLE
Allow to open tabs hidden from library via options menu

### ISSUE THREAD

**Issue by qwerty287** [OxygenCobalt/Auxio#421]
### Description

It would be nice to be able to open the tabs that are hidden from the library using something like an option in the menu in the corner (this shouldn't be tabbed the of course, but a completely new view).

### Problem solved

I usually don't need hidden items, but sometimes I'd like to use them, but not that often that I need them in my library.

### Other implementations

I don't think most support hiding tabs

### Benefit

Allows you to open tabs' content also if they're hidden

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
What you're asking is basically the role of the search view. If you want another item from an invisible tab, just search for it.
