### ISSUE TITLE
have albums group song no matter the artists

### ISSUE THREAD

**Issue by aspwil** [OxygenCobalt/Auxio#422]
### Description

when you go to the album tab
if you have songs which all share the same album tag, but have different artist tags,
each artist album combo is shown as a different album, despite them all being part of the same album

### Problem solved

I have an album which has 30 different songs by different artists.

when i open the album tab, i see 30 copies of the album name, one for each different artist.

### Other implementations

they group by album tag exclusively, instead of by artist and album tag.

### Benefit

some album are compilation of songs by different artists.

grouping by album name regardless of artist name will enable these albums to work as intended

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is working as intended. You need to add an Album Artist tag like "Various Artists" for Auxio to properly group the album. Auxio cannot rely solely on the album information, as if two artists have albums with the same name, they would be incorrectly interpreted as a single album.

**Comment by aspwil** [comment]
alright. thank you for the info, i will update the data for my mp3s accordingly
