### ISSUE TITLE
Repeated playback errors after returning to app from recents

### ISSUE THREAD

**Issue by Super12138** [OxygenCobalt/Auxio#431]
### Describe the Bug/Crash

1. Open the app
2. Choose a song
3. Play it
4. Switch the app to the background and return to the home screen
5. Open the app from the multitasking screen
6. See the bug

### Describe the intended behavior

Continue playing the current song and have the ability to pause it

### What android version do you use?

Android 10

### What device model do you use?

HUAWEI P30（EMUI）

### Bug report

It didn't crash, so I can't get the report

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I'll need a video to figure out what is specifically going on here.

**Comment by Super12138** [comment]
This is the video
![video.zip](https://github.com/OxygenCobalt/Auxio/files/11410574/video.zip)

**Comment by OxygenCobalt** [comment]
I can't reproduce anything like this @Super12138. I'm going to guess that Auxio is repeatedly encountering an error when you re-enter the app, likely due to huawei-specific issues. I would ask for some logs, but I don't think Auxio reports playback errors just yet, so I'll get back when I can implement that.

**Comment by Super12138** [comment]
In addition, this bug will appear when you use this app, lock screen, and open it.

**Comment by OxygenCobalt** [comment]
Can you please take a log/[bug report](https://developer.android.com/studio/debug/bug-report) with the following CI build @Super12138?

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11592727/Auxio_Canary.zip)

**Comment by Super12138** [comment]
> Can you please take a log/[bug report](https://developer.android.com/studio/debug/bug-report) with the following CI build @Super12138?
> 
> [Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11592727/Auxio_Canary.zip)

I tried to take a log use bug report, maybe it can help you to find the bug.

![bugreport-ELE-AL00-HUAWEIELE-AL00-2023-05-31-16-56-53.zip](https://github.com/OxygenCobalt/Auxio/files/11612491/bugreport-ELE-AL00-HUAWEIELE-AL00-2023-05-31-16-56-53.zip)

**Comment by Super12138** [comment]
> > Can you please take a log/[bug report](https://developer.android.com/studio/debug/bug-report) with the following CI build @Super12138?
> > 
> > [Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11592727/Auxio_Canary.zip)
> 


I tried to take a log use bug report, maybe it can help you to find the bug.

PS: Because this bug does not cause the application to crash, I used "bug report" to get the log
！[bugreport-ELE-AL00-HUAWEIELE-AL00-2023-05-31-16-56-53.zip](https://github.com/OxygenCobalt/Auxio/files/11612491/bugreport-ELE-AL00-HUAWEIELE-AL00-2023-05-31-16-56-53.zip)

**Comment by OxygenCobalt** [comment]
I cannot find the error logs I was looking for. Are you sure you use the "Auxio_Canary.zip" debug APK that I provided @Super12138? It seems like you just opened the normal app, which is not helpful since it will not report the playback error.

**Comment by Super12138** [comment]
> I cannot find the error logs I was looking for. Are you sure you used the [Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/11592727/Auxio_Canary.zip) debug APK that I provided @Super12138? It seems like you just opened the normal app, which is not helpful since it will not report the playback error.

Ok, I tried it again and got an error report from Bugreport, Leaks and Logcat. You can see each report below.

bugreport
[bugreport-ELE-AL00-HUAWEIELE-AL00-2023-06-01-16-37-33.zip](https://github.com/OxygenCobalt/Auxio/files/11622989/bugreport-ELE-AL00-HUAWEIELE-AL00-2023-06-01-16-37-33.zip)

Leaks
[2023-06-01_16-24-46_973.hprof.zip](https://github.com/OxygenCobalt/Auxio/files/11623002/2023-06-01_16-24-46_973.hprof.zip)

Logcat
[logcat.txt](https://github.com/OxygenCobalt/Auxio/files/11623006/logcat.txt)

**Comment by OxygenCobalt** [comment]
Okay, the app is reporting no playback error at all. This implies something is deeply wrong with the way your phone is handing media playback, and there's nothing I can do about it. I apologize.
