### ISSUE TITLE
Cover art from other albums being displayed

### ISSUE THREAD

**Issue by FreeTheTech101** [OxygenCobalt/Auxio#432]
### Describe the Bug/Crash

While updating my music library on my phone this morning, I noticed that Ed Sheeran's "-" album was not using the correct album art, despite being in the Vorbis tags. Instead, it seems to be using the album art for the next album in the list, "÷".

Auxio:
![Auxio](https://user-images.githubusercontent.com/7614507/236459644-5a72deb6-e235-45e0-88ff-0e12763f6d65.png)

Plexamp:
![Plexamp](https://user-images.githubusercontent.com/7614507/236461833-f4231220-a1d5-4dc8-aa3b-ad6b1ce73a6f.png)

AIMP (Tags):
![image](https://user-images.githubusercontent.com/7614507/236461051-9afc3a42-8d3c-42dd-8aae-97e14003ca84.png)

### Describe the intended behavior

Auxio should correctly handle all album artwork, despite odd characters being in the album name. Comparing Auxio to Plexamp, it seems that it is unable to uniquely identify albums with specific symbols in its name (in this case, "-" and "÷"). Comparing this behaviour to other music players (namely RetroMusicPlayer), it seems that Auxio still handles this case better than most, as other players seem to simply combine the two albums together, instead of just displaying the incorrect album art.

### What android version do you use?

Android 13

### What device model do you use?

Pixel 7 Pro

### Bug report

N/A, can acquire if requested.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio has separate album entries for both of those, so it's able to identify them. Can you try setting the "Album Covers" setting to high-quality? Auxio currently relies on the android media database for covers by default, which can have issues. If that doesn't work, can you provide a sample file? Remove the audio, I just need the tags.

**Comment by FreeTheTech101** [comment]
Switching it to high-quality did solve the issue! If you'd still like some samples, I'd be more than happy to upload them.

**Comment by OxygenCobalt** [comment]
Okay, since I really have no control over this problem (it's android being busted again), I'll close this issue.
