### ISSUE TITLE
Respect system font option

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [OxygenCobalt/Auxio#434]
### Description

A toggle switch that changes the app font to the system font.

### Problem solved

The app uses a font that is inconsistent with my phone.

### Other implementations

They typically don't use a custom font.

### Benefit

With this feature, the app will feel like a normal app on my phone.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is impossible to implement. I either have to pick my font or the system font, and I like my font more.
