### ISSUE TITLE
Setting to queue on top of queue, not last

### ISSUE THREAD

**Issue by Akselmo** [OxygenCobalt/Auxio#436]
### Description

Love the application! However when listening music, I usually just listen my whole library. So when I queue a song, it goes to last in the queue.. Which is around 5000 tracks :sweat_smile: 

I'd like to queue on top of the list, so it's next after the currently playing song.

### Other implementations

Spotify has this, it just queues on top of the queue list than bototm.

### Benefit

People with huge libraries like me can queue the songs they want to play next but can still leave the rest of the queue to whatever there is 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Already exists with the "Play next" option.

**Comment by Akselmo** [comment]
How did I not notice that.. Sorry for taking your time.

**Comment by gummyhulk** [comment]
Sorry to derail an old issue, 

> Already exists with the "Play next" menu option.

but where can I find this? When I turn off shuffle it seems to work, but that only leaves me with a queue of my own songs which then repeat. Is there something like Spotify's top/bottom queue system in Auxio, where users can place their queue at the top and when the last song is played the bottom queue of the other songs are played (shuffled/unshuffled)? See example...
![6303e3d3c2794d00197f119d-3781062870](https://github.com/user-attachments/assets/15b256da-acb7-41ff-b7c4-163a563c734b)

**Comment by OxygenCobalt** [comment]
@gummyhulk You can just click on the 3-dot menu on a song and click "Play next" or "Add to queue".

Auxio did actually use to have a spotify-esque "transient queue", but it made gapless playback impossible since it prevented anything resembling a reasonable timeline. Maybe in some far-flung future I will re-introduce it once I've deconstructed ExoPlayer enough that I can patch in support for the strange semantics of a transient queue.
