### ISSUE TITLE
Incorrect search results

### ISSUE THREAD

**Issue by madenerrgy** [OxygenCobalt/Auxio#437]
### Describe the Bug/Crash

1. Open audio search 
2. Capitalize the title of the track or artist
3. Write the name of the same track or artist with a small letter
4. The search will return different values, which is not a logical result.

### Describe the intended behavior

![Screenshot_20230511-003101_Auxio](https://github.com/OxygenCobalt/Auxio/assets/77206030/5eb9c0cc-e34e-4219-bfbd-983130ed1417)
![Screenshot_20230511-003104_Auxio](https://github.com/OxygenCobalt/Auxio/assets/77206030/4923ad08-308a-4178-92a6-3a38e183b327)

### What android version do you use?

Android 13

### What device model do you use?

Mi 11 Lite 5G NE

### Bug report

No need.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I'm assuming that your music files might be formatted as something like "Halsey - [Title]". In that case, Auxio is matching the file name, but it seems like I'm not doing it case-insensitively. Let me fix that.

**Comment by madenerrgy** [comment]
> I'm assuming that your music files might be formatted as something like "Halsey - [Title]". In that case, Auxio is matching the file name, but it seems like I'm not doing it case-insensitively. Let me fix that.

Hi, thanks a lot for the feedback!

![Screenshot_20230511-075015_Auxio](https://github.com/OxygenCobalt/Auxio/assets/77206030/eecd6477-0b7d-4dee-898e-c8536b1f1de2)

One of these files is named so that the word "Halsey" is not present. 

This is not a critical problem, but if you could fix it, it would be cool, thank you for your efforts!
