### ISSUE TITLE
Some covers are not visible

### ISSUE THREAD

**Issue by StefDeVannes** [OxygenCobalt/Auxio#442]
### Describe the Bug/Crash

Some covers are not shown, whatever it's :
- JPEG or PNG
- 500x500 pix or 1000 x 1000

Is there some specs wich detail the good picture format?
Thanks,

### Describe the intended behavior

.

### What android version do you use?

Android 8 (Oreo)

### What device model do you use?

LG G5

### Bug report

.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio relies on the android media database by default, which is extremely fallible. Can you try going to Settings -> Content and changing "Album Covers" to "High quality"? @StefDeVannes

**Comment by StefDeVannes** [comment]
"High quality" makes no change. I think my phone is too old.
Il will use your app without cover. Thanks, it's simple and beautiful :)
