### ISSUE TITLE
Playlist resorting

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#446]
Split from #36.

**Comment by madenerrgy** [comment]
@OxygenCobalt that's normal?

Maybe make a pop-up window where it will say "These tracks are already in this playlist" ?


https://github.com/OxygenCobalt/Auxio/assets/77206030/af32bb8f-ac9c-457d-8394-a56d6e5739a4

**Comment by OxygenCobalt** [comment]
The issue is that I don't know how to indicate tracks partially being present in a playlist @madenerrgy. Do you have any ideas?

**Comment by OxygenCobalt** [comment]
Oh no, it's trivial to do what you're asking. I think I can indicate whether "part of the selection is in the playlist" or if "all of the selection is in the playlist" in a hypothetical dialog @madenerrgy.

**Comment by madenerrgy** [comment]
> Oh no, it's trivial to do what you're asking. I think I can indicate whether "part of the selection is in the playlist" or if "all of the selection is in the playlist" in a hypothetical dialog @madenerrgy.

Yes, you can do that, but I don't know how to implement it correctly :(

**Comment by OxygenCobalt** [comment]
You don't need to worry about it, I'll be able to work on it myself @madenerrgy.

**Comment by madenerrgy** [comment]
> You don't need to worry about it, I'll be able to work on it myself @madenerrgy.

Thanks, pro!
Your work really makes us happy ;)

**Comment by madenerrgy** [comment]
> You don't need to worry about it, I'll be able to work on it myself @madenerrgy.

 Hi Alexander!
One more question, look, if you add a track to the playlist and go to the add menu again, then we see a “tick” that it has already been added, but if you click on this checkmark again, it is not deleted, but instead added.

I think this is a bit illogical behavior, I hope you understand what I'm talking about :)

![Screenshot_20230531-070811_Auxio](https://github.com/OxygenCobalt/Auxio/assets/77206030/311b13a3-1891-4085-a301-5453aa209287)

**Comment by OxygenCobalt** [comment]
That behavior makes no sense @madenerrgy, in my opinion. It's not a selection, and having a dialog called "add to playlist" *remove* a track is extremely unfriendly

**Comment by illdeletethis** [comment]
how do i remove a track from a playlist or the queue?

**Comment by OxygenCobalt** [comment]
You can swipe an item to the left to remove it @illdeletethis. I am considering indicating this behavior later with #479.
