### ISSUE TITLE
Playlist import/export

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#447]
Split from #36.

**Comment by KraXen72** [comment]
from #36:
- ability to import m3u playlist
- ability to export playlist as m3u (ideally with relative paths to the nearest shared parent folder, not absolutely to the sd card/internal storage)
- remembering of m3u file which was imported & button to overwrite playlist contents with m3u contents (refresh)
- (maybe) SQL/query dynamic playlists

**Comment by nzure** [comment]
Would it be possible to import playlists from Listenbrainz? The format is documented [here](https://musicbrainz.org/doc/jspf), I think it would integrate nicely with the already existing MBID’s

**Comment by Mikaciu** [comment]
Would it be possible to be able to select the directory where the playlists are stored ?

**Comment by OxygenCobalt** [comment]
Playlists are stored in a database normally, but you will be able to export to any directory allowed by the file picker @Mikaciu.

**Comment by OxygenCobalt** [comment]
Update: Writing a M3U parser is stupid simple, so the backend of this can be easily done. I'm just stuck on the frontend, since I actually want to use menu/"speed dial" functionality for this. See the example(s) below:

![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/d05fadc0-4986-4d86-b363-641a629e4341)

https://github.com/OxygenCobalt/Auxio/assets/65370175/a8626c91-b684-4381-8217-d2c3556c8a6f

This requires some custom view magic that will take a little bit, so I'm aiming for 3.3.0 for this.

**Comment by KraXen72** [comment]
1) yes, m3u is a simple format (make sure to also take into account relative links)
2) looks good!

**Comment by OxygenCobalt** [comment]
There shouldn't be an issue @Wjxfi, but it might take a little while.

**Comment by OxygenCobalt** [comment]
Please be patient @Wjxfi. I am extremely busy with school and will not be able to do significant work on Auxio for the next few months.

**Comment by OxygenCobalt** [comment]
![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/93d7d8e2-374d-41c9-914b-91abc1a66adf)

;)

**Comment by OxygenCobalt** [comment]
[Screen_recording_20231220_132215.webm](https://github.com/OxygenCobalt/Auxio/assets/65370175/547576c9-4950-46e3-9d91-443c79e34f56)

**Comment by OxygenCobalt** [comment]
NVM, absolute paths will be supported too, but under the assumption that they are relative to the volume of the M3U file. 

Another additional assumption is the usage of unix-style "../dir/./file" type paths. If any of you use windows-style "C:\\" paths, please let me know.

**Comment by chocmake** [comment]
> Another additional assumption is the usage of unix-style "../dir/./file" type paths. If any of you use windows-style "C:\" paths, please let me know.

foobar2000 exports such paths for its playlist M3U/M3U8 exports. I recall even old Blackberry's stock music player handling them fine, so they're presumably common enough.

**Comment by OxygenCobalt** [comment]
[1] How it handled the paths was assuming the drive letter was the root of the exposed file system (so eg: M:\music was understood to be the music dir in the root of the directory tree as seen when file transfer is enabled).

Alright, this sounds like what I can use for Auxio. I'm basically forced to assume the playlist volume is the same as the file volume.

**Comment by evanc577** [comment]
Will imported playlists automatically update when the m3u file is changed? If not automatically, an option to rescan and reimport all playlists would be good too.

**Comment by OxygenCobalt** [comment]
Sorry for the delay @evanc577. That's not planned for the MVP since it effectively requires #322 for the best results. Currently there's going to be an "Import" menu option that allows you to reimport a m3u file back into the playlist.

This feature is also basically done. There's some rough edges I need to resolve first regarding when names conflict, but otherwise it should arrive in the next release.

**Comment by OxygenCobalt** [comment]
Some of the other functionality mentioned here will be spun off into issues once I fully decide on doing them.
