### ISSUE TITLE
Reduce leading instrument

### ISSUE THREAD

**Issue by NSTAdventure** [OxygenCobalt/Auxio#45]
#### Describe the feature you want to implement:
If you don't mind can you add feature to reduce leading intrument? 🙏😊

#### Is your feature request related to a problem? Please describe:
1. Backtrackit are closed source app that have this feature I don't want pay I don't want use closed source app due to privacy concern
And yes this feature inspired by this closed source apps

#### Why do you think this will improve everyone's usage of Auxio?
Because you can easily make instrumental version only of music and yes with this FOSS apps 🙏😊
(Uh actually this feature used for removing vocal)

#### Due Diligence:

- [ ✓] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Removing vocals seems to be a pretty complex task that is not within the bounds of Auxio's purpose as a music player. If you want to process music to remove vocals, I think audio editing software like [audacity/tenacity](https://github.com/tenacityteam/tenacity) would be a better fit here. Sorry.

**Comment by NSTAdventure** [comment]
this is why i hate to give feedback not all my feedback will accepted or appreciated :)

But is okay as a user i respect everyone decision thanks for build this great apps for foss Android user :) 😊🙏

No one guilty here

Anyway is ok if i or someone else make fork of auxio with additional feature?
@OxygenCobalt
