### ISSUE TITLE
Custom Album Art

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#452]
### Description

Add the ability to attribute a custom image to an audio file (whether or not the audio file already has one)

### Other implementations

/

### Benefit

Some files, such as ones downloaded / recorded on the phone / etc., will now be able to have artwork displayed with them rather than just the placeholder logo image. This is useful functionally **and** aesthetically. 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by RustoMCSpit** [comment]
[Per-song album covers#342](https://github.com/OxygenCobalt/Auxio/issues/342)
Is this not more in line with this already approved eventual addition. It isn't really tag editing?

**Comment by RustoMCSpit** [comment]
https://github.com/OxygenCobalt/Auxio/issues/342
Is this not more in line with this already approved eventual addition. What I've proposed isn't really tag editing?

**Comment by OxygenCobalt** [comment]
#342 is a change in *interpretation* of album art, not the ability to assign it @RustoMCSpit.

**Comment by RustoMCSpit** [comment]
Well I mean, interpreting the art tags to be a different image is virtually the same thing assuming the interpreted image isn't embedded in the album somehow (or am I missing something, literally just got Github so I'm not that good at this analysis stuff). Anyways appreciate your work @OxygenCobalt

**Comment by OxygenCobalt** [comment]
No, because your idea requires me to keep track of the album cover information that must be overridden, which is extremely complex and bug-prone for something I gain no use from. Alternatively, I overwrite the album cover tag information in the file, which is tag editing. #342 does not change anything about the file or the app state, hence why it is okay.

**Comment by RustoMCSpit** [comment]
Why does #342 not change anything about the file or the app state? Are the images somehow already embedded in the file or?

**Comment by OxygenCobalt** [comment]
Yes, it's common for album covers to already be embedded in audio files. Auxio just reads them.

**Comment by RustoMCSpit** [comment]
Ahhh, now I understand. So my idea is getting third party images but there's are already there and that's what makes mine so complex. If I were to provide the code for it and PR it would it get implemented?

**Comment by OxygenCobalt** [comment]
Oh, so you mean something like #264 or similar. I've rejected that in the past since I've made a promise to make Auxio have no internet access whatsoever.

**Comment by RustoMCSpit** [comment]
No. no I mean like camera roll or other file images locally stored on the phone. Let's say someone were to have a song file downloaded as an mp3 from the internet but wanted to put an album cover on it, they'd select an image from their cam roll and it would replace the placeholder image for that song. Am I making sense? What also could be done as a far less intensive compromise is having the placeholder available in different colors which the user could pick a hex value for, it would help when scrolling through songs distinguish them but it also looks far less bland.

**Comment by OxygenCobalt** [comment]
I still disagree. You can do the same by downloading a tag editor (like automatag mentioned prior), opening your file, picking an album cover from there, then saving the changes. You can then to go Settings -> Refresh Music in Auxio, and it will read and show the new album cover. I'd rather outsource something like this to another app instead of continually increasing Auxio's complexity.
