### ISSUE TITLE
Can't play *.m4a audio files

### ISSUE THREAD

**Issue by lgjint** [OxygenCobalt/Auxio#462]
### Describe the Bug/Crash

First of all, It is a very nice music player and thank you for your hard work.

I checked the github issues and found that this issue has been resolved in 3.0.4 #388 

But recently i used the phone recording in AOSP, saved the recorded audio as *.m4a file (AAC encoding), opened it with Auxio in File Manager, nothing happened.

I also tried adding *.m4a audio files by including the folder in Auxio settings, but none of the *.m4a files were added to Auxio.

I really appreciate it if you can fix this problem.

### Describe the intended behavior

Should play the *.m4a audio files normally.

### What android version do you use?

Android 13

### What device model do you use?

Redmi K40S (Arrow OS)

### Bug report

-

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I'm assuming this you're trying to play a voice recording. Auxio is a music player by default, so you will need to disable Settings -> Content -> Exclude non-music for the app to recognize it. #388 is unrelated and tied to playback of certain MP4 files.

**Comment by lgjint** [comment]
> I'm assuming this you're trying to play a voice recording. Auxio is a music player by default, so you will need to disable Settings -> Content -> Exclude non-music for the app to recognize your recordings. #388 is unrelated and tied to _playback_ of certain MP4 files. This is largely working as intended. Hope this helps.

Thanks, it helps!
