### ISSUE TITLE
Setting preferred tab in the main view.

### ISSUE THREAD

**Issue by Breakster** [OxygenCobalt/Auxio#463]
### Description

I want to be able to change which tab is first active when the app is opened.

### Problem solved

Currently the app opens on the "Songs" tab which I never use. So my first action when opening is always to select another tab, most often "Artists".

### Other implementations

This is not an audio player specific feature as tabs are used in many apps.
Some options I have seen being used:
- Have a preference menu which allows to select the default tab
- Have a preference menu which allows to reorder tabs
- Have a preference menu which allows to reorder tabs and set visibility of tabs.

### Benefit

This feature allows users to have the relevant music shown to them faster, based on their preferences.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by illdeletethis** [comment]
there already is a menu to reorder tabs
top one opens when you start the app from having been fully closed, last active one opens if the app was a background task.
![Screenshot_20230602-121813_Auxio](https://github.com/OxygenCobalt/Auxio/assets/62331598/6d56b127-dbbb-4eeb-921e-d8742f1e60ca)
