### ISSUE TITLE
Playlist & queue item order isn't saved correctly when moving an item upwards

### ISSUE THREAD

**Issue by min7-i** [OxygenCobalt/Auxio#466]
### Describe the Bug/Crash

When adding a new song to an existing playlist I often want to move it to the beginning of the playlist. If the playlist has enough items that you need to scroll and if the item is moved beyond a certain point, the new item position (e.g. position 1) is not saved correctly.

(Tested with the current release version and the debug build v3.1.1 from https://github.com/OxygenCobalt/Auxio/actions/runs/5160555133)

Here is a screen recording showing an example:

https://github.com/OxygenCobalt/Auxio/assets/97251923/079a25c8-d8ea-488f-b75a-66e1077ddb85

This can also happen when moving an item up in the queue:

https://github.com/OxygenCobalt/Auxio/assets/97251923/60ec2bab-1519-45cf-851a-d45a3db3de4d

### Describe the intended behavior

When moving an item up in the playlist or queue it should not disappear and the intended position in the preview should be saved correctly.

### What android version do you use?

Android 13

### What device model do you use?

Google Pixel 6a

### Bug report

I don't have a bug report.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I think this is largely unfixable. The item drag system can scroll, or move items, but not both at the same time. If this wasn't the case, the RecyclerView would attempt to scroll after an item move and result in even worse visual bugs.

**Comment by min7-i** [comment]
Thanks for the explanation. I'm not an Android developer so I don't know what's possible with the different UI components.

From what I noticed, this issue only occurs
- in playlists when moving the finger dragging the item onto the notification bar. As long as I stay within the app itself, moving and scrolling works as expected. (see orange border on screenshot below)
- in the queue when moving the finger beyond the queue border onto the player bar at the top. (see orange border on screenshot below)

<details>
<summary>screenshots</summary>

| playlist | queue |
| ------------- | ------------- |
| ![playlist](https://github.com/OxygenCobalt/Auxio/assets/97251923/7423de1b-9621-4547-ad77-ae7304aa3073) | ![queue](https://github.com/OxygenCobalt/Auxio/assets/97251923/470a9a3a-ad2b-4eaa-84ca-59b6c4324600) |

</details>

Would it be feasible to stop scrolling when crossing the mentioned borders in the playlist/queue and only continue scrolling when the finger moves below the border again?

**Comment by OxygenCobalt** [comment]
I don't really want to do that, as it requires me to track layout information in code that doesn't have access to such normally. It would probably lead to worse visual issues.

**Comment by min7-i** [comment]
I see. Thanks.

As long as one is a little careful when moving an item up a long list, the issue shouldn't occur. So that's fine for me.
