### ISSUE TITLE
Migration support

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#467]
Add support for migrating playlists and settings between devices. Should be a simple configuration change.

**Comment by ildar** [comment]
a general backup could be a solution here

**Comment by OxygenCobalt** [comment]
Sure, I could add my own custom backup .zip file, but that's much more difficult than just telling android what to do.

**Comment by OxygenCobalt** [comment]
Looks like playlist databases are actually already backed up and migrated between devices by default. This is basically already done. I will exclude the music cache though, as it is at best useless and at worse would cause massive state issues.
