### ISSUE TITLE
Queue to Playlist

### ISSUE THREAD

**Issue by illdeletethis** [OxygenCobalt/Auxio#468]
### Description

I would like a button in the top bar of the queue for saving a queue order to a playlist, potentially in the red marked spot.
Making it a menu with another option to clear the queue could be useful too.
![image4](https://github.com/OxygenCobalt/Auxio/assets/62331598/712a7450-9e05-4d09-9547-bd4563edd83c)

### Other implementations

not sure

### Benefit

The other direction, loading playlists into the queue already works.
Also sometimes the random order the app generates comes up with unexpectedly good song orders.
And the Queue is easy to reorder.
All this combined would make it a great tool for starting the creation of a playlist.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is actually already tracked by #407. Alongside the ability to use multiple states will also be the ability to save a state to a playlist.

**Comment by illdeletethis** [comment]
sorry, didn"t realize
thank you very much for your work on this
