### ISSUE TITLE
Intelligent Shuffle Option

### ISSUE THREAD

**Issue by etyarews** [OxygenCobalt/Auxio#470]
### Description

I want, in some ways, a less randomized shuffle. This sounds weird, and to be fair, it is, but the intention is to prevent random mood swings. This would be dependent on proper tagging, tho.

The idea is basically:

1. Select a random song as the "current" one.
2. Take the BPM of the "current" song and filter songs that fall into a 5% range of it.
3. If there's no song that fall into that range, increase it until it finds one, or it reaches 100% range.
4. If no song is found at 100% range, ignore BPM.
5. Out of those songs, randomly select one that shares a genre tag with the "current" song.
6. Ignore songs that have already being played once in this shuffle
7. First use BPM, then Genre, fallback into true randomness if Auxio find anything.

### Problem solved

My music collection is increasing, and I like to think of myself as eclectic, there is *definitely* some songs that don't go together

### Other implementations

As far as I know no other music player does this, but then again, I didn't really use a good deal of music players in my life

### Benefit

This should help alleviate random mood swings and allow bigger song libraries to feel cohesive. Furthermore, since this is all using tags you could add a dialog to select which tags to take into consideration and which one is used first.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Interesting concept, but I don't like the BPM-dependent calculation. I have a high bar for adding tag information as it's all still in-memory. I fear one day if I keep adding more tags that I'll eventually OOM with large libraries. I could see another variant that clusters by genre instead. I could also bring in [Spotify's Old Shuffle Algorithm](https://engineering.atspotify.com/2014/02/how-to-shuffle-songs/) that I like the concept of (It's not algorithmic, just modified fisher-yates shuffle). Give me more time to consider.

**Comment by etyarews** [comment]
Hmm, I thought simply reading the BPM tag wouldn't add more overhead as I imagined it would be the same as reading the track title, or even less as BPM uses less characters.

Reason I like BPM is that it is close enough to "perceived" mood, genre alone can sometimes end with a significant slow song after a fast one, specially when the music collection isn't tagged with an absurd amount of genres per song. Which is my case, btw.

I also do have another concept I mind that I feel you wouldn't be interested in because it doesn't fit with Auxio current behavior, but to get it out of the way: 

1. Everytime the user skips a song, that song gets a 0.1 score
2. Everytime a user lands on a song after skipping multiples, that song gets a score increase of 0.1

Those scores are used to represent the likelihood of a Song playing on a shuffled playlist again. As I said, I don't think this would work with Auxio because Auxio doesn't have infinite shuffle

**Comment by OxygenCobalt** [comment]
> Hmm, I thought simply reading the BPM tag wouldn't add more overhead as I imagined it would be the same as reading the track title, or even less as BPM uses less characters.

It's not the parsing overhead, it's the memory overhead. It's not large for BPM, but it might be the straw that breaks the camel's back in the future with X more tags added.

> I also do have another concept I mind that I feel you wouldn't be interested in because it doesn't fit with Auxio current behavior, but to get it out of the way:

Yeah, that requires me to track song information (play counts specifically), which is largely out-of-scope.

> Reason I like BPM is that it is close enough to "perceived" mood, genre alone can sometimes end with a significant slow song after a fast one, specially when the music collection isn't tagged with an absurd amount of genres per song. Which is my case, btw.

That's a good point, honestly.

Additionally, I could also factor in the "mood" tags with this, but that's not as common as BPM.

**Comment by etyarews** [comment]
Yeah, actually, scratch the ideal about BPM. I tried tagging my library with BPM (using a plugin for MusicBrainz Picard) and the results are FAR from satisfactory. Certain upbeat and fast songs received lower BPM than the actual slow songs I have, so the BPM not only is inaccurate, it is also unreliable.

**Comment by OxygenCobalt** [comment]
Yeah, outside of a very basic mutation of fisher-yates I think there isn't much I can do here. Any kind of smarter shuffle requires either accurate BPM metrics or a semantic mood graph that a local music player simply cannot generate. I'm rejecting this for now.

**Comment by etyarews** [comment]
I do wish *any* sort of improvement to the shuffle could be made.

My library is now about 900 songs, I know this is a me problem, but it is sorta of frustrating that the more music you like, the more of a mess it is to listen to it. And while I haven't seen a music player that tackles it (let's be honest, this is an invisible feature, even if a music player has it, it wouldn't be advertised), I don't think the problem is unsolvable.

Like, you can't use BPM, and you don't want to track the Play count, right?

What is left? The genres, some tracks have multiple genres, so you can make sure that the next track has a 50% chance of sharing one genre with the current one (to prevent situations where one music is always used after another)

You also have access to the Album and the Artist. Make it impossible for the next track to have the same artist and album. And less likely to be on the same album but different artist.

Use the Spotify thing to spread artists and albums across the playlist.

Make albums/artists with single songs more likely to appear, or something.

**Comment by illdeletethis** [comment]
![Screenshot_20230611-210319_Auxio](https://github.com/OxygenCobalt/Auxio/assets/62331598/3ad04dc2-ede2-48f7-8b86-5bb48068764c)
how do you manage to have a mess with just 900 songs?

**Comment by etyarews** [comment]
It depends on what you expect when you want to hear music.

Out of my music collection I usually listen to ~1 hour ish of music. The issue with a randomized shuffle is that 1 hour of music isn't consistently what I expect. Due to randomness, some artists get multiple songs in that 1 hour segment, while certain albums/artists are never played.

And that is not not mention the actual issue of this thread where I hit shuffle and the first song is [Dawn of Victory](https://youtu.be/aHolTqDXipc) followed by [Space Oddity](https://youtu.be/436qgf4bDzo)

**Comment by etyarews** [comment]
![Screenshot_20230611-181622_Auxio](https://github.com/OxygenCobalt/Auxio/assets/113912802/7498ab33-bc47-4641-9c07-6de67cf57bba)
