### ISSUE TITLE
App isnt responding warning (but it is).

### ISSUE THREAD

**Issue by Samueru-sama** [OxygenCobalt/Auxio#471]
I use Auxio from the F-droid store on lineageOS 20 on a xiaomi redmi 9, ever since the latest update came out 10 days ago I sometimes get the warning telling me that the app isn't responding with the options of either wait or close the app. This usually happens when loading the music library, it gets stuck near the end for 10-20 seconds and then it completes, but the warning begings to show up fron there on.

The odd part is that the app is working perfectly after loading, but I still get those warnings every 10 seconds or so. I had to downgrade the version and the issue was fixed.

I also tested upgrading again and the issue shows up again.

**Comment by OxygenCobalt** [comment]
Have you tried 3.1.1? It fixed massive freezing issues stemming from the music equality system @Samueru-sama.

**Comment by Samueru-sama** [comment]
> Have you tried 3.1.1? It fixed massive freezing issues in #457 and #461 @Samueru-sama. It's not on f-droid yet.

I've just tested Version 3.1.1 which hit F-droid today and the issue is gone!, thank you!
