### ISSUE TITLE
Playlist stays selected after deleting it

### ISSUE THREAD

**Issue by min7-i** [OxygenCobalt/Auxio#476]
### Describe the Bug/Crash

1. Select an album.
2. Go to the playlist tab.
3. Select a playlist. (2 items selected)
4. Delete the playlist.

The deleted playlist stays selected. Creating a new playlist from the selection still includes the songs from the deleted playlist.

### Describe the intended behavior

Either remove the deleted playlist from the selection or disable the delete option for playlists when a selection is active.

### What android version do you use?

Android 13

### What device model do you use?

Google Pixel 6a

### Bug report

N/A

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Seems like this issue stems from me not updating the selection whenever playlists changed. This should be a simple fix.
