### ISSUE TITLE
Pinning items to top

### ISSUE THREAD

**Issue by niloofar-torab** [OxygenCobalt/Auxio#477]
### Description

This feature request is to have an option in 3dot menu of albums, artists, playlists, genres  to pin them to top. (Pin Up to 5 items)
These albums, artists, etc would become independent from sorting and always stay on top of the rest of the category.
🔹Example: in main screen, under albums tab, you could pin 5 albums to always be above others.

### Problem solved

Auxio currently arranges albums, genres, artists, etc. vertically and while this is great, scrolling to the place of items that are played very often, gets frustrating.

### Other implementations

Some  music players got close to solving this in other ways; such as making a Home screen which per se is usually devided into multiple parts. (Such as most played, liked songs, top artists and top albums by calculating how long played...).

But EVEN with all that, access to what user exactly wants WON'T BE as efficient as simply pinning items to top.

### Benefit

This would allow an immediate access to pinned items in each tab.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is not really in scope, honestly. If you don't want to scroll much you can use the search functionality instead. Sorry.
