### ISSUE TITLE
Allow old album cover cropping behavior as a setting

### ISSUE THREAD

**Issue by missyraja** [OxygenCobalt/Auxio#482]
### Description

Could we have a toggle to decide if our album art needs to cropped or not? As a lot of album art looks inconsistent now in my playlist.

And is the skip forward or backward 10s(changeable) by double clicking left or right side of the album art in your road map?

### Problem solved

Just add a toggle in look and feel section of the settings.

### Other implementations

Skip functionality is available on YouTube music

### Benefit

This helps in having a consistent album art and the skip functionality makes it quick to move across a song without the small seekbar

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by missyraja** [comment]
Thanks

**Comment by OxygenCobalt** [comment]
Done in 903a3e5.
