### ISSUE TITLE
Updating to 3.1.2 changes order of many songs 

### ISSUE THREAD

**Issue by niporasomo** [OxygenCobalt/Auxio#485]
### Describe the Bug/Crash

I noticed that when I updated to the latest version that it significantly changed the order of my songs, which are sorted by artist and ascending. 

The steps were:

1. Update app to latest version 3.1.2
2. Open app
3. Wait for music to reload
4. Scroll through list of songs to see many of the them are no longer in the previous/correct order. In other words, many songs are no longer ordered correctly by artist, and therefore out of alphabetical order.

I took screenshots of some examples here, but there are others too I could include if it helps. 

It moved up ones by Simon and Garfunkel from the artists starting with 'S' up to where they are under The Beatles, and also put songs by Lana Del Rey under those. It also moved ones from John Powell under these, even though other ones by John Powell remained where they were after the update.

![Screenshot 1](https://github.com/OxygenCobalt/Auxio/assets/123551471/7988aee5-e3fb-4cca-b55b-ff4b891b26b7)

![Screenshot 2](https://github.com/OxygenCobalt/Auxio/assets/123551471/0573e387-e679-4e6d-8ad2-84b5674765cc)

### Describe the intended behavior

The app should maintain the correct order of the songs I have, since I haven't made any changes to the tags of the songs that are out of order. Reverting back to the previous version of Auxio, 3.1.1, fixed the problem.

I noticed that 'artistssort, albumartistssort, and album_artists tags are now recognized' was part of 3.1.2, so that might have changed something.

### What android version do you use?

Android 13

### What device model do you use?

Pixel 6a (CalyxOS)

### Bug report

For the bug report I wasn't necessarily sure how to do it, but can see if I can figure it out if its needed. Presumably I would need to capture a report right after I update and open the app?

I'm not sure if there's other information you would need, but I figured I would report something since other people might have the same issue. Please let me know!

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is 100% derived from your sort tags. They could be broken absolutely, in which I'd recommend using a tagger like [beets](https://github.com/beetbox/beets). Alternatively, this is the result of sort tags formatted as "[last name], [first name]", which is commonly provided by the MusicBrainz database.

**Comment by niporasomo** [comment]
The John Powell ones for example were directly from when I purchased them from iTunes and then copied over. I never touched the tags though - would there be something wrong with their tagging system that caused it to be reordered? That's the case with many of the songs I have in my collection. If not then I can just use one of the tools you recommended here.

**Comment by niporasomo** [comment]
Sure, I have the program downloaded and added the songs - is this screenshot what you're looking for?

![Bourne Ultimatum Screenshot](https://github.com/OxygenCobalt/Auxio/assets/123551471/47026457-1955-4b0e-9aa1-c793ad76214e)

**Comment by OxygenCobalt** [comment]
Is that all the tags, or just some of them @niporasomo? I can't see if there's any sort tags.

**Comment by niporasomo** [comment]
@OxygenCobalt is that located under a different section? When I select a song that's the view I have. There's a little more at the bottom:

![Bourne Ultimatum Screenshot 2](https://github.com/OxygenCobalt/Auxio/assets/123551471/711f972c-391d-45d4-afec-d1a131798d99)

**Comment by OxygenCobalt** [comment]
So, there's nothing that says "sort artist"? That's weird.

Try another thing @niporasomo: Go into auxio, select the 3-dot menu of one of the songs, and press "View properties". Report what you see in the "artists" text box. This should also contain the sort name used by Auxio.

**Comment by niporasomo** [comment]
@OxygenCobalt sure, when I check the properties it says John Powell for artists.

**Comment by niporasomo** [comment]
@OxygenCobalt 

For Lana Del Rey there's the album name with the artist name in parentheses in the album section under properties: Born to Die (Lana Del Rey), and the reverse under Artists: Lana Del Rey (Born to Die)

For Simon and Garfunkel under artists it shows: Simon & Garfunkel (Best of Simon & Garfunkel)

I also installed the Auxio Debug apk, and the songs there are closer to the original order, although the same John Powell for example was moved, but this time to a different spot. It pushed it down to just below the artists that start with 'P'. Strange things happening with these tags it seems haha.

**Comment by OxygenCobalt** [comment]
My suspicion has been confirmed, it's really is a weird sort name @niporasomo. A correctly-tagged file should have something like "Lana Del Ray (Del Ray, Lana)" or "Lana Del Ray (Lana Del Ray)". I'd highly recommend fixing your tags then.

**Comment by niporasomo** [comment]
Ah okay, so when I look under properties for the songs in Auxio it should have that extra part in parentheses. Interestingly enough some of the songs that are correctly ordered don't have it, but could be a fluke or something. I'm definitely going to use one of those tools and go through at least the ones that are out of order.

Thanks again for your time and help!

**Comment by OxygenCobalt** [comment]
If they don't have it, that means that they don't have sort tags. This is also okay, as Auxio will just default to the plain name @niporasomo. You're welcome!

**Comment by niporasomo** [comment]
Oh actually one quick question, what tag or part in those tools would I need to edit to ensure that artist name is in parentheses?

**Comment by OxygenCobalt** [comment]
"Artist Sort" and "Album Artist Sort" are your best bet if you're manually tagging. Otherwise, something like beets or picard will manage it for you @niporasomo.

**Comment by niporasomo** [comment]
Perfect, thanks!
