### ISSUE TITLE
Cannot navigate to settings/about after navigating to elsewhere

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#492]
Already aware of this issue. It's some confusion brought on by the janky, busted navigation setup I currently have. It might be dependency-specific, but it also seems brought on by building the app from scratch for some...reason. Will fix this by giving up and collapsing the two nav graphs into one. Tired of dealing with this.

This can be resolved by swiping the app out of recents and opening it again, or not using the back button/gesture when exiting the settings menu.

**Comment by madenerrgy** [comment]
Oh, I'm just wanted to report this issue :)
Hope you can fix it, good luck!

**Comment by OxygenCobalt** [comment]
This should be fixed now due to the massive navigation rework I've been doing for 3.2.0.

**Comment by OxygenCobalt** [comment]
The things I have to do in android dev...

![Screenshot_2023-07-04_20-46-31](https://github.com/OxygenCobalt/Auxio/assets/65370175/9ea3aca3-454d-4038-b88f-cbef55abe82b)

**Comment by OxygenCobalt** [comment]
Scratch that, just made a 3.1.4 patch that addresses this since it's actually much more critical than I thought.
