### ISSUE TITLE
Support for compilation albums 

### ISSUE THREAD

**Issue by rickdtc** [OxygenCobalt/Auxio#493]
### Description

There are compilation albums where different artists have tracks under same album. Like -
![Screenshot_20230628_124309_Auxio](https://github.com/OxygenCobalt/Auxio/assets/74096544/e83a4d4d-9d34-40f6-bf7f-81e62b3484cf)
Would be appreciated if the songs were under on album and would be not shown as different albums.

### Other implementations

I used to use retro, it just put everything under one album name under one album even if having different artists on different songs.

### Benefit

This feature just would bring a continuous album listening experience.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by illdeletethis** [comment]
do you use album artist tags?
if not, this is why you should. Auxio will group albums with the same name and album artist as the same album, but albums from different artists that happen to have the same name stay separate.

**Comment by rickdtc** [comment]
I will try to edit the metatadata, but it would still be cool to have an option to group all songs with same album name.



Or maybe a different implementation, we would able to select the album names and only the songs with those album names would get affected.

**Comment by OxygenCobalt** [comment]
I'd recommend using album artist tags. I don't like adding settings to change the way Auxio interprets music unless there really isn't a "correct" way to interpret it. Album artists have been standard since the late 90s, and have become trivial to tag with automated tools like [Picard](https://picard.musicbrainz.org) or [Beets](https://github.com/beetbox/beets).
