### ISSUE TITLE
App crashing on viewing list of songs

### ISSUE THREAD

**Issue by GithbUser** [OxygenCobalt/Auxio#5]
Describe the bug/crash:
App failed to load Songs list

Steps To Reproduce the bug/crash:
1. Open Auxio app
2. Click on Songs icon 
3. See error

Logs/Stack Traces:
[2021-02-20-09-23-06.txt](https://github.com/OxygenCobalt/Auxio/files/6014090/2021-02-20-09-23-06.txt)

Screenshots:
https://user-images.githubusercontent.com/75420364/108583359-cdc53080-72ed-11eb-9120-286c58949c8f.mp4

Phone Information:
[device_info.txt](https://github.com/OxygenCobalt/Auxio/files/6014092/device_info.txt)

**Comment by OxygenCobalt** [comment]
Seems like its a metadata issue with albums. I assumed that songs would always have an album attached to them and I think that is what's causing the crash. Ill try to resolve it when I get the time.

**Comment by OxygenCobalt** [comment]
I may have fixed the issue, actually. Can you test this debug APK on your device? [Rename it to `.apk` instead of `.zip`]
[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/6016786/app-debug.zip)

**Comment by GithbUser** [comment]
I tested the debug build,now its working fine
Thank you

**Comment by OxygenCobalt** [comment]
Got it. Ill close this issue, the fix should arrive in 1.3.1. Thanks for letting me know about this.
