### ISSUE TITLE
The search does not display correct data about the amount of music

### ISSUE THREAD

**Issue by madenerrgy** [OxygenCobalt/Auxio#502]
### Describe the Bug/Crash

![Screenshot_20230708-012923_Auxio](https://github.com/OxygenCobalt/Auxio/assets/77206030/4f64efaf-c9ee-4500-ae83-b029a794f3a1)

If you enter the artist's name in Russian, not all tracks will be shown. The screenshot should have shown 9 tracks, but in fact only 2 of them are displayed.
I checked the metadata - there are no problems in it. I checked on another player - everything is fine too.
I hope, dear Alexander, u will be able to check what the bug is, and if u have any questions about this bug, I will be happy to try to answer them.

### Describe the intended behavior

Higher.

### What android version do you use?

Android 13

### What device model do you use?

Mi 11 LE

### Bug report

No need

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [x] I have checked this issue for duplicates.
- [x] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is somewhat intentional @madenerrgy. Auxio only matches song names when searching. However, the way it's matching song names is definitely bugged.

I need to know if you are using any sort tag information. This can be done by going to `View properties -> Artists` and seeing if there are any names in parentheses, as that's how Auxio displays sort names if present. It could be possible that your tag information is a bit mangled in that regard, resulting in the songs being matched. Otherwise, it's some other oversight in the search process that I can likely reproduce myself.

**Comment by madenerrgy** [comment]
> I need to know if you are using any sort tag information.

Huh... You're right 👍

![Screenshot_20230709-074131_Auxio](https://github.com/OxygenCobalt/Auxio/assets/77206030/df6b7b52-e8ac-4afb-8ecd-2d7a9fe85b2d)
![Screenshot_20230709-074151_Auxio](https://github.com/OxygenCobalt/Auxio/assets/77206030/f25edca8-bb52-4686-925b-65b4b1860195)

The search showed 3 tracks, although when you click on the "artist" button, there are 10 of them.

![Screenshot_20230709-074317_Auxio](https://github.com/OxygenCobalt/Auxio/assets/77206030/b8dc884e-930e-4886-b1b8-6e155b3d7e7c)

However, in these 3 tracks the file name was in Russian, and in the remaining 7 in English (for example, Кино / Kino).
Idk, dear Alexander, whether this is the correct implementation because I am a stand-alone user of your perfect app, but somewhere I would like the search to go by the author, bypassing the file name.
If you think otherwise, then I will understand and there will be no questions from my side;)
Thank you for your answer!

**Comment by OxygenCobalt** [comment]
Okay, I see now. It's matching the file-name of your music.

> Somewhere I would like the search to go by the author, bypassing the file name.

I'm not really considering this at the moment. It would clutter the search view too much. I think I will add some kind of "Search in artist" functionality in the future with #288, but that's in flux.
