### ISSUE TITLE
Music panel album art (Android 13) not updated properly 

### ISSUE THREAD

**Issue by enricocid** [OxygenCobalt/Auxio#507]
### Describe the Bug/Crash

1. Open music panel in quick settings.
2. Skip track.
3. Cover is not updated when album art is not found

The cover is updated only when the music panel is not visible. Same applies to lock screen notification.

### Describe the intended behavior

Cover should be updated even if not available.

### What android version do you use?

Android 13

### What device model do you use?

Oppo find X3 lite

### Bug report

Nan

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by enricocid** [comment]
https://github.com/OxygenCobalt/Auxio/assets/7274841/2c0bb46d-0aad-4cd6-b261-8f4d72239ec4

**Comment by OxygenCobalt** [comment]
Testing on my end, I can't reproduce this. Everything is uploaded to the MediaSession. This is probably oppo-specific and there's nothing I can do about it.

**Comment by enricocid** [comment]
Thanks 🫂
