### ISSUE TITLE
Nested playlist

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#508]
### Description

Basically, a 'playlist' in a playlist. Let me explain because a 'playlist' doesn't convey it right. Rather, a collection of the same song. Imagine I have 5 versions of My Way for variety sake but I don't want to put 5 of the same song (played differently) in one playlist, I can put them all under one parent My Way entry and Auxio picks one of the versions (each has a 20 percent chance of playing at 5 songs). Now I can do this for every song so my playlist may only have 3 visible entries: My Way, Fly me to the Moon, Let it Snow! each with a 33.34 percent chance of being selected on shuffle (as there's three entries) but if it hits My Way it will then pick one of its entries at a 20 percent chance (as there's five entries). 

Also, I could nest two songs or I could nest every entry in the playlist actually, it would show 3 entries visually (unless you inspected an entry in which you'd see its children entries) but there could be 23 tracks in there. I hope what I have said makes sense, if not I will clarify. I genuinely do not know id any music player has done this but it 

### Other implementations

I have never seen a player do this

### Benefit

1) Visual Cleanliness 
2) Variety: Makes the experience a bit unique every time
3) Proper Odds: If I shoved five versions of My Way with Fly me to the Moon and Let it Snow!, My Way would have a 5/7 of being shuffled rather than its proper 1/3. 
4) Longevity: Prevents the song's 'soul' from being drained after multiple re-listens to the exact same track, please try it genuinely

I could think of other reasons later on, bit busy rn
I know this is a very bizarre concept but genuinely think about how many songs you used to love but don't due to re-listens and find that song online but a different version of it, maybe a concert? (not talking about covers but up to you, im talking about the same artist playing the song but not the studio recording of it)

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I think you're asking more so for a kind of "Multi-Song" functionality. This is an intriguing idea, but honestly it's too niche for me to consider at the moment. Not a lot of people have several different versions of a song in a library.

**Comment by RustoMCSpit** [comment]
> consider at the moment

so maybe deep into the future?

**Comment by OxygenCobalt** [comment]
Depends on user demand

**Comment by RustoMCSpit** [comment]
> Depends on user demand.

well i mean, i thought you made decisions solely off of if you would use it. regardless, please try listening to a song thats burnt out for you but as an acoustic, a cover, a live concert, etc.. th

**Comment by RustoMCSpit** [comment]
considering playlists have been worked out i think the infrastructure to implement this is already 90% there, again it really does just act as a nested playlist

**Comment by OxygenCobalt** [comment]
> well i mean, i thought you made decisions solely off of if you would use it. regardless, please try listening to a song thats burnt out for you but as an acoustic, a cover, a live concert, etc.. try it out, genuinely refreshing

It's me *and* everyone elses use. I think it's a cool idea, but I'm trying to balance technical complexity with how in-demand something like this is. Currently that balance teeters more to `wontadd-out-of-scope`.

> considering playlists have been worked out i think the infrastructure to implement this is already 90% there, again it really does just act as a nested playlist

Not really. A nested playlist completely wrecks the playlist model I've built for the app. It would yet require another database and another data model since it's closer to song than it is a playlist. I would need to accommodate the fact that a song item can now have multiple albums. I would need to figure out either good heuristics to build a nested playlist, or somehow build a dialog to manually create them that is not incomprehensible. I also have to consider interactions with the playback system and other music items. It's on similar level of difficulty as cuesheets, which is another feature I'm not considering at the moment due to sheer technical difficulty.

**Comment by RustoMCSpit** [comment]
well i mean, at least it isnt totally out of the picture. thanks for everything you do

**Comment by illdeletethis** [comment]
Could see this functionality being useful for a playlist that collapses all songs by one artist into one spot, to then after a few listens be sure which fits best,
but i wouldn"t put a high demand on it.
Would be occasionally neat, but by no means as big an experience improvement as #229
