### ISSUE TITLE
ability to play multiple tracks at once

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#511]
### Description

select multiple songs, hit play. you could expand on this and make one song go left ear and one right but thats limkted to two songs and also killd stereo

### Problem solved

i cant play multiple ai covers at the same time blending them harmonically as they are exactly in time (being exact replicas of their source msterial)

### Other implementations

n/a honestly

### Benefit

go on youtuve and find a song you like, find multiple ai covers and play at the exact same time (tough and annoying to do but get it right). youll hear them harmonise, it'll be great. dont close this issue until you try it

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
There's no way to do this with `ExoPlayer` unless you want to make the app crash with an OOM. Just isn't technically feasible.

**Comment by RustoMCSpit** [comment]
> There's no way to do this with ExoPlayer unless you want to make the app run out of memory and crash. Not really technically feasible.

could you go to their repo and make an issue request youd be able to word it more technically

**Comment by OxygenCobalt** [comment]
It would require a massive retooling on their end and would probably be rejected.

**Comment by RustoMCSpit** [comment]
> It would require a massive retooling on their end and would probably be rejected.

ask regardless!!
