### ISSUE TITLE
change text color

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#512]
### Description

to change the text of a specific song to a specifc hex / font

### Other implementations

they dont 

### Benefit

looks cool idk man, ricing my audio player rofl

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I don't like adding extremely fine-grained customization like this. Not to mention that arbitrary hex colors would wreck the theming system.
