### ISSUE TITLE
sound effect when deleting, selecting songs, creating a playlist, etc..

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#514]
### Description

serotonin every time i add a song to my playljst and get a cool sound effect

### Other implementations

other players dont do this cause thwyre nkt as cool as auxio

### Benefit

cool sound effects, it's self-explanatory

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
If I'm going to be honest, I think that's incredibly tacky. Reminds me of the horror of pre-lollipop android devices. Sorry.

**Comment by RustoMCSpit** [comment]
> If I'm going to be honest, I think that's tacky. Reminds me of the horror of pre-lollipop android devices. Sorry.

what about an explosion sound when you delete more than ten things at once
