### ISSUE TITLE
equaliser feature should match aesthetics of main app

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#515]
### Description

a

### Other implementations

a

### Benefit

prettier, coherent

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
That's controlled by the android system, not me. I'd recommend [Wavelet](https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet&hl=en_US&gl=US) if you want a slicker experience (and more features!).

**Comment by RustoMCSpit** [comment]
> That's controlled by the android system, not me. I'd recommend [Wavelet](https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet&hl=en_US&gl=US) if you want a slicker experience (and more features!).

what repo do i recommend to the android team that this should be betyer

**Comment by RustoMCSpit** [comment]
> That's controlled by the android system, not me. I'd recommend [Wavelet](https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet&hl=en_US&gl=US) if you want a slicker experience (and more features!).

is wavelet foss

**Comment by OxygenCobalt** [comment]
> what repo do i recommend to the android team that this should be betyer
I seriously doubt you can get google to work on this. They usually don't care about stock android functionality.

> is wavelet foss
No, there aren't many FOSS equalizers out there for some reason.

**Comment by RustoMCSpit** [comment]
> > what repo do i recommend to the android team that this should be betyer
> 
> I seriously doubt you can get google to work on this. They usually don't care about stock android functionality.
> 
> > is wavelet foss
> 
> No, there aren't many FOSS equalizers out there for some reason.

could you make an issue request to google just in case. also, a new widget with those lines that measure EQ would look cool
