### ISSUE TITLE
mp4 support

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#516]
### Description

basically, plays as a song but the cover art is a 1:1 aspect ratio crop

### Other implementations

n/a

### Benefit

music videos idk man trying to think of ideas

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio plays music, it does not play music videos. Not accepting this, sorry.
