### ISSUE TITLE
smaller imageless widget

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#517]
### Description

.

### Problem solved

.

### Other implementations

.

### Benefit

smaller screen size occupied, also woild be cool to habe another widget that woukd show the next song 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I don't like making several widget variations when one responsive widget would do. In this case, #420 might be what you want.

**Comment by RustoMCSpit** [comment]
> I don't like making several widget variations when one responsive widget would do. In this case, #420 might be what you want.

rught cool
