### ISSUE TITLE
compressor effect

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#518]
### Description

a compressor

### Other implementations

nope

### Benefit

compressuon sounds awesome listen to it on yt man

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I wouldn't even know how to do this, let alone desire it since it actively reduces music quality. Not doing this, sorry.

**Comment by RustoMCSpit** [comment]
> I wouldn't even know how to do this, let alone desire it since it actively reduces music quality. Not doing this, sorry.

a compressor isnt about "compression" like a bitcrusher, it's an EQ thing kinda
