### ISSUE TITLE
Google Cast functionality

### ISSUE THREAD

**Issue by jf916** [OxygenCobalt/Auxio#520]
### Description

I would like auxio to have google cast support so that i can play my music from auxio on a google speaker through google cast.

### Problem solved

Being forced to use my phone speaker

### Other implementations

Spotify has this functionality

### Benefit

Me and others will be able to play our music on a google speaker

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Requires Auxio to depend on proprietary google services, which makes it a non-starter. Can't do this.
