### ISSUE TITLE
Apply Opus header ReplayGain value

### ISSUE THREAD

**Issue by Schyrsivochter** [OxygenCobalt/Auxio#521]
### Description

Opus R128 gain tags are referenced against −23 LUFS, not −18 LUFS as for replay gain in other formats. This is generally compensated for by the Opus header gain being +5 dB. However, it seems Auxio is not adding these extra +5 dB. This leads to inconsistent playback levels in mixed-format libraries.

I’d like Auxio to read and apply Opus header gain when playing an Opus file (option A). If that’s not possible, Auxio could instead add this value to the parsed R128 gain, if present (option B). Another alternative would be to ignore header gain and simply add +5 dB unconditionally to R128 gain (option C) – this is probably easiest to implement.

### Problem solved

My music library is a mixture of formats – Opus, MP3, and some AAC. Since Auxio version 3.1.4, Opus-encoded files are now always noticeably quieter than those encoded in MP3 or AAC.

A workaround would be to encode the entire music library in Opus and use Auxio’s global preamp settings to add the missing +5 dB. However, I do not have lossless copies of all of my songs, and reëncoding from MP3/AAC would degrade quality, which is undesirable.

### Other implementations

DeaDBeeF on Linux and foobar2000 on Android both play my Opus files at the correct volume. However, I don’t know whether they actually read Opus header gain or just add +5 dB to the R128 tags.

### Benefit

Replay gain is meant to even out loudness differences between different music; that is its primary purpose. Having it adjust volumes to different target loudnesses depending on the format defeats this purpose.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
So, I can implement this using existing ExoPlayer functionality by parsing the OPUS header data myself. I'll get to it soon.

**Comment by denny466** [comment]
Hi! Opus addict here who noticed the exact above issue by comparing the volume of a song in opus and aac each.

Yep, Opus is weird with the -5 thing and it definetely does not help when EU is already enforcing lower volume laws for Bluetooth headphones :(

Personally my phone only has opus files and manually adding +5db solves the issue. 

If you look into this issue, I love you. if you don't, I still love you, for making this awesome app. Best regards!

**Comment by Schyrsivochter** [comment]
In v3.3.3 my Opus files are still noticeably quieter than MP3. :/

**Comment by OxygenCobalt** [comment]
Okay, this is really weird. Can I please have sample files @denny466 @Schyrsivochter?

**Comment by denny466** [comment]
Hi @OxygenCobalt !
Here you go, here's a zip with:
m4a as sample with replaygain -11.18 dB, the prefered volume i perceive on Auxio
opus with replaygain -16.18 dB that could do with +5 like you usally see on foobar2000 and musicbee, -11.18 dB under the line
opus with replaygain and opus header gain that is way too quiet, because both gains get added up as mentioned (foobar2000 default setting)
Royalty free and transcoded using foobar2000. I hope it helps!
[stomping-rock-four-shots-111444.replaygain.zip](https://github.com/OxygenCobalt/Auxio/files/14324560/stomping-rock-four-shots-111444.replaygain.zip)

**Comment by OxygenCobalt** [comment]
So, Auxio is correctly parsing the header gain @denny466. What's confusing is why is the header gain just not +5 dB or -11.18 dB? Why does it have to be applied implicitly?

**Comment by denny466** [comment]
This is because the people at Xiph, who made Opus, are special and target -23 LUFS for their format. This is 5 less than standard Replaygain (-18 LUFS) on virtually any format other than Opus.

Foobar2000 for instance accepted this and always writes -5 when you use the Replaygain scanner on Opus files. But, because -18 LUFS has the greater market share, and to make Opus coexist with other formats, the offset is +5 for playback on both foobar2000 and musicbee. I'm not confident wether Replaygain or Opus header should have the higher priority, but a offset of +5 would be great to coexist with the other music formats. I hope this makes sense ^^

**Comment by OxygenCobalt** [comment]
Okay, so R128 tags and header gain should always be adjusted by +5 decibels? That wouldn't work for @Schyrsivochter's tags, which I assume have their header gain set to +5 decibels. I need a sample file from them to confirm this.

**Comment by denny466** [comment]
Yes, R128 tags (when format is Opus) or header gain best be +5 to stay -18 LUFS.

When you wrote that Auxio correctly parsed the header gain, is it just the header gain (-16.18db) or ontop of R128 gain, resulting -32.36 on playback? Because this is what i got when i used the sample files. I'm on 3.4.0, Android 13 MIUI.

**Comment by OxygenCobalt** [comment]
> When you wrote that Auxio correctly parsed the header gain, is it just the header gain (-16.18db) or ontop of R128 gain, resulting -32.36 on playback? Because this is what i got when i used the sample files. I'm on 3.4.0, Android 13 MIUI.

If you go into `3 dots -> View properties` of a song item, it should be -16.18 dB under "ReplayGain Track Gain", unless your sample file had both a header and tag gain @denny466. I checked the files and they only had one or the other. I confirmed this with running `opusinfo` on the files:

```
Processing file "stomping-rock-four-shots-111444.replaygain and opus header gain.opus"...

New logical stream (#1, serial: 00002a47): type opus
Encoded with libopus 1.3, libopusenc 0.2.1
User comments section follows...
	ENCODER=opusenc from opus-tools 0.2-3-gf5f571b
	ENCODER_OPTIONS=--bitrate 96 --vbr
	TITLE=RG and Opus header gain
	R128_TRACK_GAIN=0
Opus stream 1:
	Pre-skip: 312
	Playback gain: -16.1758 dB
	Channels: 2
	Original sample rate: 44100Hz
	Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
	Page duration:   1000.0ms (max),  992.7ms (avg),  120.0ms (min)
	Total data length: 1407070 bytes (overhead: 0.763%)
	Playback length: 1m:59.106s
	Average bitrate: 94.51 kb/s, w/o overhead: 93.79 kb/s
Logical stream 1 ended
Processing file "stomping-rock-four-shots-111444.replaygain.opus"...

New logical stream (#1, serial: 00002a47): type opus
Encoded with libopus 1.3, libopusenc 0.2.1
User comments section follows...
	ENCODER=opusenc from opus-tools 0.2-3-gf5f571b
	ENCODER_OPTIONS=--bitrate 96 --vbr
	TITLE=just RG
	R128_TRACK_GAIN=-4141
Opus stream 1:
	Pre-skip: 312
	Playback gain: 0 dB
	Channels: 2
	Original sample rate: 44100Hz
	Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
	Page duration:   1000.0ms (max),  992.7ms (avg),  120.0ms (min)
	Total data length: 1407070 bytes (overhead: 0.763%)
	Playback length: 1m:59.106s
	Average bitrate: 94.51 kb/s, w/o overhead: 93.79 kb/s
Logical stream 1 ended
```

Did you send the right files?

**Comment by denny466** [comment]
Interesting. It appears that opusinfo ignores/nulls R128 if the header gain is not null. 
I checked the file with both RG and header gain on foobar2000, and both are present as you can see:
![grafik2](https://github.com/OxygenCobalt/Auxio/assets/107651888/84e49dd0-525d-457f-a749-06738bc1386c)

I'm very surprised that the spec wants you to apply both ontop of each other. When you open Auxio and listen to Unknown Artist > title "RG and Opus header gain", you will find it is much quieter than "just RG".

So, I'm going to deduct that Foobar2000 is the dumdum here for keeping both tags around, that will make the tracks double quiet or double loud, when the used player follows the spec. Guess I'm gonna shoot them a message on Hydrogenaudio, or just keep using foobar and go to File > Preferences > Advanced > Tagging > Opus > header gain > Leave null, to not deal with the issue. Foobar itself ignores (but still displays) the header gain but actually uses R128 with +5, which is off spec but needed when you're multi format user.

**Comment by OxygenCobalt** [comment]
Okay, I took a look at the file you gave me and it has no OPUS header gain according to opusinfo:

```
Processing file "sifamoocap.opus"...

New logical stream (#1, serial: da97d4c7): type opus
Encoded with Lavf58.76.100
User comments section follows...
	ENCODER=Lavc58.134.100 libopus
	R128_TRACK_GAIN=-837
Opus stream 1:
	Pre-skip: 312
	Playback gain: 0 dB
	Channels: 2
	Original sample rate: 48000Hz
	Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
	Page duration:   1000.0ms (max),  984.9ms (avg),   20.0ms (min)
	Total data length: 1188650 bytes (overhead: 0.706%)
	Playback length: 1m:04.000s
	Average bitrate: 148.6 kb/s, w/o overhead: 147.5 kb/s
Logical stream 1 ended
```

This implies that it's also using the implicit 5 dB adjustment that @denny466 was talking about, so I guess I also have to implement that.

**Comment by OxygenCobalt** [comment]
I just realized: I think the reason why you might be experiencing a double application of the adjustment is because the media framework was already applying the OPUS base gain @denny466. I'll stop parsing it for now (Eventually I might try to indicate it in such a way that it's shown in the UI but not applied)

**Comment by Schyrsivochter** [comment]
After some investigation it seems that Deadbeef is to blame here. Its handling of R128 and header gain is weird – it seems like it’s adding +5 dB implicitly, going so far as displaying it in the properties window with those +5 dB added. So it always _looked_ like my Opus files had +5 dB header gain, when in reality they did not! My apologies for the confusion!

**Comment by OxygenCobalt** [comment]
> So it always looked like my Opus files had +5 dB header gain, when in reality they did not! My apologies for the confusion!

That makes sense. It's likely that Auxio will do the same. This should be good to go in whatever the next release is.
