### ISSUE TITLE
clicking the 3 dots of a song in a playlist should offer to be able to remove that song too

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#523]
### Description

also should work when yiyve multiple songs selected

### Other implementations

n/a

### Benefit

intuitive

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is accessible via the edit button, like it is in the queue. I don't like the friction of having to search & click twice to remove a song.
