### ISSUE TITLE
Can add songs to playlists, cannot remove them

### ISSUE THREAD

**Issue by Innominatapersona** [OxygenCobalt/Auxio#528]
### Description

I'd like to have a "remove from playlist" entry among a song's options.
I read this from other users, but I'd also appreciate a better way to close the app from the notification, like an X button on the right side of the notification.
Thanks

### Problem solved

I don't like the fact that I have to delete a whole playlist and recreate it ex novo to remove songs from it.
I also don't like to kill the app via android system to remove the notification. 

### Other implementations

Other music players have an entry to remove songs from playlists and a button to close the app from the notification.

### Benefit

This feature would make people save much time when modifiyng a playlist and little when exiting the app.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is available via pressing the "edit" button and then swiping songs to the left.

**Comment by Innominatapersona** [comment]
😍 thanks
