### ISSUE TITLE
instead of album cover audio analyser

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#530]
### Description

not a widget but instead in app https://www.youtube.com/watch?v=7z2ppEhz4gE

this or something like it in a widget (btw this is https://github.com/yliniemi/AcidAnalyzer )

### Problem solved

.

### Other implementations

.

### Benefit

cool

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is impossible to implement without an extremely suspicious permission (Record Phone Calls). Not doing this.

**Comment by RustoMCSpit** [comment]
> This is impossible to implement without an extremely suspicious permission (Record Phone Calls). Not doing this.

oh what damn, you cant eq it otherwise wtf
