### ISSUE TITLE
very irrelevant midi idea

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#533]
### Description

hey oxygen, was wondering if you knew how / wanted to set up this midi file github page resource 
https://github.com/Fannon/midi-chords-and-scales-pack/issues/2

heres a list of free midi resources, i want there to be a singular github for everyone to access them

### Other implementations

none

### Benefit

massively helps out musicians

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
That's not related to the app much. I really don't have the time to contribute. Sorry.

**Comment by RustoMCSpit** [comment]
> That's not related to the app much. I really don't have the time to contribute. Sorry.

dw about it!

**Comment by RustoMCSpit** [comment]
also loojs like the tonehunt guys will do it
