### ISSUE TITLE
change the font of the auxio on top to be bolder and add  the logo beside it

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#534]
### Description

a nicer font for the title

### Other implementations

nahbabzb

### Benefit

looks prrttier

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Looks tacky, honestly. Not doing this, sorry.

**Comment by RustoMCSpit** [comment]
> Looks tacky, honestly. Not doing this, sorry.

dw about it
