### ISSUE TITLE
is there any way to make it louder without altering pre amp

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#536]
### Description

.

### Other implementations

.

### Benefit

.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
No. I don't really like adding redundant volume controls when the system volume works fine.

**Comment by RustoMCSpit** [comment]
> No. I don't really like adding redundant volume controls when the system volume works fine.

you dont find it too quiet?

**Comment by OxygenCobalt** [comment]
No, max system volume is just fine.
