### ISSUE TITLE
add recommened foss apps to apply images to files in the readme

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#539]
### Description

.

### Other implementations

.

### Benefit

will prevent confusion and needless issues being raised

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is already in the wiki [here](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F#tag-editor). I only know automatag in this regard, which is closed-source. At points I've considered making my own companion tag editor app, but music metadata is much more complex than one might think, and beets works just fine for me.
