### ISSUE TITLE
Add crossfade support

### ISSUE THREAD

**Issue by RockfordRoe** [OxygenCobalt/Auxio#54]
#### Describe the feature you want to implement:
It should be self-explanatory.

#### Is your feature request related to a problem? Please describe:
The album: [None of This Is Real by DJ Rozwell ](https://djrozwell.bandcamp.com/album/none-of-this-is-real) requires the listener to play the album on shuffle mode with a 5-6s crossfade. Auxio cannot do so.

#### Why do you think this will improve everyone's usage of Auxio?
The feature is very useful to make playlists more seemless by having tracks flow into each other.

#### Due Diligence:

- [x] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Hm. That seems like a good feature to add to the Audio settings. Let me see if ExoPlayer has a way for me to do this.

**Comment by OxygenCobalt** [comment]
Sadly I don't think I can add this. According to exoplayer/#3438, having crossfade support would require some extreme refactoring on the ExoPlayer end and would make it's internal state inconsistent, so the devs aren't looking to add it. The last thing I want to do is have to rip out ExoPlayer's demuxer and write my own, so unless they somehow change their mind here I don't think this feature is feasible. Sorry.
