### ISSUE TITLE
a widget with a time slider

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#542]
### Description

yk how in app at the bottom theres a time slider, that. that bottom sectikn would actually make a great looking widget

### Other implementations

.

### Benefit

skip forward or back

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Impossible for the same reasons that putting a visualizer on a widget is. Sorry.
