### ISSUE TITLE
Choose search type based on current tab

### ISSUE THREAD

**Issue by MaxsimLionel** [OxygenCobalt/Auxio#543]
### Description

When I open the app and am in the Songs tab, when I hit search I want to search songs. And when I am in Artists or any other tab, I would like the app to automatically adjust the search to that type. Instead of it being defined separately.  

It feels more intuitive to me and someone else I've shown the app to. 

### Other implementations

They handle it by searching in the current tab, I think. Maybe they don't implement it at all 

### Benefit

This feature allows you to search in the tab your are already in. 

Thank you. 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
In my opinion, this is really bad UX. It's implicitly changing how the search view works based on something not immediately obvious to a user. Sorry.

**Comment by MaxsimLionel** [comment]
I disagree. I believe the current way of specifying what kind of search to do is bad UX and not immediately obvious to most users.

**Comment by MaxsimLionel** [comment]
Or have both...

**Comment by OxygenCobalt** [comment]
I disagree. I believe the current way of specifying what kind of search to do is bad UX and not immediately obvious to most users.

How so? The search view isn't hiding anything. If you're aiming for a song, you can still find the song. Is the issue that you have to scroll past non-song items to find what you want?

I could alternatively dynamically re-order the search categories. If you are in the songs tab, songs will show at the top, and so on.
