### ISSUE TITLE
Permission rationale button not centered

### ISSUE THREAD

**Issue by enricocid** [OxygenCobalt/Auxio#544]
### Describe the Bug/Crash

![Screenshot_2023-08-15-09-59-03-45_65b8df5a000978b3161002a299fb7747](https://github.com/OxygenCobalt/Auxio/assets/7274841/e565513b-9ba7-47bf-9201-2fd15a0572d4)

### Describe the intended behavior

Should be centered?

### What android version do you use?

Android 13

### What device model do you use?

Oppo Find X3 lite

### Bug report

Button not centered

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Whoops. I accidentally made the new error information button invisible instead of gone in the permissions prompt. I'll fix this.
