### ISSUE TITLE
add icons for every setting like the first four icons

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#547]
### Description

.

### Other implementations

.

### Benefit

lpoks cool

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
There really aren't icons that can accurately describe a lot of settings. So either I have a cryptic icon tied to a setting, or I have a jarring and inconsistent setting layout. Instead I don't use icons. Sorry.

**Comment by RustoMCSpit** [comment]
> There really aren't icons that can accurately describe a lot of settings. So either I have a cryptic icon tied to a setting, or I have a jarring and inconsistent setting layout. Instead I don't use icons. Sorry.

icons for 

Library:
a folder
a refresh swirl
a radar

Persistence:
a floppy disk
an eraser
a tombstone? (wpuld be cool)
