### ISSUE TITLE
ability to pan certain elements of a song

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#548]
### Description

ive a file that has a bass track and a vocal track and i want to pan one lwft and one right, can it be done

### Other implementations

.

### Benefit

.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
No, that would require implementing stem extraction which is far too slow. Sorry.
