### ISSUE TITLE
Queue Feedback

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#55]
Facing a possible rework of the playback system because of #52, I would like to have some feedback on Auxio's current queue system.

I designed Auxio's queue to be "transient", like Spotify. You add a song to the queue, and then it disappears once it's done playing. This is the queue system that I preferred the most, but internally it's a technical nightmare and acts as a huge hold-up with features like gapless playback [#35]. Plus, add to queue was inflexible and would only add to the end of the transient queue, which some people requested be changed in #44.

The way I could fix this is by switching to a more traditional single queue system with a "Play Next" option that adds a song to the top of the queue, and then an "Add to queue" option that appends a song to the end of a queue. This would be easier to implement internally and would possibly be beneficial to most people who use this app, but isn't exactly the system I prefer, and I'm not sure how popular it would be with others.

I have to pick one system or the other, as adding a configuration option would simply add too much complexity to be worth it.

I want to pass the question off to other people who use this app. Would you prefer the current two-queue system or a single-queue system? Thanks.

**Comment by resom78** [comment]
Hi,

I would definitely prefer the two queue system, like in many other players.
Right now it's my favorite audio player!
I just miss the replaygain functionality and the player would be perfect!

**Comment by itsmusictomyears** [comment]
Having both 'play next' and 'add to queue' would be perfect for me.

**Comment by kenktk** [comment]
Using a simple single queue system does not bother me. I prefer the ability of gapless playback over the current queue system. And I am always for decreasing the complexity of the codebase.

**Comment by OxygenCobalt** [comment]
I've decided to switch to a single queue, as this would not only aid gapless playback support, but will also create a more seamless experience when I implement ReplayGain support as well [#7].
