### ISSUE TITLE
Audio files not recognized

### ISSUE THREAD

**Issue by Duvio** [OxygenCobalt/Auxio#556]
### Describe the Bug/Crash

Under settings > music folders > include i have added "Internal shared storage/Music". There are a ton of .opus files in this folder. Yet none of them are recognized by Auxio.
![Screenshot_20230830-022006_Auxio](https://github.com/OxygenCobalt/Auxio/assets/29256280/de8fadc7-9512-45a4-acd4-c142a99573f1)
![Screenshot_20230830-022144_Auxio](https://github.com/OxygenCobalt/Auxio/assets/29256280/6c5c5dff-1977-4d61-b034-3fc4cbead73d)
![Screenshot_20230830-022157_Cx File Explorer](https://github.com/OxygenCobalt/Auxio/assets/29256280/341c24d5-c13d-4922-87e5-b0730c7828b0)

### Describe the intended behavior

Recognize the audio files properly

### What android version do you use?

Android 13

### What device model do you use?

Galaxy A52s 5G
Latest LinageOS

### Bug report

It didn't finish the bug report for me

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
The android system does not detect .opus files below Android 10, sadly. You need to mass-rename their extensions to OGG. I want to resolve this with #322 eventually.
