### ISSUE TITLE
Accept native multi-value M4A tags

### ISSUE THREAD

**Issue by chocmake** [OxygenCobalt/Auxio#558]
### Describe the Bug/Crash

Preface: tested with AAC encoded M4A tracks, tagged via Mp3Tag.

If a single (that is, 1) track that has a RELEASETYPE tag of `Single` is added to the music library, and it's the only track for that particular artist, then Auxio doesn't display its discrete cover art (that is, a non-embedded standalone `Cover.jpg`) or report the artist as having any songs ('No songs') when viewed in the Artist tab.

However if the RELEASETYPE is `Album` then even if there's only a single track copied to the music library the discrete cover art will display and '1 song' will be reported in the Artist tab.

I separately tested if this was related to the Total Tracks tag being `1` but increasing the total tracks tag and rescanning the library in Auxio still produced the same lack of cover art and song counter in the Artist tab if the RELEASETYPE is `Single`.

Screenshots:
![Image - 1](https://github.com/OxygenCobalt/Auxio/assets/34178938/72805827-8637-40d6-a774-90babb17c867)

Showing a release type of 'Single' that contains only 1 track:
![Image - 2](https://github.com/OxygenCobalt/Auxio/assets/34178938/6c9ab4d7-c6dd-4720-9c04-2ea17895c520)

Showing a release type of 'Single' that contains 4 tracks:
![Image - 3](https://github.com/OxygenCobalt/Auxio/assets/34178938/8a315dc8-69ef-48e5-ba96-1cad8b720e01)

### Describe the intended behavior

The discrete cover art and and track counter should display for single tracks in the Artist tab.

### What android version do you use?

Android 13

### What device model do you use?

LineageOS 20.

### Bug report

.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is largely intentional behavior. The first single only references "August Rosenbaum" as an album artist and never as a track artist, so Auxio only links it to an album. The second artist references "Geotheory" as an album and track artist, so Auxio links it to the songs and the album. The only issue is that artists aren't sampling cover art from their albums, which should be an easy fix.

**Comment by chocmake** [comment]
> The first single only references "August Rosenbaum" as an album artist and never as a track artist, so Auxio only links it to an album. The second artist references "Geotheory" as an album and track artist, so Auxio links it to the songs and the album.

Hmm, as both actually have the album artist also as an Artist tag. Via Mp3Tag fields:

The August Rosenbaum release:
Artist: `August Rosenbaum\\Coco O.`
Album Artist: `August Rosenbaum`

And seen in Mp3Tag's Extended Tags view which shows the artist values separated:

![Screenshot](https://github.com/OxygenCobalt/Auxio/assets/34178938/60d93067-c3bf-4140-b60b-bc0f30dd8436)

The Geotheory release:
Artist: `Geotheory`
Album Artist: `Geotheory`

**Comment by OxygenCobalt** [comment]
> August Rosenbaum\\Coco O.

Are these native multi-value or delimited multi-value tags? Auxio might be assigning the track artist to `August Rosenbaum\\Coco O.`, which would also cause the issue. You can change what separators Auxio splits by in `Content -> Multi-value separators`. Albeit, Auxio doesn't support splitting by `\\`, so I would recommend changing it to something like `/` or `;`.

**Comment by chocmake** [comment]
> Are these native multi-value or delimited multi-value tags?

It's the way Mp3Tag handles defining multi-artists for its tag editor, which is just showing all individual artist tags in a single field from what I understand, rather than some literal delimiter string. As from the Extended Tags one can see that in reality it has produced multiple Artist tags from it.

**Comment by OxygenCobalt** [comment]
> It's the way Mp3Tag handles defining multi-artists (or any multiple value) for its tag editor, which is just showing all individual artist tags in a single field from what I understand, rather than some literal delimiter string. As from the Extended Tags one can see that in reality it has produced multiple Artist tags from it.

That doesn't help. Mp3Tag may be abstracting away the delimited multi-value tags it's actually using. I would recommend opening up the file in [kid3](https://kid3.kde.org/) which doesn't do this.

**Comment by chocmake** [comment]
Here is Kid3's view of the artist tags, which is odd in comparison to multiple other tagging and audio metadata viewers, in that `Coco O.` as an artist tag shows as entirely absent:

![Kid3 screenshot](https://github.com/OxygenCobalt/Auxio/assets/34178938/61ddb57b-5c09-491b-a3b3-956bb0ee3750)

Since in Mp3Tag, foobar2000 and MediaInfo both artists correctly appear for the M4A.

---

I wondered if this was a difference in FLAC vs M4A handling so swapped out the M4A transcoded version and put the original lossless FLAC in its place and rescanned. **Result: it behaved as expected, showing the cover art and song counter.**

![Image - 4 (FLAC)](https://github.com/OxygenCobalt/Auxio/assets/34178938/fb1b56f3-75a3-4fec-bf55-1761c68e7f93)

Here's a side-by-side with the FLAC on the left (correct) and M4A on the right (unexpected behavior). Note that in the M4A version `August Rosenbaum` isn't detected as a track artist, while they are in the FLAC version.

![Image - 5 (FLAC vs M4A)](https://github.com/OxygenCobalt/Auxio/assets/34178938/0369fcda-9ebe-4b02-ba0c-3bea7d4523c3)

In Kid3 for the FLAC file OTOH it shows both track artists, as one would expect.

---

I wonder if this is some unexpected Linux/Android handling of M4A or what :thinking:

**Comment by OxygenCobalt** [comment]
Okay, I think I need a sample M4A file. You can cut out the copyrighted audio, just give me the tags.

**Comment by OxygenCobalt** [comment]
Preferably give me the entire single, as it also might cascade into weird behavior with Auxio's music grouper.

**Comment by chocmake** [comment]
Here you are, a FLAC and M4A containing just 5s silence with the tags copied from the original track. The M4A was converted from the FLAC using qaac (using Apple's AAC encoder), which was how the M4As discussed above were made.

[Zipped.zip](https://github.com/OxygenCobalt/Auxio/files/12504480/Zipped.zip)

(FWIW I removed the Genre tag from my source files after I noticed it was present in a prior screenshot, so ignore that difference)

**Comment by OxygenCobalt** [comment]
Oh, there's the issue:

![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/9da1d097-2c0f-4d50-8a04-7e71feadbd02)

Apparently M4A allows several atoms of the same ID, like vorbis. I did not expect this in my music loader. I'll get to fixing this.
