### ISSUE TITLE
Re-add black theme in Android 12

### ISSUE THREAD

**Issue by kenktk** [OxygenCobalt/Auxio#56]
#### Describe the feature you want to implement:

Toggleable black OLED theme

#### Is your feature request related to a problem? Please describe:

Feature request is not related to any problems.

#### Why do you think this will improve everyone's usage of Auxio?

- Consistant theming for users that have an OLED display. 
- Better battery usage. More pleasing to the eye (IMO). 
- Seriously my last grudge against this simple yet absolutely refreshing application. 

Thanks for sticking to a frugal design choice concept. By far one of my favorite privacy respecting applications.

#### Due Diligence:

- [ ] Determine if toggling black backgrounds is available in upstream UX libraries that are already in use by Auxio.
- [ ] Determining most effective/efficient method of changing and toggleing the UX elements' background color. 
- [ ] Determine if/how the toggle should or should not interact with the system theme.
—

- [x] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I think I added this under the "Black theme" option. Are you on Android 12? I didn't disabled that option starting with Android 12 since I wanted to let dynamic colors theme the app instead.

**Comment by kenktk** [comment]
I am on Android 12, specifically running GrapheneOS. Dynamic colors might be broken on GrapheneOS. https://github.com/GrapheneOS/os-issue-tracker/issues/133

Not entirely sure if RRO is at fault. But yeah I don't have a black theme.

**Comment by OxygenCobalt** [comment]
Ah. I'm going to re-add the option to enable black theme in 2.0.0 then. Thanks for the suggestion.
