### ISSUE TITLE
(Question) which MBID tags does auxio rely on?

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#561]
I am planning to re-tag my library soon-ish. in fact, i already started in the past, since i learnt that auxio recommends and reads the musibrainz id tags. however, there are several different musicbrainz id tags, and i'm unsure which ones to use or which ones are requred for good functionality.
see: https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id17
- I am going to use the MusicBrainz Picard tagger, most likely with a post-processing tagging script too (if needed) and some custom tagger script for the youtube/soundcloud downloads (TBD since i wanna use youtube music/soundcloud api to get metadata)
- I am planning to use FLAC (deezer), OPUS (youtube) and MP3 (soundcloud) file formats.
- if there are some caveats, stuff i should do differently or stuff i should keep in mind, please let me know! Thanks!

**Comment by OxygenCobalt** [comment]
There should be an distinct MBID for songs, albums, and artists. With multi-value tags, the MBIDs should be specified in the same order that the names were. You can find the identifiers Auxio uses at https://github.com/OxygenCobalt/Auxio/wiki/Supported-Metadata.

**Comment by KraXen72** [comment]
thank you!
