### ISSUE TITLE
Widget taking up too much space

### ISSUE THREAD

**Issue by Samyyoff** [OxygenCobalt/Auxio#562]
### Description

The play music widget is taking too much space idk if it's fixable if not could you separate the widget in 2 widgets so the the empty space become usable (the space that the image doesn't take when 4x2/5x2)

![Screenshot_2023-09-04-18-53-19-59_b783bf344239542886fee7b48fa4b892](https://github.com/OxygenCobalt/Auxio/assets/114173233/827a8e8c-a715-439c-ab5c-55f969de657e)

### Other implementations

Other music players usually fix this problem by just removing the image part but its so beautiful I think it's probably the most beautiful music widget I've ever seen

### Benefit

This feature helps
 people like me who want to have a single page in the home screen take up very valuable space and it just looks better not having empty spaces on home screen 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I sadly can't do this. Android doesn't allow widgets to take a custom shape, so that space can only be unused with the current design. You can size it down to 2x2, which should free the space a little.

**Comment by Samyyoff** [comment]
Can't you separate the widget into 2 widgets (I know it would be a little
complicated for a music player that simple but you can also make like a
setting that activates more complex and experimental features a little bit
like developer mode in android)

**Comment by OxygenCobalt** [comment]
No, not really. I want to keep my attention focused on a single widget to reduce bugs. I'm also unsure on what kind of widget you actually want.

**Comment by Samyyoff** [comment]
No I don't ask for multiple widgets I just found a solution to the problem
of unusable space the solution being separate the music widget into 2 parts
(2 widgets) the first being the music controls the second being the image
so the empty space (sorry if my English is trash I'm not native English
speaker)

**Comment by OxygenCobalt** [comment]
I don't see myself doing that, it's much harder to make music controls by themselves work as a responsive widget without it looking ugly.

You might be interested in #420 though, it promises to add some new thinner layouts to make the widget take up less space.
