### ISSUE TITLE
Song cover is cut out in widget 

### ISSUE THREAD

**Issue by Samyyoff** [OxygenCobalt/Auxio#563]
### Describe the Bug/Crash

When the widget is in 5x2/4x2/3x2 half of the song cover is not here

The song cover in widget:
![Screenshot_2023-09-04-19-42-53-56_b783bf344239542886fee7b48fa4b892](https://github.com/OxygenCobalt/Auxio/assets/114173233/e6c28b61-fd0a-44d2-9235-4bf3af12e151)

The correct song cover:
![Screenshot_2023-09-04-19-48-27-88_e7dcd68fdcfdc2ab307738dbc82b3952](https://github.com/OxygenCobalt/Auxio/assets/114173233/f4685ffd-d8c7-45c9-bc63-a5f3e5afbbd9)

### Describe the intended behavior

Half of the cover shouldn't be deleted 

### What android version do you use?

Android 12

### What device model do you use?

Oppo a93 (color os 12.1)

### Bug report

Didn't found how to do it

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is intented. The cover is sitting "behind" the player controls in that design. You can increase the height of the widget to make it switch to another layout that shows the full cover.

**Comment by Samyyoff** [comment]
Oh ok sorry for wasting your time
