### ISSUE TITLE
Album view is not grouping songs properly by album

### ISSUE THREAD

**Issue by acathub** [OxygenCobalt/Auxio#564]
### Describe the Bug/Crash

1. I have many albums in my collection, which contain songs from various different artists
2. Example an album called "Bar Jazz, Volume 3 (disc 1)" with n songs each from a different artist
4. I choose to view songs by album
5. Songs from same one album by different artists are grouped first by artist and then by album
6. This leads in the sample case above to schow 12 times the same album with only one song each for the one single artist of that single song

### Describe the intended behavior

1. In view by album I expect to see one album called "Bar Jazz, Volume 3 (disc 1)"
2. in best case it would mention for each album the number of songs (12) and number of diffrent artists (like 12) or if all songs from same artist then name of the artist
3. If I then tip one single album, only then the songs which belong to the selected album should be listed each song with their individual artist information 

### What android version do you use?

Android 10

### What device model do you use?

Fairphone 2

### Bug report

![auxio album wrong grouping](https://github.com/OxygenCobalt/Auxio/assets/143071985/fc9bfbc8-9155-4549-9087-c7dae7b7d939)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is intentional. You need to add an "Album artist" tag that allows Auxio to understand that these aren't all albums by different artists that happen to have the same name, but is just one album with songs by many artists. Usually you set it to "Various artists" or similar.

**Comment by acathub** [comment]
Thanks for kind support. It works with additional tag "album artist". 🙌
