### ISSUE TITLE
Display chapter points

### ISSUE THREAD

**Issue by tempo660** [OxygenCobalt/Auxio#565]
### Description

Lengthy audio tracks occasionally have chapter points embedded into them. It would be nice if these chapter points were indicated on the timeline as a small mark. Nothing other required, just a little graphical tip for how close to the next chapter. I believe there are multiple metadata fields for chapter points, I'm unsure which is the dominant one.

### Problem solved

Nope. Sometimes I'm listening to an audiobook or full album as a single file and wish to know how far along until the end of track.

### Other implementations

They don't as far as I'm aware.

### Benefit

It's just a little convenient. I don't believe it should be too complicated to implement, and it remains unseen until you encounter a track with chapter points so the simple feel is retained.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I kind of get the appeal to this a little. While I don't optimize Auxio for audiobooks, bands like Godspeed You! Black Emperor have 20+ minute songs which also tend to be subdivided into "parts" that can be useful to seek through. Sadly:

1. these tags are not universal. ID3v2 has `CHAP`, but there's no analogue for Vorbis Comments, so I'd have to make something up or just exclude all vorbis users from this.
2. There's no way to do indicate arbitrary tick marks in the UI component I use. You can only have periodic dividers, such as one every second. There's also possible UI conflicts with #130.
3. I don't know how to indicate that this behavior is related to chapters. If I just have tick marks with no context, people with poorly tagged libraries will get confused and file bug reports.

Great idea, there's just not a feasible route to execution that doesn't lead to technical debt or a confusing UI.
