### ISSUE TITLE
Mark timecode

### ISSUE THREAD

**Issue by tempo660** [OxygenCobalt/Auxio#566]
### Description

I would like the ability to quickly take note of moments during an audio track, for later inspection or use of those moments. For lengthy audio tracks, sometimes I encounter moments I want to come back to later and wish to quickly take a note of the time.

### Problem solved

No. It's not a problem but it would be useful to me. Quite honestly I don't use the Equalizer function, so I would happily embrace the option to swap it for a button which upon pressing records the present timecode into a plaintext.

### Other implementations

They don't as far as I'm aware. Presently my solution is to pause the track, read the timecode, change over to LesserPad (plaintext editor), write down the title and time, and return to Auxio then resume playing.

### Benefit

I'm sure people use audio players for purposes other than enjoying music. For research, work, education and general use. I want as much control as possible and this seems like a useful but simple utility which would improve my workflow. Listening to lengthy audio is often best done when not chained to chair indoors, so this is why a portable music player deserves this utility function imho.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I get your reasoning, but I feel that this is too esoteric. I say that every feature I add must benefit everyone mostly so I can adequately maintain it as a solo developer. Adding an esoteric feature like this would add technical debt that could cause me to accidentally break it at a later date, and the low user count of this feature would not make me realize the error until it's in a release. I'm really sorry about this.
