### ISSUE TITLE
Swipe to queue

### ISSUE THREAD

**Issue by shinysocks** [OxygenCobalt/Auxio#567]
### Description

Please add in swipe to play next functionality similar to what the spotify app does.

### Problem solved

I have to click a bunch in order to play songs next.

### Other implementations

Spotify implements this feature nicely
![image](https://github.com/OxygenCobalt/Auxio/assets/91911303/e9978814-8cf8-4120-9e4a-586addfe039c)

### Benefit

speed. it will allow users to add songs to play next faster and improve overall user experience.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is poor design, actually. The "Swipe to X" pattern should remove items from the current list in some way. Adding to the queue will not do this. Additionally, the swipe gestures on android are finicky and can activate for no reason, which will probably lead to a lot of useless bug reports. Not doing this, sorry.

**Comment by lsomm** [comment]
Would you be open to other ways of simplifying the `add to queue` mechanic? The current behaviour is clunky and interrupting my workflow. ([Irrelevant xkcd](https://xkcd.com/1172/))

**Comment by OxygenCobalt** [comment]
I really don't know other ways to simplify it that would not violate design guidelines @lsomm.

**Comment by lsomm** [comment]
@OxygenCobalt, on the off-chance that I find the time and motivation, would you accept a PR that implements this and hides it behind a setting that off by default?

**Comment by OxygenCobalt** [comment]
No, not really @lsomm. This would greatly increase the technical complexity of list-related code and make it prone to breakages given that I would not be actively using it. And as I described prior, it's a violation of design guidelines that I don't want to be doing in the first place.
