### ISSUE TITLE
Option to remain paused on next track

### ISSUE THREAD

**Issue by tempo660** [OxygenCobalt/Auxio#568]
### Description

If I have the player paused, I would like it to remain paused as I advance to the next track. If the audio is playing, it plays the next track. Basically the app keeps memory of if you are paused or not and respects that as you skip forward and back.

### Problem solved

Sometimes I want to advance to the next shuffle track, but wish for the player to be quiet until I've made my choice what track to settle on. Having every track play can be distracting and annoying.

### Other implementations

Vanilla Music player has this. It's self-explanatory.

### Benefit

Implementing this makes Auxio more intelligent. Greater intelligence strengthens trust in the app. More trust allows happiness to flourish and the world keeps spinning and we all get to enjoy music in peace.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by chocmake** [comment]
Just my two cents but if this were to be implemented I'd hope it were an optional setting. Auxio actually displays the entire upcoming playback queue by swiping the 'Queue' panel up from the Now Playing screen—which includes shuffled order—and is uniquely helpful in deciding which next shuffled track to play without playing it.

For some examples which match Auxio's current playback behavior I tried two other Android apps (stock LineageOS and Symphony) and they similarly begin playback on Next, as do various desktop audio players I've used (foobar2000, miscellaneous older players) and web store players (Spotify, bandcamp, Bleep).

The notable exception is iTunes, which does remain paused on pressing next track, though it lacks insight into the shuffle queue.

**Comment by OxygenCobalt** [comment]
This seems reasonable as a setting, since there's no consistent behavior between all players. There's also precedent for customizing what Auxio does after a track finishes. I'll do it eventually.

**Comment by OxygenCobalt** [comment]
I might extend this functionality a bit. By default Auxio will generally play when a song changes in any context, which includes skipping but also weirder things like removing the current song from the queue. Working on Gapless Playback, it seems like the default configuration is to carry over the existing play/pause state, so it seems good to also allow that behavior to be controlled in settings.
