### ISSUE TITLE
Sort by file path

### ISSUE THREAD

**Issue by vbakc** [OxygenCobalt/Auxio#57]
#### Describe the feature you want to implement:

Ability to sort songs by file path.

#### Why do you think this will improve everyone's usage of Auxio?

It is very demanded type of sorting because it is the easiest (from implementation perspective) way to sort music library in the way you like.

#### Due Diligence:

- [x] I have read  [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) and the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I need a bit more clarification. Do you want a file path as in "path/to/music.mp3" or as "music.mp3"?

**Comment by vbakc** [comment]
I suggest using the full path. With that you can do almost any type of sorting by building a hierarchy.

**Comment by OxygenCobalt** [comment]
Hm. You want a full directory view then. I rejected this back in #10, sorry.
