### ISSUE TITLE
Fully circular queue when repeat all enabled

### ISSUE THREAD

**Issue by chocmake** [OxygenCobalt/Auxio#570]
### Description

It would be useful when repeat is set to repeat all for Auxio to loop back around to the end track in the queue if pressing the Previous track button when the first track is active.

(Searched but didn't see a prior request/issue but maybe I missed one)

### Problem solved

This would resolve an inconsistent behavior where upon the last track it cycles forward to the first track but pressing Previous doesn't cycle back to the end track of the queue that was previously playing.

### Other implementations

foobar2000 and iTunes do this for repeat all as does the stock LineageOS Music app.

### Benefit

Would behave in a more expected way.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This sounds like a good idea. The issue is the interaction with #35. I'm paused on adding new playback settings until gapless playback, as it risks me being forced to remove them if ExoPlayer doesn't want to play along.

**Comment by OxygenCobalt** [comment]
Looks like I've gotten this feature added automatically with #110!
