### ISSUE TITLE
have a setting to make the top banner lighter in shade always

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#573]
### Description

currently only if you scroll it gets lighter, i always want it to be like that.

also have an option to centre the five tabs as it's currently indented slightly to the left

### Other implementations

.

### Benefit

pretty

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
That would generally be a violation of the material design guidelines, and there really isn't a good way to communicate the setting without it being very cryptic. Not doing this, sorry.
