### ISSUE TITLE
Use correct PICTURE block for cover art in FLAC files

### ISSUE THREAD

**Issue by llamasblade** [OxygenCobalt/Auxio#574]
### Description

The FLAC format allows for multiple pictures to be embedded in a single file. Each picture is stored in a `METADATA` block of type `PICTURE`; each of this `PICTURE` blocks has itself a `type` attribute, defining the content of the related picture. These are the possible `type`s (the same list can be found [here](https://xiph.org/flac/format.html#metadata_block_picture)):
0 - Other
    1 - 32x32 pixels 'file icon' (PNG only)
    2 - Other file icon
    3 - Cover (front)
    4 - Cover (back)
    5 - Leaflet page
    6 - Media (e.g. label side of CD)
    7 - Lead artist/lead performer/soloist
    8 - Artist/performer
    9 - Conductor
    10 - Band/Orchestra
    11 - Composer
    12 - Lyricist/text writer
    13 - Recording Location
    14 - During recording
    15 - During performance
    16 - Movie/video screen capture
    17 - A bright coloured fish
    18 - Illustration
    19 - Band/artist logotype
    20 - Publisher/Studio logotype

Type `3` is what should be used for cover art. When extracting the cover art from a flac file, Auxio should check that the `type` of the `PICTURE` block is correct.

### Problem solved

I've recently added other pictures with other types (e.g. lead artist, publisher logotype) to some songs and I've noticed that Auxio seems to always use the last `METADATA` block with type `PICTURE`.
I usually add the cover art in the first block, so if there is more than one picture in the flac file Auxio won't display the correct one as album cover.

As an example, the following is the output of `metaflac --list --block-type=PICTURE <filename>.flac | grep -A11 METADATA` of one of those songs. As you can see, there are 5 `METADATA` blocks with type `PICTURE` (meaning 5 pictures embedded), where the first one is the cover art, but Auxio uses the last (n. 6).
```
METADATA block #2
  type: 6 (PICTURE)
  is last: false
  length: 287627
  type: 3 (Cover (front))
  MIME type: image/jpeg
  description: 
  width: 600
  height: 600
  depth: 24
  colors: 0 (unindexed)
  data length: 287585
--
METADATA block #3
  type: 6 (PICTURE)
  is last: false
  length: 13291
  type: 7 (Lead artist/lead performer/soloist)
  MIME type: image/jpeg
  description: 
  width: 300
  height: 300
  depth: 24
  colors: 0 (unindexed)
  data length: 13249
--
METADATA block #4
  type: 6 (PICTURE)
  is last: false
  length: 76771
  type: 19 (Band/artist logotype)
  MIME type: image/jpeg
  description: 
  width: 600
  height: 600
  depth: 24
  colors: 0 (unindexed)
  data length: 76729
--
METADATA block #5
  type: 6 (PICTURE)
  is last: false
  length: 35243
  type: 20 (Publisher/Studio logotype)
  MIME type: image/jpeg
  description: 
  width: 480
  height: 480
  depth: 24
  colors: 0 (unindexed)
  data length: 35201
--
METADATA block #6
  type: 6 (PICTURE)
  is last: false
  length: 22400
  type: 20 (Publisher/Studio logotype)
  MIME type: image/jpeg
  description: 
  width: 250
  height: 250
  depth: 24
  colors: 0 (unindexed)
  data length: 22358
```

### Other implementations

I've quickly tried other music players on F-Droid (Phonograph Plus, Simple MP, mucke) and they all behave like Auxio. I guess it might have something to do with a common library that's been used for parsing metadata.

### Benefit

I think this is a feature with low priority because most people probably add only the cover art to their files, not to talk about the fact that I've only checked this behavior for flac files. But I also think I'de be a nice little detail that would make this app more "rational" ;)

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is already handled by Auxio, but only if you change Settings -> Content -> Album covers to "Quality" instead of "Fast". By default Auxio defaults to the faster android behavior that sadly just picks a random image to use.

**Comment by santiago046** [comment]
>This is already handled by Auxio, but only if you change Settings -> Content -> Album covers to "Quality" instead of "Fast".

It's not working here (v 3.4.2), even with album covers set to “Quality”.

**Comment by OxygenCobalt** [comment]
@santiago046 Can I have a sample file?

**Comment by santiago046** [comment]
@OxygenCobalt Sure. Where should I safely upload it to you (copyrighted content)?

**Comment by OxygenCobalt** [comment]
Strip out the audio but keep the tags/metadata, put the files in a ZIP, and then upload them here @santiago046

**Comment by santiago046** [comment]
@OxygenCobalt Here's [song.zip](https://github.com/OxygenCobalt/Auxio/files/15380334/song.zip)

**Comment by OxygenCobalt** [comment]
Thanks, will test later @santiago046

**Comment by OxygenCobalt** [comment]
Your sample file works @santiago046. It shows the front cover just fine. What is exactly the problem with the cover again?

**Comment by santiago046** [comment]
@OxygenCobalt
The FLAC file I sent you has 4 picture blocks:
- Type 3: Cover (front)
- Type 4: Cover (back)
- Type 5: Leaflet page
- Type 6: CD label side

Currently, it's showing the latest picture block, which is the [CD label side](https://ia801304.us.archive.org/6/items/mbid-41d276c9-66bd-489b-99e2-c0198026fd25/mbid-41d276c9-66bd-489b-99e2-c0198026fd25-29242477120_thumb500.jpg), instead of the [front cover art](https://ia801304.us.archive.org/6/items/mbid-41d276c9-66bd-489b-99e2-c0198026fd25/mbid-41d276c9-66bd-489b-99e2-c0198026fd25-37025341228_thumb500.jpg).

**Comment by OxygenCobalt** [comment]
That's really weird, the front cover art is always extracted on my end @santiago046. I assume that removing the copyrighted audio ended up causing the metadata to be rewritten and become well-formed. You might just have to send me the original file.

**Comment by santiago046** [comment]
It also happens with the stripped ![one](https://github.com/OxygenCobalt/Auxio/assets/88282401/989797d5-d604-40a2-9ef0-b883b16afbf8)

**Comment by OxygenCobalt** [comment]
Wait, I see. Yeah, I think I can reproduce the bug. Let me look into this @santiago046

**Comment by OxygenCobalt** [comment]
Figured it out: I was still actually defaulting to Android's bugged metadata extractor, even in quality mode. Changing it to use ExoPlayer fixes it, but that comes with more efficiency concerns.
