### ISSUE TITLE
App crashes when using hebrew language

### ISSUE THREAD

**Issue by LDA55** [OxygenCobalt/Auxio#575]
### Describe the Bug/Crash

On a RTL language device, the app crashes at launch. 
Tried to launch it on a separated profile in english language : works perfectly

### Describe the intended behavior

Should launch on RTL device

### What android version do you use?

Android 13

### What device model do you use?

Pixel 7a

### Bug report

.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I need a stack trace to debug this issue @LDA55. Please go to [here](https://developer.android.com/studio/debug/bug-report) for guidance on how to take one.

**Comment by LDA55** [comment]
Hi First, here is the crash report from Android. I did a few tests. The app lauches. But it crashes after scanning folder for files. (Only when in RTL language) In the same profile when I change language to english for example it works fine immediately Thank you for your work !!!```type: crashosVersion: google/lynx/lynx:13/TQ3A.230901.001/2023091800:user/release-keyspackage: org.oxycblt.auxio:35process: org.oxycblt.auxioprocessUptime: 1132 + 224 msinstaller: com.android.packageinstallerandroid.content.res.Resources$NotFoundException: Plural resource ID #0x7f120000 quantity=4 item=other	at android.content.res.ResourcesImpl.getQuantityText(ResourcesImpl.java:317)	at android.content.res.Resources.getQuantityText(Resources.java:527)	at android.content.res.Resources.getQuantityString(Resources.java:603)	at okio.Okio.getPlural(SourceFile:1)	at org.oxycblt.auxio.list.recycler.ArtistViewHolder.bind(Unknown Source:65)	at org.oxycblt.auxio.home.list.SongListFragment$SongAdapter.onBindViewHolder(SourceFile:29)	at org.oxycblt.auxio.list.adapter.SelectionIndicatorAdapter.onBindViewHolder(SourceFile:34)	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(SourceFile:43)	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:1262)	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:6)	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(SourceFile:54)	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(SourceFile:113)	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:54)	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:868)	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(SourceFile:43)	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:79)	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:7)	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(SourceFile:142)	at androidx.recyclerview.widget.RecyclerView$1.run(SourceFile:38)	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)	at android.view.Choreographer.doCallbacks(Choreographer.java:899)	at android.view.Choreographer.doFrame(Choreographer.java:827)	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)	at android.os.Handler.handleCallback(Handler.java:942)	at android.os.Handler.dispatchMessage(Handler.java:99)	at android.os.Looper.loopOnce(Looper.java:201)	at android.os.Looper.loop(Looper.java:288)	at android.app.ActivityThread.main(ActivityThread.java:7940)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)	at com.android.internal.os.ExecInit.main(ExecInit.java:49)	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)```‫ב-18 בספט׳ 2023, בשעה 16:52, ‏‏Alexander Capehart ***@***.***> כתב/ה:‬﻿
I need a stack trace to debug this issue @LDA55. Please go to here for guidance on how to take one.

**Comment by OxygenCobalt** [comment]
Can you specify which RTL language you use normally @LDA55?

**Comment by LDA55** [comment]
Hebrew‫ב-20 בספט׳ 2023, בשעה 6:02, ‏‏Alexander Capehart ***@***.***> כתב/ה:‬﻿
Can you specify which RTL language you use normally @LDA55?

**Comment by OxygenCobalt** [comment]
Okay, I know the the issue now, apparently Weblate just mangled the hebrew translation of one of the strings.

**Comment by illdeletethis** [comment]
have you considered leaving this bug in, and hoping you"ll get an ADL page for that to promote the app?
