### ISSUE TITLE
Crash when adding to playlist from playlist view

### ISSUE THREAD

**Issue by MaxsimLionel** [OxygenCobalt/Auxio#577]
### Describe the Bug/Crash

1. Start playing a playlist
2. Go to the now playing screen and add the current song to a playlist from the ... Menu In the top right hand corner. 
3. The app will crash. The app also crashes when selecting multiple songs in a playlist and adding them to another playlist. 

### Describe the intended behavior

Should not crash, and add the song(s) to the playlist. 

### What android version do you use?

Android 13

### What device model do you use?

Pixel 6 (graphene os)

### Bug report

Sorry cannot provide

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Caused by an unimplemented navigation route. I will fix it when I have time.
