### ISSUE TITLE
Playback state forgotten after a reboot

### ISSUE THREAD

**Issue by Tom4tot** [OxygenCobalt/Auxio#578]
### Describe the Bug/Crash

1. Use Auxio normally
2. Reboot
3. Open Auxio
4. The current song will be a song played from a queue played a long time ago

### Describe the intended behavior

Auxio should remember the last song played, ideally with its timestamp as well.

### What android version do you use?

Android 13

### What device model do you use?

Pixel 6 (Graphene OS)

### Bug report

If you need any log, please let me know, but I think my issue should be fairly easy to reproduce.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is due to a current limitation in how Auxio does not save the playback state after every song change, but once playback has been gracefully stopped by the user. If Auxio ends up being stopped by the system, nothing will happen. I'm tracking a fix in #404.
