### ISSUE TITLE
Do not count albums an artist only appears on

### ISSUE THREAD

**Issue by afontenot** [OxygenCobalt/Auxio#581]
### Describe the Bug/Crash

1. Enable "hide collaborators" - my understanding of this feature is that it shows album artists on the artist page rather than showing all artists tagged on every song
2. Look in the artist panel at an artist with a guest appearance on one song of another album
3. Observe that guest appearances (which show up as "appears in" in the interface) are counted in the *album* count on the artist tab.

### Describe the intended behavior

This is actually a little difficult to specify. Strictly, you could argue that only an album is an album, so e.g. a single or EP would not count as an album. In this case, the text should probably read "5 releases" instead of "5 albums". I think this is overly nit-picky though.

Less nitpicky, if we're categorizing all credits into "album credit" or "not album credit", in hide collaborators mode any release that credits an artist as an *albumartist* should be considered an album, even if that's an EP or single.

However, I can't think of any categorization where it makes sense to count appearances on others' albums as album credits in their own right. To underscore this argument, consider that in "hide collaborators" mode, artists that *only* ever appear or others' albums are *hidden from the artist view entirely!* If this behavior makes sense, then likewise it makes sense not to count appearances as album credits.

If I have an artist with one credited album, and 50 guest appearances on 50 different albums, I'd like Auxio to say "1 album · 63 songs" or what have you, not "51 albums · 63 songs".

By the way, thanks for taking the time to add support for release type to Auxio. For well-tagged music collections, it's really great to be able to see EPs and singles as clearly labeled. I think Auxio is the only app I've ever seen do this correctly, kudos.

### What android version do you use?

Android 12

### What device model do you use?

Samsung Galaxy S10e

### Bug report

Here's a screenshot of the issue. All my files are tagged with MusicBrainz data.

![Screenshot_20230922-134157_Auxio](https://github.com/OxygenCobalt/Auxio/assets/3870410/eafc9a9e-95ed-4518-bffd-699e99cf17fd)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Good catch. I can make this change pretty easily.

**Comment by OxygenCobalt** [comment]
>  This is actually a little difficult to specify. Strictly, you could argue that only an album is an album, so e.g. a single or EP would not count as an album. In this case, the text should probably read "5 releases" instead of "5 albums". I think this is overly nit-picky though.

About this: 'Release' is definitely the correct wording for well-tagged libraries, but I also have to consider libraries with simple tags too, in which those users are more familiar with "albums". So, I just use the more general (but less correct) term so that those users don't get confused.

This is also the same reason why there's just one "Albums" tab that is filled with all EPs, Singles, etc. Having a tab for each release type would be both cluttered and unfriendly to simpler libraries. This *could* be a setting one day though if there was a enough demand and a technically feasible implementation.

**Comment by afontenot** [comment]
Thanks! Appreciate the quick response.

Incidentally, I realize both this and the other report I just filed are both of the nit-picky variety, but Auxio's handling of tags is so excellent that I figured you'd be receptive. Thanks for that - Auxio is just *really really good*, and handles things like release type that are forgotten about in every other player I've tried. Plus the queue handling is basically perfect. I don't know if you do a lot of desktop development, but if you ever made a native (e.g. Qt or GTK) player for Linux I'd be very interested in trying it out and contributing.

**Comment by OxygenCobalt** [comment]
> If you ever made a native (e.g. Qt or GTK) player for Linux I'd be very interested in trying it out and contributing.

Well, if Auxio were to perhaps move to Jetpack Compose one day, I could port it to Compose Multi-platform. This hasn't happened currently, as I want to keep my skills sharp in non-greenfield android development.

Thanks for the kind words.
