### ISSUE TITLE
Option(a checkbox?) to exclude subdirectories of the selected folder

### ISSUE THREAD

**Issue by mexicancartel** [OxygenCobalt/Auxio#583]
### Description

I want a feature to exclude all sub directories when selecting a music folder. I would also be happy if i can just :
 - Include folder /sdcard/Music, but exclude /sdcard/Music/SomeAppName, and some other specified directories
 - Exclude a folder, say /sdcard/Download, but still include /sdcard/Download/SomeSpeceficSongs

Since this might be requiring bigger effort for you, i suggest adding a checkbox to exclude all subdirectories of the selected folder

### Problem solved

Its annoying when there are non-song music files in the android's /sdcard/Music, resting in subdirectories.  but i just want the content of that single folder and not any songs from /sdcard/Music/NewPipe or similiar app music folders.

### Other implementations

I don't know many music players to show such implementations. Only other app I use was vlc which is not even a music player. 

### Benefit

More flexibility in picking music from folders. Helps to view the "real" songs unmixed from other audio files. Currently my all songs, albums, artist and genre sections are useless since other audio files interfere everywhere. Playlist feature is the one way i escape but its also mesay when adding new songs

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is not possible with the current music loader, and is generally significantly more complex to implement and use. I'd instead recommend moving all of the files you want to use into a folder, and then using the 'Include' mode with that folder selected.
