### ISSUE TITLE
Remove/hide/shorten Artist list in Genre page

### ISSUE THREAD

**Issue by Eclectiq** [OxygenCobalt/Auxio#584]
### Description

Due to the lack of folders, I have started to use the Genre tag to categorize my music the way I categorize them into folders, based on different languages and style. However, songs inside a genre are buried deep down below a huge list of artists. It is an inconvenience whenever you want to explore songs inside a genre, which is how I always listen to music based on a particular folder at a time.

Different ways to handle this issue:
1. Remove Artists list from Genre
2. Provide a toggle in settings to hide Artists list
3. Shorten number of artists (maybe 3) with a drop down to expand the full list

### Other implementations

BlackPlayer (EX) has separate tabs for tracks, albums and artists inside a genre. Others list songs directly.

### Benefit

Provides an alternative/convenient approach to implement folder based categorization with ease of exploring songs list in a genre.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This would make the genre view inconsistent with the rest of the app. If I were to use this pattern elsewhere in the app, it would likely be technically complicated and/or highly confusing to most users. I would recommend using playlists to organize tracks arbitrarily like that anyway. Sorry.
