### ISSUE TITLE
how does auxio handle multiple artists

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#586]
trying to tag edit but auxio wont recognise ; or / delimiters

**Comment by OxygenCobalt** [comment]
You need to go to Settings -> Content -> Multi-value separators and enable them. Auxio does not natively enable separators since they risk mangling real artist names, like "Black Country, New Road" becoming two artists named "Black Country" and "New Road".

**Comment by RustoMCSpit** [comment]
> You need to go to Settings -> Content -> Multi-value separators and select '/' and ';'. Auxio does not natively enable separators since they risk mangling real artist names, like "Black Country, New Road" becoming two artists named "Black Country" and "New Road".

is id3 foss, this sounds like a dumb bottleneck. whyvnot just be able to add multiple artist tags rather than stuffing them into one

**Comment by RustoMCSpit** [comment]
could you add a more obscure separator like Π

**Comment by RustoMCSpit** [comment]
> You need to go to Settings -> Content -> Multi-value separators and select '/' and ';'. Auxio does not natively enable separators since they risk mangling real artist names, like "Black Country, New Road" becoming two artists named "Black Country" and "New Road".

does auxio support vorbis comments?

**Comment by OxygenCobalt** [comment]
> is id3 foss, this sounds like a dumb bottleneck. whyvnot just be able to add multiple artist tags rather than stuffing them into one

Kinda? Like, it has a specification. There are FOSS implementations. The MP3 patent is also expired. Yes, you can use multiple. It's supported in taggers like `kid3` if you use the `|` character to separate artists in an ID3v2.4 tag. Auxio will support these by default.

> could you add a more obscure separator like Π

No, there are separators like `;` that are uncommon but still not too obscure.

> does auxio support vorbis comments?

Yes. You can make multiple artist values there by adding additional `ARTIST` comments.

**Comment by RustoMCSpit** [comment]
> The MP3 patent

what does that have to do with it sorry

**Comment by RustoMCSpit** [comment]
> Yes, you can use multiple artist values too

no i mean having separate fields to input artists rather than using a separator, makes more logical sense. is there any way to alter the id3 specification standard to incorporate this?

**Comment by RustoMCSpit** [comment]
> an ID3v2.4

does auxio detect if it's id3v2.3 or 2.4, if so can it display that info somewhere

**Comment by OxygenCobalt** [comment]
> what does that have to do with it sorry i dont understand

I was guessing at what you were asking whether ID3 is FOSS. It's not really relevant.

> no i mean having separate fields to input artists rather than using a separator, makes more logical sense. is there any way to alter the id3 specification standard to incorporate this?

> like this but id3

No, the standard is to use a special separator for multiple values.  kid3 visually represents the  as `|`, but in practice the separator is called a "null terminator" and it shouldn't collide with any artist name. As a result, Auxio will **recognize it by default**. You don't need to enable any multi-value separators if you use it. No tagger I know of even supports outputting more than one artist value.

> does auxio detect if it's id3v2.3 or 2.4, if so can it display that info somewhere

No, it's not possible to do that in the app. That information is better shown in your tagger of choice.

**Comment by RustoMCSpit** [comment]
> `|`, but in practice the separator is called a "null terminator" and it shouldn't collide with any artist name. As a result, Auxio will **recognize it by default**

'|' wait so if i copy paste this into kid3 it'll separate and it'll work without configurarion in auxio?

**Comment by RustoMCSpit** [comment]
> No tagger I know of even supports outputting more than one artist value.

for id3 or for vorbis comments too? also isnt that dumb, shouldnt they support that? this whole separator business makes jackshit sense when you consider that an artist cpuld have that symbol in their name. i dont see any benefit to this approach

**Comment by RustoMCSpit** [comment]
> I was guessing at what you were asking whether ID3 is FOSS. It's not really relevant.

ohh i just thought yoy meant mp3 and id3 had some special relarionship, i use opus for my files and got worried. only learnt about vorbis comments todat

**Comment by OxygenCobalt** [comment]
> '|' wait so if i copy paste this into kid3 it'll separate and it'll work without configurarion in auxio?

Yeah, as long as the tag is set to ID3v2.4 (You can see it at the top where it says "Tag 2")

> for id3 or for vorbis comments too? also isnt that dumb, shouldnt they support that? this whole separator business makes jackshit sense when you consider that an artist cpuld have that symbol in their name. i dont see any benefit to this approach. dyk why this is the standard and how would the standard be amended?

I was implicitly saying that taggers don't output multiple artist values with ID3 tags. It's allowed with vorbis. Sorry.

**Comment by RustoMCSpit** [comment]
> I was implicitly saying that taggers don't output multiple artist values with ID3v2 tags. It's allowed with vorbis. Sorry.

but why??

**Comment by RustoMCSpit** [comment]
> Yeah, as long as the tag is set to ID3v2.4 (You can see it at the top where it says "Tag 2")

i'll look into it, thanks

**Comment by OxygenCobalt** [comment]
> but why??

Because they were made by different people with different design choices.

**Comment by RustoMCSpit** [comment]
> > but why??
> 
> Because ID3 and Vorbis were made by different people with different design choices.

can we amend this

**Comment by OxygenCobalt** [comment]
> can we amend this

No. These formats have both existed for 20 years and are extremely unlikely to change in any capacity. Just pick vorbis and move on if you really want to avoid the separator problem.

**Comment by RustoMCSpit** [comment]
> > can we amend this
> 
> No. These formats have both existed for 20 years and are extremely unlikely to change in any capacity. Just pick vorbis and move on if you really want to avoid the separator problem.

is vorbis exclusive to .opus btw

**Comment by OxygenCobalt** [comment]
No, you can use it for vorbis and FLAC too @RustoMCSpit. Albeit OPUS is recommended now since it's smaller than OGG while providing similar quality.

**Comment by RustoMCSpit** [comment]
> No, you can use it for vorbis and FLAC too @RustoMCSpit. Albeit OPUS is recommended now since it's smaller than OGG while providing similar quality.

opus over flac or just ogg, flac is lossless and opus lossy right?
