### ISSUE TITLE
Compilation Albums With Album Artist Tag "Various Artists" Show No Songs In Artist Tab

### ISSUE THREAD

**Issue by mitchwalton** [OxygenCobalt/Auxio#588]
### Describe the Bug/Crash

1. Go to album artist "various artists" with hide collaborators on or off and it shows no songs but reads the albums. The play button for "various artists" is greyed out. I have to go to each album to view and play songs. 

### Describe the intended behavior

When you go to "various artists" album artist it should show all albums as it does but also give me the total amount of songs with a working play button to play them all. My assumption is that the play button for each artist is set to only read and play artist / songs with that tag as it should but when I go to a artist that's an album artist it should read all album artist / songs with that album artist tag. This has caused problems with studio albums that aren't considered compilation albums with the "various artist" album artist tag. For example, Maroon 5 album artist for me has 26 songs but only reads 25 because one album called V (Deluxe Edition) has one extra track with the artist tag "Adam Levine." With hide collaborators on or off I would assume it should show all songs by that specific artist or album artist. The play button is only reading artists not album artists and the songs that go with it. 

### What android version do you use?

Android 10

### What device model do you use?

Samsung Galaxy S9+

### Bug report

None.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is working as intended. Album artists do not link to an album's songs since that would mangle the artist credits of certain albums. It's also not really correct to describe an album with "Various Artists" when only one song has a collaborator.

**Comment by mitchwalton** [comment]
Ok. However, when an album is not released by a single artist and is a compilation album the proper tagging for album artist would be Various Artists. I'm anal retentive about tagging. This has been done by big digital stores. I understand that songs by album artists do not show under a artist in that tab being a collaborator (if the tab shows artists and album artists it should obviously show songs by that album artist and counted). Clearly the tab is taking each name as an artist not an album artist. However because of "hide collaborators" being turned on or off I take it as turning the tab into an artist / album artist tab or just an album artist tab. If I hide collaborators why isn't it showing all songs counted under that album artist when I turned the tab into an album artist tab only? When it's off turning it into an artist / album artist tab you'd think it show all songs by that album artist too. I understand it's counting all artists in the tab as an artist not an album artist yet it's showing artists and album artists. It makes no since to show album artists under the tab with the proper albums but not count the songs under that album artist:)

**Comment by OxygenCobalt** [comment]
Because "Hide collaborators" isn't changing Auxio's interpretation of music at all. Auxio has no distinction between artist and album artist. All that setting is doing is just hiding the artists that aren't linked to any album.

**Comment by mitchwalton** [comment]
Understood. However, if the tab only is an artist tab why would it be showing names in my collection that are album artists only?

**Comment by OxygenCobalt** [comment]
Auxio doesn't really know what album artists are internally. Early during the music loading process it unifies both artist and album artist tags into a single "Artist" entry.

**Comment by mitchwalton** [comment]
Ok, that understood. Everyone is different. Personally the unification for me is to cluttery. However, that is a personal design decision as I would have artist show up only. Either way great work and thanks for the answer!
