### ISSUE TITLE
Quick refresh option

### ISSUE THREAD

**Issue by anonymousaga** [OxygenCobalt/Auxio#589]
### Description

Could you add a refresh button on the 3 button menu? Thanks

### Problem solved

I need to refresh my library often since I often add music.

### Other implementations

The app Symphony (Foss android music player) has a quick rescan option on the 3 button menu. 

### Benefit

Refreshing the library is one of the most common tasks, so to have it in 2 clicks would be helpful for everyone.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
That honestly sounds extremely clunky and easy to accidentally trigger. If your music library changes that frequently I'd recommend enabling Automatic reloading in Settings -> Content.

**Comment by anonymousaga** [comment]
Ah, I didn't realize there was auto refresh. Thanks!
