### ISSUE TITLE
Random list does not include all songs

### ISSUE THREAD

**Issue by jcv99** [OxygenCobalt/Auxio#595]
### Describe the Bug/Crash

1.- Click the randomize button.
2.- Start listening songs.
3.- At more or less 30 songs, it repeats the same list.

### Describe the intended behavior

Should randomize all the songs I have, now 1003. 

### What android version do you use?

Android 13

### What device model do you use?

Samsung s21 Ultra 5g

### Bug report

No bug report

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I need more information. Can you provide a screenshot? @jcv99

**Comment by jcv99** [comment]
When trying to recreate manually (skipping songs with the button) I can't do it. When it happens again I'll try to make video/screenshot.

**Comment by OxygenCobalt** [comment]
Alright. I'm personally under the belief that this was a fluke out of my control, so I'm going to be closing this until there's real proof for it.
