### ISSUE TITLE
Is it possible to remove empty space?Is it possible to remove empty space?

### ISSUE THREAD

**Issue by person10301** [OxygenCobalt/Auxio#597]
### Description

There's an empty space at the bottom

### Other implementations

Everything else is fine 

### Benefit

It just spoils the view

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by person10301** [comment]
![Screenshot_2023-10-06-02-20-05-21_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/OxygenCobalt/Auxio/assets/105549221/b4ab5706-83b7-49fa-85d6-f27a421277ab)
![Screenshot_2023-10-06-02-20-07-54_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/OxygenCobalt/Auxio/assets/105549221/34d5f1ee-549b-40bb-af92-bae58250115a)

**Comment by OxygenCobalt** [comment]
The space is there so that Auxio's UI does not overlap with the navigation bar. However, you don't seem to have one, likely because you disabled it. The issue stems from how your phone is still telling Auxio to add this space for a non-existent navigation bar. There's nothing I can do about this on my end.

**Comment by chocmake** [comment]
> The issue stems from how your phone is still telling Auxio to add this space for a non-existent navigation bar.

Interesting. I'd also noticed the margin though Auxio seems the only one I've found with it, while all others shift their UI downward when the OS option is toggled (various apps even flush with the bottom of the screen).

**Comment by OxygenCobalt** [comment]
It's likely because they are not edge-to-edge, or faking it with a colored navigation bar @chocmake. I can do neither.
