### ISSUE TITLE
Widget/notification actions don't work on Android 14

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#598]
Experiencing this on my device. No idea why it's occurring.

**Comment by RustoMCSpit** [comment]
can we have a pre-release with this

**Comment by OxygenCobalt** [comment]
I don't have the free time to prepare a release right now. Maybe I'll have time in like a week or two. @RustoMCSpit

**Comment by RustoMCSpit** [comment]
> I don't have the free time to prepare a release right now. Maybe I'll have time in like a week or two. @RustoMCSpit

out of curiousity how long does that take

**Comment by OxygenCobalt** [comment]
Probably around an hour or two so I can thoroughly check that there aren't any half-broken in-development things in the release. I have to revert a changeset this time, which makes it take a little longer.

**Comment by RustoMCSpit** [comment]
thanks for everythinf
