### ISSUE TITLE
WebDAV Purpose

### ISSUE THREAD

**Issue by Mickeywaugh** [OxygenCobalt/Auxio#602]
### Description

Hope to be able to increase support for the WebDAV protocol musics(https will be better).

### Other implementations

Auxio Player may the first one.

### Benefit

For people with NAS servers at home, playing the same set of music on multiple supported devices will be a requirement.
That way, he doesn't have to distribute local musics to all his devices.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio is not planned to be a music streaming client at this time. The technical undertaking required is far too immense. Sorry.
