### ISSUE TITLE
longer song titles shouldnt start scrolling until after a second has passed

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#604]
### Description

title self-explanatory

### Other implementations

.

### Benefit

aesthetics

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Not possible with android's text scrolling system. It always starts without delay.
