### ISSUE TITLE
No music found on a Inkpalm 5 (Allwiner EPD105)

### ISSUE THREAD

**Issue by csdvrx** [OxygenCobalt/Auxio#605]
### Describe the Bug/Crash

On a Inkpalm 5 (an eink "reader" running Android 8) no music is found, whether the mode is inclusion or exclusion of folders.

I first tried with inclusion + the /sdcard/Music folder (which only contains 2 FLAC files for tests), then with exclusion and no folder, at which point it gave an error : Music Loading failed (Illegal State exception: MediaStore discovery is deadlocked)

My device works offline, so I can't report in any better way.

Other players like PowerAmp don't have the problem. 

Permissions are granted, as checked in Settings.

There is no .nomedia file, music was transferred with adb and is working with other players.

Rebooting fixed the problem.

This happens with the default apk found on fdroid.

### Describe the intended behavior

Should find the files without a reboot, or at least suggest instead of just saying "No music found", since 2 FLAC files were present in /sdcard/Music

### What android version do you use?

Android 8 (Oreo)

### What device model do you use?

Inkpalm 5

### Bug report

(could not copy paste)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Largely unfixable MediaStore-related issue. Sometimes it just refuses to locate audio files unless you reboot the entire device. Several other factors can cause this kind of error (up to deliberate OEM-specific breakage), so I can't really just suggest rebooting the device.
