### ISSUE TITLE
Manually rescanning music does not cancel prior rescans

### ISSUE THREAD

**Issue by Cwpute** [OxygenCobalt/Auxio#606]
### Describe the Bug/Crash

Thinking the app's cache was not being reset, i tapped thrice on the Cache Reset option in the settings, which caused the UI to be a bit confused afterwards… as the app was seemingly performing three Cache Resets at the same time.

### Describe the intended behavior

One should not be able to start three Cache Reset actions at the same time.
The button in the Options should be greyed-out and dispaly a toast-message or something elese to communicate it is performing a Cache Reset, as to not let the user trigger it several times.

### What android version do you use?

Android 11

### What device model do you use?

Nokia TA-1157

### Bug report

https://github.com/OxygenCobalt/Auxio/assets/80604512/bf661e5a-6b05-4cc4-bfd4-a057370968c4

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Welp, seems like at some point the code that was specifically preventing that from occurring just...broke. I'll look into it.

**Comment by foss-** [comment]
Ran into a similar situation where re-scans got stuck. This happened several times in the past weeks when initiating a manual re-scan and also when the application was doing a re-scan on startup.

**Comment by OxygenCobalt** [comment]
That's a deadlock, and largely unrelated. Can you file a separate issue @foss-?
