### ISSUE TITLE
Music loading hangs at random

### ISSUE THREAD

**Issue by foss-** [OxygenCobalt/Auxio#609]
### Describe the Bug/Crash

Unsure how to trigger the problem, but it is somewhat new as in I had not seen it ~1-2 months ago.

This happens when opening Auxio, only to find it stuck already on a re-scan `Loading your music library... (n/n)`. It does not get stuck at the same track.

The way out is to open App Info and `Force stop` Auxio. Re-open and Loading will go through as expected.

Maybe related: https://github.com/OxygenCobalt/Auxio/issues/608 https://github.com/OxygenCobalt/Auxio/issues/607

### Describe the intended behavior

Don't get stuck on loading library in background.

### What android version do you use?

Android 13

### What device model do you use?

Xiaomi Lisa
Android 13.1 (ArrowOS)
Auxio 3.2.0

### Bug report

Logcat filtered for auxio (1 year): https://bin.disroot.org/?7dd9d702ecde8883#3F9SyBCGebKkaHYv936syM4HwNLg4p3w4tVXjEKZoTgV

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Hopefully I can debug where exactly the deadlock is with #607, but otherwise you will need to hold on a little. I won't have much time to work on this.

**Comment by foss-** [comment]
This is happening at a different track and seemingly random. Often when I open Auxio after a while I am greeted with the stuck loading screen requiring a force stop.

Since Tibbi sold SimpleApps to an Adware company, are you aware of another open music app to fall back to until this is addressed?

**Comment by OxygenCobalt** [comment]
Hey, I've quickly added timeouts to the music loader now that I have time @foss-. Care to try this APK and report every stack trace you encounter? I hope that it will indicate exactly which routine it's deadlocking at.

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13710075/Auxio_Canary.zip)

Sorry, I don't know of any fallbacks of similar quality at this moment. There is symphony, which has at least a modern UI.

**Comment by foss-** [comment]
Installed the debug build. The initial scan always goes through as do re-scans. Auxio scan seems to get stuck when the app is sitting in the background and (maybe?) file changes happen and a background scan is triggered. So frequently when then opening Auxio it greets me with that stuck loading bar which is not moving. I now have to wait for that to happen and will take a look at the logcat then and hope something useful is in there.

PS: Fell back on [RetroMusicPlayer](https://github.com/RetroMusicPlayer/RetroMusicPlayer) which however has not seen active development for over 7 months. [Symphony](https://github.com/zyrouge/symphony) looks nice, thanks for the hint.

**Comment by foss-** [comment]
It kind of does, but before that can be done, the app has to be force quit. After that a re-scan usually goes through. I have yet to see the hang with the debug build but that was installed 11 hours ago so will report back how things go with some more testing.

**Comment by OxygenCobalt** [comment]
I mean, have you ever tried rescanning without force quitting first @foss-?

**Comment by OxygenCobalt** [comment]
The issue I see is that if the loader is being prematurely killed, then it's leaving an incomplete loading state of some sort. It's not that loading is being *stuck*, it's the app showing an old loading state that will never be updated.

**Comment by foss-** [comment]
So been using Auxio for a few days and this problem has not reoccurred. Since I had uninstalled Auxio I am now wondering if something got corrupted locally which got fixed by deleting and re-installing Auxio. Since I appear to be unable to reproduce and the problem was not seen for the past days while previously it happend fairly frequently, closing this report.

**Comment by OxygenCobalt** [comment]
> So been using Auxio for a few days and this problem has not reoccurred. Since I had uninstalled Auxio I am now wondering if something got corrupted locally which got fixed by deleting and re-installing Auxio. Since I appear to be unable to reproduce and the problem was not seen for the past days while previously it happend fairly frequently, closing this report.

Weird. This might have wiped whatever weird state was there before that was causing your system to go haywire with killing Auxio's services.
