### ISSUE TITLE
add 'look and feel' option to make songs displayed as big as albums

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#611]
### Description

albums are given a larger box resulting in a less cramped look

### Other implementations

.

### Benefit

aesthetics

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I don't add list item styles for the same reason I don't add a grid view. They set a precedent that I can add a UI style when requested, which only results in bloated and unusable apps as I now have to maintain several components instead of perfecting one. I mean, just look at Retro. Sorry.
