### ISSUE TITLE
Music loading crashes on duplicate artists with different casing

### ISSUE THREAD

**Issue by cebzab** [OxygenCobalt/Auxio#614]
### Describe the Bug/Crash

When the app starts it does the regular scanning that it always does, but since the latest version came out after the loading bar finishes loading there's a prompt saying "Music Loading Failed".

### Describe the intended behavior

It should not fail and it should display music after the loading process.

### What android version do you use?

Android 13

### What device model do you use?

Pixel 4a GrapheneOs

### Bug report

java.lang.IllegalStateException: Malformed song Sohn - Lights.flac: Artist grouping mismatch
	at org.oxycblt.auxio.music.device.DeviceLibraryImpl.<init>(SourceFile:258)
	at okhttp3.ConnectionPool.create(SourceFile:1042)
	at org.oxycblt.auxio.music.device.DeviceLibraryFactoryImpl$create$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Can you please provide the file that's causing the error? As in the error message, it should be `Sohn - Lights.flac`. Feel free to strip all the audio out if it's copyrighted, all I need is the tags. @cebzab

**Comment by OxygenCobalt** [comment]
Preferably do this ASAP. I've been trying to identify a music loader bug that has been appearing on and off, and this might be it.

**Comment by cebzab** [comment]
Sorry, it was night time where I'm from.
Here you go:
https://drive.google.com/file/d/1iqHKvH3jdDxXPrZBi3EheFPgwdpxbr_M/view?usp=sharing

**Comment by OxygenCobalt** [comment]
There it is:

![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/957a7aa6-99e1-485b-9ccd-f97c28717858)

You have two different artists with different casing. Auxio groups these one artist case-insensitively, but the original case-sensitive artist data is still there, causing a mismatch.

I'll get to fixing this. Thanks for reporting it.
