### ISSUE TITLE
[Bug] Album Titles and Artwork/Covers do not take Artists into account.

### ISSUE THREAD

**Issue by ORIOLESFan02** [OxygenCobalt/Auxio#617]
### Describe the Bug/Crash

1. Import Music Files (no folders, the raw music files) into the Android Music Folder (I did this via MTP and my playlist on my computer)
2. Have at least one Album with Cover Art on it with a name that other albums from other artists may have as well. (e.g: Greatest Hits [Multiple Artists, but only one of them have Album Art. For me, it's the band Heart with the Album Art, while the other bands with 'Greatest Hits' Albums don't have cover art at all.])
3. Open Auxio and see that other Artists with the same Album name have the Album Art [e.g: Heart's 'Greatest Hits' and Journey's 'Greatest Hits' have the same Album Cover/Artwork, when only the Heart one should]
- Just a note: I'm not the best at explaining things, so if you need anything else, please just respond below. Thank you :)

### Describe the intended behavior

Only the one Artist with the Album Art should have the Album Art, not the ones without it. [e.g: Heart's 'Greatest Hits' should be the only one with the Artwork/Cover, not the ones from other artists with the same Album name]

### What android version do you use?

Android 13

### What device model do you use?

Pixel 7 Pro (Android 14 [There is no option for Android 14 on the selector])

### Bug report

Not possible.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by ORIOLESFan02** [comment]
I'd just like to say, this has been one of the best music apps I've used in a very long time and this bug is something that I can live with, but it's also something that should be solved in the near future. Also, if you're coming from a different app (I came from YT music), the music is usually in folders, and the bug doesn't apply there, but if you just have it as a list (no folder), the bug applies.

**Comment by ORIOLESFan02** [comment]
Possibly related to #342, but not entirely sure (I was confused on 342, so it could be related, but it didn't make sense to me).

**Comment by OxygenCobalt** [comment]
Can you send screenshots?

**Comment by ORIOLESFan02** [comment]
> Can you send screenshots?

Honestly, I wish I took screenshots when it happened. I revered back to my previous state after it happened, and now when I tried to do it again, it's not doing it. That was very odd, and I assumed it had to do something with your application. I was wrong. I'm going to keep this open just so you can read it, and then I'll close it. I don't understand what just happened.

**Comment by OxygenCobalt** [comment]
I think I could know why. Auxio by default obtains cover art by the android system by default, and that's done by album usually. In your case, the system probably naively grouped all of the 'Greatest Hits' songs into one album, and then picked a random piece of cover art for it. Auxio on it's end groups by album name and artist, so it will display separate albums, but with the wrong covers. If this is true, it's definitely a #342 issue. You can make Auxio use a slower method of extracting covers that is more correct by going to Settings -> Content and setting "Album covers" to "Quality", if you're okay with Auxio using more memory. I'll be closing this as an effective duplicate.
