### ISSUE TITLE
Gadgetbridge media control is not working

### ISSUE THREAD

**Issue by Golbinex** [OxygenCobalt/Auxio#62]
#### Describe the bug/crash:

Gadgetbridge is a FOSS app for controlling smart watches and bands. It also supports controlling media playback from watches. Most players are supported and play/pause, forward/rewind actions on the gadget are working. However on Auxio I can only see the name of played track and change volume. Auxio is not visible in Gadgetbridge music player list.
#### Steps To Reproduce the bug/crash:

1. Play a track on Auxio
2. Go to music section on smart watch/band
3. Try to pause track
#### Screenshots:

![Screenshot_20220104-085912_Gadgetbridge_1](https://user-images.githubusercontent.com/62813600/148028305-f795fcbc-6da5-4a08-8867-fa16d886b333.png)

#### Phone Information:

Android 12
#### Due Diligence:

- [ x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Do you use an Android Wear smartwatch or an external smartwatch, like pebble? If it's the former, then I haven't added Android Wear support yet. If it's the latter, then theres something wrong with Auxio's MediaSession implementation again.

**Comment by Golbinex** [comment]
I use Mi Band 6, so an external smart band.

**Comment by OxygenCobalt** [comment]
Probably a MediaSession issue again then, my implementation is god-awful. I'll lump it in with #52 and address it eventually.

**Comment by OxygenCobalt** [comment]
I actually think I figured out some of it. Gadgetbridge queries for `BroadcastReciever` instances in the app manifest that handle the `Intent.ACTION_MEDIA_BUTTON` intent. Auxio does not do this, as it relies on the media session to intercept media button events instead. 

I doubt I can fix this issue on my end, as my only options are to reintroducing #20 or having every media action call twice. I would recommend reporting this as an issue to the Gadgetbridge developers. Their service should be able to handle apps that only expose a `MediaSession` instead of using an implementation straight out of 2011.

**Comment by OxygenCobalt** [comment]
@Golbinex @foldfree

I found a way around this issue. The media library does actually expose it's `BroadcastReceiver` under `androidx.media.session.MediaButtonReceiver`. So, I believe it's possible to hack around this issue by simply exposing that library class in my manifest.

Can you guys try this debug APK? [Rename the extension] I don't have a smartwatch, so I'm only able to confirm that GadgetBridge detects the media button intent and not if it can use it.

[Auxio_GadgetBridge.zip](https://github.com/OxygenCobalt/Auxio/files/7921085/Auxio_GadgetBridge.zip)

**Comment by foldfree** [comment]
I tried multiple times and the app crash when i press pause.
I shared the log below 

https://pastebin.com/7N4FZ6wZ

PS: I'm not sure if thoses logs are relevant, let me know if I need to do something else.

**Comment by OxygenCobalt** [comment]
@foldfree I think I may have gotten the intent structure wrong. Try this APK?

[Auxio_GadgetBridge2.zip](https://github.com/OxygenCobalt/Auxio/files/7921208/Auxio_GadgetBridge2.zip)

**Comment by foldfree** [comment]
> @foldfree I think I may have gotten the intent structure wrong. Try this APK?
> 
> [Auxio_GadgetBridge2.zip](https://github.com/OxygenCobalt/Auxio/files/7921208/Auxio_GadgetBridge2.zip)

Thanks, it works perfect, tried all the buttons.

**Comment by OxygenCobalt** [comment]
Fantastic. From what I've seen also, this also enables someone to start playback with their headset from any point as long as Auxio is open. I'm going to try to unify this with the other "system event" `BroadcastReciever` and then close this issue with a final debug APK.

**Comment by foldfree** [comment]
Media control are not responsive with the latest release (2.3.0)
I checked back with 2.2.2 and it worked so something broke it after that release.

**Comment by OxygenCobalt** [comment]
If you want, heres a 2.3.0* build with the fix in. I'm only doing this since this fix will likely arrive in a 2.4.0 (which could be a ways away with the changes I'm working on)

[Auxio_2.3.0_GadgetBridgeFix.zip](https://github.com/OxygenCobalt/Auxio/files/8819125/Auxio_2.3.0_GadgetBridgeFix.zip)
