### ISSUE TITLE
Don't restart playing a whole album after playback stopped

### ISSUE THREAD

**Issue by Porkepix** [OxygenCobalt/Auxio#622]
### Describe the Bug/Crash

In the situation where a whole album playback was skipped due to an error such as https://github.com/OxygenCobalt/Auxio/issues/619 after the last track, playback stops.
However, it seems like after it completely stops, playback starts playing the whole album again after a couple of dozens of seconds.

### Describe the intended behavior

Once album have finished to play, even if it skips everything, it shouldn't restart it completely, especially when instead of doing so immediately, it does after being stopped for a couple dozens of seconds

### What android version do you use?

Android 8 (Oreo)

### What device model do you use?

Xperia XZ

### Bug report

According to https://github.com/OxygenCobalt/Auxio/issues/619#issuecomment-1822052689 it should be fixed by https://github.com/OxygenCobalt/Auxio/issues/621  (because yeah, if it stops on an error it shouldn't try anything new); I do think however there's some background process acting to do this that *maybe* shouldn't exist.
I even thought that could happen with the playback of an album without issue, but after trying that it seems like it's not the case.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is a natural consequence of #621 and the way that ExoPlayer "prepares" to play something by reading the file and then putting the first pieces of audio data into the renderer, regardless of if it is being played or paused. The FLAC problem stems from such.

**Comment by OxygenCobalt** [comment]
> Yep, but is it supposed to start preparing something again almost one minute after it reached the end of the album it was playing? That still seems curious to me, but I got no idea of how does it work internally.

It's inconsistent. Lot's of things can trigger ExoPlayer to prepare playback.
