### ISSUE TITLE
Playback stops if left in the background for ~2 minutes

### ISSUE THREAD

**Issue by teamspoad** [OxygenCobalt/Auxio#625]
### Describe the Bug/Crash

When playing (bluetooth speaker & others) it stops if phone not used in ~2 minutes.

### Describe the intended behavior

Should play in headphone mode as most other audio apps, such as newpipe, youtube, spotify, etc.

### What android version do you use?

Android 12

### What device model do you use?

Samsung S20+

### Bug report

Na

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Please add a bug report. This is impossible to debug otherwise. If I were to guess, Samsung is deliberately killing the app in the background since it's quite overzealous with such.

**Comment by OxygenCobalt** [comment]
Please add a bug report. This is impossible to debug otherwise. If I were to guess, Samsung is deliberately killing the app in the background since it's quite overzealous with such. @teamspoad

**Comment by OxygenCobalt** [comment]
If you do not know how to create a bug report, please follow [this link](https://developer.android.com/studio/debug/bug-report) @teamspoad.

**Comment by midtsveen** [comment]
Might be related to App battery usage, if set to restricted it will indeed stop playback.

**Comment by OxygenCobalt** [comment]
Given that it seems to be reproducible if you restrict the app's battery use, I'm going to forward you to https://dontkillmyapp.com/. There's nothing I can really do about this on my end.

**Comment by OxygenCobalt** [comment]
https://dontkillmyapp.com/samsung @teamspoad
