### ISSUE TITLE
OneDrive & Drive libraries

### ISSUE THREAD

**Issue by teamspoad** [OxygenCobalt/Auxio#626]
### Description

I have my music in the cloud.  Would love to link that library.

### Problem solved

No

### Other implementations

CloudPlayer is the only decent example, but it lacks status info on whats been loaded vs. What needs to load as far as database on app side .  aka, you get some songs showing up, but never know if the others are going to show up, even on refresh database button.

### Benefit

By allowing large backup cloud libraries

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
OneDrive and Drive are non-free services that I will not connect to out of principle. Navidrome/Subsonic are more palatable, but Auxio really isn't designed for cloud playback at all right now, and I have no plans for such. Sorry.
