### ISSUE TITLE
Add an option to sort Artists by "ALBUM ARTIST" instead of "Artist"

### ISSUE THREAD

**Issue by Tom4tot** [OxygenCobalt/Auxio#634]
### Description

When I browser my music, I'm personally used to look for album artist ("ALBUM ARTIST" tag, or more rarely "ALBUMARTIST") rather than for artist.
Typically, in some genres, I have compilation albums of tens or even hundreds of songs, which equal to almost the same number of artists. It makes my library on Auxio very messy, and it would look much clearer if there was only one artist shown for one compilation (the album artist).

Would it be possible to add an option to chose to sort by ALBUM ARTIST? Or if you think it would become inaccurate, add an "album artist" tab and be able to choose album artist over artist when opening genres?

Thank you in advance for your answer!

### Other implementations

Usually, other players offer the option.

### Benefit

Make the player slightly more flexible, potentially better for some users, depending on how they tag and use their library.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio's music model is deliberately unaware of album artist tags. There's only artists that are derived from both artist and album artist tags, so sorting or associating by album artists alone is not possible. This is intentional, as I have always disliked the disjoint artist/album artist separation of other music players. Sorry.

**Comment by Lord-Valen** [comment]
Just a note: Hiding collaborators seems like the best solution for your use case while remaining within Auxio's model.
