### ISSUE TITLE
Incorrect album art cover

### ISSUE THREAD

**Issue by ggjjjii** [OxygenCobalt/Auxio#640]
### Describe the Bug/Crash

When having multiple album art inside of a folder such as 'cover.png' and 'back.png' the former is being displayed over the latter

### Describe the intended behavior

the album cover should be preferred 

### What android version do you use?

Android 14

### What device model do you use?

Pixel 8 Pro

### Bug report

No

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
The android media database cannot handle multiple cover arts in one folder and simply picks one. There's nothing I can do about this, and I have no in-app support for folder-based cover art just yet.
