### ISSUE TITLE
Download the sample file below Auxio uses the wrong cover art

### ISSUE THREAD

**Issue by polyester2023** [OxygenCobalt/Auxio#647]
### Describe the Bug/Crash

Download the sample file below
Auxio Showing Cover Art from Different Album
[Ed.Sheeran.zip](https://github.com/OxygenCobalt/Auxio/files/13734847/Ed.Sheeran.zip)

![292052603-12f7ddcd-8ab4-429f-9adc-d227f045daad](https://github.com/OxygenCobalt/Auxio/assets/154487331/c0402460-f1f3-4a85-927a-f7479ade1d48)

### Describe the intended behavior

It should use the correct cover art based on the folder.

### What android version do you use?

Android 13

### What device model do you use?

Xiaomi 12

### Bug report

-

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio does not natively support folder-based cover art. It instead inadvertently relied on the broken functionality provided on android. I would highly recommend using embedded cover art until I can implement this manually with #104.
