### ISSUE TITLE
Auxio Shows the Wrong Artists Credit

### ISSUE THREAD

**Issue by polyester2023** [OxygenCobalt/Auxio#648]
### Describe the Bug/Crash

1. Download the sample below
2. Auxio shows the wrong artist credit even though every album/single all have different artists, only one artist is the same
![292053516-f6719178-1d52-4d2d-b586-f427f38b0219](https://github.com/OxygenCobalt/Auxio/assets/154487331/45fc52ea-39ab-4699-b1d2-16d9698b51b5)

### Describe the intended behavior

Auxio should show the correct artists credit according to the tag

### What android version do you use?

Android 13

### What device model do you use?

Xiaomi 12

### Bug report

[maisondes.zip](https://github.com/OxygenCobalt/Auxio/files/13734866/maisondes.zip)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Your files seem to be missing `ALBUMARTISTS` tag information, so Auxio just uses the concatenated Album Artist field, resulting in fragmentation. I'd recommend you retag your library.

**Comment by polyester2023** [comment]
huh weird, I use musicbrainz to tag it

**Comment by OxygenCobalt** [comment]
Picard is finicky with mutli-artist support @polyester2023, seemingly just not tagging artist fields unless you coerce it to. This has been discussed in #195. The development branch of [beets](https://github.com/beetbox/beets) should also work like a charm too, if you want to fiddle with the command line.
