### ISSUE TITLE
Some unusal characters are not displayed properly in the "Now playing" and library screens

### ISSUE THREAD

**Issue by breversa** [OxygenCobalt/Auxio#65]
#### Describe the bug/crash:
Some unusal characters aren't displayed properly in Auxio.

Please see the screenshots for:
- KEYGEN CHURCH's album : https://keygenchurch.bandcamp.com/album/--2 (yes, those blocky characters are the "letters" of the album name :) )
- Scooter's "…and the beat goes on" where the "…" (one character, not three dots) isn't displayed properly either

Admittedly, the first case is VERY obscure, but the second may be much more frequent, as "…" is a correct character in French.

#### Screenshots:
![Screenshot_20220109-223308_Auxio_Debug](https://user-images.githubusercontent.com/2071276/148702100-050e974f-8a95-4f31-8379-b3d0cbd570d5.png)

![Screenshot_20220109-223528_Auxio_Debug](https://user-images.githubusercontent.com/2071276/148702120-a9218f39-d08b-4bb0-b371-d31df012bf56.png)

#### Phone Information:
Samsung Galaxy S9 (SM-G960F) running /e/ OS 0.20 (Android 10)

#### Due Diligence:

- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
What file format are these in? I know that album titles in FLAC songs will be interpreted as Latin-1 despite them being supposed to be read as UTF-8, which results in corrupted characters.

**Comment by breversa** [comment]
Yes, they are (of course :)) in FLAC.

**Comment by OxygenCobalt** [comment]
Yeah, this is sadly unfixable. Android's media capabilities are stuck in 2008, so any metadata functionality outside of "ID3v2.3 MPEG-3 Files" are an afterthought. I am legitimately considering creating a patch for this issue myself given how frustratingly ubiquitous it is.

**Comment by breversa** [comment]
You would do the entire Android community a huge favour by providing a patch for this! :)

**Comment by OxygenCobalt** [comment]
Hey, I've actually implemented my own metadata parser as of #128. If you want, you can try out this ***extremely*** experimental APK with the functionality enabled, and report back to me if it fixes your issue.

[Auxio_Ignore_MediaStore_Tags.zip](https://github.com/OxygenCobalt/Auxio/files/8828959/Auxio_Ignore_MediaStore_Tags.zip)

**Comment by breversa** [comment]
It works! :D
![Screenshot_20220603-154402_Auxio_Debug](https://user-images.githubusercontent.com/2071276/171866627-21b95a7e-59ae-4f00-b686-b706ee8548d9.png)
![Screenshot_20220603-154409_Auxio_Debug](https://user-images.githubusercontent.com/2071276/171866634-3f717c34-7921-4f6a-8e0c-11ea8b373433.png)
![Screenshot_20220603-154430_Auxio_Debug](https://user-images.githubusercontent.com/2071276/171866638-31ebbd29-e11e-4cde-a083-3f77511e1902.png)
![Screenshot_20220603-154444_Auxio_Debug](https://user-images.githubusercontent.com/2071276/171866642-1ea64c53-3108-416f-bc61-511572ad1420.png)

**Comment by OxygenCobalt** [comment]
Fantastic. I have no idea when this feature will arrive (there needs to be some more changes to how music is loaded before it is viable), but I'd imagine it may show up in a 2.4.0 or similar.
