### ISSUE TITLE
Resource leak / Abnormal usage

### ISSUE THREAD

**Issue by AttentionGrabber** [OxygenCobalt/Auxio#654]
### Describe the Bug/Crash

1. open the app
2. Play a music
3. Close the app (make sure music is topped and notification is removed)
4. Check running apps, Auxio is still there

![Screenshot_20231228-160106](https://github.com/OxygenCobalt/Auxio/assets/150506323/aa280941-7b31-4878-83a7-769dd57de4b6)

### Describe the intended behavior

It should stop running background as soon as app is closed and music isn't playing anymore.

### What android version do you use?

Android 14

### What device model do you use?

AOSP / Pixel OS

### Bug report

No need logs here.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I think you have "Automatic reloading" on. It requires a perpetually running foreground service to function currently (I really want to change it, but there's some annoying restrictions to work around). It should display a notification normally, but Android 13 got rid of that in favor of this "Active Apps" dialog for some reason.
