### ISSUE TITLE
Show SHA-256 certificate hash on releases page

### ISSUE THREAD

**Issue by greensheeps** [OxygenCobalt/Auxio#656]
I'm trying to verify the SHA-255 hash using [AppVerifier](https://github.com/soupslurpr/AppVerifier/) but can't because it isn't listed anywhere, would be appreciated.

**Comment by OxygenCobalt** [comment]
Can you elaborate further on what's needed from me. I do include a SHA-256 digest on my releases.

**Comment by greensheeps** [comment]
> Can you elaborate further on what's needed from me? I do include a SHA-256 digest in my release changelogs.

The hash for the APK file is different to the hash for the signing key and changes every release.

DA:84:E2:53:4C:1A:CC:0B:6E:4F:57:DE:DB:64:0D:4D:C8:93:F5:BF:41:37:A2:E1:EC:BA:87:AD:F8:25:BA:44 is the signing key hash.

**Comment by OxygenCobalt** [comment]
Oh, I get that. I can do that.

**Comment by OxygenCobalt** [comment]
Certificate hash should be in the v3.3.0 changelog now.
