### ISSUE TITLE
Use ExoPlayer for duration parsing

### ISSUE THREAD

**Issue by nemesis-vampy** [OxygenCobalt/Auxio#661]
### Describe the Bug/Crash

some songs in my library show a duration of --:--, and the albums they are in show a duration of 0:00:
![image](https://github.com/OxygenCobalt/Auxio/assets/75443150/b2e6a4ad-6d6b-4889-9bf2-5d3c7f0edec4)

### Describe the intended behavior

should display the true duration of the songs and their albums.
vlc, for example, correctly displays the duration:
![image](https://github.com/OxygenCobalt/Auxio/assets/75443150/4937809f-347f-4917-9fc8-c6412fa64704)

### What android version do you use?

Android 14

### What device model do you use?

samsung galaxy s22

### Bug report

 n/a?

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Can you provide sample files @nemesis-vampy? I cannot tell if this is a consequence of poor format support or your device's MediaStore database being broken (VLC uses it's own custom parser for durations, for now I still rely on MediaStore which is much flakier). Just make sure to strip the audio out if its copyrighted, I only need the tags anyway.

**Comment by nemesis-vampy** [comment]
of course.
[examples.zip](https://github.com/OxygenCobalt/Auxio/files/13846511/examples.zip)

**Comment by OxygenCobalt** [comment]
I can't seem to reproduce this. This implies this is largely device-specific. I'll convert this issue into a related enhancement about effectively using ExoPlayer for duration parsing as well (Currently the maintainers don't support it, so it would have to be a manual patch).

**Comment by zalnaRs** [comment]
Clear data of Auxio and com.android.providers.media.

**Comment by OxygenCobalt** [comment]
#924 resolves this issue now.
