### ISSUE TITLE
Crash when  go back from settings

### ISSUE THREAD

**Issue by Richard38907** [OxygenCobalt/Auxio#664]
### Describe the Bug/Crash

When I try to go back just after entering to the settings page, the app crashes. V 3.3.0
Android 14 and android 13 (Pixel and OnePlus)
![Screenshot_20240105-201850](https://github.com/OxygenCobalt/Auxio/assets/148692265/dfbcb7b2-d7cd-493a-9939-c3d635b97ddb)
![Screenshot_20240105-202417](https://github.com/OxygenCobalt/Auxio/assets/148692265/f22f0844-3567-448b-b9e7-d9443154cddc)

### Describe the intended behavior

When I try to go back just after entering to the settings page, the app crashes. V 3.3.0
Android 14 and android 13 (Pixel and OnePlus)

### What android version do you use?

Android 14

### What device model do you use?

OnePlus 10t android 14
OnePlus Nord (pixel experience 13)

### Bug report

[Uploading bugreport-CPH2415EEA-UKQ1.230924.001-2024-01-05-20-26-19.zip…]()

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Your bug report didn't successfully upload. Can you try again @Richard38907? Make sure it stops saying "Uploading bugreport-[file].zip"

**Comment by OxygenCobalt** [comment]
Wait, just reproduced it by accident. It's related to the new playlist add button. Don't need to provide a bug report.

**Comment by OxygenCobalt** [comment]
Should be fixed now, will release a patch soon for this and some other fixes.

**Comment by Richard38907** [comment]
![Screenshot_20240109-213656.png](https://github.com/OxygenCobalt/Auxio/assets/148692265/4e0e3282-265f-4f24-bff1-70955abf68e2)

![Screenshot_20240109-213900.png](https://github.com/OxygenCobalt/Auxio/assets/148692265/dbc148bd-dff8-4205-ac8d-1fc7c0ec13ab)

![Screenshot_20240109-213839.png](https://github.com/OxygenCobalt/Auxio/assets/148692265/3d457d14-6613-43fe-9fe6-2007c229e921)

![bugreport-CPH2415EEA-UKQ1.230924.001-2024-01-09-21-37-32-dumpstate_log-2570.txt](https://github.com/OxygenCobalt/Auxio/files/13878866/bugreport-CPH2415EEA-UKQ1.230924.001-2024-01-09-21-37-32-dumpstate_log-2570.txt)

I reproduced the bug on my OnePlus 10t (android 14)

The error is detailed here:

android.database.sqlite.SQLiteException: near "OR": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT _id, date_added, date_modified, _size, duration, mime_type, title, year, album, album_id, artist, album_artist, _display_name, volume_name, relative_path, cd_track_number, disc_number FROM audio WHERE ((((is_pending=0 AND NOT _modifier=4) OR (is_pending=1 AND lower(_data) NOT REGEXP '.*/\.pending-(\d+)-([^/]+)$' AND owner_package_name IN ( 'org.oxycblt.auxio' )))) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' ))) AND (NOT _size=0 AND is_music=1 AND NOT  ( OR (volume_name LIKE ? AND relative_path LIKE ?)))
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
	at android.content.ContentResolver.query(ContentResolver.java:1255)
	at android.content.ContentResolver.query(ContentResolver.java:1181)
	at android.content.ContentResolver.query(ContentResolver.java:1137)
	at org.oxycblt.auxio.music.fs.StorageUtilKt.safeQuery(Unknown Source:6)
	at org.oxycblt.auxio.music.fs.MediaStoreExtractorImpl.query(SourceFile:369)
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$mediaStoreQueryJob$1.invokeSuspend(SourceFile:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.fragment.app.Fragment$4.run(SourceFile:43)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

**Comment by Richard38907** [comment]
Oops not the right channel, sorry.
