### ISSUE TITLE
Project Not Runing ( I got  one error) please help me 

### ISSUE THREAD

**Issue by okmusicapp** [OxygenCobalt/Auxio#666]
Gradle DSL method not found: 'UnsupportedOperationException()'

Possible causes:

Your project may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).

Upgrade plugin to version 8.2.1 and sync project
Open Gradle wrapper file
Apply Gradle plugin

**Comment by OxygenCobalt** [comment]
I haven't upgraded the gradle plugin. Seems like you just need to change a variable.
