### ISSUE TITLE
Interpret all M3U paths as relative and absolute

### ISSUE THREAD

**Issue by JHXmas** [OxygenCobalt/Auxio#673]
### Describe the Bug/Crash

1. Press plus to make new playlist
2. Select imported playlist
3. Choose m3u (uploaded below) 
4. Met with error "Unable to import a playlist from this file."

[Screenshot](https://github.com/OxygenCobalt/Auxio/assets/156576149/84afdd5c-f55f-4c32-b3bd-ecb34f45e9f5)

[THPS3.zip](https://github.com/OxygenCobalt/Auxio/files/13930964/THPS3.zip)

### Describe the intended behavior

Should import as a new playlist, can confirm these files worked in Poweramp at least.

### What android version do you use?

Android 13

### What device model do you use?

Asus Zenfone 8

### Bug report

[bugreport-WW_I006D-TKQ1.220807.001-2024-01-14-04-59-09.zip](https://github.com/OxygenCobalt/Auxio/files/13931000/bugreport-WW_I006D-TKQ1.220807.001-2024-01-14-04-59-09.zip)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
The files seemingly all consist of absolute paths, like:

`/The Nextmen/Amongst the Madness/1-01 Amongst the Madness.m4a`

Do you have folders at the root of your internal storage that are like this? If not, then your M3U file is improperly indicating absolute paths as relative paths.

**Comment by OxygenCobalt** [comment]
The files seemingly all consist of absolute paths, like:

`/The Nextmen/Amongst the Madness/1-01 Amongst the Madness.m4a`

Do you have folders at the root of your internal storage that are like this? If not, then your M3U file is improperly indicating absolute paths as relative paths.

@JHXmas

**Comment by JHXmas** [comment]
Nah, they're all sitting in their own folder. Definitely a me problem then, thanks for looking.

**Comment by OxygenCobalt** [comment]
At the same time though, given that Poweramp seems to be really leniant with this, I'm going to assume I need to be more tolerant of this error. I'll make it so I'm searching by both the absolute and relative path when working with playlists, regardless of the true path composition.

**Comment by OxygenCobalt** [comment]
Can you try this out with your old relative playlists @JHXmas? Auxio will now interpret the paths as relative and absolute. If it can't find anything absolute, it will fall back and try to find a relative path instead.

[Auxio_Canary.zip](https://github.com/user-attachments/files/15749214/Auxio_Canary.zip)

**Comment by OxygenCobalt** [comment]
Closing this for now since my test playlists with similar path formats do parse properly.

**Comment by JHXmas** [comment]
Sorry for missing the response, but I can confirm mine are now working in 3.5.0
