### ISSUE TITLE
Playlist no delete or remove music function

### ISSUE THREAD

**Issue by 3pka** [OxygenCobalt/Auxio#674]
### Description

Created playlist and music library nor don't have remove or delete music function.

### Other implementations

Sometimes i update my tracks but there is duplicates found maybe same problem happening lot of users.

### Benefit

Manage library

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by Chzy2018** [comment]
You may see [#624 ](https://github.com/OxygenCobalt/Auxio/issues/624) for your answer.

In the playlist, songs can be deleted by swiping them away. As for deleting songs from the music library, please remove them through the file manager of your Android device or exclude directories in the software's settings.
