### ISSUE TITLE
Playback and Library Scan notifications not shown on Android 14, OriginOS 4

### ISSUE THREAD

**Issue by april4356** [OxygenCobalt/Auxio#680]
### Describe the Bug/Crash

I'm using an iQOO 12 Pro running Android 14 under an OriginOS 4 skin. Auxio doesn't request the notification permission and is unable to show playback and library scan notifications. The ROM allows me to enable notifications and configure them, but the moment I leave the notification settings screen, the notifications are disabled automatically and none are shown.

The reason I'm reporting this is because OriginOS doesn't support the modern, persistent, native (Android 11+) music playback notification/widget in the notification shade. But having some control over playback would be nice. This might be a device specific issue, but if it's not too much hassle, please take a look.

### Describe the intended behavior

Auxio doesn't request the notification permission, and therefore doesn't show playback and library scan notifications. However, all the relevant settings are shown in the settings section.

### What android version do you use?

Android 14

### What device model do you use?

Vivo iQOO 12 Pro

### Bug report

![Screenshot_20240118_143450](https://github.com/OxygenCobalt/Auxio/assets/157015375/9b2fabf5-a9e1-4066-b72d-db6aeb9ba639)
![Screenshot_2024_0118_143532](https://github.com/OxygenCobalt/Auxio/assets/157015375/09386342-8df1-4166-be90-4d4199ee9776)
![Screenshot_20240118_143457](https://github.com/OxygenCobalt/Auxio/assets/157015375/664ce107-469a-4842-b9c9-30bdfb9feff5)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Wait, so if I'm getting this right, OriginOS implements the notification permission (Something from Android 13 onwards), yet not the native media player (Something from Android 11 onwards)? That doesn't seem right. Are there any other resources on this issue @april4356?

**Comment by april4356** [comment]
> Are there any other resources on this issue @april4356?

Is there anything useful I could provide? Like a log?

**Comment by OxygenCobalt** [comment]
> China-exclusive phones and ROMs are just like that, heh.

Getting this vibe. I'm terrified of all the god-awful hacks I'm going to have to do as HarmonyOS and friends continue to diverge from AOSP...

> Update: I tried a few more apps. Metro, InnerTune, Vanilla Music and LibreTube all don't request the notification permission, but show the playback widget anyway.

Huh. I think they all have the `<uses-permission android:name="android.permission.POST_NOTIFICATIONS" />` permission. I guess I need to add that even though it's only for non-foreground notifications.

**Comment by april4356** [comment]
> Huh. I think they all have the `<uses-permission android:name="android.permission.POST_NOTIFICATIONS" />` permission. I guess I need to add that even though it's only for non-foreground notifications.

I've read your comments on other issues that your time for Auxio's development is quite limited, and this notification thing is a minor issue affecting a tiny minority of users, so if adding this permission would be too much work, feel free to close this bug report.

**Comment by OxygenCobalt** [comment]
Nope @april4356, hopefully it's as simple as adding it to the manifest. Care to try the apk in this zip file and see if it works?

[Auxio_Canary.zip](https://github.com/OxygenCobalt/Auxio/files/13983588/Auxio_Canary.zip)

**Comment by april4356** [comment]
> Nope @april4356, hopefully it's as simple as adding it to the manifest. Care to try the apk in this zip file and see if it works?

It does indeed:
![Screenshot_20240119_060743](https://github.com/OxygenCobalt/Auxio/assets/157015375/558584cb-66c2-426a-98d9-d20e7a0032cc)
Thank you so much!

However, upon launching the debug app, I got this leak report:
[2024-01-19_06-03-25_267.zip](https://github.com/OxygenCobalt/Auxio/files/13983759/2024-01-19_06-03-25_267.zip)

**Comment by OxygenCobalt** [comment]
Very weird, at least it works now! The leak report is a false positive, no need to report it.
