### ISSUE TITLE
Album arts

### ISSUE THREAD

**Issue by Lucky390163** [OxygenCobalt/Auxio#684]
Some albums arts are shown wrong even an album contains different album arts![Screenshot_20240120_232249_Poweramp.jpg](https://github.com/OxygenCobalt/Auxio/assets/115852216/06e57ddc-181b-437a-9633-102bda2cf3be)

![Screenshot_20240120_232235_Auxio.jpg](https://github.com/OxygenCobalt/Auxio/assets/115852216/9b6b0fc1-aa0e-4bee-ad8d-521990eea998)

**Comment by OxygenCobalt** [comment]
Have you tried going to "Settings -> Content -> Album covers" and setting it to "high quality." MediaStore is often finicky with album art, but I don't enable the better system by default since it's more resource-intensive.

**Comment by Lucky390163** [comment]
Yes still wrong albumart and not working at all.

I think it requires a option to ignore media store covers just like oto music app.Oto music has same problem but after enabling disable media store album art fix this

**Comment by OxygenCobalt** [comment]
Wait, I see.

Your album has several cover arts. I only support per-album cover art currently, see #342.
