### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Lucky390163** [OxygenCobalt/Auxio#685]
I have money i will definitely consider you contribute.For now i use a paid app called poweramp full version (2010-2024).https://play.google.com/store/apps/details?id=com.maxmpz.audioplayer

It has multiple functionality but your app is also good appreciate it.👍

**Comment by OxygenCobalt** [comment]
Poweramp and Auxio definitely have different philosophies. Poweramp has one guy paid full-time to work on it, so they can load it up with an absurd about of features, while I'm a stressed-out college student and can't handle an app of that scale. If you do want some functionality completed sooner though, you can sponsor me and prioritize features. Someone just sponsored and prioritized #342, the fix you wanted in #684, for example.
