### ISSUE TITLE
Make moving song in queue smoother

### ISSUE THREAD

**Issue by dmint789** [OxygenCobalt/Auxio#686]
### Description

Right now whenever I move a song up or down in the queue far enough that it needs to scroll the queue, it scrolls way too fast and I just cannot see the songs going by anymore.

### Other implementations

It would be good to make the speed of the scrolling dependent on how far down you move the song you're holding with your finger, with the bottom of the screen being the fastest speed.

### Benefit

This would make moving around songs in the queue much easier.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Huh. I'll look into if there's a way to clamp the speed.

**Comment by dmint789** [comment]
@OxygenCobalt also, would it be able to prioritize this one too?

**Comment by OxygenCobalt** [comment]
Yep, you're an $8 sponsor, so you get 2 features prioritized. You cannot prioritize any more though.

**Comment by dmint789** [comment]
@OxygenCobalt yeah, I remember. Thank you!

**Comment by OxygenCobalt** [comment]
Resolved @dmint789
