### ISSUE TITLE
UI Customization "Player Themes"

### ISSUE THREAD

**Issue by mehedi2580** [OxygenCobalt/Auxio#688]
### Description

Add "Player Themes" this is the good features for a music player. Retro Music Player have this features but this player kind of dead. Specially "Color Theme" is so amazing. Check Screen Video. I think that will be good features for "Auxio". I hope you will add this features.

Retro Music Player Source:
https://github.com/RetroMusicPlayer/RetroMusicPlayer

### Other implementations

Retro Music Player

https://github.com/RetroMusicPlayer/RetroMusicPlayer

https://github.com/OxygenCobalt/Auxio/assets/39218757/6848cc0c-7984-48fe-b0f8-bffbb95e3d5a

### Benefit

I think that is the good features for Auxio. Everyone want a good minimalistic Audio Player. That color adaptive features is amazing.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Sorry, I've already rejected this in the past. The thing is that this is the exact sort of functionality that killed Retro. I am one person, my attention simply cannot be split across 10 different playback screen styles.
