### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by resom78** [OxygenCobalt/Auxio#69]
#### Describe the bug/crash:
I start the app and as soon as I allow to access internal storage the app stop working and close itself

#### Steps To Reproduce the bug/crash:
- start the app
- allow access to storage
- the app crash

#### Phone Information:
Android 10 on Soyes S10 max

#### Due Diligence:

- [ ] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I need two things:
1. What version of the app did you download? 2.0.0 or 2.1.0?
2. Can you provide a logcat? I cannot debug your issue without a stack trace for the crash.

**Comment by resom78** [comment]
I can answer the first point: it is the 2.1.0.I used the 2.0.0 without problem, so maybe you changed the way it access the storage?For the second point I have to find how to make a logcat!
    Le lundi 31 janvier 2022, 15:35:06 UTC+1, Alex ***@***.***> a écrit :  
 
 


I need two things:
   
   - What version of the app did you download? 2.0.0 or 2.1.0?
   - Can you provide a logcat? I cannot debug your issue without a stack trace for the crash.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OxygenCobalt** [comment]
> I can answer the first point: it is the 2.1.0.I used the 2.0.0 without problem, so maybe you changed the way it access the storage?

This is not good. 2.1.0 actually patched the player library to add some extra features, which could have resulted in the crash since patching android libraries is notoriously finicky. That's why I need the stack trace so I can identify the crash and if/where it occurred in the patched library. In the meantime, I may make an APK that does not patch the library and see if the crash does not occur then.

> For the second point I have to find how to make a logcat!

I'll try to find a guide on making one. A stack trace would be useful, but now that I know that you used 2.1.0, I'll try creating debug APKs first.

**Comment by OxygenCobalt** [comment]
Can you try these APKs? Rename the extension from ZIP. I removed the patched libraries entirely in one APK while keeping an extension on the other. Just tell me what happens when you open them, and then I can narrow down the issue further.

[Auxio_OnlyFlacExt.zip](https://github.com/OxygenCobalt/Auxio/files/7975458/Auxio_OnlyFlacExt.zip)
[Auxio_NoExtensions.zip](https://github.com/OxygenCobalt/Auxio/files/7975457/Auxio_NoExtensions.zip)

**Comment by OxygenCobalt** [comment]
Forgot an APK. Try this one too:

[Auxio_NoFlacExt.zip](https://github.com/OxygenCobalt/Auxio/files/7975476/Auxio_NoFlacExt.zip)

**Comment by resom78** [comment]
I tried all these APK's but none of them work... As soon as I allow access to internal storage the app close itself.
If I can do something or send you a log file, tell me how to do it and I will do it!

Thanks

**Comment by OxygenCobalt** [comment]
Okay, to take a logcat you have to do the following:

1. Use a desktop/laptop to download the android platform tools from [here](https://developer.android.com/studio/releases/platform-tools).
2. Extract the downloaded file to a directory
3. [Enable USB debugging](https://developer.android.com/studio/command-line/adb#Enabling) on your phone, and then connect it to the desktop/laptop. 
4. Open up a command line in that directory and run `./adb -d logcat AndroidRuntime:E *:S`
5. Copy and paste the output to a comment on this issue.

I'm assuming that you have at least some technological literacy here, but if you don't understand a part of the process, please let me know. Depending on the crash that goes on here, I may need to get you to gather some other logs, but this should be enough.

**Comment by resom78** [comment]
OK, here is a screen copy of the logcat, hope it helps!
![image](https://user-images.githubusercontent.com/37101973/152136975-101d86e5-f6a1-48b5-8ec7-9279f9894f64.png)

**Comment by OxygenCobalt** [comment]
Oh. I think I know what's happening. What language have you configured android to use?

**Comment by OxygenCobalt** [comment]
Actually, seeing the top bar, your system language is probably french. I know what happened here.

Basically, I have some strings in the app that change depending on the amount of items. These are called "plurals". In 2.1.0, I was following lint guidelines when I renamed the "other" field in the french plurals to "many", as I thought they had the same effect. They evidently do not. I'm going to create an APK with that "other" field re-introduced and see what happens.

**Comment by OxygenCobalt** [comment]
Try out this APK, I fixed the translations, or at least I hope I did.

[Auxio_FixPlurals.zip](https://github.com/OxygenCobalt/Auxio/files/7987137/Auxio_FixPlurals.zip)

**Comment by resom78** [comment]
Yes, my Android phone use French language!I am waiting for the release of the new apk!
    Le mercredi 2 février 2022, 15:08:24 UTC+1, Alex ***@***.***> a écrit :  
 
 


Actually, seeing the top bar, your system language is probably french. I know what happened here.

Basically, I have some strings in the app that change depending on the amount of items. These are called "plurals". In 2.1.0, I was following lint guidelines when I renamed the "other" field in the french plurals to "many", as I thought they had the same effect. They evidently do not. I'm going to create an APK with that "other" field re-introduced and see what happens.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OxygenCobalt** [comment]
Sounds good. I just uploaded the APK, if you want to test it.

**Comment by resom78** [comment]
Ok it works!! Thanks a lot!
