### ISSUE TITLE
Support M3U paths starting with /storage/

### ISSUE THREAD

**Issue by paradoxical95** [OxygenCobalt/Auxio#693]
### Describe the Bug/Crash

I have over a 1000 songs and currently use BlackPlayer. Exported all my playlists from it. Tried importing those and it says "Unable to import playlist"
Is there some backwards compatibility that you need to add or is BlackPlayer messing around in the m3u file? I'd love to daily drive Auxio but I cannot without my playlists.

### Describe the intended behavior

Should simply import playlist from the exported M3U file.

### What android version do you use?

Android 11

### What device model do you use?

RealMe Narzo 50A (Android 11)

### Bug report

-

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Can I have a sample playlist file?

**Comment by OxygenCobalt** [comment]
Can I have a sample playlist file? @paradoxical95

**Comment by paradoxical95** [comment]
Yeah sure. Here you go.
[FewPlaylists.zip](https://github.com/OxygenCobalt/Auxio/files/14047905/FewPlaylists.zip)

**Comment by OxygenCobalt** [comment]
Okay, so Black Player just outputs the absolute android path (with /storage/emulated/0) with their M3U files. Auxio expects absolute paths that are at least relative to their volume, since it's somewhat difficult to work with volume info. Evidently I'll need to handle and support this.

Try seeing if Black Player supports exporting with relative M3U paths. Auxio should support those fine @paradoxical95.

**Comment by paradoxical95** [comment]
I checked and currently BlackPlayer doesn't support relative paths. 
Can you tell me what I must edit manually? If I can edit those files so that I can make them usable in Auxio? And will you be pushing this in next update?

**Comment by OxygenCobalt** [comment]
That's weird. Relative paths are usually supported by most players. 

You would need to edit the files and remove all instances of `/storage/B8E5-FB87` or `/storage/emulated/0` in the paths. Then Auxio should be able to understand it as an absolute path.

Currently, I cannot work on this fix since a sponsor has prioritized another feature. I will get to it as soon I am done with that.

m3u and m3u8 will not change anything. Those file extensions just signal what the character encoding is.

**Comment by paradoxical95** [comment]
Okay. I see. No worries mate, take your time. The app is superb otherwise. 
By removing the instances of storage, you mean this right? I should edit all my playlist to look more like this right? 
(starting with /MusicMine/... as that's my Music Folder in my SD Card)
![image](https://github.com/OxygenCobalt/Auxio/assets/50901457/cba0c0a3-1f02-4fc7-8f02-25ec982f9d6c)

**Comment by OxygenCobalt** [comment]
Yeah, that works.

**Comment by paradoxical95** [comment]
Okay so I tried that and it didn't work. Attaching my fixed files. I removed the starting portion as I mentioned before and tried re-importing but it failed again. IDK how to fix this now.
[Playlists_Fixed.zip](https://github.com/OxygenCobalt/Auxio/files/14057269/Playlists_Fixed.zip)

**Comment by OxygenCobalt** [comment]
Are the playlists in the same folder as your sd card @paradoxical95?

**Comment by paradoxical95** [comment]
Yep, that helped. I made a folder and moved it to the root of my SD card instead of Phone storage and it worked. ! Thanks

Just a suggestion @OxygenCobalt , after importing it asks me to Name the playlist, but instead I suggest it should name whatever the name of the .m3u file was and let the user rename it if need be? Is that possible?

**Comment by OxygenCobalt** [comment]
> Just a suggestion @OxygenCobalt , after importing it asks me to Name the playlist, but instead I suggest it should name whatever the name of the .m3u file was and let the user rename it if need be? Is that possible?

Eh, I don't like the idea of using the M3U filename, it just looks strange.

**Comment by chocmake** [comment]
> Eh, I don't like the idea of using the M3U filename, it just looks strange.

fwiw when I save M3U/M3U8 playlists I name the file like I would the playlist in-player (whether desktop or mobile), which means it's the desired title as-is (eg: `Video Game OST Selections.m3u8`). Perhaps you've encountered some kind of auto-generated playlist filenames leading to a negative association though.

**Comment by paradoxical95** [comment]
> > Eh, I don't like the idea of using the M3U filename, it just looks strange.
> 
> fwiw when I save M3U/M3U8 playlists I name the file like I would the playlist in-player (whether desktop or mobile), which means it's the desired title as-is (eg: `Video Game OST Selections.m3u8`). Perhaps you've encountered some kind of auto-generated playlist filenames leading to a negative association though and prefer normalizing their appearance by a prompt.

IKR? I do that too but then it became redundant to me. Like my playlist is named "EDMs". Why are you asking me to name it when it's literally named EDMs 🤣

**Comment by OxygenCobalt** [comment]
Okay. While I could autofill with the file name in the playlist name dialog, the issue is that I don't want someone to have to search for a playlist (possibly within a big list) just to rename it. There's a lot of friction in that process compared to always asking to rename the playlist first.

**Comment by KraXen72** [comment]
You could have the playlist filename as a placeholder text, and if the name field is submitted empty, it uses the placeholder, otherwise, it uses the value

**Comment by OxygenCobalt** [comment]
This is done now.
