### ISSUE TITLE
Reducing Font Size? 

### ISSUE THREAD

**Issue by paradoxical95** [OxygenCobalt/Auxio#695]
### Description

To edit the Font size.? Some of my songs have longer names and at this scaling the names do trim themselves so I suggest a Font Size control? 

### Other implementations

Black Player gives no Font control either but it looks better. If not a font control then having a smaller font would work as well.
Lowering the font by 1-3 units would do just fine. Smaller looks cleaner too.

![Screenshot_2024_01_26_16_33_07_07_986bd1f6f0be4ef9831dc7ba244afa0f](https://github.com/OxygenCobalt/Auxio/assets/50901457/0b0f0d9f-1d42-40d8-8b11-781a4e7b8b5c)

![Screenshot_2024_01_26_16_32_49_66_e7dcd68fdcfdc2ab307738dbc82b3952](https://github.com/OxygenCobalt/Auxio/assets/50901457/b2e2dcab-d9e8-49e4-9b86-b78d1e622761)

### Benefit

Allows for more content on the screen.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by april4356** [comment]
This would be nice, as well as an option to use the system font.

**Comment by OxygenCobalt** [comment]
I'm just following the font sizing defined by Material Design 3. It's not really something I want to be able to configure. Sorry.

**Comment by OxygenCobalt** [comment]
> This would be nice, as well as an option to use the system font.

Regarding this, I really don't like how Roboto looks.
