### ISSUE TITLE
Music loading failed with no album error

### ISSUE THREAD

**Issue by Nishantkantgaurav** [OxygenCobalt/Auxio#699]
### Describe the Bug/Crash

Upon installing the app and granting the storage permission, it says "Music loading failed". Pressing retry yields the same error. I have ensured the storage permission was granted. According to MediaStore I have approximately 10 to15 songs but I not sure if that is related.

### Describe the intended behavior

Music loading failed

### What android version do you use?

Android 14

### What device model do you use?

Mi 11x 
Inbuilt in matrix rom

### Bug report

java.lang.Exception: DeviceLibrary creation failed: java.lang.IllegalArgumentException: Invalid raw Path(volume=InternalVolumeImpl(storageVolume=StorageVolume: Internal shared storage), components=YMusic/Gold AP55 100W Amplifier Module You Like Electronic (720 X 1280).mp4): No album name
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(SourceFile:92)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Can you please provide the "YMusic/Gold AP55 100W Amplifier Module You Like Electronic (720 X 1280).mp4" file?

**Comment by OxygenCobalt** [comment]
Can you please provide the "YMusic/Gold AP55 100W Amplifier Module You Like Electronic (720 X 1280).mp4" file? @Nishantkantgaurav

**Comment by OxygenCobalt** [comment]
I just realized that you reported this issue prior, and still did not respond when I asked for a sample file. Merging back into #639.
