### ISSUE TITLE
Using non-automatic theme causes app to crash

### ISSUE THREAD

**Issue by trollman64** [OxygenCobalt/Auxio#701]
### Describe the Bug/Crash

1. Change theme to Dark in the Look and Feel menu
2. Close the app through the recent apps screen
3. Upon attempting to relaunch, the app will immediately crash until the app data is deleted

### Describe the intended behavior

App should open after enabling dark mode, notably the bug does not occur if the theme is set to Automatic and the systemwide dark mode is used.

### What android version do you use?

Android 11

### What device model do you use?

Amazon Fire HD 10 2023
Fire OS 8.3.2.1 (based on Android 11)

I can confirm the bug also occurs on a Samsung Galaxy S23 FE with Android 14

### Bug report

[bugreport-tungsten-RS8321.1924N-2024-02-01-12-45-27.zip](https://github.com/OxygenCobalt/Auxio/files/14129026/bugreport-tungsten-RS8321.1924N-2024-02-01-12-45-27.zip)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Thanks for reporting this, I can reproduce it. Turns out a piece of problem code was only partially fixed.
