### ISSUE TITLE
Play MP4 videos as music, ignoring video

### ISSUE THREAD

**Issue by bsammon** [OxygenCobalt/Auxio#702]
### Description

It appears that Auxio does not support opening MP4 videos and playing just the audio track (in the files I tried, encoded as mpeg4-audio).

Is that correct, or have I made a mistake?

If correct, would you consider adding such a feature?

### Other implementations

I've found one other player that does what I want, playing MP4s with the same interface as MP3s, but it is old and no longer maintained.

### Benefit

This allows users to be lazy (and wasteful of storage) and not bother converting their youtube-downloaded MP4s into M4As.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by bsammon** [comment]
I suspect this would be a relatively small change, but maybe it's rather complicated, in which case I'm not sure it's worth the trouble.

**Comment by OxygenCobalt** [comment]
I think I deliberately stripped the MP4 video extractor from the app to reduce APK size. Weird for ExoPlayer to still fail to extract it since I kept the audio extractor. Can you share any error logs? @bsammon

**Comment by OxygenCobalt** [comment]
I don't know if the issue is @bsammon:
- Auxio is not loading your videos. Auxio by default only loads files considered music, but you can disable this by turning Settings -> Content -> Exclude non-music off.
- Auxio is failing to play your videos. I think I deliberately stripped the MP4 video extractor from the app to reduce APK size. Weird for ExoPlayer to still fail to extract it since I kept the audio extractor. In this case, I need error logs

**Comment by bsammon** [comment]
The MP4 files never show up in the files list.  I copied a directory-full (a few dozen or so) of music files on to my Android device, and there's a few MP4s in the mix.  None of the MP4s show up in the list of files that Auxio reports.  All/most of the non-MP4 files do (Oggs and MP3s).
Toggling the "exclude non-music" setting doesn't appear to make a difference.  (Side note-- wouldn't it make sense for Auxio to always treat any file under the "Music" directory, regardless of file extension, as music, and try to play it, on the assumption that the user intended it so when they put the file there?)

My current thinking: If this is a problem that affects only me, than maybe it would save my time and yours for me to simply switch to another player app.

**Comment by OxygenCobalt** [comment]
Weird. So that means MediaStore itself is not indexing your video. I guess this makes some sense, since I am indexing the *audio* database. This is sadly unfixable, you'll need to wait for #322.
