### ISSUE TITLE
Background blurry

### ISSUE THREAD

**Issue by SimoLRepo** [OxygenCobalt/Auxio#704]
### Description

Hello, Would it be possible to implement an option (optional) to make the background blurry and more engaging? I saw the issue #155 which dates back to a few years ago, Is implementation still possible? Thank you.

[Here's an example](https://drive.google.com/file/d/1En5Q5nEI1LPzyNqt6GnlXMlba2CPNp46/view?usp=sharing)

### Other implementations

Slightly blurs the cover image and spreads it into the background.

### Benefit

It will make listening to music more pleasant

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
It's not that I can't implement the feature, it's just that the feature is out of scope. Sorry.

**Comment by SimoLRepo** [comment]
@OxygenCobalt Okay, thanks anyway. Would it be possible to implement at least one option to enlarge the size of the cover?

**Comment by OxygenCobalt** [comment]
I don't know what you mean by "enlarge the size of the cover" @SimoLRepo. Can you provide a visual example?

**Comment by SimoLRepo** [comment]
> I don't know what you mean by "enlarge the size of the cover"

@OxygenCobalt Because the cover appears to me to be rather small compared to the space available I wanted to ask if an option could be added to enlarge it.

Here's [an example](https://drive.google.com/file/d/17JboY54fSZRs3EPS1K_hYukpCtOlRWbR/view?usp=sharing)

**Comment by OxygenCobalt** [comment]
I see. Changing that would be a violation of design guidelines and would look really weird in practice. Sorry.

**Comment by SimoLRepo** [comment]
> I see. Changing that would be a violation of design guidelines and would look really weird in practice. Sorry.

All right, thank you all the same.
