### ISSUE TITLE
Folders Library Tab

### ISSUE THREAD

**Issue by jeet-74** [OxygenCobalt/Auxio#705]
### Description

There needs to be an option to view folders tab in the library option.

### Other implementations

Other apps have it as an option at the last or disabled out of box.

### Benefit

This allows user to have custom collection of tracks like language or artist.

> It can be used to add whole folder to playlist

> Delete folders or track

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This has already been rejected. Auxio is not designed with file management in mind, in favor of using metadata tags instead.
