### ISSUE TITLE
multi-value musicbrainz album-artist tags in m4a cause a crash

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#706]
### Describe the Bug/Crash

- write multiple album-artist mbids in an m4a file (i'm using mutagen, just pass an array of strings in)
- click on song in auxio
- auxio freezes and crashes in a while

### Describe the intended behavior

while i know this is bad tagging, it shouldn't crash the app imo. i fixed my tagging but it's still a bug worth reporting.
probably just take the first album-artist mbid tag if internally multiple album-artists aren't supported

### What android version do you use?

Android 12

### What device model do you use?

Galaxy M21 Oneui 4.1

### Bug report

- if needed, i'll provide
- although, i'd rather just provide a sample m4a file if it's hard to reproduce

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Odd. I'll need a sample m4a @KraXen72.

**Comment by KraXen72** [comment]
damn, i can't reproduce it now.
