### ISSUE TITLE
The swiping experience of "tabs" is a bit terrible

### ISSUE THREAD

**Issue by YuBans** [OxygenCobalt/Auxio#709]
When you swipe to switch between "tabs", it is easy to slide up and down instead of switching

**Comment by OxygenCobalt** [comment]
What do you mean by this @YuBans?

**Comment by YuBans** [comment]
> 你这是什么意思？

The experience is not smooth when switching between pages by swiping left or right. It is easier to accidentally scroll up and down or trigger a click when swiping left or right.

**Comment by OxygenCobalt** [comment]
Hm, I think this is more of a sensitivity/touch issue on your device. I find it pretty easy to move back and forth without swiping. If anybody else is having this issue, please let me know.

**Comment by YuBans** [comment]
I have installed this software on a different device, and there still exists a poor user experience with the left-right swiping, perhaps I have been too demanding. I tried to capture a video to demonstrate my point to you, comparing the experience of left-right swiping in this application with another. From the video, it can be seen that when swiping left or right in this music app, if the trajectory of the swipe is not perfectly horizontal or is too long, it will be recognized as an upward or downward swipe or as a click operation.

**Comment by YuBans** [comment]
I have installed this software on a different device, and there still exists a poor user experience with the left-right swiping, perhaps I have been too demanding. I tried to capture a video to demonstrate my point to you, comparing the experience of left-right swiping in this application with another. From the video, it can be seen that when swiping left or right in this music app, if the trajectory of the swipe is not perfectly horizontal or is too long, it will be recognized as an upward or downward swipe or as a click operation.

Uploading studio_video_1707755304264.mp4…

**Comment by OxygenCobalt** [comment]
Your video did not upload @YuBans.

**Comment by YuBans** [comment]
Uploading studio_video_1707755304264.mp4…

**Comment by OxygenCobalt** [comment]
You need to wait for "Uploading studio_video_1707755304264.mp4…" to turn into something like "[studio_video_1707755304264.mp4](...)" before you post the comment @YuBans.

**Comment by YuBans** [comment]
I think the upload was successful this time. 
https://github.com/OxygenCobalt/Auxio/assets/78398248/1877db45-c6fc-4e1c-96b0-b204869a7994

**Comment by OxygenCobalt** [comment]
Okay, I guess I do need to tune the sensitivity. This is strange though since it works perfectly fine on my device. What device do you use @YuBans?

**Comment by YuBans** [comment]
Sony Xperia XZ1

**Comment by OxygenCobalt** [comment]
Alright, I'll add a special exception for sony then, since I assume it did some idiotic OEM touch code modification.
