### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Lucky390163** [OxygenCobalt/Auxio#710]
Please disable the list visualisations of small bars.It uses somehow much battery.As my playback time is up to 110 hours.

Mean 1 per cent battery on 1 hour.

And fix those media covers.Thanks

**Comment by AttentionGrabber** [comment]
> Please disable the list visualisations of small bars.It uses somehow much battery.As my playback time is up to 110 hours.
> 
> Mean 1 per cent battery on 1 hour.
> 
> And fix those media covers.Thanks

Sorry, How do you know it's the small bar visualisation that drains your battery?

Actually this thing that tells me which song I have played from the list is so useful in much cases so I don't think removing it would be a good idea.

**Comment by OxygenCobalt** [comment]
> Please disable the list visualisations of small bars.It uses somehow much battery.As my playback time is up to 110 hours.

How do you know they use that much battery @Lucky390163? It's likely the playback system consuming battery, unless you are always keeping the display on, in which you have bigger issues battery-wise.

**Comment by Lucky390163** [comment]
Because i always use other music apps.
App with visualizations always drain battery while smart apps like aimp, musicolet or poweramp do not drain any battery in 1 hour.

**Comment by OxygenCobalt** [comment]
Other players have years of optimizations whereas Auxio has to use the relatively unoptimized ExoPlayer. It would make sense for playback to use a bit more battery in that case. You're associating entirely different phenomena.
