### ISSUE TITLE
Playback without pauses between one song and another

### ISSUE THREAD

**Issue by danjde** [OxygenCobalt/Auxio#712]
### Description

It would be very nice to be able to play songs without pauses between songs.
Thanks!

### Other implementations

Vinyl and Phonograph does this, and has an option to enable/disable it on settings

### Benefit

Listen Pink Floyd songs without swearing [ :-D ]

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Gapless playback is already implemented, just in the 3.4.0-dev testing build @danjde. You can try that out in the releases page.

**Comment by danjde** [comment]
Very well, I will try.
Thanks!!
