### ISSUE TITLE
widget transparency slider

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#714]
### Description

the 2x4 ans 1x4 have transparency while the 3x4 and 4x4 do not. can we have a 1-100% slider like other widgets do for transparency?

### Other implementations

.

### Benefit

aestehtics

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This violates the design guidelines set for widgets. Sorry.
