### ISSUE TITLE
1:1 crop for the quick settings media player

### ISSUE THREAD

**Issue by TGRush** [OxygenCobalt/Auxio#718]
### Describe the Bug/Crash

1. Enable "force square album covers"
2. Play a song
3. Observe all instances except the notification (widget, app) cropping it correctly

### Describe the intended behavior

It *should* crop the notification's album art too.

### What android version do you use?

Android 13

### What device model do you use?

Poco F3, Arrow OS, TQ3A.230901.001

### Bug report

[bugreport-alioth_global-TQ3A.230901.001-2024-02-23-08-35-20-1.zip](https://github.com/OxygenCobalt/Auxio/files/14382792/bugreport-alioth_global-TQ3A.230901.001-2024-02-23-08-35-20-1.zip)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is not fixable, sadly. It is impossible to predict the exact dimensions and cover behavior of the media player on all devices, so Auxio has to disregard it's configurations and conform to the system UI convention. Sorry.
