### ISSUE TITLE
F-Droid release delay

### ISSUE THREAD

**Issue by orangesunny** [OxygenCobalt/Auxio#719]
I am becoming more and more enthusiastic about Auxio, as my favorite Android player app is deprecated (Shuffle). Discovered the amazing Auxio thanks to Weblate.

One of the troubling things for me is the delay between the GitHub release and the F-Droid one. 3.4.0 still unavailable after a week. Is the ball on the F-Droid team’s side, or where’s the issue?

**Comment by orangesunny** [comment]
Thank you, @OxygenCobalt, for this kind and detailed response. I am happy that the developer's partially painful experience with F-Droid is written somewhere, next to an uncomfortable experience of a user. Good luck for the future!

**Comment by licaon-kter** [comment]
> F-Droid auto-accumulates updates, but does not build them. I do not know why.

It builds them in cycles...

> A maintainer manually starts a build cycle (No, it's not a rolling build, I do not know why.)

A maintainer signs only, then the cycle restarts

> The build cycle runs for 3-4 days.

as many apps in 72h max

> The maintainers wait for 3 days. I do not know why.

the maintainer is a human

> A maintainer logs into a airgapped server, obtains the signing key, and signs all of the new builds and publishes a new index.

yup

> The maintainers wait anywhere from 3 days to a week.

nope, the cycle has already started after publishing the previous one

@orangesunny  ref:  https://mastodon.social/@orangesunny/111982122255300882 all these are explained in the FAQ: https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

**Comment by licaon-kter** [comment]
@OxygenCobalt 
> I've talked to them about at minimum having rolling builds that accumulate unsigned APKs that are then signed regularly, but they just disregarded it. 

Didn't we discuss this? Who disregarded anything? Methods has pro and cons, merge requests are welcomed. What did you expect to happen after communicating the idea?

**Comment by licaon-kter** [comment]
The development takes place elsewhere, not here.
