### ISSUE TITLE
Use system font

### ISSUE THREAD

**Issue by xronin01** [OxygenCobalt/Auxio#720]
Would it be possible to use the default system font ?

**Comment by OxygenCobalt** [comment]
I've rejected this prior. It's not that it's impossible, it's that using the default system font often results in inconsistent behavior (read: samsung and friends randomly injecting their own fonts that do not have the variable weights required for Material Design 3) and generally makes the app look worse. Implementing a setting would also be technically complicated for something that would not be used often.
