### ISSUE TITLE
Play once feature

### ISSUE THREAD

**Issue by Chaman-veteran** [OxygenCobalt/Auxio#721]
### Description

It would be nice to be able to play a music only once and stop right after the end of it.

### Other implementations

In my memories, the SMT music player UI (now Fossify?) was cycling between those possibilities:

- stop after end of playlist
- repeat playlist
- repeat song
- repeat once 

### Benefit

It's for sure something that I'm missing to be able to start a song for my friends to discover it and that I can put down my phone to do something else as I knew it will stop at the end. 
It's also a nice feature to have for those (I'm part of them at least) that want to fall asleep with a song -it could be an alternative to the non arrival of Sleep Timer :)-

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
That's already available in Settings -> Audio -> Pause on repeat.

**Comment by Chaman-veteran** [comment]
Oh, thanks for the tips! I did tried to search but didn't thought that the top right burger on a song's view would bring less options than the one in the main menu 😅

Do you think it would be interesting to discuss about the setting's UI? If so, I could open an issue for it :)
