### ISSUE TITLE
Artists discography duration 

### ISSUE THREAD

**Issue by demarkz** [OxygenCobalt/Auxio#726]
### Description

I wish there's was a time duration for discographies, because I keep many cds from a artists and I use to play the whole discography and love to have as many information as possible from them.

![Screenshot_20240225-165232](https://github.com/OxygenCobalt/Auxio/assets/16445902/5135259f-f6d8-4fd2-aeef-df60b8abf2bf)
![Screenshot_20240225-165147](https://github.com/OxygenCobalt/Auxio/assets/16445902/49916208-2695-41e2-8de6-5f4f1999ec85)

### Other implementations

Many players add this option in the artists tab for better information about the artists.

### Benefit

To keep as many information as possible about the artists 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
To be honest, I don't like this. The total duration is far more relevant to an album or a playlist in my opinion compared to an artist. Sorry.
