### ISSUE TITLE
Application crashes when attempting to add a song to the playlist while any song is playing.

### ISSUE THREAD

**Issue by chiragwad** [OxygenCobalt/Auxio#728]
### Describe the Bug/Crash

1. Open the application.
2. Go to the Songs tab.
3. Play any song.
4. Click on the meatballs menu of any song.
5. Add that song to a playlist.
6. Same issue happens when you try to add a song to playlist while the song is full screen.
7. Added video showing the same.

https://github.com/OxygenCobalt/Auxio/assets/70256225/ccef12ff-97de-48cf-b0be-6466f44f874d

https://github.com/OxygenCobalt/Auxio/assets/70256225/ea1e411e-3ce5-4bda-8da5-c21e449347e2

### Describe the intended behavior

The song should be added to the playlist and the application does not crash.

### What android version do you use?

Android 13

### What device model do you use?

Redmi Note 11

### Bug report

I couldn't generate one.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Thanks for this. I'm pretty sure this is related to the #723 issue, something about my player hot-reloading is causing issues I think.

**Comment by OxygenCobalt** [comment]
This should be fixed now.

**Comment by OxygenCobalt** [comment]
Available in 3.4.2.
