### ISSUE TITLE
whats this number

### ISSUE THREAD

**Issue by dhishkyaon** [OxygenCobalt/Auxio#73]
![Picsart_22-02-06_09-45-25-418.png](https://user-images.githubusercontent.com/88529066/152668044-9c7052bf-c5a6-4215-8ca6-7d600d501098.png)

**Comment by OxygenCobalt** [comment]
That's the track number. I guess for that song the media database could not resolve it, so it just kept the number as zero.

**Comment by dhishkyaon** [comment]
i have 12 songs loaded currently and only one is showing right track number. Others are zero

![IMG_20220206_190209.jpg](https://user-images.githubusercontent.com/88529066/152683376-55eac977-1cc5-4076-a999-bafe96feb6c8.jpg)

**Comment by OxygenCobalt** [comment]
Okay, two questions:
- What format are those audio files in?
- Did you check if those files actually have a track number value in their metadata?

**Comment by dhishkyaon** [comment]
so the one thats showing correct track number is mp3 and all others are m4a.

In there tags only mp3 song is showing track number 1 and for others its blank.

**Comment by OxygenCobalt** [comment]
> In there tags only mp3 song is showing track number 1 and for others its blank.

In that case, I think you could just add some track numbers to your M4A files using a program like [kid3](https://kid3.kde.org). If Auxio can't find a track number for your song, it will just be shown as zero, hence why your songs have 0 next to them.

**Comment by dhishkyaon** [comment]
i have to do this for every single song then and it really sucks.

can you add an option to remove tracks no. from showing?

**Comment by OxygenCobalt** [comment]
> can you add an option to remove tracks no. from showing?

Personally, I feel like that's somewhat out of scope for Auxio. I would prefer track numbers to hide themselves if there were none, but that risks inconsistent behavior. Sorry.

**Comment by dhishkyaon** [comment]
hiding them when zero will work tho.

**Comment by OxygenCobalt** [comment]
Yes, however I'm concerned about accidental collisions if setting the track to zero was intentional. I don't see why I couldn't add it anyway though and just see what changes.

**Comment by OxygenCobalt** [comment]
Could you try out this APK? Rename the extension from zip. Any tracks with "zero" should now replace their track numbers with a generic song icon. This should preserve consistency regarding your tracks.

[Auxio_TrackFix.zip](https://github.com/OxygenCobalt/Auxio/files/8010836/Auxio_TrackFix.zip)

**Comment by dhishkyaon** [comment]
its working fine now. Thanks

**Comment by dhishkyaon** [comment]
hi, i am having an issue on the debug version. The artist name showing under the song name is 'artist' but on selecting it opens 'album_artist' which is different. so it doesn't make any sense.

**Comment by OxygenCobalt** [comment]
It was added in v2.2.0. You can find it [here](https://github.com/OxygenCobalt/Auxio/releases/tag/v2.2.0).

**Comment by dhishkyaon** [comment]
well im using the latest version 2.0.0 but that doesn't include the patch.

**Comment by dhishkyaon** [comment]
so sorry. its there.
