### ISSUE TITLE
Automatically generate playlists according to the directory.

### ISSUE THREAD

**Issue by Darkhell101** [OxygenCobalt/Auxio#731]
### Description

I designated "/music" as the main directory for Auxio (version 3.4.0) on my phone and attempted to download music there. However, I realized that I may need to manually create playlists and then add music to them.
Here I want to make the process more organized. For example, when creating a playlist, generate a subdirectory named by the list name in the folder. When I add songs, move the corresponding files into the respective subfolder. If there is already a subdirectory, load it as a playlist into Auxio.

### Other implementations

Fossify Music Player allows loading playlists from a local directory, but it lacks the ability to move files and has some imperfections.

### Benefit

People generally organize files according to some rules, rather than randomly throwing them into a folder. I think this feature is useful for many people. Thank you for your contribution.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This would be extremely complicated and has niche use-cases. The recommended playlist format that is used by most people is M3U, which references file paths into playlists. Auxio supports import/export through these, and will eventually natively operate on them seamlessly.
