### ISSUE TITLE
Impossible to play multi-artist songs when play from artist enabled

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#734]
### Describe the Bug/Crash

1. Go to Settings > Personalize > When playing from the library > Play from artist
2. click a song with more artists, nothing happens. The dialog to pick the artist to play from doesen't show up. You can still play other songs.
3. When you click on an artist or album from the now playlig screen, the dialog to pick the artist from the previous song finally shows up

### Describe the intended behavior

The artist picker dialog would show right away

### What android version do you use?

Android 12

### What device model do you use?

Samsung Galaxy M21 OneUI 4.1

### Bug report

i think this should be pretty easily reproducable since it happened to me on any multi-artist song in auxio 3.4.2. (if it helps, i was using flacs but i don't think it matters. I don't really have a way to test it with m4a since #708 . If you can't reproduce it, i'll try grabbing a logcat.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Forgot to add a navigation handler I think. I'll go fix this.
