### ISSUE TITLE
The name of the song and author in the widget

### ISSUE THREAD

**Issue by maikcrew** [OxygenCobalt/Auxio#738]
### Description

Please add the track name and author in the widget.

### Other implementations

Take a look at the musicolet widget for example.

### Benefit

You can see immediately what is playing in the widget.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by maikcrew** [comment]
![Screenshot_20240312-210435_Nova Launcher](https://github.com/OxygenCobalt/Auxio/assets/1246572/62f7584c-45b0-4b14-a7fe-3af9ba0b17a5)

I thought you would leave one as it is and the other widget would be from the bottom name of the author and the song. There is plenty of space. I'm using Nova Launcher which can extend the widget.

**Comment by OxygenCobalt** [comment]
The issue lies in that there is not enough space present in the widget to add such text while also having proper spacing as per Material Design 3. Additionally, that combined "Title - Artist" line will become easily truncated for a lot of songs and thus largely useless.
