### ISSUE TITLE
Material Design 3.1

### ISSUE THREAD

**Issue by Martysh12** [OxygenCobalt/Auxio#743]
### Description

The Material 3 guidelines [have been updated with a new slider design](https://github.com/material-components/material-components-android/commit/a641e18b6ab3bfe7f972c6216ce820fd9bfdd662):
<img width="328" alt="lqc3vjs7- 1P  Types-continuous" src="https://github.com/OxygenCobalt/Auxio/assets/49569238/60d35f90-575d-48dd-8b23-741b50836af1">
This new slider design is only available in MDC-Android, as of creating this issue.

### Other implementations

AFAIK, no other Android music players implement this slider.

### Benefit

Implementing a fix will benefit the general design of the app, making it look more modern.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This requires me to update MDC, which is somewhat risky since they changed their elevation overlay system and I need to update themes/code to handle that. Thanks for letting me know.

**Comment by NMrocks** [comment]
See also: [New progress indicator designs](https://m3.material.io/components/progress-indicators/overview)
For the progress bar below the mini player

**Comment by OxygenCobalt** [comment]
Starting work on this under a general move to "Material Design 3.1", which has a bunch of visual and color tweaks. As part of this, I'm also working on a new icon:

![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/10ded733-b484-45bf-88c7-3ca850b0e908)

**Comment by OxygenCobalt** [comment]
![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/9cbd869d-a0a4-4432-9b3f-7b39233d1e0a)

**Comment by Martysh12** [comment]
I feel like the 3 playback controls (the ones with the background) are a bit too big, other than that everything looks really good!

**Comment by NMrocks** [comment]
+1 to Martysh12's comment. Additionally, the slider doesn't really follow the Material 3 spec. The thick slider track looks kinda nice and modern IMO, which this implementation omits

**Comment by OxygenCobalt** [comment]
![Screenshot_20240418-103343](https://github.com/OxygenCobalt/Auxio/assets/65370175/e3fe66de-4dc7-4229-acdb-960007869a2b)

I'm not going to compromise I think on the buttons (I've been wanting to re-emphasize then for awhile now), but I did slightly shrink them

**Comment by NMrocks** [comment]
It seems the previous larger buttons looked better (😅), the icons are now occupying way too much space within the button. The slider looks nice however :)

**Comment by OxygenCobalt** [comment]
also experimenting with centering/resizing text to prioritize functionality a bit better:

![Screenshot_20231231-141239](https://github.com/OxygenCobalt/Auxio/assets/65370175/32d545c5-bcc2-43ce-9714-251893fad206)

This design assumes #448, which might be coming in a 4.0.0 release. I'm not certain about this, the centering is a drastic change but it also harmonizes it really well.

**Comment by OxygenCobalt** [comment]
![Screenshot_20240419-123925](https://github.com/OxygenCobalt/Auxio/assets/65370175/81ec6f02-b285-4aed-ad30-cefe3721b0e8)

Also experimenting with this.

**Comment by NMrocks** [comment]
The centred text looks really nice. Just one minor thing though: I feel like the "Now Playing" text is a bit too small, otherwise it looks fantastic

**Comment by KraXen72** [comment]
i really hope the un-rounded mode for album covers stays as an option.
Other than that, even though I prefer the current design and think that Google has once again outdone themselves in worsening their design language (all downhill after md 2 but w/e), it doesen't look half bad.
I would re-consider the skip/backward buttons not having a backgroun color, i think right now, there are too many emphasized elements, especially with the way you can now swipe to skip/back songs.

**Comment by KraXen72** [comment]
also, while the centered text is nice for shorter titles, i feel it would still be better if it was left aligned, the 3 dots where they were and the heart on the right side in the same height as the text

![Screenshot_20240423-010015_Auxio.png](https://github.com/OxygenCobalt/Auxio/assets/21956756/c8d03897-7805-4d03-9875-d08bd2143be3)

long title:
![Screenshot_20240423-010039_Auxio.png](https://github.com/OxygenCobalt/Auxio/assets/21956756/df35623a-137c-4485-9059-15adedce7bac)

**Comment by OxygenCobalt** [comment]
Un-round mode is staying @KraXen72. I've just had it enabled right now since I'm trying to make a "maximally M3" design and then gracefully reducing it when round mode is off. I still don't like round album art.

As for the more button, I'm sorry to say but it's going back to the song. This is kind of due to the new bottom sheet transition that I implemented from the M3.1 spec:

https://github.com/OxygenCobalt/Auxio/assets/65370175/75c02ba3-621f-4409-99b6-9454976048c5

Without the automatic inset padding, the "Now Playing" header ends up needing to be shrunk and centered to not look visually jarring with the playback bar transition. Hence, the more button needed to be moved.

**Comment by HyperWinX** [comment]
> ![image](https://private-user-images.githubusercontent.com/65370175/323463534-9cbd869d-a0a4-4432-9b3f-7b39233d1e0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDc1MDksIm5iZiI6MTcxNDIwNzIwOSwicGF0aCI6Ii82NTM3MDE3NS8zMjM0NjM1MzQtOWNiZDg2OWQtYTBhNC00NDMyLTliM2YtN2IzOTIzM2QxZTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA4NDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZDIwYzgxMzBmNWFmZjEzNmI4YmU4MzdjNjY0OGI5OWRiYTNhYzU2NTQ0MDUyNzNmMDM3MDQ5MTZlNGQ1NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-bTuBCC9KqsyxNWkNWuagCWZy99ZL4Kv8xHaGMMR9cs)

This looks amazing!

**Comment by HyperWinX** [comment]
This looks amazing!

**Comment by andr202** [comment]
> Un-round mode is staying @KraXen72. I've just had it enabled right now since I'm trying to make a "maximally M3" design and then gracefully reducing it when round mode is off. I still don't like round album art.
> 
> As for the more button, I'm sorry to say but it's going back to the song. This is kind of due to the new bottom sheet transition that I implemented from the M3.1 spec:
> 
>  screen-20240419-125447.mp4 
> Without the automatic inset padding, the "Now Playing" header ends up needing to be shrunk and centered to not look visually jarring with the playback bar transition. Hence, the more button needed to be moved.

are background colors for the next and previous buttons really necessary? it seems so extra.

**Comment by OxygenCobalt** [comment]
Just following the examples set in [material design](https://m3.material.io/styles/icons/applying-icons) @andr202.

![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/9d5f2424-8644-443e-8871-ac3fbcce1fcd)

**Comment by KraXen72** [comment]
i do agree with @andr202 , it really seems weird to have the rewind/skip buttons with backgrounds. you can see even google themselves isn't consistent and in the screenshot you provided, they're using the old progress bar

**Comment by Martysh12** [comment]
@OxygenCobalt Will the widget be redesigned as well?

**Comment by OxygenCobalt** [comment]
Slightly @Martysh12. I think I'm going to add even larger widget designs with bigger text/buttons, highlight the skip buttons, and make sure it's all colored correctly.

**Comment by OxygenCobalt** [comment]
Okay, I guess you are right @KraXen72. They aren't consistent in those guidelines. But it's also not explicitly forbidden in the spec, and the pattern of a central brightly filled icon surrounded by dimly filled icons is a common pattern in a lot of the examples. Additionally, increasing the icon sizes without adding those containers makes it look jarring IMO. I also don't want to leave them as-is, since the new thicker slider makes the tiny and non-hierarchical buttons look frankly out of date.

**Comment by Martysh12** [comment]
I made some mockups of how I think the new widgets should look like, any feedback?
![image](https://github.com/OxygenCobalt/Auxio/assets/49569238/f06505ff-2160-4d93-a648-c8da32759d68)

**Comment by OxygenCobalt** [comment]
Those look legitimately incredible @Martysh12. The only issues lie in that I can't dynamically overlay text onto the Widget image without risking illegibility, but I also can't cram it all into the same bar without squishing the text and making it to ellipsized to be readable or reducing controls. Widget 4 seems like a good tweak to make to the very thin widget. Out of the larger widgets, Widget 1 and Widget 3 are the best (but suffer from the issues I described). See how you can tweak those.

**Comment by Martysh12** [comment]
Alright, I fixed the text illegibility issues and added a new widget type! What do you think?
![image](https://github.com/OxygenCobalt/Auxio/assets/49569238/a9733f1d-ebfe-4114-85e3-00841f3ab08f)

**Comment by OxygenCobalt** [comment]
I'm not feeling any of these widgets, to be honest. It's like either I pick a confusing button layout or I pick a really jarring way to display song information.

Can you try a layout like this @Martysh12? This was my original plan to make widgets of that size look better. It's basic but it works.

![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/4f0ff35f-78fe-48e3-bffe-a48a368a3376)

**Comment by Martysh12** [comment]
Alright, yeah, I'll try this layout out tomorrow (as it's getting pretty late).
Though I don't really understand why you feel like the button layout is confusing / the song information is jarring. Would you mind elaborating on that?

**Comment by OxygenCobalt** [comment]
I like maintaining a simple, linear button layout of `repeat, previous, play, next, shuffle`. It's consistent and expected by muscle memory.

As for the jarring song information, just putting a box around it ends up obscuring the cover and making it somewhat useless. I'm not really sure how to make it work.

@Martysh12

**Comment by Martysh12** [comment]
Hmm, I see.
I'll try to fix my designs tomorrow. Though, it would be nice to have multiple widgets for different button layouts / styles.

**Comment by Martysh12** [comment]
I've been looking through the Android UI Kit and one of the notification templates seems to use this kind of layout... Maybe it's not that bad?

![Screenshot_2024-05-01-00-20-32-050_com.figma.mirror-edit.jpg](https://github.com/OxygenCobalt/Auxio/assets/49569238/0f2778f3-55a2-462e-b4b1-5266ab48234d)

**Comment by OxygenCobalt** [comment]
The consistency remains the concern. If people have muscle memory for "previous, play, next", I want to maintain that muscle memory in the widget. I like "stylish" UI as much as anyone else, but it must be balanced with usability.

**Comment by OxygenCobalt** [comment]
Actually, realized that the widget layout I told you earlier actually wont work now that I think about it. I think this idea I photobashed will work though:

![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/70222804-b0cf-4e41-90e2-5275ba446756)

Can you translate this into a design @Martysh12?

**Comment by Martysh12** [comment]
Sure, I'll also see what I can do about the circular widgets.

**Comment by e-zk** [comment]
@Martysh12 just wanted to say good work these widgets do indeed look incredible.

**Comment by OxygenCobalt** [comment]
Widget 10 looks solid @Martysh12. Holding on anything circular for the same reason I hold on text-based widgets. The maintenance burden is just too heavy and will grow heavier as more and more people request more and more widgets.

**Comment by Martysh12** [comment]
@OxygenCobalt Alrighty, do you need the measurements / design files?

**Comment by OxygenCobalt** [comment]
No, the visual is enough. I'll have to tweak it to work in the limitations of android widgets @Martysh12.

**Comment by KraXen72** [comment]
@Martysh12 the designs look great! i like the widget 10 as well. can you show how it would look, if it was in a 1.4:4 height:width aspect ratio?

**Comment by Martysh12** [comment]
@KraXen72 Here you go, hope this is what you meant
![image](https://github.com/OxygenCobalt/Auxio/assets/49569238/78c24b8e-de11-4cbe-96ef-7a11c8d1bd68)

**Comment by KraXen72** [comment]
i'm using niagara launcher and the widget has a non-standard size, like this:
![Screenshot_20240502-005306_Niagara Launcher.png](https://github.com/OxygenCobalt/Auxio/assets/21956756/0cb8f9d5-da55-445a-9c3b-1a497b836723)

i don't know if it's going to look like in your screenshot, but it's atleast given me an idea of it

**Comment by OxygenCobalt** [comment]
@KraXen72 will let you know that the current wide widget is staying, this one is only going to be for 3x4-ish widgets.

**Comment by OxygenCobalt** [comment]
Finally doing real predictive back

https://github.com/OxygenCobalt/Auxio/assets/65370175/b62e5557-687d-4273-b7b3-1a4065e9464d

**Comment by OxygenCobalt** [comment]
Going to hard-accelerate this to beat Gramophone 2.0's launch in October.

**Comment by Martysh12** [comment]
@OxygenCobalt, would it be possible to change the disc number indicator as well? Currently it blends in a bit too much with the track items:
![image](https://github.com/user-attachments/assets/fcce9ba0-18e6-400b-a12a-2a75b7effc62)

If you scroll through a large list of tracks, it's easy to miss this indicator.

I made an alternative design for this, which contrasts more with the track items. The divider at the top of the track list is replaced with a bolder `outline` version, and the `outline-variant` version is used to separate discs:
![image](https://github.com/user-attachments/assets/88dc8d09-c50f-47f0-98e0-2d7997307f67)
![image](https://github.com/user-attachments/assets/82131864-08f7-494d-b2af-d6b98300ee8f)

**Comment by OxygenCobalt** [comment]
Okay, I'd say that the main sweep of Material3.1 stuff is kinda "done" now. Gotta now go back and fix what I broke (notably re-add sharp corners for non-round mode). Widget stuff & other eye candy can come later, but I don't want to bog down 4.0.0 when I have a plethora of other changes to deliver.

Here's a new disc design @Martysh12, hope you like it

![Screenshot_20241022-221153](https://github.com/user-attachments/assets/5c7919ea-7286-453e-938c-55c59498379c)

**Comment by Martysh12** [comment]
It looks great!

**Comment by OxygenCobalt** [comment]
This is done, 4.0.0 soon.

**Comment by OxygenCobalt** [comment]
Quick poll: Debating whether I should make "Round mode" the default (even if non-round mode is off) and focusing the main branding on that. I guess it depends on whether the majority of people like round covers over sharp.

**Comment by KraXen72** [comment]
vote here for sharp corners by default (teach people the correct way) - also spotify has sharp corners on albums too

**Comment by Martysh12** [comment]
Personally I'm a round corner kind of guy, but focusing on round corners in the branding might discourage potential ~~customers~~ users from trying the app.
I suggest mixing sharp and rounded corners to show that they can be toggled.

**Comment by OxygenCobalt** [comment]
Thanks for the feedback, round corners is going to be the default in 4.0.0 (but your existing configuration won't change). Sharp corners will still be in the branding to show how Auxio can be customized.

Here's the new banner art I've been working on. Yes, I'm going to make real branding images.

![Image](https://github.com/user-attachments/assets/31fa8a94-ac4d-42f7-ab0c-c78c607579d6)
![Image](https://github.com/user-attachments/assets/46d56bbe-01b4-49cb-8d12-ded12951434d)
![Image](https://github.com/user-attachments/assets/c63a0fba-3ab4-44a0-a87f-6e9d71b3b09e)
![Image](https://github.com/user-attachments/assets/7901a11a-2665-4200-879a-bfc15b6e9744)

**Comment by KraXen72** [comment]
wonderful!

**Comment by KraXen72** [comment]
It's just an idea, but this app is already used by a bunch of people, so it might be beneficial to offer the space in the screenshots to some music artists which want to promote their music for a one-time payment, or if you have some friends who make music, you could just promote their songs so they get more listens.

This would also prevent any possible issues with having copyrighted music in the screenshots.

**Comment by chocmake** [comment]
> Here's the new banner art I've been working on. Yes, I'm going to make real branding images.

Nice. Just coming from the perspective of what I was looking for when investigating Android music players, my first priority was finding track multi-artist tagging support (surprisingly difficult to find\*) and robust tagging handling, along with Material You support/just looking decent and being open source.

Auxio ticked all the boxes. So glad you've focused a bit on those strengths here. Could showcase perhaps more of the advanced tagging support.

\* Oto Music advertised this on their app store page but IIRC I think they only used character delimiters to handle splitting single tags rather than handling true multi artist tags.

**Comment by slushspirit** [comment]
i dont know if it's just me, but i feel like it could be good idea to emphasize the fact it supports gapless playback (at least in the eventual play store description). it's the reason i stuck with this player and a reason I love it so much.

**Comment by OxygenCobalt** [comment]
Good point @Martysh12, gapless playback will be disableable soon so I'll have a setting UI I can put in the branding at some point.

**Comment by Martysh12** [comment]
it was @slushspirit who suggested that :P @OxygenCobalt
