### ISSUE TITLE
Add option to disable ReplayGain

### ISSUE THREAD

**Issue by eylenburg** [OxygenCobalt/Auxio#746]
### Describe the Bug/Crash

When I have a playlist of random songs (not the same album or artist) I notice that the volume will often wildly change in between songs. This means I always have to adjust the volume in between songs. This is not the case with any other music players - both for Android and Desktop - and I only noticed it with Auxio. My suspicion is that this has to do with Replaygain. I couldn't find an option in the settings to disable Replaygain, you can only choose between "Prefer track" and "Prefer album", none of which seems to solve the problem for me.

### Describe the intended behavior

Songs should not change their volume. There should be option to disable Replaygain, assuming that's the cause of the problem.

### What android version do you use?

Android 14

### What device model do you use?

Pixel 8, GrapheneOS

### Provide a sample file

n/a

### Bug report

n/a

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Do you use ReplayGain tags at all @eylenburg?

**Comment by eylenburg** [comment]
I have no idea. I use Mp3tag or Puddletag to make sure my Artist / Album Artist / Album / Title / Genre tags are correct but I don't care about anything else.

**Comment by OxygenCobalt** [comment]
Can you open your audio files in tag editors like [kid3](https://kid3.kde.org) that don't abstract away the information @eylenburg?

**Comment by chocmake** [comment]
Mp3Tag can display and edit ReplayGain tags fwiw. From the *View>Extended tags* menu item. They'll appear like:

![Screenshot](https://github.com/OxygenCobalt/Auxio/assets/34178938/8fff2ffc-5329-4800-9b18-856cb374e2db)

**Comment by eylenburg** [comment]
So I just checked 3 random songs. 2 of them have no Replaygain tag, the third one has a tag similar to the one on your screenshot.

But to get back to my main question: there should simply be an option to ignore Replaygain. I used Musicolet before which afaik doesn't support Replaygain, and I had no issues with a difference in volume.

**Comment by OxygenCobalt** [comment]
Sigh. There was a point at which you could disable ReplayGain, but once the functionality was stable enough I removed it assuming that most people would just retag their files if they have unwanted ReplayGain tags. Judging by this, I was extremely wrong. I guess I have to re-add it.

**Comment by eylenburg** [comment]
Thank you for adding it back.

As for me, of course I could re-tag my library by either applying ReplayGain to all files or removing it from all files. But I get my music from various sources, so some will have these tags already and some don't, and the easiest way would be to just ignore the tags and play the music "as is".

Me personally, I will look into re-tagging my library. But other users might not want to bother.

**Comment by OxygenCobalt** [comment]
There are tools like beets and MusicBrainz Picard that auto-tag your library @eylenburg, Auxio is tuned to have the best experience with those kinds of libraries.
