### ISSUE TITLE
Auxio doesn't stop playing when audio from another app start to play.

### ISSUE THREAD

**Issue by foldfree** [OxygenCobalt/Auxio#75]
#### Describe the bug/crash:

I play music in auxio, i switch to another app, play audio. Auxio is still playing tracks but silently.
#### Expected behavior

Auxio should stop playing - be on pause - when another audio stream take over.
#### Steps To Reproduce the bug/crash:

1. Play audio in auxio
2. start audio in another app

#### Screenshots:

video capture of the issue below. Note that the sound of the two streams play at the same time in the video capture. But in real usage, there was a fade out of auxio when i play the other audio.
https://user-images.githubusercontent.com/34523150/153578456-51839b70-b405-49fc-a654-207ffbdab0f9.mp4

#### Phone Information:
Android 12 - and I did rebooted my phone multiple times before sharing this issue.

**Comment by OxygenCobalt** [comment]
Android 12 added a pretty long crossfade whenever the audio streams change. However, it seems on your device that the fadeout doesn't occur, so Auxio just keeps playing until it stops.

I don't really know what I can do. I think this issue may lie with how Vanilla Music handles it's audio focus or how your ROM handles it.

**Comment by OxygenCobalt** [comment]
Wait. Looking at the video again, Auxio isn't stopping at all. There's something more going on here.

**Comment by OxygenCobalt** [comment]
Okay, I've tested Auxio on my device [also A12], and it works for me.

@foldfree Can you try the following:
1. Do you have the "Audio Focus" setting switched off?
2. If you don't have that switched off, can you install the debug build below and try to take a logcat of what happens when the audio focus changes?

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/8049098/app-debug.zip)

**Comment by foldfree** [comment]
Audio focus is off

> Wait. Looking at the video again, Auxio isn't stopping at all. There's something more going on here.

The audio in the video is still full volume but the audio in the phone usage has a fade out occuring. Is it expected behavior?

Here are logcat https://pastebin.com/Vj5W5Dev

**Comment by foldfree** [comment]
>Try turning that setting on. Does it still occur?

Nope it's good.
Thanks for the explanation.
I'll close the issue

**Comment by OxygenCobalt** [comment]
Cool. Yeah, there seems to be a bug on A12 now where when audio focus is off, the audio will fade out, but it won't stop. This should be an easy fix.

**Comment by OxygenCobalt** [comment]
Looks like I actually can't hack my way around this issue. I'll just disable this feature on Android 12.
