### ISSUE TITLE
Group only by album by default

### ISSUE THREAD

**Issue by Bhaskarlimu55** [OxygenCobalt/Auxio#750]
### Description

If an app gathers details to organize songs into albums, that's wonderful. But if it fetchs that all songs, in an album, must have the same album artist's name, it's not doing the right thing. This way, it ends up splitting songs into different albums.

![Screenshot_20240401-093001_Auxio](https://github.com/OxygenCobalt/Auxio/assets/165627192/d57fba9d-cb3a-4057-a79b-625a03d72458)

The rule that all songs in an album must have the same artist doesn't work everywhere. For example, in India, Bollywood movie albums often feature 10-11 singers.

I suggest "Auxio" should just gather the album name, like other apps do, without trying to match the album artist name.

### Other implementations

Auxio should match albums based only on their names, similar to what other apps like 'Grammaphone/Accord do.
![Screenshot_20240401-100127_Accord](https://github.com/OxygenCobalt/Auxio/assets/165627192/1947e94d-100e-45e0-b631-c0a8fe12ebea)
![Screenshot_20240401-100041_Accord](https://github.com/OxygenCobalt/Auxio/assets/165627192/f0a28cbc-fcae-410b-9140-576212a117a2)

### Benefit

For efficiently find song in single folder.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I would recommend to just retag your library, but since I keep getting duplicate issues regarding this again and again I'm going to just switch the behavior to group by album by default. Seems like more users expect Auxio to blindly group by album rather than album and artist.

**Comment by SunBreaker1** [comment]
I second this change, it's quite annoying when on of my albums breaks up in 10 different albums because of how the apps sorts. This will definitely be good for UX and UI

**Comment by fbbb2** [comment]
> I would recommend to just retag your library, but since I keep getting duplicate issues regarding this again and again I'm going to just switch the behavior to group by album by default. Seems like more users expect Auxio to blindly group by album rather than album and artist.

I still have this issue in Version 3.4.3. It makes more sense to group albums by album name not combining it with the artists name. Especially Compilation Albums with many different Artists gets messy. I think it's a better UX/UI choice.

**Comment by OxygenCobalt** [comment]
> I still have this issue in Version 3.4.3. It makes more sense to group albums by album name not combining it with the artists name. Especially Compilation Albums with many different Artists gets messy. I think it's a better UX/UI choice.

I think the original reason I went with it was actually technical, judging by the code. It's easier to group up albums if I have common artist info. But I've been needing to redo the grouping code because of #555.

**Comment by KraXen72** [comment]
what if 2 separate artists release an album with the same name? if this becomes default behaviour, i think it should be configurable. i'd suggest not grouping albums with *different* mbids (however, if an album is missing a mbid and another one has it, they should be merged. just not different mbids)

**Comment by OxygenCobalt** [comment]
Here is my logic @KraXen72:

Auxio's music loader is too geared towards nerdier libraries. Not that those libraries should be neglected, but I think if I want to gracefully degrade it shouldn't be at the cost of non-nerdy libraries. Music nerds with well-tagged libraries are probably more capable of diagnosing an issue than a casual user.

Thus, nerdy edge cases like two artists making an album with the same name should degrade rather than more common edge cases. As for MBIDs, I'll keep splitting by them, *but only if all tracks have MBIDs.* This is strict, but also the failure mode is pretty obvious and diagnosable by music nerds that will actually run into this.

**Comment by steam3d** [comment]
It's really annoying. Even if two artists have the same album name, it's much easier to rename them than to have 100,500 albums with one song.

**Comment by OxygenCobalt** [comment]
I agree @steam3d. Really sorry for being stubborn about this for a long time.

**Comment by OxygenCobalt** [comment]
This is done, will arrive in 4.0.0 @steam3d @fbbb2 @SunBreaker1.
