### ISSUE TITLE
DSD file type support

### ISSUE THREAD

**Issue by SunBreaker1** [OxygenCobalt/Auxio#752]
### Description

Add DSD support for DSD file types; DSF & DFF

### Other implementations

Other players have this feature and the files play as any other music 

### Benefit

I personally have a DSD128 vinyl rip and hopefully will expand. DSD is the best quality file type out there, having this support will allow the player to play the highest quality file type

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I'll tack it onto #361. The issue is that it requires to write my own parsers and decoders (likely by hooking into ffmpeg), so it's really low-priority given how complicated it'll be.

**Comment by OxygenCobalt** [comment]
If I declare it feasible however (I don't know how practical it'll be), you can become a [sponsor](https://github.com/sponsors/OxygenCobalt) and prioritize it, which will make me implement it immediately.
