### ISSUE TITLE
Crash when adding next song to empty queue

### ISSUE THREAD

**Issue by HyperWinX** [OxygenCobalt/Auxio#755]
### Describe the Bug/Crash

1. Open any song from "Albums" tab, to prevent queue creation (album should contain only one song) 
2. Select any other song, and click "Play next".
3. Auxio crashes! NullReference;)

Another variant:
1. Add two or more songs to queue, and switch to the last song in queue.
2. Select any song and click "Play next".
3. Same thing tho! 

### Describe the intended behavior

It should extend queue and add new song to the end! You definitely need to use FIFO stack here;) 

### What android version do you use?

Android 11

### What device model do you use?

Ulefone Armor 8 Pro, stock ROM

### Provide a sample file

It works with all songs, because its not related to file metadata/contents. 

### Bug report

[Uploading bugreport_Armor_8_Pro_EEA_RP1A_200720_011_2024_04_13_20_08_08.zip…]()

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Fixed in the latest version (v3.4.3)
