### ISSUE TITLE
Repeat mode is not saved after a restart

### ISSUE THREAD

**Issue by greentroll88** [OxygenCobalt/Auxio#757]
### Description

Tap repeat mode to the one you like:
![photo_2024-04-16_11-12-50](https://github.com/OxygenCobalt/Auxio/assets/161693875/3488c557-c628-4057-804b-846df99b2f76)
Then close player (forced) and run again. The repeat mode has been reset to the default:
![photo_2024-04-16_11-12-51](https://github.com/OxygenCobalt/Auxio/assets/161693875/3724285d-c7f1-4998-98f0-38c78db96f8a)

### Other implementations

Memory repeat mode by default/or option in settings

### Benefit

Ease of Use. No need to switch the repeat mode manually every time

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Fixed in current development branch.
