### ISSUE TITLE
Odd behavior with duplicate items

### ISSUE THREAD

**Issue by klues** [OxygenCobalt/Auxio#759]
### Describe the Bug/Crash

* add a song to a playlist 2 times (probably this also shouldn't be possible)
* try to remove one of the duplicated songs From the playlist
* both duplicates are selected, if selecting one of them (bug)
* I cannot find a way to remove the song from the playlist

### Describe the intended behavior

Probably it shouldn't be possible to add a song 2 times to a playlist.
It should be possible to remove songs from a playlist.

### What android version do you use?

Android 11

### What device model do you use?

A5 2016 lineageos

### Provide a sample file

-

### Bug report

-

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is already a duplicate of #624, but the duplicate behavior is still an issue I've been aware of for awhile now.

**Comment by klues** [comment]
Ah, ok, thanks for looking at it. Now I've also found out how to remove an item by the explanation in [this comment](https://github.com/OxygenCobalt/Auxio/issues/624#issuecomment-1826189261). But yes, it seems like it's a feature which isn't very intuitive, there should be an explicit option to remove an item. But I'll close this, since it's a duplicate. Thanks!
