### ISSUE TITLE
Album artist tag stopped working in 2.2.0

### ISSUE THREAD

**Issue by alanorth** [OxygenCobalt/Auxio#76]
#### Describe the bug/crash:
Some time in the last few weeks around 2.2.0 (I was building from git) I noticed that the album artist tag stopped working. Here several of Juice WRLD's songs have other artists on the track and they are displayed as separate artists. Here are the relevant ID3 tags for one of the tracks:

```console
$ eyeD3 10\ -\ Life’s\ a\ Mess.mp3 | grep artist
artist: Juice WRLD & Halsey
album artist: Juice WRLD
```

I've tried reloading the music, clearing app storage, etc. Now I am running 2.2.0-dev (04bec3161f1f2e1be42d8cd262ee2063bc931850).

#### Expected behavior
Artist should be displayed according to the Album Artist tag.

#### Screenshots:
![signal-2022-02-12-184213_001](https://user-images.githubusercontent.com/191754/153743681-b6a7c8b8-185c-41ca-9566-280e2000b483.png)

#### Phone Information:
Google Pixel 4a, Android 12

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by alanorth** [comment]
Thanks @OxygenCobalt. I just compiled the 2.2.0 tag and reloaded the music library from settings and the problem is still there.

**Comment by OxygenCobalt** [comment]
Curious. I don't really know what to do here except reach for `printf`, so can you install this debug build [rename the extension from ZIP] and then take a logcat of everything auxio prints? I'll need to see if Auxio does something insane with the new grouping functionality or if `MediaStore` is being busted again.

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/8056419/app-debug.zip)

**Comment by OxygenCobalt** [comment]
Okay, judging by the logs here:

```
Life's a Mess ALBUM: Legends Never Die ARTIST: Juice WRLD & Halsey ALBUM ARTIST: null
```

Auxio is not able to get the album artist field from the database, which results it in falling back to the artist to group everything up. Can you try out this APK?

[app-debug.zip](https://github.com/OxygenCobalt/Auxio/files/8056544/app-debug.zip)

If doesn't work out. I'll need you to identify whether 2.0.0/2.1.0 properly supports album artists. If that doesn't work, then I have no idea what's going on.

**Comment by alanorth** [comment]
Hey I tried the latest debug APK and it's worse now: all the tracks on that particular album are "Unknown Artist" now, but there are three other albums where it is correct. I even deleted those MP3s from my phone and re-copied them to my phone, rebooted the phone, reloaded the library in Auxio.

I will try to git bisect when I get some more time. Thanks

**Comment by OxygenCobalt** [comment]
That is incredibly strange. Can you identify the version where Auxio still works correctly? I can then try to bisect to see what happened.

**Comment by alanorth** [comment]
I take back what I said: I compiled v1.4.2, v2.0.1, and v2.2.1-dev and none of them work with that particular album. They all show "Unknown Artist". I checked those MP3s again on my desktop and they definitely have IDv3 v2.4 album artist tags. I deleted the files from my phone, rebooted it (getting superstitious), reloaded the music in settings, and still "Unknown Artist". So I have no idea what's going on.

**Comment by OxygenCobalt** [comment]
> ID3v2.4 album artist tags

That's could be the culprit. Android has *notoriously* poor ID3v2.4 support. Can you check how ID3v2.3 files with album artists are handled by Auxio?

**Comment by OxygenCobalt** [comment]
Any updates on this @alanorth? Have you tried switching those music files to ID3v2.3 and seeing what happens?

**Comment by OxygenCobalt** [comment]
Hey @alanorth, I've made an ***extremely*** experimental APK that implements #128. If you want, you could try it out and report back to me if it solves your issue.

[Auxio_Ignore_MediaStore_Tags.zip](https://github.com/OxygenCobalt/Auxio/files/8827999/Auxio_Ignore_MediaStore_Tags.zip)

No guarantees that there aren't any weird bugs with this new system, but I hope it finally resolves these unfixable issues.

**Comment by alanorth** [comment]
@OxygenCobalt this solves the "Unknown Artist" issue for the Juice WRLD album. Excellent work. Finally some good news haha.

![signal-2022-06-03-203409_001](https://user-images.githubusercontent.com/191754/171916916-db52c5c8-404b-49a4-977a-0a05c95ae33d.png)

Compare with previous screenshots with the same library.

**Comment by OxygenCobalt** [comment]
Just what I thought. Android's media database is a mess and I have to use my own parser. I have no idea when this will arrive in Auxio proper, as there are some other changes I need to make before it's viable.

**Comment by OxygenCobalt** [comment]
I'm going to roll this into #128 given that I know it's fixed with it. I'm trying to aim for this feature to arrive in 2.4.0.
