### ISSUE TITLE
Artist not sorting properly - Seems to be caused by ALBUMSORT tags

### ISSUE THREAD

**Issue by bryanparadis** [OxygenCobalt/Auxio#760]
### Describe the Bug/Crash

<img src="https://github.com/OxygenCobalt/Auxio/assets/2258437/048edea4-c457-4f9b-bd62-1def217fe414" width=50%>

You can see that Katatonia and Shlohmo are both in the D section. Shlohmo has extended artistsort field in tag but it is set to Shlohmo. Katatonia has extended artistsort field in tag but it is set to Katatonia. I saw a previous issue where this extended field had some other value in it but this isn't the case here. Everything has been manually tagged with mp3tag.

Looking further it seems like it's to do with m4a files from itunes which do have sort tags. After looking at about 5-6 examples I can confidently say that it is because the artists have an album that begins with that letter so it's related to the ALBUMSORT tag.

### Describe the intended behavior

Should actually sort by Name Ascending.

### What android version do you use?

Android 13

### What device model do you use?

Fairphone 4

### Provide a sample file

Can provide privately if actually needed.

### Bug report

Can provide if actually needed.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by bryanparadis** [comment]
I added edited one of the Vitalism track's ALBUMSORT tags and changed it to "0testing" to see if I could get it to appear at the top of the Artist list and it did.

<img src="https://github.com/OxygenCobalt/Auxio/assets/2258437/7a343039-2918-4139-a930-6726dc8c5298" width=50%>

**Comment by bryanparadis** [comment]
Could not reproduce with a Mp3 by adding albumsort and rescanning library. Seems to do with MP4/M4A and albumsort specifically. I had a look through the source for TSOA/soal/albumsort/artistsort but couldn't find any smoking gun.

**Comment by bryanparadis** [comment]
Saw that you were using androidx.media3.exoplayer.MetadataRetriever so I thought I would take a quick look at Android source and found [someting interesting](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/extractor/src/main/java/androidx/media3/extractor/mp4/MetadataUtil.java#L389C7-L394C55).

Opened an issue over there:

https://github.com/androidx/media/issues/1302

**Comment by OxygenCobalt** [comment]
Wow. I thought this would be another "I don't tag my library well and don't realize I have sort tags" issue, but instead it's a legit media3 bug. For now I can patch this myself easily since I vendor media3. Can I have a sample file @bryanparadis?

**Comment by bryanparadis** [comment]
> Huh, I thought this would be another "I don't realize I have sort tags" issue, but instead it's a legit media3 bug. For now I can patch this myself easily since I vendor media3. 

Glad I could surprise you! Haha. Funnily enough finding bugs in third parties is kind of my thing.

> Can I have a sample file @bryanparadis? Just e-mail me one w/no copyrighted audio.

Sent a couple your way

**Comment by bryanparadis** [comment]
@OxygenCobalt A fix commit already upstream!

**Comment by OxygenCobalt** [comment]
Okay, I'll cherry-pick it when I get the chance @bryanparadis. Thanks for reporting this!

**Comment by bryanparadis** [comment]
> Okay, I'll cherry-pick it when I get the chance @bryanparadis. Thanks for reporting this!

Glad I was able to contribute. Cheers

**Comment by bryanparadis** [comment]
Got the 3.5.0 update installed and after a quick check artists seem to be in expected order now. Cheers
