### ISSUE TITLE
Add option to disable lockscreen artwork

### ISSUE THREAD

**Issue by HyperWinX** [OxygenCobalt/Auxio#767]
### Description

Most players, like AIMP or Namida has already implemented this switch. Namida developer did it pretty quickly after i asked him to do this, so its not that hard, i think. On some phones lockscreen artwork looks ugly, so its better to disable it.

### Problem solved

Nuh uh~

### Other implementations

AIMP and Namida have this switch, and some players too

### Benefit

Lockscreen will be without ugly artwork.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
To do this means that you need to disable the cover uploaded to the app's media session, which breaks countless other things in modern android (notification, output switcher, etc.). It's an extremely short-sighted move to make, especially when most ROMs allow you to disable that functionality from what I'm aware.

**Comment by HyperWinX** [comment]
Just add warning that some things can break with disabled lockscreen artwork

**Comment by OxygenCobalt** [comment]
Most people don't read warnings or clarifications. They'll enable it, realize it breaks something else, and then make an issue without looking for duplicates or documentation or even reading any dialog I add for it. Everyone does this every once in awhile.

Working on this is also a deeply slippery slope, as I've held my line on strictly conforming to what the android OS wants from me over allowing customization in the past. If I do this, then that justifies a bunch of other options that will also cause strange bugs and other conflicts which I would have to manage as a single maintainer. I would rather keep the load light, especially when you can disable this from what I'm aware.
