### ISSUE TITLE
child lock settings

### ISSUE THREAD

**Issue by super-lurker** [OxygenCobalt/Auxio#769]
### Description

password protect settings to prevent third party tampering

### Other implementations

no idea...

### Benefit

 prevents third party form changing app settings

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This seems extremely out of scope and more the domain of the OS than anything else. Sorry.
