### ISSUE TITLE
Two toolbars appear when tapping and holding on two songs

### ISSUE THREAD

**Issue by dnbz** [OxygenCobalt/Auxio#77]
#### Description
If you tap and hold two entries(songs, albums, artists, etc.) at the same time, two toolbars with "Play Next" will appear.
Most of the time the toolbars will overlap which doesn't look good.
Auxio 2.10

#### Expect behavior
I like the way this is implemented in VLC, where it allows to multi-select songs for adding to playlist, though personally i don't use it

#### Screenshots
![Screenshot_20220214-065310322_1](https://user-images.githubusercontent.com/42440367/153798675-dc436071-30b8-4606-8a25-92f58d965303.jpg)

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by dnbz** [comment]
Just checked, same thing in 2.2.0

**Comment by OxygenCobalt** [comment]
I've been thinking about adding a restriction for that, but I'm not sure how to go about implementing that. I'll keep this issue open until I have a resolution.

**Comment by OxygenCobalt** [comment]
I also definitely won't add a mutli-select mechanism. It adds far too much friction to the song menu process and opens up all manners of state bugs.

**Comment by OxygenCobalt** [comment]
I'll be rolling this into #93. The new system will still prevent duplicate menus.
