### ISSUE TITLE
Selected songs are not properly highlighted in playlist view

### ISSUE THREAD

**Issue by nitinsooni** [OxygenCobalt/Auxio#773]
### Description

When select a song, show 'Select All' option in menu to select all songs. Obviously in songs, album, artist,... tabs, but inside playlists also.

And very minor bug, so don't wanna open new issue. When selects song inside playlists, songs don't highlights like in songs tab.

### Other implementations

.

### Benefit

Can save hard labour.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
There's no more room in the UI to add any kind of "select all" option unfortunately. However I do notice the highlight issue, so I'm converting this to a bug issue regarding that.

**Comment by OxygenCobalt** [comment]
More people expect Play Next/Add to queue over Spotify's weird transient queue. It's also significantly harder to implement internally. And there are a good amount of people that want to select a specific queue to play.

I'm also not talking about the menu UI. I'm talking about the album/artist/genre view, there is more or less no space to put anything like "select all" without making it cluttered.

**Comment by OxygenCobalt** [comment]
Yeah, currently you need to have album artist tags @nitinsooni until I can do #750. Basically, it's easier technically to group by album and artist combination rather than just album, which leads to this splitting.
