### ISSUE TITLE
Cannot parse M3U playlists with `\Paths\Like\This`

### ISSUE THREAD

**Issue by alexceltare2** [OxygenCobalt/Auxio#774]
### Description

PLS/M3U/M3U8 playlist support

### Other implementations

Files added in the Playlists folder get automatically displayed in Playlist tab

### Benefit

More playlist support

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
You have to manually import playlists right now until #322.

**Comment by alexceltare2** [comment]
> You have to manually import playlists right now until #322. You can do this by tapping the plus button and then tapping "imported playlist".

But...but...It doesn't work either way.

**Comment by OxygenCobalt** [comment]
Can I have a sample M3U file @alexceltare2?

**Comment by alexceltare2** [comment]
There you have it. I've zipped it as github won't allow me to upload it directly.
[My Music.zip](https://github.com/OxygenCobalt/Auxio/files/15394766/My.Music.zip)

**Comment by OxygenCobalt** [comment]
Thanks @alexceltare2, will take a look and get back to you

**Comment by OxygenCobalt** [comment]
I see that all of your files start with a backslash `\`. Are you using relative or absolute paths @alexceltare2?

**Comment by alexceltare2** [comment]
Absolute, from what I recall. It's generated by Winamp.

**Comment by OxygenCobalt** [comment]
Can you try this out @alexceltare2? It should parse those paths as absolute (relative to your main volume)

[Auxio_Canary.zip](https://github.com/user-attachments/files/15749211/Auxio_Canary.zip)

**Comment by alexceltare2** [comment]
> Can you try this out @alexceltare2? It should parse those paths as absolute (relative to your main volume)
> 
> [Auxio_Canary.zip](https://github.com/user-attachments/files/15749211/Auxio_Canary.zip)

YES! It works amazingly well! Nicely done though. Can't wait to see this in the next major release along with Android Auto.
