### ISSUE TITLE
Conform to standard media service lifecycle

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#775]
Somehow find a way to completely and totally depend on Media3's media service lifecycle, which is actually supposed to be standard for android. This requires me to know exactly how to handle long-running loading tasks with the intrinsically transient nature of the default media service lifecycle.

**Comment by etyarews** [comment]
Well, as this is required for a Tasker Plugin, I'm asking you to mark it as prioritized

**Comment by OxygenCobalt** [comment]
Can do @etyarews

**Comment by OxygenCobalt** [comment]
Okay, actually looks like this isn't desirable.

- The playback notification would become outright unusable during loading (I would have to trigger a loading state and at best disable the playback button and at worst completely destroy the player state)
- Playback resumption (a big goal w/this) looks like the player is actually just flat out broken rather than simply in stasis.

I'm just going to give google a couple more years to cook media3 until it reaches sufficient usability standards. For now I'll stick with my custom lifecycle until they disallow that for some reason (probably around Android 18 or so, I'd wager :upside_down_face:).
