### ISSUE TITLE
Cannot select all music to a playlist????

### ISSUE THREAD

**Issue by CyanDragonS** [OxygenCobalt/Auxio#776]
### Description

Cannot select all music to a playlist????

### Other implementations

cannot select all items!

### Benefit

!

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
There is no room in the UI to put an option to add all songs/albums/etc. to a playlist. Sorry.
