### ISSUE TITLE
Tap on media notification doesn't open app anymore

### ISSUE THREAD

**Issue by min7-i** [OxygenCobalt/Auxio#777]
### Describe the Bug/Crash

1. Install [3.5.0-dev](https://github.com/OxygenCobalt/Auxio/releases/tag/v3.5.0-dev).
2. Play a song in Auxio.
3. Open the notification shade.
4. Tap on Auxio's media controls/notification.
5. Nothing happens.

### Describe the intended behavior

The app is opened. (This is how it works in v3.4.3.)

### What android version do you use?

Android 14

### What device model do you use?

Google Pixel 6a (GrapheneOS) / Also happens on an LG G6 with Android 9.

### Provide a sample file

N/A

### Bug report

N/A

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Forgot about this, will patch it out
