### ISSUE TITLE
Search and scrollbar functionality in playlists

### ISSUE THREAD

**Issue by nitinsooni** [OxygenCobalt/Auxio#779]
### Description

Self explanatory.
(Search only in that particular playlist)

### Other implementations

Self-explanatory 

### Benefit

I only use the playlist layout for songs, so search functionality will help finding songs more effectively. And for scrollbar, i have hundreds of songs in each playlist so it'll help in navigating faster without scrolling many time to get down.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Duplicates of #288 and #229, both of these are kind of blocked right now since they are actually really hard to implement in a nice way.
