### ISSUE TITLE
Setting the app to be the standard music player

### ISSUE THREAD

**Issue by talal12bfk** [OxygenCobalt/Auxio#78]
#### Describe the feature you want to implement:
In the setting you can set some apps to be the standart app of its kind if posible can u make the app to be able to dothat

#### Is your feature request related to a problem? Please describe:
sometimes the app gets closed by the system if i have battery saving on
#### Do other music players handle this? If so, how?
other apps i use are closed source and im not so good in prgramning

#### Why do you think this will improve everyone's usage of Auxio?
because now every audio file you want to play plays automaticly in auxio

#### Due Diligence:
- [X] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [X] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [X] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by talal12bfk** [comment]
https://user-images.githubusercontent.com/85613292/153887849-e19e84b6-6954-40b0-b1d2-5d9f4b95c7bf.mp4

**Comment by talal12bfk** [comment]
i hope this will be useful

**Comment by OxygenCobalt** [comment]
Okay, looks like Auxio is missing some (Huawei-specific?) manifest flag. I'll go take a look at what MPV/Termux expose.

**Comment by talal12bfk** [comment]
thank u i love it to see that u are actively putting effort into the app

**Comment by OxygenCobalt** [comment]
Can you test this APK? Rename the extension from ZIP. Okay, I've tried to copy-paste some values from other manifests into my manifest in an attempt to get MIUI to detect my app.

[Auxio_MIUIFixed.zip](https://github.com/OxygenCobalt/Auxio/files/8075815/Auxio_MIUIFixed.zip)

**Comment by talal12bfk** [comment]
Hello dear Alex,
it works now i can set the app as the default musicplayer thank u very much.

btw. im searching for a way to use logcat on my phone.

**Comment by OxygenCobalt** [comment]
Cool, thanks for reporting this issue.
