### ISSUE TITLE
Auxio crashes when trying to export or import a playlist

### ISSUE THREAD

**Issue by eylenburg** [OxygenCobalt/Auxio#781]
### Describe the Bug/Crash

Tried to export a playlist. Auxio crashes, the playlist file is created but empty (0 bytes).

Tried to import a playlist (.m3u, created by Strawberry on PC), Auxio crashes and playlist is not found in app afterwards.

### Describe the intended behavior

Should work without crashing

### What android version do you use?

Android 14

### What device model do you use?

Pixel 8, GrapheneOS

### Provide a sample file

(m3u files not supported but anyway Auxio just creates an empty file!)

### Bug report

n/a

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Can you please make a bug report @eylenburg? Go to [here](https://developer.android.com/studio/debug/bug-report) for guidance on how to take one.

**Comment by eylenburg** [comment]
[bugreport-shiba-AP1A.240505.005-2024-05-31-19-32-32.zip](https://github.com/user-attachments/files/15517559/bugreport-shiba-AP1A.240505.005-2024-05-31-19-32-32.zip)

**Comment by min7-i** [comment]
@eylenburg Do you have [storage scopes](https://grapheneos.org/usage#storage-scopes) enabled for Auxio?

I couldn't reproduce this with the current releases 3.4.3 and 3.5.0-dev, but in previous versions I had to specify the export/import folder(s) for playlists in storage scopes.

**Comment by georgepestell** [comment]
I reproduced this bug when using a third party file manager (simple file manager). It works when going through the default file selection menu.

**Comment by eylenburg** [comment]
I'm using the default file manager of GrapheneOS

**Comment by OxygenCobalt** [comment]
[]()![markup_1000002661.png](https://github.com/OxygenCobalt/Auxio/assets/65370175/2afd22c1-83ba-4b1f-9cee-5bc28b51cbae)

Does the file manager look like this @eylenburg?

**Comment by eylenburg** [comment]
Yes that's the one

**Comment by min7-i** [comment]
> I don't think so, in fact in only has "music and audio" permissions.

@eylenburg Storage scopes is also available for apps requesting access to media files (audio, images or videos). In the permissions view for Auxio tap on the "music and audio" permission:

| music and audio permission | storage scopes |
| --- | --- |
| ![permissions](https://github.com/OxygenCobalt/Auxio/assets/97251923/c445f8f3-9d77-4509-bae0-7ff8db9c4f70) | ![storage scopes](https://github.com/OxygenCobalt/Auxio/assets/97251923/974504f5-8941-4b1d-9f52-e40c0c10b210) |

In storage scopes you could add the music and download folder and try to import/export playlists from/to those folders.

**Comment by eylenburg** [comment]
Thank you! That actually solves the problem and I can export the playlist now. It's a strange workaround though, having to forbid access to music at first.

**Comment by OxygenCobalt** [comment]
Great, thanks for figuring it out @min7-i
