### ISSUE TITLE
Music loading failed with missing album error

### ISSUE THREAD

**Issue by at-pyrix** [OxygenCobalt/Auxio#782]
### Describe the Bug/Crash

1. Install app.
2. Open it.

### Describe the intended behavior

it should work

### What android version do you use?

Android 12

### What device model do you use?

Samsung Galaxy M31 (OneUI)

### Provide a sample file

All files.

### Bug report

java.lang.Exception: DeviceLibrary creation failed: java.lang.IllegalArgumentException: Invalid raw Path(volume=InternalVolumeImpl(storageVolume=StorageVolume: Internal storage), components=Music/Other/tere bina.m4a): No album name
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(SourceFile:92)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Can you provide the m4a file at `Music/Other/tere bina.m4a` @at-pyrix? Strip the audio if copyrighted.

**Comment by at-pyrix** [comment]
k 
[tere bina.zip](https://github.com/user-attachments/files/15517364/tere.bina.zip)

**Comment by OxygenCobalt** [comment]
Ill take a look at it later @at-pyrix

**Comment by at-pyrix** [comment]
sure ;)

BTW I just cleared the app data and launched the app again. This time, the error message is the same but the file is different. Personally I don't think it has anything to do with the file itself.

I might be wrong though.

Thanks for such a speedy response!

**Comment by OxygenCobalt** [comment]
The music loader is multi-threaded, so if a bunch of your files have a tag I can't parse Auxio may fail on different ones depending on which one it manages to parse first @at-pyrix 

It could also be caching, but I'm not sure about that.

**Comment by at-pyrix** [comment]
I see. Any workarounds?

**Comment by OxygenCobalt** [comment]
Ive used taggers like MusicBrainz Picard, Beets, and kid3, so Auxio's music loader works with them well.

**Comment by at-pyrix** [comment]
Does it really need to check for tags? Can't it just ignore them? (like other music player apps). It could just display the album as "Untitled" or something like that.

**Comment by OxygenCobalt** [comment]
I would rather fail loud and get an easy to figure out issue than fail quietly and get a very annoying way to figure out issue @at-pyrix

**Comment by at-pyrix** [comment]
Is it possible to make the metadata checker optional while loading? (fetch metadata if available, else ignore / untitled)

**Comment by OxygenCobalt** [comment]
That would multiply my issue, users would enable it, run into a bug, and then report it. I might only have one reply I can get out some issue reporters before they stop responding, so I don't want that friction @at-pyrix

**Comment by OxygenCobalt** [comment]
I can't reproduce this on my end. I need you to take this APK:

[Auxio_ExtraLogging.zip](https://github.com/user-attachments/files/15749393/Auxio_ExtraLogging.zip)

And take a [bug report](https://developer.android.com/studio/debug/bug-report) after music loading fails. This is the only way I'll be able to identify where Auxio is failing to interpret tags @at-pyrix.

**Comment by OxygenCobalt** [comment]
This is likely fixed, I wasn't properly handling when the android OS would return nothing for an album. It's just highly inconsistent when that actually happens.
