### ISSUE TITLE
Android Auto not working

### ISSUE THREAD

**Issue by PantherFella** [OxygenCobalt/Auxio#783]
### Describe the Bug/Crash

1. Open Auxio 3.5.0-dev
2. Plug into AA compatible car
3. Can't find Auxio in the AA app menu

### Describe the intended behavior

Should be avaliable to use Auxio on AA

### What android version do you use?

Android 14

### What device model do you use?

Pixel 6 Pro 

### Provide a sample file

![Screenshot_20240531-181700](https://github.com/OxygenCobalt/Auxio/assets/171389548/7f0fc77e-be95-4884-9078-4c7261e2559d)
![PXL_20240531_221633905](https://github.com/OxygenCobalt/Auxio/assets/171389548/2d6278e3-8cd6-4637-a10d-6ac2027cc299)

### Bug report

Unsure how

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
You have to enable unknown applications within the Android Auto settings since Auxio was not downloaded from google play. Read [this](https://developer.android.com/training/cars/testing#unknown-sources) for more instructions.
