### ISSUE TITLE
DEV Version Behavior settings not being followed

### ISSUE THREAD

**Issue by Fluffyveee** [OxygenCobalt/Auxio#787]
### Describe the Bug/Crash

Doesn't follow the settings for "When playing from the library" and "When playing from item details" it insteads does whatever "When playing from the library" is set to but not when "Play song by itself" is selected as it instead uses the default option of "Play from all songs" this bug is not a thing in 3.4.3

### Describe the intended behavior

Does what is set in the settings 

### What android version do you use?

Android 14

### What device model do you use?

Pixel 7 (default Google Pixel ROM for the Pixel 7)

### Provide a sample file

N/A any files work and it's not a music loading issue 

### Bug report

N/A

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Thanks for reporting this, will check it out.

**Comment by OxygenCobalt** [comment]
I managed to fix the second issue, but I can't figure out the first one at @Fluffyveee. "When playing from library" and "When playing from item details" are acting independently. Can you provide specific steps?

For now, I'm closing the issue since I believe I've fixed it.

**Comment by OxygenCobalt** [comment]
Never mind, not closing since I'm actually not sure whether I fixed it.

**Comment by Fluffyveee** [comment]
I thought I was clear on the bug I reported guess not well here's video of it working in 3.4.3 and how it's not working in 3.5.0

3.4.3: https://youtube.com/watch?v=Lf0i2cb8BrQ&si=iXUV4dF_hddLYMG1

3.5.0: https://youtube.com/watch?v=toVkNnKyXp4&si=sVE-khADQQJv0kN4

**Comment by OxygenCobalt** [comment]
> I thought I was clear on the bug I reported guess not well here's video of it working in 3.4.3 and how it's not working in 3.5.0 @OxygenCobalt 
> 
> 3.4.3: https://youtube.com/watch?v=Lf0i2cb8BrQ&si=iXUV4dF_hddLYMG1
> 
> 3.5.0: https://youtube.com/watch?v=toVkNnKyXp4&si=sVE-khADQQJv0kN4

Judging by your demo I have fixed the issue (Play by itself not working). Next dev revision will have the fix @Fluffyveee
