### ISSUE TITLE
I wish they'd eliminate the white space on the album cover.

### ISSUE THREAD

**Issue by tokumei123456** [OxygenCobalt/Auxio#791]
### Description

I would like the white space on album covers that are not one-to-one ratio to be eliminated.
By eliminated, I mean made into the background color.
In this image, I would like it to be black.
![Screenshot_20240605-065634~2](https://github.com/OxygenCobalt/Auxio/assets/171477482/ca1cecc5-c404-4130-8805-63898952e6b0)

### Other implementations

I wish it would eliminate the blank spaces like other music players.
![Screenshot_20240605-070517](https://github.com/OxygenCobalt/Auxio/assets/171477482/90952573-f374-4645-8d66-77cded64c748)

### Benefit

There is a function to force the album cover to be 1:1, but depending on the album cover it may be cropped unnaturally.
This can be prevented.
I think this is a valuable feature for people who are concerned about white space on album covers.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I did this since Auxio isn't visually designed to have this extreme whitespace, especially with vertical covers which look extremely strange. Sorry.

**Comment by tokumei123456** [comment]
It is solved.
Sorry for the inconvenience.
![Screenshot_20240607-221831](https://github.com/OxygenCobalt/Auxio/assets/171477482/6f8dc6c1-1801-4185-a6a4-a36723ecac49)
