### ISSUE TITLE
Added a feature to stop music playback and close the app when the app is removed from the "Recently Used Apps" list by swiping it.

### ISSUE THREAD

**Issue by tokumei123456** [OxygenCobalt/Auxio#792]
### Description

I would like a feature added that stops music playback and closes the app when the app is swiped away from "Recently Used Apps."

### Other implementations

Other music players have this feature and it is useful.
![Screenshot_20240605-074417~2](https://github.com/OxygenCobalt/Auxio/assets/171477482/cfaa34b3-ffb5-4b06-8924-7470514f8911)

### Benefit

As you can see in the image, even when you stop the music, it continues to run in the background.
To completely stop the app, you have to stop it from the quick settings panel.
This is inconvenient.
Also, I think it's not a good thing because it could affect battery life.
My proposal is a feature that can improve these things.
![Screenshot_20240605-074928](https://github.com/OxygenCobalt/Auxio/assets/171477482/0cd81fb5-3230-4c26-96e5-bf1417f679ce)

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Already present, it just wont occur when actively playing. I'm not really comfortable making it configurable since it's a very niche setting and I don't want to clutter the settings with things like that. Sorry.
