### ISSUE TITLE
Development is slow right now

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#793]
~~Not abandoning this project, I just have a job + 3 hrs of public transit commute daily  + chores 🙃~~

Update 2: Well my job is done, but now I'm back to school with another 18 credit hours and internship openings to grind :upside_down_face: 

Please be patient, 3.5.0 soon and a 4.0.0 big UI & music rework as well

**Comment by quazar-omega** [comment]
Love the dedication, it really shows in the level of polish, keep it up dude!!

**Comment by alexceltare2** [comment]
We definetly appreciate the GOAT who gave us the most modern, complete and independent music player.

**Comment by OfflinePuffin** [comment]
Auxio is honestly the best music player I have used hands down! Thankyou so much for your time and dedication to this project!! You rock!

**Comment by OxygenCobalt** [comment]
This is no longer the case, 4.0.0 is coming soon (tm)
