### ISSUE TITLE
Swiping down on More Options creates an empty menu

### ISSUE THREAD

**Issue by Martysh12** [OxygenCobalt/Auxio#794]
### Describe the Bug/Crash

1. Go to any screen where clicking on More Options (the button with 3 vertical dots) opens a bottom sheet
2. Swipe down on the button
3. The button will create an empty menu
![Screenshot_2024-06-05-18-08-46-976_org oxycblt auxio-edit](https://github.com/OxygenCobalt/Auxio/assets/49569238/c0d9cb22-81f2-412d-af90-76c55580011a)

### Describe the intended behavior

Disable the swipe behaviour in screens where the button needs to open a bottom sheet

### What android version do you use?

Android 13

### What device model do you use?

Xiaomi Redmi Note 11 Pro+ 5G (veux)

### Provide a sample file

N/A

### Bug report

Taking bug reports is broken for some reason on my phone (Xiaomi moment 小米时刻), though this bug should be pretty easy to pin down and solve.

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Ah should have seen this. Will take a look at your PR.
