### ISSUE TITLE
Support for android auto

### ISSUE THREAD

**Issue by wennaspeedy** [OxygenCobalt/Auxio#800]
### Description

I would like use app with android auto

### Other implementations

Some music players has this feature

### Benefit

It is difficult to use app in car without android auto.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Coming in 3.5.0. There's already a development build available.
