### ISSUE TITLE
Repeat does not work

### ISSUE THREAD

**Issue by jcv99** [OxygenCobalt/Auxio#803]
### Describe the Bug/Crash

Select song
Put mode repeat 1 song
When song ends, it stops

Unable to upload bug report.zip beacuse og 25 mb cap

### Describe the intended behavior

It should repeat the song

https://github.com/OxygenCobalt/Auxio/assets/73550009/d48b698f-3c48-4db7-a804-6f9e12a4bf15

### What android version do you use?

Android 14

### What device model do you use?

Samsung s21 ultra

### Provide a sample file

https://github.com/OxygenCobalt/Auxio/assets/73550009/def4b479-cb66-44f3-a0b8-1b38ad121659

### Bug report

[dumpstate.txt](https://github.com/user-attachments/files/15839524/dumpstate.txt)
[dumpstate-stats.txt](https://github.com/user-attachments/files/15839525/dumpstate-stats.txt)

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Can I get the sample file you have @jcv99?

**Comment by jcv99** [comment]
Happens to all songs, here are 2 with different format
[Songs.zip](https://github.com/user-attachments/files/15849491/Songs.zip)

**Comment by OxygenCobalt** [comment]
> Happens to all songs, here are 2 with different format
> [Songs.zip](https://github.com/user-attachments/files/15849491/Songs.zip)
> 

Wait I see, you have pause on repeat on. It might be accidentally turned on by default. Will fix.

**Comment by OxygenCobalt** [comment]
Actually, there's no bug. Pause on repeat was just accidentally turned on at some point.
