### ISSUE TITLE
Name sorting not working properly

### ISSUE THREAD

**Issue by nitinsooni** [OxygenCobalt/Auxio#804]
### Describe the Bug/Crash

https://github.com/OxygenCobalt/Auxio/assets/154743206/fd4366cd-28a8-478f-bb9a-60f6aa68d575

Name ascending putting that 'lean on' song in last. Also tried with other songs, only that particular song placed in last.

### Describe the intended behavior

Should sort alphabetically

### What android version do you use?

Android 14

### What device model do you use?

Poco x4 pro (pixelos)

### Provide a sample file

[04 - Lean On (feat. DJ Snake & MØ).zip](https://github.com/user-attachments/files/15857480/04.-.Lean.On.feat.DJ.Snake.MO.zip)

### Bug report

...

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
You are using sort tags, which Auxio automatically uses by default. Want to make this better with #612, but I'm not really sure how.

![image](https://github.com/OxygenCobalt/Auxio/assets/65370175/8414787a-8fd7-4a5a-bb15-37aaf61789ae)
