### ISSUE TITLE
sort artists/albums/playlists by recently played

### ISSUE THREAD

**Issue by KraXen72** [OxygenCobalt/Auxio#809]
### Description

whenever you play from an arist/album/playlist and this sort mode is selected, it gets moved to the top in it's tab. I think it's very intuitive, this is how spotify's library tab is sorted

a variation of this is in the 'won't implement' list, but i think it's simple to implement (just remember played dates) and the benefit is very big. (see problem solved)

### Problem solved

sometimes i forget about good albums, this way, i could just scroll down a bit and see what i was listening to a month or two back

### Other implementations

-

### Benefit

see problem solved

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I don't see adding this for the same reason I don't have play counts, it requires another layer of music attribute tagging that must work independently of the library and playlists (which themselves operate independently), so it would be very technically complicated and likely to break since I won't use it. Sorry.

**Comment by KraXen72** [comment]
okay, understandable. thanks!

**Comment by KraXen72** [comment]
could this be re-considered now that musikr is implemented? it's one of the few features that keeps me coming back to different music players every once in a while, even though auxio's metadata system and ux are the best...

thanks!

**Comment by KraXen72** [comment]
also see other users like to listen to recent songs: #1068

**Comment by OxygenCobalt** [comment]
Musikr is intrinsically stateless in design @KraXen72. It's stateful components are mostly isolated and used as inputs. You would have to have an extra system in Kindred, the future system that will be the stateful managers around Musikr and Harmonic (the future playback system). This still more or less applies, I really really want to minimize state and ESPECIALLY the state in Kindred.

**Comment by KraXen72** [comment]
Couldn't this be implemented by adding some sort of a custom metadata tag on the file?

Everything else could be reused the same way that you read metadata like artists and album of the file - whenever you go to play something, you can just update the timestamp in this custom tag.

There are likely to be some caveats I'm overlooking, but it's just an idea.

**Comment by KraXen72** [comment]
I keep running into this. 
I like listening to music from my downlaoded flacs, but i often feel like the singles in my library flood it and it's hard to keep track of the artists and albums i actually like listening to somewhat-often to often. 
On spotify, you have a recents sort in the library: if you play an album, it goes up in the list.

Could you please re-consider @OxygenCobalt ?

Possible path to be added (via Perplexity):
- Add a last_played_ms: Long column to Auxio's song table (Room)
- Update it when a song finishes playing (there'll be a playback callback somewhere in the service)
- In the album sort comparator, use max(last_played_ms) across all songs in the album

Additionally, I would be open to sponsoring this feature if it won't get implemented otherwise.
Thank you again, and thank you for all the work on auxio! :)

**Comment by OxygenCobalt** [comment]
To be honest that tempts me towards wanting to prioritize #593.

Effectively if tagged Albums gains filter chips for Albums, EPs, Singles and thus you could remove the cluttered singles and only have your albums (or any other combination). Much less state involved since it's recomposition of existing tags. Not sure how well it resolves it though @KraXen72

**Comment by KraXen72** [comment]
That is not a bad idea, i didn't know about that issue. That'd definitely help in re-discovering old albums without the clutter of singles, but not completely reslove the issue of me forgetting that an album exists (i have like 200-600 albums (some are singles)) 

If you'd be open to the idea, I could take a look at implementing this. I'm not super experienced in android dev, but I do have _some_ experience contributing to kotlin/java apps, and know java/scala pretty well (among others), so while it'd be quite a lot of work for me, i think it'd also be an interesting experience as well as meaningfully improve one of my music listening qol.
