### ISSUE TITLE
Alert Tone genre

### ISSUE THREAD

**Issue by illdeletethis** [OxygenCobalt/Auxio#81]
#### Describe the bug/crash:
genres list shows an empty genre called "Alert Tone", for which there are no music files

#### Expected behavior
only genres with music files in them should show up

#### Phone Information:
Samsung Xcover 5, Android 11, Magisk 24

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
What version of Auxio are you using?

**Comment by illdeletethis** [comment]
2.1.0
it is the currently newest version in fdroid
sorry for reporting something already fixed since

**Comment by OxygenCobalt** [comment]
Yeah, 2.2.0 wasn't on F-Droid because of a bug with headset focus. v2.2.1 should arrive soon though.
