### ISSUE TITLE
Inline Remote-Rewind/Previous not working

### ISSUE THREAD

**Issue by achouinard** [OxygenCobalt/Auxio#812]
### Describe the Bug/Crash

I use wired headphones with an inline 3-button remote that works through the TRRS connector. As is typical, 2 of the buttons control volume and the third handles transport controls. A single press triggers play/pause, double press is fast forward/next track, and 3 *should* be rewind/previous track. However, Auxio interprets 3 button presses as 2+1, where the next track is selected and then paused or resumed.

### Describe the intended behavior

Pressing the transport control button 3 times should rewind or go to the previous track. It does work as it should in Apple Music, though UAPP has the same issue as described above.

### What android version do you use?

Android 12

### What device model do you use?

Galaxy S10/G973U1 (one UI 4.1)

### Provide a sample file

N/A

### Bug report

N/A

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I don't have control over raw media button key events, as far as I am aware. It's largely the android system mis-interpreting the media buttons and then giving the incorrectly resolved command to Auxio. Apple music apparently has the engineering time to hook into low-level communications APIs to override the behavior manually, something I don't have the bandwidth to maintain. Sorry.
