### ISSUE TITLE
Reverb slider

### ISSUE THREAD

**Issue by RustoMCSpit** [OxygenCobalt/Auxio#814]
### Description

a slider for reverb

### Other implementations

https://github.com/zyrouge/symphony/issues/288
https://developer.android.com/reference/android/media/audiofx/PresetReverb

### Benefit

reverb

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I don't really see the use in this for most users. It fits into more of the category of equalizers anyway, which I outsource to other apps to keep Auxio simple. Sorry.

**Comment by Hallilogod** [comment]
> I don't really see the use in this for most users. It fits into more of the category of equalizers anyway, which I outsource to other apps to keep Auxio simple. Sorry.

Do you by chance know any other audio player for android 8.1 ? Im really happy with auxio but it sadly doesnt have any options to adjust playback speed/pitch. Im also thinking about making a fork for myself that adds this functionality, but i know nothing about android app dev and would have to look through the code for hours to understand it. Do you know how i could implement this? It shouldnt be too complicated, just add some code before playback that reads the pitch and speed from somewhere (i expect the android api to have pitch and speed adjust support). Is there really no way you will ever add this to auxio? It would be so amazing

**Comment by OxygenCobalt** [comment]
Use [Wavelet](https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet&hl=en_US&gl=US&pli=1) @Hallilogod, it's perfect for this stuff.

**Comment by RustoMCSpit** [comment]
> Use [Wavelet](https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet&hl=en_US&gl=US&pli=1) @Hallilogod, it's perfect for this stuff.

foss?

**Comment by OxygenCobalt** [comment]
No @RustoMCSpit, but it's a paid app so I trust it a little more not to do sketchy stuff.

I've yet to see a good FOSS equalizer yet, and I don't have the bandwidth to do it myself.
