### ISSUE TITLE
Android Auto feature not working as expected.

### ISSUE THREAD

**Issue by alexceltare2** [OxygenCobalt/Auxio#815]
### Describe the Bug/Crash

I'm on Android 13 and 3.5 final version of the app and Android Auto detects that I'm playing music from Auxio and is fine and dandy, but, no controls are visible on the Media panel, no icon on the Android Auto dashboard and my remote Play/Next/Previous buttons don't work. In other words, I have no control over the music played outside the app. No issues with playing with the previous version over just bluetooth.

### Describe the intended behavior

Should just work like Youtube Music app.

### What android version do you use?

Android 13

### What device model do you use?

Redmi Note 10 Pro with Lineage OS

### Provide a sample file

N/A

### Bug report

N/A

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
You have to enable developer settings and then enable 'allow unknown' in order to use Auxio in android auto, at least until I can put the app on google play. Yeah, it's a little scummy.

Read [this](https://developer.android.com/training/cars/testing#unknown-sources) for more instructions.
