### ISSUE TITLE
Auto Queue

### ISSUE THREAD

**Issue by Lucky390163** [OxygenCobalt/Auxio#821]
### Description

Search results are not auto Queued please sdd this functionality.

### Problem solved

Iam always look uncomplete because of its absence

### Other implementations

Please add

### Benefit

To queue

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Please do not make duplicate issues to get my attention. If you want me to prioritize something, you can [become a sponsor](https://github.com/sponsors/OxygenCobalt).
