### ISSUE TITLE
Auxio Android Auto Support

### ISSUE THREAD

**Issue by ZebMad** [OxygenCobalt/Auxio#826]
### Describe the Bug/Crash

1. Android Auto Support is listed under Auxio features.

2. Auxio doesn't appear in applications list in Android Auto 'Customize Launcher' section.

### Describe the intended behavior

1. Auxio would appear in the Android Auto 'Customize Launcher' section with attendant functionality.

### What android version do you use?

Android 14

### What device model do you use?

OnePlus 11 5G rooted with Magisk 27.0

### Provide a sample file

not applicable

### Bug report

not applicable

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
You have to enable developer settings and then enable 'allow unknown' in order to use Auxio in android auto, at least until I can put the app on google play. Yeah, it's a little scummy.

Read [this](https://developer.android.com/training/cars/testing#unknown-sources) for more instructions.
