### ISSUE TITLE
Playlist from home screen 

### ISSUE THREAD

**Issue by Epic-Fox-1234** [OxygenCobalt/Auxio#827]
### Description

I want a possibility to add a home screen shortcut to shuffle/play a playlist without opening the app.

### Other implementations

I dont have a example of other music players, but I imagine it like when you add a home screen shortcut in chrome.

Edit: or maybe a Widget, that allows to select a playlist to play.

### Benefit

This feature allows to quickly start a playlist without opening the app and swiping multiple times 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Rolling this into #663, perhaps. I don't really know how I want to do app shortcuts.
