### ISSUE TITLE
[Feature Request] Cuesheet support for albums in single file + .cue format

### ISSUE THREAD

**Issue by xfzv** [OxygenCobalt/Auxio#83]
#### Describe the feature you want to implement:

It would be nice if we could get cuesheet support, especially for albums ripped as a single file + .cue

<details>
  <summary>Poweramp</summary>
  
![Poweramp](https://user-images.githubusercontent.com/78810647/155388694-5236f7bd-87d2-4a7a-abc1-9548ad26f39a.png)
</details>

<details>
  <summary>Auxio</summary>
  
![Auxio](https://user-images.githubusercontent.com/78810647/155388708-0fa05da8-6f62-4062-aaa5-58885449b441.png)
</details>

#### Due Diligence:
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Accepted Additions and Requests](https://github.com/OxygenCobalt/Auxio/blob/dev/info/ADDITIONS.md) document.
- [x] I have checked for this feature in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).

**Comment by OxygenCobalt** [comment]
Android doesn't exactly expose cuesheet functionality, not to mention the issues with making Auxio treat one file as several songs. I don't think I'll be able to add this.

**Comment by OxygenCobalt** [comment]
Update: Two big changes have made this possible.

- #322 is feasible to implement now, so I can obtain cuesheets myself easily.
- #110 was completed, so I have much stronger control over the player.

See #762 for the new issue.
