### ISSUE TITLE
MIDI support

### ISSUE THREAD

**Issue by Prajitura** [OxygenCobalt/Auxio#830]
### Description

Being able to play midi files in auxio.
I don't how complex this is and it may require to manualy download a .sf2 file

### Other implementations

Vlc on pc with external .sf2 file can play midis

### Benefit

Midi files are very small and can hold instrumental music very good, I listen to a lot of midi files on pc and adding it on mobile would help many people

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
ExoPlayer has no public support for MIDI, sorry.
