### ISSUE TITLE
Unable to load music from folder

### ISSUE THREAD

**Issue by rafutek** [OxygenCobalt/Auxio#833]
### Describe the Bug/Crash

1. Have Nextcloud app installed with files synced locally (like Music folder)
2. Try to include folder in Auxio pref
3. Error message saying "This folder is not managed"

### Describe the intended behavior

I expected Auxio to manage this type of folder to be able to listen to my music...

### What android version do you use?

Android 12

### What device model do you use?

Samsung Galaxy S5 (LineageOS)

### Provide a sample file

No file to provide

### Bug report

No bug report was generated

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio's folder management requires me to determine an exact file path to a folder, which isn't practical for folders managed by another app as far as I'm aware. Might look into this later if I have time, but for now #322 should help by making controlling what music is loaded not require this kind of exact path guessing.
