### ISSUE TITLE
Wrong "Now playing" state

### ISSUE THREAD

**Issue by nullpeer** [OxygenCobalt/Auxio#834]
### Describe the Bug/Crash

**If you open the album and play it, then add another album to the end of the queue, the name of the previous album will be shown**

How to reproduce:
1. Open "Albums" folder
2. Choose any album
3. Play it
4. Add another album to queue
5. "Skip" first album and go to second

![Screenshot_2024-07-19-06-27-22-816_org oxycblt auxio](https://github.com/user-attachments/assets/2ae02009-3633-4de5-8742-eafbf9697160)

### Describe the intended behavior

Don't needed

### What android version do you use?

Android 12

### What device model do you use?

XiaoMi Redmi 12C (MIUI 13)

### Provide a sample file

Don't needed

### Bug report

Don't needed

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is working as intended, Auxio seeds the original "Now playing" state from what you played first, anything you add afterwards won't update it.
