### ISSUE TITLE
Exclude / Include Music folders does not work

### ISSUE THREAD

**Issue by antiboem** [OxygenCobalt/Auxio#839]
### Describe the Bug/Crash

1. Go to '*Settings - Library - Music Folders*'
2. Click on '*Include*' (or '*Exclude*', that does not make any difference) and click the '+' sign
3. Navigate to any folder (in my case '*Device - Android - media - com.nextcloud.client - nextcloud - account_name - Audio*')
4. Click on '*Use this folder*' and allow Auxio access to files in that directory
5. The folder appears in the '*Include*' list, but (this is the bug) also in the '*Exclude*' list
6. Click on '*Save*', the situation described in step 5 is still there: the folder appears both in the '*Include*' and '*Exclude*' list
7. When trying to play music, Auxio gives the error message '*No music found*', but there is definitely music present in the directory I added to the '*Include*' list

### Describe the intended behavior

1. When adding a directory to the '*Include*' list, it should not also be listed in the '*Exclude*' list
2. Auxio should only play music found in the directories listed in the '*Include*' list, except the directories listed in the '*Exclude*' list
3. When adding directories to the '*Include*' list, Auxio should be able to find music that is present in that directories and it's subdirectories (recursive).

### What android version do you use?

Android 13

### What device model do you use?

Samsung Galaxy S9 Plus (SM-G965F/DS) on /e/OS 2.1-t-20240605406922-dev-star2lte

Auxio version 3.5.2

### Provide a sample file

[Health Ranger Report - July 20th 2024 – Crowdstrike IT apocalypse.ogg.zip](https://github.com/user-attachments/files/16351862/Health.Ranger.Report.-.July.20th.2024.Crowdstrike.IT.apocalypse.ogg.zip)

### Bug report

With '*Developer options*' enabled, I clicked '*Bug Report - Full Report*' in order to generate a bug report. But after clicking '*Report*' nothing happens (I waited more than 10 minutes). and no folder '*Bug reports*' appears. 

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by hilariousrage** [comment]
I had a similar issue, but I don't know much about Auxio's source code, so take this comment with a grain of salt.

I think the folder appearing in the 'Include' and 'Exclude' sections is intentional, since you have to choose whether to include the folders or exclude them. Otherwise, what would be done with the folders that aren't in any of the lists?

As for the fact that Auxio doesn't scan the folder, you may be dealing with a similar problem: #364. Maybe the media database (again, see #364 - but I'm not sure if it's related) can't scan that directory? I suggest you move the 'Audio' folder to the “root directory” (is that how you say it?) of your device (i.e. the same directory as the Downloads folder), at least for testing purposes.

**Comment by OxygenCobalt** [comment]
This is just #364 mixed with #322. MediaStore isn't good at loading app-managed storage, ESPECIALLY media within the `/Android` folder which is very locked down nowadays.

Include and Exclude folders mostly act as options to filter to a folder (Include) or filter out a folder (Exclude) from all of the music that Auxio can find. It can't control what music Auxio has access to. This will change with #322, but even then I'm unsure if I will have the ability to traverse the restricted directory.

Would highly recommend seeing if you can mount NextCloud to a more traditional directory like `/Music`, Auxio tends to play nicer when it's in a location Google doesn't lock down.

**Comment by antiboem** [comment]
Hi, Nextcloud is restrictive in what data directory to use. The only options are: 

* `/data/user/o/com.nextcloud.client/files` which makes downloaded Nextcloud-files inaccessible for other apps.
* `/storage/emulated/o/Android/data/com.nextcloud.client/files` similar story
* `/storage/emulated/o/Android/media/com.nextcloud.client` In this last option the local nextcloud files are accessible for other apps

The Nextcloud in-app music player is terrible, so I thought that by giving Auxio access to nextcloud's local music directory, I would be able to locally play music that I downloaed from my nextcloud-hosted music collection, with a much nicer user-interface.

Unfortunately it seems that this is not possible, since there is no way to let nextcloud use a 'normal' directory (as a root/base) for it's downloaded files, and Auxio will not behave normally when accessing files within the 'Android' folder.

**Comment by OxygenCobalt** [comment]
I would highly recommend asking NextCloud's maintainers about what exactly stops them from having the ability to mount to a non-android folder @antiboem

Maybe #322 will work, I'm going to be starting it soon-ish.

**Comment by antiboem** [comment]
thanks anyway!
