### ISSUE TITLE
Propose playlist filename as playlist name when importing playlist

### ISSUE THREAD

**Issue by eylenburg** [OxygenCobalt/Auxio#841]
### Description

When you import a playlist from a file, it will ask you to give the new (internal) playlist a name. I think in most cases the file name is already reasonable, so it would be nice if the textbox in Auxio is already pre-populated with the file name So if you're importing "Classic Rock.m3u" then when Auxio asks you how you want to call the playlist it should already have "Classic Rock" in the textbox, but still possible to edit of course.

### Problem solved

Personally, I edit my playlists on the PC and when something has changed I just send them to my phone, delete the old one in Auxio and re-import the new one. It's slightly bothersome to re-enter the playlist name each time.

### Other implementations

Don't know

### Benefit

Saving a few seconds when importing a playlist because you don't have to type the name as long as the .m3u file you're importing is already reasonably named.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I believe this was discussed elsewhere and I accepted it, will do.
