### ISSUE TITLE
Add some e-mail/website/contact/feedback handle from within the app

### ISSUE THREAD

**Issue by sedha344** [OxygenCobalt/Auxio#845]
### Description

Hi, it seems that currently people can only suggest stuff about this project through github platform, which makes it very cumbersome, along with US email providers, for people who use proxy, to express themselves and give feedbacks to projects' developpers.
I wish there were other ways to give feedbacks.

Thanks for the good work anyway, I appreciate the app a lot :1st_place_medal: 

### Other implementations

.

### Benefit

.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
I can do this, would probably be a good idea for engagement.

**Comment by OxygenCobalt** [comment]
Added an e-mail form to the app, should arrive in the next release.
