### ISSUE TITLE
"Hide collaborators" doesn't work for mp3 files

### ISSUE THREAD

**Issue by gelerum** [OxygenCobalt/Auxio#849]
### Describe the Bug/Crash

I added slash to multi-value separators, since that i see collaborators (names from artist tag) despite of "Hide collaborators" option. But this is true only for mp3 files, not for flac. How i see, structure of my flac and mp3 files almost the same. If a track has a collaborator i add them to artist tag, not to album artist tag.

Auxio version: 3.5.2

### Describe the intended behavior

Artists separated with slash in artist tag of mp3 files should be hidden, because they are excluded from album artist tag

### What android version do you use?

Android 13

### What device model do you use?

OneUI

### Provide a sample file

bad (mp3) - https://drive.google.com/file/d/1nshlgHzGlEh41LwpLCdqBank87S43Hxq/view?usp=drive_link
good (flac) - https://drive.google.com/file/d/1sWUPpP4RtjgeH5_s5KgJ91Ya-RCLGrC0/view?usp=drive_link

### Bug report

-

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Are you splitting your artists in Settings -> Content -> Multi-value separators @gelerum? Auxio does not parse separated multi-value tags by default to encourage the use of native multi-value separators and reduce the likelihood of accidentally mangled split artists.

Let me know what that changes. I believe Auxio should be interpreting album artist tags as to avoid split albums, so you will need to provide the sample files in that case for me to confirm.

**Comment by gelerum** [comment]
One album is separated into four pieces, because there is four combinations of artists. And i am able to select one of multiple artists in the album view.
![Screenshot_20240814_033101_Auxio](https://github.com/user-attachments/assets/6af344ea-f522-4f62-a1df-7f72f4dc23e1)
![Screenshot_20240814_033104_Auxio](https://github.com/user-attachments/assets/1dd302e5-2cfb-4ec8-8711-3c665931aa34)
![Screenshot_20240814_033124_Auxio](https://github.com/user-attachments/assets/50cbe706-ed62-4afb-b1ed-fb7369d88e36)
![Screenshot_20240814_033127_Auxio](https://github.com/user-attachments/assets/ca1bfc0c-ca7e-45aa-999e-1f9d6c4e492e)
![Screenshot_20240814_033131_Auxio](https://github.com/user-attachments/assets/fcb7a60c-4ea6-4cd0-b49d-c8e3289546b9)
![Screenshot_20240814_033135_Auxio](https://github.com/user-attachments/assets/026601c9-3c0c-4120-88b9-9fffc23b7943)
![Screenshot_20240814_033424_Auxio](https://github.com/user-attachments/assets/48b89317-0296-40a0-8c1e-e432ecca4312)
I enabled slash as multi-value separator and 'hide collaborators' options which didn't work.
![Screenshot_20240814_033520_Auxio](https://github.com/user-attachments/assets/47c7823f-20d2-4d3f-9a97-f109d28ef1e5)
![Screenshot_20240814_033523_Auxio](https://github.com/user-attachments/assets/11a75bdb-dd2c-4cde-9944-d7d4a89d1a1d)

I sent you and email with this album. I am sure i always had this problem, i usually re-encode mp3 to flac, that works.

**Comment by Lord-Valen** [comment]
A quick look at the tags reveals that there is no album artist metadata.![Screenshot_20240813-175301.png](https://github.com/user-attachments/assets/874e1378-828b-4b5d-ac1e-ec3c711817e9)

Adding the field should fix the issue.

**Comment by gelerum** [comment]
@Lord-Valen 

I opened bad.mp3 in DeadBeef and Kid3, i see album artist tag.
[Kid3](https://github.com/user-attachments/assets/1554304a-ac24-49b9-8950-3fea2c3a553b)
[DeadBeef](https://github.com/user-attachments/assets/2aebafe4-56b3-496c-80f6-8e74e0eafda7)

**Comment by OxygenCobalt** [comment]
I see @gelerum, I wasn't picking up `album artist` as a valid tag. Doing that right now.

**Comment by OxygenCobalt** [comment]
Fixed, will probably arrive in a patch release. Here's a canary build you can test with @gelerum 

[Auxio_Canary.zip](https://github.com/user-attachments/files/16620310/Auxio_Canary.zip)
