### ISSUE TITLE
Start playing when song in queue is selected

### ISSUE THREAD

**Issue by VoxelPrismatic** [OxygenCobalt/Auxio#853]
### Description

When you select a song in the queue, it should immediately start playing, regardless of the previous playback state.

### Problem solved

I click a song, expect to hear something, mess with my bluetooth settings, and only realize later that it never started playing to begin with.

### Other implementations

The following automatically play when you select a song in queue:
- Android
  - Samsung Music
  - VLC
  - Sony Music
- Linux
  - Elisa
  - VLC

### Benefit

One less button to click when you want to listen to a song

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by VoxelPrismatic** [comment]
[screen-20240820-083533.webm](https://github.com/user-attachments/assets/c81c3490-93a8-4a2e-8c7e-e095a742db77)

**Comment by OxygenCobalt** [comment]
Turn off "Remember pause" in Settings -> Audio.
