### ISSUE TITLE
Playback state not retained after app is swiped away or device rebooted

### ISSUE THREAD

**Issue by marco170475** [OxygenCobalt/Auxio#863]
### Describe the Bug/Crash

Since version 3.5.3, when the music is paused, the service exits after swiping away Auxio from the recent apps, even with the "Reload the music library whenever it changes (requires persistent notification)" option enabled. When this occurs, after some time, the playback state is lost. Additionally, the playback state does not seem to persist after a device reboot.

### Describe the intended behavior

Playback state is always retained, also when the app is swiped away from recent apps and across the device reboot.

### What android version do you use?

Android 14

### What device model do you use?

Google Pixel 8

### Provide a sample file

none

### Bug report

none

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
> The service exits after swiping away Auxio from the recent apps

This is actually intentional behavior added in #257.

> even with the "Reload the music library whenever it changes (requires persistent notification)" option enabled

> When this occurs, after some time, the playback state is lost. Additionally, the playback state does not seem to persist after a device reboot.

These are both regressions it seems, will have to fix them.

**Comment by OxygenCobalt** [comment]
Rolling this into #869 since it seems in the same vein.

**Comment by OxygenCobalt** [comment]
Can you try this @marco170475?

[Auxio_Auto2.zip](https://github.com/user-attachments/files/17079279/Auxio_Auto2.zip)
