### ISSUE TITLE
360 reality audio file hangs playback requiring force stop

### ISSUE THREAD

**Issue by apvilkko** [OxygenCobalt/Auxio#864]
### Describe the Bug/Crash

1. Attempt to play the song Akira Inoue - Total Immersion (this ships with Sony phones, 360 reality audio)
2. Song won't play, time stays at 0:00. Further songs won't play either when skipping tracks, have to force stop app to recover.

I assume this is because of the large amount of channels in the audio, but could be some other thing (incompatible codec?).

### Describe the intended behavior

1. Should play the track (with some kind of downmatrixing) or
2. Skip the track if it's unplayable

### What android version do you use?

Android 14

### What device model do you use?

Sony Xperia 1 VI (XQ-EC54)

### Provide a sample file

The m4a file is available in the [Internet Archive](https://archive.org/details/akira-inoue-total-immersion-360-reality-audio)

### Bug report

-

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is likely an issue with ExoPlayer, I'd recommend you report this to [them](https://github.com/androidx/media). Auxio doesn't have the greatest error handling.
