### ISSUE TITLE
Playback is stopped when swiping away Auxio from recent apps

### ISSUE THREAD

**Issue by TL-P** [OxygenCobalt/Auxio#866]
### Describe the Bug/Crash

1. Play some music (v3.5.3)
2. Swipe away Auxio from recent apps
3. Active music playback and foreground service (Task Manager) are stopped

### Describe the intended behavior

Playback should continue (which still worked for me in v3.5.2)

### What android version do you use?

Android 13

### What device model do you use?

Xiaomi Mi 9T (PixelOS)

### Provide a sample file

N/A

### Bug report

N/A

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Intentional behavior from #257. This is what the android system expects from Auxio and I so it's not really in the bounds of a setting (This is the same reason audio focus is non-configurable)

#844 is probably also going to make some auto-timeout system where Auxio will naturally exit it's foreground state after some level of time, so @ego-lay-atman-bay's concern isn't going to be relevant soon I hope.

**Comment by TL-P** [comment]
Is this really the intended behavior? According to https://github.com/OxygenCobalt/Auxio/issues/257#issuecomment-1377881403, if music is playing, then playback will not be stopped.
> In this system, if the music is still playing, playback will not stop @KraXen72. The notification will only disappear if it's paused.

However, that is exactly what is happening on my device (playback is stopped even if playing).

**Comment by OxygenCobalt** [comment]
Can you send a screen recording @TL-P? The code explicitly checks for ongoing playback before it stops the current session.

**Comment by TL-P** [comment]
https://github.com/user-attachments/assets/79466ce5-d90f-4956-a329-9536da3469a9

Recorded without audio, it stops as soon as Auxio is swiped away.

**Comment by OxygenCobalt** [comment]
Okay, this was reported again in #869.

I assume that I set some absurd magic flag that's now giving the horrible OEM ROMs license to kill my app for no discernable reason. You will need to wait until I can generate a bunch of bisect builds to test with @TL-P.
