### ISSUE TITLE
App doesn't run in the background like it should on the latest 3.5.3 update

### ISSUE THREAD

**Issue by Fuoxden** [OxygenCobalt/Auxio#869]
This is the latest version 3.5.3, the bug only happens on the latest version

Version 3.5.3 -https://github.com/user-attachments/assets/84296ab9-c658-4f98-b9b2-2c3117694549

Version 3.5.2-https://github.com/user-attachments/assets/d37ea4d8-e0b8-4536-aa95-e3ac2877bc3e

hope that helped, if you need more info then just ask :)

(I didn't see the template at first so I'm just gonna say sorry, so here's the info I left out)

**What android version do you use?**

Android 14

**What device model do you use?**

Samsung a54 5G

**Provide a sample file**

none

**Bug report**

none

**Duplicates**

I am on the latest version, I have checked if this has been reported before, and I now have read the contribution guidelines (like I should have)

**Comment by OxygenCobalt** [comment]
Another instance of #863, which I am completely unable to reproduce. Everything works fine on my end, so I assume it's some magic thing I did that randomly gave Samsung the liberty to kill my app (Something I loves doing, apparently).

You will need to wait for me to make a bunch of bisect builds to test @Fuoxden.

**Comment by Fuoxden** [comment]
Strange, well, I was gonna add, its working now, for some reason, the app is now running in the background like it should, I wonder what happened to make it stop running in the background

**Comment by Fuoxden** [comment]
Okey, thanks for a response! I am a bit happy its not just me, right now I'm sticking to 3.5.2 when the issue is not present, I can't wait till its fixed! I really love the work your doing on auxio, hope to keep it up!

**Comment by OxygenCobalt** [comment]
Theres only one cause I could see @Fuoxden. Media3 session is stepping in and otherwise overridding Auxio's task removal functionality for some reason, which would make sense since Media3 is an awful library. That does mean 3.5.2 should have it, but maybe it wasn't expressed until now. I'm working on getting rid of that, so hopefully that issue self-resolves.

**Comment by OxygenCobalt** [comment]
Can you try this @Fuoxden?

[Auxio_Auto2.zip](https://github.com/user-attachments/files/17079235/Auxio_Auto2.zip)

Somewhat unstable right now, but should be possible to test if the issue still happens somehow.

**Comment by OxygenCobalt** [comment]
Also @TL-P and @marco170145, can you try this too?

[Auxio_Auto2.zip](https://github.com/user-attachments/files/17079270/Auxio_Auto2.zip)

**Comment by Fuoxden** [comment]
I just tried it! and I'm happy to say its running in the background as it should! Thank you for letting me try this dev build :)

**Comment by OxygenCobalt** [comment]
Awesome, thanks! Will push it in 3.6.0

**Comment by Fuoxden** [comment]
wooooo hooo! can't wait

**Comment by TL-P** [comment]
> I just tried it! and I'm happy to say its running in the background as it should! Thank you for letting me try this dev build :)

same for me 👍

**Comment by TL-P** [comment]
However, I've noticed that the 'x' notification action button does not seem to do anything anymore. @OxygenCobalt

**Comment by marco170475** [comment]
The fix works also for me (issue #863)! However, i have also noticed the "x" button on the notification not closing the notification itself anymore.

**Comment by hoangchungk53qx1** [comment]
same bug pixel 8

**Comment by HellsBells24** [comment]
Pretty sure I'm seeing this on my Pixel 8 as well (GrapheneOS)

**Comment by bad1080** [comment]
> Another instance of #866, which I am completely unable to reproduce. Everything works fine on my end, so I assume it's some magic thing I did that randomly gave Samsung the liberty to kill my app (Something I loves doing, apparently).
> 
> You will need to wait for me to make a bunch of bisect builds to test @Fuoxden.

i also have this issue, started with v3.5.3. i am >not< on samsung (but on xiaomi) and i am on android 13 (crDroid custom rom based on LineageOS). battery mode for auxio is set to "unrestricted". i installed 3.5.2 again to get around it, would be great to have a way to easily downgrade!

**Comment by OxygenCobalt** [comment]
Should be in 3.6.0 now @HellsBells24 @bad1080 @hoangchungk53qx1 @marco170475 @Fuoxden @TL-P

**Comment by Fuoxden** [comment]
I'm gonna download it in a bit, the one thing I need to do is export all my playlists (I have around 20 or even 30 playlists) it will take me a while before I can use it

**Comment by Fuoxden** [comment]
> Should be in 3.6.0 now @HellsBells24 @bad1080 @hoangchungk53qx1 @marco170475 @Fuoxden @TL-P 

I just installed it, it doesn't have the background issue anymore! thank you!

**Comment by TL-P** [comment]
While the background issue is fixed, I still experience the following bug @OxygenCobalt. This did not happen when the background issue was still present.

 > However, I've noticed that the 'x' notification action button does not seem to do anything anymore. @OxygenCobalt

**Comment by OxygenCobalt** [comment]
Sorry, didn't fix that bug @TL-P, making another patch
