### ISSUE TITLE
Audio stopping/stuttering while opening apps.

### ISSUE THREAD

**Issue by Fuoxden** [OxygenCobalt/Auxio#872]
### Describe the Bug/Crash

https://github.com/user-attachments/assets/1ac44e13-98fb-4ed8-a7ec-b0ff75c46f0c

### Describe the intended behavior

Well, audio is not supposed to stutter when switching apps, it also seems like it doesn't do it everytime.

### What android version do you use?

Android 14

### What device model do you use?

Samsung A54 5G

### Provide a sample file

none

### Bug report

none

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is almost certainly a device issue. Samsung A-series devices are the budget ones, right? In that case, Auxio only has limited CPU provisioning and can't decode/process audio fast enough during times of high load (Also see #174).

**Comment by Fuoxden** [comment]
Darn, well alright then! I will just live with it, Will it do the same on a pixel 6? I was planning on buying a pixel 6 by the end of the month so i could flash it with grapheneOS

**Comment by OxygenCobalt** [comment]
A pixel should be enough @Fuoxden
