### ISSUE TITLE
Exporting app settings to a file

### ISSUE THREAD

**Issue by Fuoxden** [OxygenCobalt/Auxio#873]
### Description

I want to export my setting to a file, to make it Easier and convenient to switch to a new device for example

### Problem solved

It is a bit frustrating having to change the app settings manually, like, if I switch devices I would have to change all my settings manually

### Other implementations

Maybe exporting it to .json? or to a text file as well? Depends on how easy it is to implement... (Of course I'm no Dev so i dont really know =w=)

### Benefit

Easy and convenient for people if and or they switch devices! 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Thought about this for some time, given how big Auxio's settings have become. Not really a priority though.
