### ISSUE TITLE
music lags when adding music to playlist

### ISSUE THREAD

**Issue by brvn0** [OxygenCobalt/Auxio#877]
### Describe the Bug/Crash

1. play some music
2. add multiple songs to a playlist (20+ songs so the lag is easily noticable)

### Describe the intended behavior

Music should as there is no change in files or - as described in the troubleshooting page - library content continue playing and not lag.
This behaviour is probably caused by music playback and the playlist edit running in the same thread (afaik, my kotlin knowledge is rather simple therefore I cant prove that with references to the source code)

### What android version do you use?

Android 14

### What device model do you use?

Pixel 7 Pro
Rom: latest GrapheneOS (stable channel)

### Provide a sample file

As this is not a problem with the file playback itself I will skip this step. The behaviour should be seen with any set of files.

### Bug report

As there is no crash or other apps involved, a bug report will not show any additional information

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Folding into #883.
