### ISSUE TITLE
Support for m4a

### ISSUE THREAD

**Issue by ftmiranda** [OxygenCobalt/Auxio#880]
### Description

It would be great if this app would also support m4a file formats - migrations from other (coff coff Apple) would really appreciate that. m4a is already a standard and most modern players such as VLC support that already, why not Auxio? 

### Other implementations

VLC supports m4a no issues, but I really like Auxio and it would be a heck a new feature !

### Benefit

Migrations from iTunes library would not have to be converted to mp3 format anymore, all the original metadata within the m4a would be preserved. Most modern players support m4a... 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by chocmake** [comment]
Have you tried adding them and encountered an issue? As all my music library used with Auxio is in M4A.

**Comment by ftmiranda** [comment]
I really apologize ! I know now what happened! Auxio had for some reason on its configuration to IGNORE the Music folder.... I removed that and switched to INCLUDE folders and added the Music directory, and you are right !!! Now it can see and play all my migrated m4a files, thank you very much !
