### ISSUE TITLE
Wrong text in new_playlist_actions

### ISSUE THREAD

**Issue by Leawind** [OxygenCobalt/Auxio#881]
### Describe the Bug/Crash

1. Open Auxio
2. Navigate to playlist
3. Click button `+`
4. You see the wrong text: Empty playlist

### Describe the intended behavior

Correct text: New playlist

### What android version do you use?

Android 14

### What device model do you use?

Redmi K70

### Provide a sample file

unnecessary

### Bug report

unnecessary

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by Leawind** [comment]
https://github.com/OxygenCobalt/Auxio/blob/94c48406720f9a1c8e2e45d05836177e3469cdc2/app/src/main/res/menu/new_playlist_actions.xml#L10

https://github.com/OxygenCobalt/Auxio/commit/08ca71b7b0a9d04e97cc1fab6736ec8be3569a1c#r147693789

**Comment by Leawind** [comment]
By the way, 

https://github.com/OxygenCobalt/Auxio/blob/94c48406720f9a1c8e2e45d05836177e3469cdc2/app/src/main/res/menu/new_playlist_actions.xml#L6

Why not `lbl_import_playlist` ?

**Comment by OxygenCobalt** [comment]
Because the add button itself represents "New playlist", and then each sub-option represents the type of playlist to create @Leawind. This is largely intended UI design.
