### ISSUE TITLE
Replaygain: Prefer album if one is playing doesn't work when queuing multiple albums

### ISSUE THREAD

**Issue by Riksu9000** [OxygenCobalt/Auxio#882]
### Describe the Bug/Crash

1. Play an album
2. Add another album to queue
3. Play songs from the second album

When playing songs from the second album, it will not use the album gain, but the song gain.

### Describe the intended behavior

Because I queued entire albums, I expect it to use the album gain.

### What android version do you use?

Android 14

### What device model do you use?

Sony Xperia 5 III Lineageos

### Provide a sample file

Sorry, I don't think I can provide albums. The first album can be anything. The Dark Side of the Moon tagged with rsgain as the second album clearly demonstrates the issue when changing from the first to the second track.

### Bug report

-

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Auxio can only really know what started playing, once you edit the queue itself it can no longer be sure it's playing from an album. There's not really a way I can work around this with0out causing the inverse bug (someone plays an album, really modifies the queue, and expects ReplayGain to be normal track gain).
