### ISSUE TITLE
Audio pauses for split second when adding a song to a playlist while playing music

### ISSUE THREAD

**Issue by secretServant** [OxygenCobalt/Auxio#883]
### Describe the Bug/Crash

1. Start music playback.
2. Add current song to a playlist.
3. Audio is interrupted, but resumes pretty much instantly.

### Describe the intended behavior

Audio should play even during adding a song to a playlist.

### What android version do you use?

Android 14

### What device model do you use?

Motorola Lineage

### Provide a sample file

nada, will consider collecting upon request

### Bug report

nada, will consider collecting upon request

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by Richard38907** [comment]
Same here on OnePlus nord Pixel Expérience 13

**Comment by OxygenCobalt** [comment]
I've identified and fixed this issue I think, it just hasn't landed in a patch. I've finally gotten back to this project after a week of non-stop schoolwork, so will address it.

**Comment by OxygenCobalt** [comment]
Should be in v3.6.0. I think a gap is possible if the delay in a refresh takes too long, but I'll do a more robust fix later.
