### ISSUE TITLE
Crash with playback state restoration

### ISSUE THREAD

**Issue by dhishkyaon** [OxygenCobalt/Auxio#89]
#### Describe the bug/crash:
App not opening. It works fine now and i didn't changed anything.

#### Expected behavior

Working fine

#### Logs/Stack Traces:

[Bug report](https://mega.nz/file/jsNkyBDT#Yzw1KIxxBmQLxPtigjCUcAL753311pmytVuQzJAErHM)

#### Screenshots:

Not Available

#### Phone Information:

Pixel 4a, Android 12 (GrapheneOS)

#### Due Diligence:
- [x] I have checked this issue for any duplicates.
- [x] I have checked for this issue in the [FAQ](https://github.com/OxygenCobalt/Auxio/blob/dev/info/FAQ.md).
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Judging by the bug report (thanks for that), the playback state saved in a way that caused the app to crash. I'll look into it.

**Comment by OxygenCobalt** [comment]
I've identified the issue. More or less, you saved the playback state, but then removed a song at some point that resulted in the current position in the queue de-synchronizing. When Auxio went to re-synchronize the queue position, it would use that synchronized position that pointed to an out-of-bounds area in the queue, resulting in a crash. It's really the only list access that I could see that was not already protected. I'll be pushing a fix soon.
