### ISSUE TITLE
Song lyrics, hear me out

### ISSUE THREAD

**Issue by OfflinePuffin** [OxygenCobalt/Auxio#892]
### Description

Would the technique used by Alex Kostarevas over at FUTO for his live caption software be applicable to provide Song lyrics, 

Using thr OpenAi whisper model

https://www.youtube.com/watch?v=gkCofPjEwOg

### Other implementations

Use a Lyric file

### Benefit

To have generated lyrics for songs

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
If they are, I imagine they are still quite intensive to run over time, especially regarding something like batter life. @OfflinePuffin

**Comment by OfflinePuffin** [comment]
Probably, I thought it would work like the Manual full sync button, 
All songs would be processed with a manual sync, then a lyrics file would be generated for each file, And saved a lyrics dir with the same name. 
Some logic could be added so that If it detects a lyric file that it's already been created based off of a file name for the song then it will skip it. 

If there are new songs added it can be done on the fly...
I know this issue is closed, I apologize

@OxygenCobalt
