### ISSUE TITLE
Album artists not working in 3.6.2

### ISSUE THREAD

**Issue by alanorth** [OxygenCobalt/Auxio#895]
### Describe the Bug/Crash

Album artists are not working in v3.6.2. I have a well-tagged library (MusicBrainz) with the "intelligent sorting" and "hide collaborators" options enabled:

<p align="center">
  <img src="https://github.com/user-attachments/assets/777e93be-1c50-4a7b-a848-f0dac1f7b503" width="400px">
</p>

### Describe the intended behavior

Here is the same library in v3.5.3 with "intelligent sorting" and "hide collaborators" options enabled.

<p align="center">
  <img src="https://github.com/user-attachments/assets/5e3c0e30-64a5-4e08-b472-d7e65a945be2" width="400px">
</p>

### What android version do you use?

Android 14

### What device model do you use?

Nothing Phone 2a

### Provide a sample file

N/A

### Bug report

N/A

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Wait, I get it now. I accidentally got rid of the hide collaborators check while doing a refactor. This completely slipped past my radar.

**Comment by OxygenCobalt** [comment]
Fixed in 3.6.3 @alanorth

**Comment by alanorth** [comment]
Thank you, @OxygenCobalt. I understand about being busy etc. I thought the least I can do is report it!
