### ISSUE TITLE
Opening artist view crashes for artists that appear on an album by another (album) artist on v3.6.2

### ISSUE THREAD

**Issue by TL-P** [OxygenCobalt/Auxio#896]
### Describe the Bug/Crash

I hope the title is clear enough?

I'm pretty sure this did not happen in v3.5.3 or earlier. I can test other versions or provide sample files if needed.

### Describe the intended behavior

Should not crash.

### What android version do you use?

Android 13

### What device model do you use?

Xiaomi Mi 9T (PixelOS)

### Provide a sample file

N/A

### Bug report

N/A

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Noticed this, have had no time to fix, but will try to investigate.

**Comment by OxygenCobalt** [comment]
Fixed in 3.6.3 @TL-P
