### ISSUE TITLE
Remove songs in playlist

### ISSUE THREAD

**Issue by gummyhulk** [OxygenCobalt/Auxio#897]
### Description

This isn't about deleting a file but rather a song from a playlist. It seems the feature doesn't exist.

### Problem solved

It's annoying to not be able to delete it since it just stands in the playlist gathering dust, especially if I've already deleted the file and want to remove the song from a playlist.

### Other implementations

Other music players like Metro have a basic function to be able to choose a song in a playlist and remove it.

### Benefit

It benefits everyone because you can more easily customise your playlists.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by chocmake** [comment]
It's not the most obvious but the steps for removing tracks from a playlist are:

1. Open the playlist and click the pencil icon to toggle edit mode.
2. Swipe left on the track desired to be remove. It will display a brief background color and a trash icon.
3. Toggle back to regular mode by clicking the floppy disk (save) icon in the top right corner.

IIRC there was a separately posted issue about adding some direct 'remove' item to the per track playlist item overflow menu to improve discoverability.

**Comment by OxygenCobalt** [comment]
Basically what @chocmake said.

**Comment by gummyhulk** [comment]
Oh thank you! I tried it a bit ago and it didn't seem to work but it worked now, thanks for helping out.

**Comment by dmint789** [comment]
I'm still not seeing how to remove a playlist item without the pencil at the very top. How do I do this?

**Comment by OxygenCobalt** [comment]
Hi @dmint789, you need to swipe to the left on items to remove them. Sorry that it's not really "obvious", I've been meaning to provide some guidance on it.

**Comment by dmint789** [comment]
> Hi @dmint789, you need to swipe to the left on items to remove them. Sorry that it's not really "obvious", I've been meaning to provide some guidance on it.

What version does this work on? I'm on version 3.6.3.
