### ISSUE TITLE
Remove the loading Splashscreen when opening the app.

### ISSUE THREAD

**Issue by main-character** [OxygenCobalt/Auxio#9]
I searched for a music app for so long and yours is the most stable enough for me. It has everything I need.

I have a question tho. Is the loading splash screen when opening the app necessary? I think it is better without the splash screen to show more speed.

Thank you and more power.

**Comment by main-character** [comment]
![Screenshot_2021-03-23-17-11-05-58_e7dcd68fdcfdc2ab307738dbc82b3952.jpg](https://user-images.githubusercontent.com/79792960/112121975-c8b01580-8bfa-11eb-888c-c4a7b3f893cd.jpg)


i mean this splashscreen if im not clear enough.

**Comment by OxygenCobalt** [comment]
The splash screen is necessary, mostly to hide the fact that the entire music library is being loaded.

I could change it to a Phonograph/Odyssey like implementation where the music is loaded on the fly, but that comes with multiple speed and architecture problems as well.

**Comment by main-character** [comment]
Thank you for the response but if it could cause you much trouble then you can leave it as it is. Please continue innovating this application.

kuddos
