### ISSUE TITLE
Android 15 Auxio shows network usage.

### ISSUE THREAD

**Issue by wallmenis** [OxygenCobalt/Auxio#900]
### Describe the Bug/Crash

To start, please forgive me for posting for the exact previous version.

So I recently downloaded the app on my Pixel 8a (stock rom, Android 15) from F-Droid. The version is 3.6.2.

I noticed on the Non-mobile network usage page on Android that the app used a few kilobytes of network. Is this for MusicBrainz indexing (I have some tracks with MusicBrainz IDs but not all of them have those).

![Screenshot_20241021-224037](https://github.com/user-attachments/assets/c1fe2a46-09af-47cc-acc8-7e16b6c08aca)

### Describe the intended behavior

I guess it should not connect anywhere?

### What android version do you use?

Android 14

### What device model do you use?

Pixel 8a

### Provide a sample file

No sample file.

### Bug report

I don't have any of those

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [x] I have checked this issue for duplicates.
- [ ] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by wallmenis** [comment]
Hmm that is certainly weird... I don't know what would cause this... Does Android do that frequently? Maybe it counts some loopback connection that Exo Player or notification system might be using? But then again...

**Comment by OxygenCobalt** [comment]
Notification system uses no network-based loopback, and neither does ExoPlayer @wallmenis.

I've noticed that even empty size metrics on android are given some random value like 5.3kb, so I assume the same is going on here. It's all approximation and that approximation can be wrong.

The only other thing I can assume is if google telemetry is being rolled into my app's usage statistics. Possible.

**Comment by wallmenis** [comment]
Interesting!

Since I am using the F-Droid build, it should be the approximation thing since I checked that the F-Droid build is different than the one here:

https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.oxycblt.auxio.yml

They use sed to remove gms on the yaml file.

**Comment by OxygenCobalt** [comment]
Yeah, that's required to comply with f-droids closed-source binary blob sanitizer @wallmenis, it otherwise doesn't change behavior.

I'm talking about Google's Pixel ROM itself sending off some tiny telemetry about "User opened Auxio at 8:41 AM and it didn't crash", and that being rolled into Auxio's stats due to some technical thing.

**Comment by wallmenis** [comment]
Oh, I mean that could be the case as well!

It looks weird though... I wish if someone has a Pixel with stock rom as well, to verify the findings as per the telemetry... I will try running it through Waydroid with Gapps to check if it is the Google play services too.
