### ISSUE TITLE
Removing space normally covered by square cover art

### ISSUE THREAD

**Issue by deadendpl** [OxygenCobalt/Auxio#908]
I don't know if this is a bug fix or feature request, so I didn't choose a template.

Cover art that is not square is leaving a darkened spot that would be filled by square cover art.
![Screenshot_2024-11-09-14-37-24-906.jpg](https://github.com/user-attachments/assets/b27de506-43a9-4774-a58b-18eb4fe6dbda)

Could that spot be removed?

This is how it looks in Poweramp:
![Screenshot_2024-11-09-14-37-45-242.jpg](https://github.com/user-attachments/assets/2e393d4e-f5c2-49d7-815a-de5f91499840)

**Comment by OxygenCobalt** [comment]
This is an intentional visual choice such that I am still able to provide the "visual space" required for non-square cover art within the UI. There are a lot of UI elements outside of the playback view that will look outright odd without it. This may change in the future though.
