### ISSUE TITLE
Move icons to bottom 

### ISSUE THREAD

**Issue by Akshaythorat376** [OxygenCobalt/Auxio#911]
### Description

Please add option to move icons of songs,albums, artists, playlists to bottom. 

### Other implementations

Musicolet does it. 

### Benefit

This feature eases navigation. 

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is actually a violation of design guidelines. Tabs are meant for groups of semantically related content (like music), while navigation bars are for distinct destinations rather than related content (like different kinds of audio). Sorry.

**Comment by Akshaythorat376** [comment]
Thank you for the clarification.
