### ISSUE TITLE
Triple click earphone button to go to the previous track

### ISSUE THREAD

**Issue by xzitthamerr** [OxygenCobalt/Auxio#912]
### Description

Triple clicking the earphone's button (wired) doesn't load the previous track. It just takes it as two click to move next + one click to stop the song.

### Other implementations

Usually one click means play/pause, two click means next and three clicks mean previous.

### Benefit

Some of us enjoy the wired earphones on our potato devices. It would be a great addition.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is unfixable on my end. It's the Android System's job to intercept headset events and translate them to correct command. Unless you can point towards another app that works and has open source code, I can't do anything.
