### ISSUE TITLE
No Cover visible with ogg vorbis file

### ISSUE THREAD

**Issue by Malte007** [OxygenCobalt/Auxio#913]
### Describe the Bug/Crash

I ripped some of my audiobooks with rythmbox in ogg vorbis format. However Auxio does not display the cover art. I also changed the cover "Quality" from "fast" to "high"
Would be great to have the cover displayed.

Kind regards and thank you for the beautiful app.

### Describe the intended behavior

Cover art should be displayed when playing ogg vorbis audio file.

### What android version do you use?

Android 14

### What device model do you use?

Nothing phone 2A

### Provide a sample file

File format is not supported to upload 

### Bug report

Nope

### Duplicates

- [X] I have checked the [Troubleshooting](https://github.com/OxygenCobalt/Auxio/wiki/Troubleshooting) page.
- [X] I have checked this issue for duplicates.
- [X] I have checked that this issue occurs on the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by Malte007** [comment]
It seems that Rythmbox doesn't add the cover to the file. Sorry for spam.

**Comment by OxygenCobalt** [comment]
No problem, I'd recommend beets or MusicBrainz Picard if you want a really good tagger @Malte007.

**Comment by Malte007** [comment]
> No problem, I'd recommend beets or MusicBrainz Picard if you want a really good tagger @Malte007. I use beets and so Auxio's music loader generally works well with it.

Thank you very much. These are exactly the apps I was looking for. 👍🤩
