### ISSUE TITLE
One-Click Music Playback Android Auto

### ISSUE THREAD

**Issue by Procee** [OxygenCobalt/Auxio#915]
### Description

Currently, when I select an album, artist, or playlist using Android Auto, I'm taken to a list of songs. To start playing music, I have to select a specific song. It would be more convenient if Android Auto could automatically play the first song in the list.

### Problem solved

I'm always frustrated when I have to take my eyes off the road to turn on the music in Android Auto. It would be safer if the app could automatically start playing music when I select an album, artist, or playlist.

### Other implementations

YouTube Music starts playing immediately, I think Spotify does the same thing.

### Benefit

Enhanced safety: Fewer interactions with the screen mean less time spent looking away from the road.
Improved user experience: A more intuitive and efficient interface can make driving less stressful.
Quicker access to music: Users can start listening to music faster, reducing the time it takes to get into their desired listening experience.
Reduced cognitive load: Fewer decisions to make while driving can help reduce mental fatigue.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
For some reason Android Auto doesn't allow you to choose whether to play or enter an item, either it's playable or explorable. I guess this is best as a setting, since some (me, mostly) like exploring a music tree, at least until Android Auto decides to...work.
