### ISSUE TITLE
[Feature Request]: Add marquee title text scrolling

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [OxygenCobalt/Auxio#917]
### Description

Add option to add marquee scrolling to text that exceeds the width, instead of just showing an ellipsis.

### Problem solved

Since I have my phone font size larger than most, a lot of the songs tend to have titles that extend past the width of the container, which makes it harder to see the full title text (such as finding which song is the extended version). Here's a screenshot showing how bad it currently is.
![Screenshot_20241117-120121](https://github.com/user-attachments/assets/ee0a4994-4ed8-4264-962e-1c3a7eb53bda)

It would also be nice for this to be on disc subtitles, artists, album names, etc, since my soundtrack does contain some long disc subtitles, and many of my albums also have long titles.

Here are a few more screenshots.
![Screenshot_20241117-121003](https://github.com/user-attachments/assets/01454715-2474-4407-a985-a0ebc5c7e3f2)
![Screenshot_20241117-120946](https://github.com/user-attachments/assets/67908030-9065-4f5b-85d0-6ef8e84528e4)

### Other implementations

I know vlc has the option for scrolling marquee text, as well as changing the location of the ellipsis (left, center, right).

### Benefit

Other people who have their font size larger like me, will also allow them to read the full text without much difficulty.

I also don't think something like just adding marquee scrolling is very difficult to add, so I don't see a downside to it.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This is pretty much impossible without severely bogging down application performance and making the UI extremely visually cluttered. Making it a configuration setting will generally only destabilize the app, since I'll likely stay on the default setting and won't be able to track if it breaks for any reason. I'd also gen

**Comment by ego-lay-atman-bay** [comment]
I don't think it should decrease performance very much, since you can make it only scroll text that is currently on-screen. Plus, adding a single option wouldn't make the settings menu large (there's plenty of room in the "look and feel" section).

I personally have this issue due to having larger font size than most people, and not being able to see the full title is kind of annoying.
