### ISSUE TITLE
Add 'exclude playlist' from playing all songs

### ISSUE THREAD

**Issue by gummyhulk** [OxygenCobalt/Auxio#920]
### Description

I would like to see a function that allows users to choose to exclude playlists created in Auxio to be excluded from playing all songs. For example, I have a jazz playlist, but when I click shuffle on all songs I would rather the songs be excluded as I already have a playlist for that specific purpose.

### Problem solved

N/A

### Other implementations

I haven't explored how other players do this.

### Benefit

It can benefit users who create specific playlists for specific purposes that are only to be played within that playlist as opposed to being part of all songs. It can be especially helpful if you want to explore your songs that you haven't added in playlists as to discover hidden gems.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
This seems extremely difficult to implement, with a very niche benefit. As a result, I don't think I want to implement this, as in all likelihood the functionality will simply rot over time as I don't use it (and thus become unable to test it). Sorry.
