### ISSUE TITLE
A feature that will count how long you have been listening collectively.

### ISSUE THREAD

**Issue by potassium-cyanide** [OxygenCobalt/Auxio#926]
### Description

A feature that will count how long you have been listening collectively. It should work almost like the Android screen time tracker. 

### Other implementations

So far I haven't seen any "music player" with this feature, seems like it's only on online music streaming apps.

### Benefit

It will help to, yes, track how long you have been listening to music on the app, to let users know and control how much should they listen daily.

### Duplicates

- [X] I have checked this feature request for duplicates.
- [X] I have checked that this feature is not implemented in the [lastest version](https://github.com/OxygenCobalt/Auxio/releases).
- [X] I have checked the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.
- [X] I agree to the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).

**Comment by OxygenCobalt** [comment]
Don't see myself adding this. Long-term tracking like this and play counts is very technically difficult and not really in-scope for the app, I'd recommend using a scrobbler like [Pano](https://github.com/kawaiiDango/pano-scrobbler), it should track the data much better than I could as a single maintainer. Sorry.
