### ISSUE TITLE
Disc number support

### ISSUE THREAD

**Issue by OxygenCobalt** [OxygenCobalt/Auxio#96]
This feature is about adding disc number support to Auxio. Starting in 2.2.2, all tracks that may have disk values will become flat track values, which isn't exactly good UX for those who use disks. This addition is really composed of three things:
1. Extracting disc values in a good way [i.e using `CD_TRACK_NUMBER` on versions that support it and using `TRACK` on versions that don't]
2. Modifying sorting to rely on track and disk values
3. Finding a way to integrate disk numbers into the album view

**Comment by dusnm** [comment]
This is exactly what I had in mind. A lot of my albums have multiple discs, ane while I could go and modofy them to use sequential track numbers instead, this feature would be very welcome. Auxio is one of the few truly great FOSS music players, and this would make it perfect in my book.

**Comment by foldfree** [comment]
Is it expected that now we have the disc tag being ignored? My albums with multiples discs goes cd 1, track 1, cd 2 track 1, cd 1 track 2, cd 2 track 2 etc...
![image](https://user-images.githubusercontent.com/34523150/168630524-5563a355-7e19-4f4f-8c37-69bca0dce508.png)

**Comment by OxygenCobalt** [comment]
Yes @foldfree, I made this issue after resolving #88, which I knew resolved weird track numbers but did not organize by discs. I really want to implement this soon, but not only am I working on some internal technical issues right now, I also have maybe 30 or 40 minutes of free time per day usually. I have no idea when this will arrive.

**Comment by OxygenCobalt** [comment]
Okay, I've started to begin work on disc numbers. Currently I've formalized the UI and implemented indexing functionality, but the addition is still non-functional. I decided to go for a cross between a song item and a "header" item to indicate disc numbers, as it seems to be the clearest way to indicate disc grouping without looking awful. Even nicer, this may open the door for the ability to select a disc of songs with #93.

![Screenshot_20220518-200004_Auxio_Debug](https://user-images.githubusercontent.com/65370175/169188139-5cabd18c-9a60-405d-8bf8-b5974e2fcf92.png)

**Comment by OxygenCobalt** [comment]
Disc number support is now in Auxio. Expect it to arrive in 2.3.0.

**Comment by foldfree** [comment]
I noticed Android 10 has this bug, but previous versions may work ?https://github.com/gateship-one/odyssey/issues/210#issuecomment-733908229

**Comment by OxygenCobalt** [comment]
Oh, thanks for that. Just an Android 10 issue then it seems. I still have the disc number code implemented for API <30, so it should be fine on older versions.

**Comment by ChristianCiach** [comment]
And just by this, Auxio is currently the best audio player on F-Droid, since it is the only one properly handling albums with multiple discs! I've searched for literally hours and finally found Auxio.

Thank you so much and sorry for hijacking this issue! I would have used the "discussion" feature of github for expressing my thanks, but it hasn't been enabled for this repo. Anyway, **thank you so much** for Auxio! Other players have almost driven me insane because of this missing feature.
