### ISSUE TITLE
Ability to hide Albums/Artists

### ISSUE THREAD

**Issue by PierPab2003** [OxygenCobalt/Auxio#99]
I was using MusicPlayerGo for the past 6 months, but i changed phone last day and I've download Auxio to test it instead of MusicPlayerGO, because altough it as good customisation etc available, it was very buggy, particularly on displaying albums cover.
Now that I've tested Auxio, I want to stick to it because it has a flawlessly experience with this new android 12.

However, I miss one fonctionality of MPG, and this is the ability to hide some content, like Artists and Genres etc (separatly if possible, for each colone).
![Screenshot_20220311-174007](https://user-images.githubusercontent.com/94078961/157910164-8e1c4c24-a8bb-4777-aa7b-9c7d75feba49.png)

I think this could be very usefull for every user, because you will be able to better customize the look and feel of the app. In my usecase, this would be awesome, because for some song, I listen only one of an artist, and so the fact that i can see this artist, with only one song, is not usefull and is visually awkward. (The song could be visible only in genre or playlist, that I can't wait for ^^, MPG dosen't have them either.)

Without hidding them :

![Screenshot_20220311-175217](https://user-images.githubusercontent.com/94078961/157911950-39fe7d6b-7272-4e10-812c-164268b8bb36.png)

And then :

![Screenshot_20220311-175257](https://user-images.githubusercontent.com/94078961/157912030-08e4aadc-61eb-4d76-9b17-6f01f0d1f479.png)

That's it, I do not know if I made my self clear, but I think it could be a great implementation.

Thanks a lot for your time

**Comment by PierPab2003** [comment]
And this applies to other things, like albums, if you like only three songs of un album, and you listen to them only when listening to genre or tracklist, it maybe a good idea to hide thie album. I think you get the idea ?

**Comment by OxygenCobalt** [comment]
I don't like this idea, honestly. Much of Auxio's navigation flow and codebase is predicated on the assumption that every song has an album, artist, and genre. If items were to be hidden and simply excluded from the loading process, than that breaks that model and would require a major refactor.

The only way I would tolerate such an addition is if it only applied to the "Home" screen with all the items. The album/artist/genre still exists, you just can't see it in the list. In that case, I may be more okay with it. However, I would still have to deal with how to integrate it in a sensible manner and how to differentiate it from the very similar "Excluded directories" setting.

**Comment by PierPab2003** [comment]
Yep absolutely, the idea is just to hide it in the list to get a better look, (as the screenshoot show), not to delete metadata or whatever.

Maybe you can install MPG to see what i mean by that, but in few word as a user, you just are in your Artist/Album/Genre list, and by pressing an Artist/Album/Genre (For now you can choose Play/Random etc), you just hide it from the list.

**Comment by OxygenCobalt** [comment]
Okay, so what you want is for hidden items to not be shown in the home menu, but still be visible in search and in the artist/album/genre views. I think I can add this.

**Comment by OxygenCobalt** [comment]
Honestly, on further thought, I don't really like this feature. It's far too hard to differentiate it from Excluded Directories, with the benefit being largely related to a niche subset of users. It's far more likely someone will think hiding an item excludes it from everywhere, reporting a "bug" when its actually intended behavior. Sorry.
